### ISSUE TITLE
Question: Z axis for  Reprojecting a Shapefile

### ISSUE THREAD

**Issue by dscott4410** [DotSpatial/DotSpatial#1000]
I apologize in advance, I'm completely new to all things shapefile related...

Regarding this code sample: https://dotspatial.codeplex.com/wikipage?title=Projecting%20to%20USA%20Contiguous%20Lambert%20Conformal%20Conic

I assume we get the x/y values from the geom value in the shape file, but where do we get the z axis value?

**Comment by jany-tenaj** [comment]
If you don't have z values pass 0 values for z. If your feature has z values you can get them from your geometry like you do x and y.

**Comment by dscott4410** [comment]
Thank you for the reply, it solidified my recent findings.
