### ISSUE TITLE
Add an Example for Buffer.AddBuffer Method

### ISSUE THREAD

**Issue by mysticFalls0709** [DotSpatial/DotSpatial#1002]
Please add an example for Buffer.AddBuffer Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: ms-its:E:\FGIS\DotSpatial.chm::/html/b6b18b83-d610-b757-eef9-16e068a48ca5.htm

**Comment by jany-tenaj** [comment]
Have a look at the [example](https://github.com/DotSpatial/DotSpatial/blob/master/Source/Examples/CodeSnippets/BufferExamples.cs#L25-L39) that was just added.
