### ISSUE TITLE
Question: How does this code work?

### ISSUE THREAD

**Issue by karthikaditya** [DotSpatial/DotSpatial#1003]
Hi,

I found a piece of code shown below. I know how to use it i.e. selecting a conduit in the map displays an arrow at one the ends of the conduit. It turns out the arrow shows the direction of flow i.e. from the upstream end to downstream end of conduit. I wanted to know how DS is able to recognize the flow direction in the conduit or does the arrow stand for something else?

`var mys = mapDisplay.GetAllLayers();
                        
            for (int i = 0; i < mys.Count; i++)
            {
                if(mys[i].GetType().Name== "MapLineLayer")
                {
                    MapLineLayer ml = (DotSpatial.Controls.MapLineLayer)mys[i];
                    
                    var stroke = new CartographicStroke(Color.Cyan) { Width = 2 }; 

                    var dec = new LineDecoration
                    {
                        Symbol = new PointSymbolizer(Color.DarkCyan,  DotSpatial.Symbology.PointShape.Triangle, 12), 
                        NumSymbols = 1, 
                        RotateWithLine = true, 
                        PercentualPosition = 100, 
                        FlipAll = true
                    };
                    stroke.Decorations.Add(dec);
                    ml.SelectionSymbolizer.Strokes.Clear(); 
                    ml.SelectionSymbolizer.Strokes.Add(stroke);  
                }
            }
            mapDisplay.FunctionMode = FunctionMode.Select;
`
![capture1](https://user-images.githubusercontent.com/16631223/27177385-cda04128-51e3-11e7-8398-1c113565caee.PNG)

Find the arrow indicated on the selected conduits in a map

Thanks for any help,
Karthik

**Comment by jany-tenaj** [comment]
Your line is defined with a start and an end poind. DS draws the line from this start to end point also rotating the arrow based on this line.
