### ISSUE TITLE
Load from Database

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1004]
Hi,

Recently i managed to load the shape file to SQLite database so that we may not be dependent on shape file, but now i am finding difficult to load the data from database to dotspatial map.

Please suggest any suitable ways to achieve this shape file from database to map.

Rgds,
Amit

**Comment by amitnkukanur** [comment]
I was able to load the geometry by doing some rnd the below piece of code represents the same
  byte[] test = null;
                test = (byte[])dr["geometry"];
                NetTopologySuite.IO.WKBReader rd = new NetTopologySuite.IO.WKBReader();
                var geo = rd.Read(test); 
                myPointFeatureSet.AddFeature(geo);

But the new problem am facing is other attributes are not coming.
Kindly suggest which function attaches the attributes also.

**Comment by jany-tenaj** [comment]
Check out [this example](http://dotspatial.codeplex.com/wikipage?title=CreateAttributes&referringTitle=Desktop_SampleCode). It explains how to add attributes to a layer and add a feature with attributes.

**Comment by amitnkukanur** [comment]
This helped me.
Thanks.
