### ISSUE TITLE
Dotspatial Version 2 Controls.dll problem on paint

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1006]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. add userControls To project
2. inherit from Map in Dotspatial.Controls
3. Drag some Controls duplicate paint it and usercontrol problem

DotSpatial version: 2

**Comment by jany-tenaj** [comment]
Please explain more clearly. If possible attach source code. I've got no idea what you're talking about.

**Comment by am2222** [comment]
@jany-tenaj Hi,
I think he refers to map control which is not available using toolbox and we must add it manually.
