### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1011]
I am trying to import 2 shape file's.
1 with flags and other without flags.

The other without flags will load well, but the one with flags loads without flags.
My question is is it possible to load flags while importing shape file.

Regards,
Amit

**Comment by jany-tenaj** [comment]
Please explain what you mean by flag.
Please attach the shapefile that doesn't work.

Please indicate which DotSpatial version you use.

**Comment by amitnkukanur** [comment]
1) Let us assume we have a property called shape_type in Shape file
2) In this shape_type i have RECTANGLE, CIRCLE, SQUARE
3) So i have created a excel file where for RECTANGLE property i have some color, CIRCLE some color and SQUARE some color.
4) When i import this excel file to Dotspatial it should read the properties and assign colors to map and change color identity.
This field is flags.

I use Dotspatial 2.0

**Comment by jany-tenaj** [comment]
So what code do you use to import your excel file and assign the colors?

**Comment by amitnkukanur** [comment]
I use Interop to import excel.
Firstly i load datagrid with existing shape file data, then based on logic i loop row by row to find if CIRCLE or RECTANGLE is available.

If available i will mark then color and then click OK. The colors should get updated as flags in shapefile.

**Comment by jany-tenaj** [comment]
No idea how to help you if you don't post your code.
