### ISSUE TITLE
Add an Example for DgvSelect.MoveLayers Method

### ISSUE THREAD

**Issue by fivecwuchen** [DotSpatial/DotSpatial#1016]
Please add an example for DgvSelect.MoveLayers Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: ms-its:E:\FGIS\DotSpatial.chm::/html/c80b9443-1be3-5728-0cc4-694952f70151.htm

**Comment by jany-tenaj** [comment]
Not sure adding an example for this makes sense because this function is specifically for the given plugin. Please explain why you need this example.

**Comment by mysticFalls0709** [comment]
i just wanna move the features in the featureset, only find this function related to moving a feature. If you can help realize the moving feature function, it would very helpful to me. Thank you!
