### ISSUE TITLE
Migrating 1.9 to 2.0   Coordinate.Reproject

### ISSUE THREAD

**Issue by Enhakiel** [DotSpatial/DotSpatial#1026]
Hello,
I'm trying to migrate DotSpatial and I don't know how to easily replace `coords = feature.Coordinates.Reproject(layer.Projection, ProjectionInfo.FromEpsgCode(model.ProjectionOrigin));`

Regards.

**Comment by jany-tenaj** [comment]
Try whether the following code works for you.

```
coords = feature.ToShape().Vertices;

Projections.Reproject.ReprojectPoints(coords, null, layer.Projection, ProjectionInfo.FromEpsgCode(model.ProjectionOrigin), 0, coords.Length / 2);
```

**Comment by Enhakiel** [comment]
Yes, thanks, I've came to same solution using extension methods... for those interested in:
`
public static Coordinate Reproject(this Coordinate coordinate, ProjectionInfo source, ProjectionInfo target)
{
	var xy = new[] { coordinate.X, coordinate.Y };
	DotSpatial.Projections.Reproject.ReprojectPoints(xy, new []{0d}, source, target, 0, 1);

	var coord = new Coordinate(xy[0], xy[1]);

	return coord;
}



public static Coordinate[] Reproject(this Coordinate[] coordinates, ProjectionInfo source, ProjectionInfo target)
{
	return Reproject(coordinates.ToList(), source, target).ToArray();
}



public static List<Coordinate> Reproject(this List<Coordinate> coordinates, ProjectionInfo source, ProjectionInfo target)
{
	var i = 0;
	var xy = new double[coordinates.Count * 2];
	foreach (var coord in coordinates)
	{
		xy[i] = coord.X;
		xy[i + 1] = coord.Y;
		i += 2;
	}

	DotSpatial.Projections.Reproject.ReprojectPoints(xy, new[] { 0d }, source, target, 0, coordinates.Count);

	var coords = new List<Coordinate>();

	i = 0;
	for (i = 0; i < xy.Length; i+=2)
	{
		coords.Add(new Coordinate(xy[i], xy[i+1]));
	}

	return coords;
}
`
