### ISSUE TITLE
Move a Node

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1028]
Hi,

Am working on moving of Nodes to different location. 
The in the attached paint file, i am moving node 'B' to different location here only node 'B' moves.
I am interested in moving the line connected to it also.

Please suggest way to do this.

Regards,
Amit

![temp](https://user-images.githubusercontent.com/25892886/28459291-774ee960-6e2a-11e7-9393-05a71a2f0e21.png)

**Comment by jany-tenaj** [comment]
What do you mean by moving the line connected to it also?

**Comment by amitnkukanur** [comment]
Hi,

Thanks for the reply.

When i move the node B, not only the node B should move but its connected with two lines.

That should also move, like in second image B is on top, i moved B a bit downwards, the connected lines also should come down.

**Comment by jany-tenaj** [comment]
So I'm going to guess. 
- You've got a point layer that contains B. 
- You've got a line layer that contains the 2 lines connected to B.

And you want the lines to still be connected to B after you moved B.

If this is the case you'd have to do the following.

- Find the lines that are connected to B. 
- Update the line point that was connected to B to the new x/y values of B.

How to find the lines:

1. Use B to create a small area. 
```
IPoint B; // as you changed Bs coordinates you should no how to get it
var area = B.Buffer(0.001);
```

2. Use the area to find the lines.

IFeatureLayer yourLineLayer; // get your line layer
yourLineLayer.Select(area);

3. Circle through all the selected features of yourLineLayer and check which lines contain B as coordinate.

4. Update the coordinate to the new x/y values of B.

**Comment by amitnkukanur** [comment]
Thanks for comment jany-tenaj.
Your guess was perfecr i was looking for same and this helped me.

**Comment by amitnkukanur** [comment]
Hi,

There seems to be problem with this below line.
`fl.Select(area, area, ClearStates.Force);`

ClearStates.Force is not recognised.

**Comment by jany-tenaj** [comment]
ClearStates are contained in DotSpatial.Symbology.

Make sure you are using the dlls from the latest changeset as ClearStates were added only 6 days ago.

**Comment by amitnkukanur** [comment]
Ok.

**Comment by amitnkukanur** [comment]
As you suggested i did and tried by adding various parameters also, but the `var features = fl.Selection.ToFeatureList();`

returns 0 selectioncount.

**Comment by jany-tenaj** [comment]
1. Are you really using the old B coordinate for the selection?
2. Is your line layer in IndexMode? (fl.DataSet.IndexMode)
3. Is the extent of your line features correct?
4. Try using a larger Buffer (e.g. 0.1 or 1).

**Comment by amitnkukanur** [comment]
I was able to get the selection set, i was getting the coodinate by using `e.X and e.Y`
but when i realized the `PixelToProj` coordinate system, i got the selection set.

Buffer was also required to be increased.

**Comment by amitnkukanur** [comment]
Its working, but not to the level of perfection. Because once i move the node some times line still stays in its location or unpredictable movement of conduits.
Need to see completely.

**Comment by jany-tenaj** [comment]
I'd have to see your code (including the line and point shapefile your working with) to tell you where it's going wrong.

**Comment by amitnkukanur** [comment]
Its working well. I had created a wrong mouse event.
