### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1030]
Hi,

I used nettopology suite to convert well know text geometry to load to map.

Here result is `ref IFeatureSet result`

`NetTopologySuite.IO.WKTReader readWKT = new NetTopologySuite.IO.WKTReader();
            var temp=readWKT.Read(drGeom);
            result.AddFeature(temp);`

After doing so the graphics of application changes and application do not behave as required.

Please suggest alternate if WKTReader we have.

Regards,
Amit

**Comment by jany-tenaj** [comment]
Are you sure the WKTReader is your problem? As far as I know it works correctly. Did you use the WKTReader from [DotSpatial.NetTopologySuite](https://github.com/DotSpatial/NetTopologySuite)? If not try whether this works better.

What exactly do you mean by the graphics of application changes and application do not behave as required.

It would be nice if you could explain your problems more clearly so we don't always have to guess what could be wrong.
