### ISSUE TITLE
FID not coming

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1032]
Hi,

Please review the below piece of code for Points
`result being featureset`
```

tstShData.Add(WkbFeatureReader.ReadShape(mstream));
                    result.IndexMode = true;
                    IGeometry tstGeom = tstShData[0].ToGeometry();
                    IFeature ifs = result.AddFeature(tstGeom);
                    foreach (DataColumn column in result.DataTable.Columns)
                    {
                        var colNameTemp = column.ColumnName;
                        var colTypeTemp = column.DataType.ToString();
                        ifs.DataRow.BeginEdit();
                        ifs.DataRow[column.ColumnName] = dRow[column.ColumnName];
                        ifs.DataRow.EndEdit();
                    }
```

This code is not producing FID and its coming as null or wrong data, kindly suggest appropriate way to load bytes to map so that i can get FID and quality is also maintained.

**Comment by amitnkukanur** [comment]
Any Ideas?

**Comment by jany-tenaj** [comment]
Don't do `result.IndexMode = true;` if result contains features before you run this code. 
If possible show the code before the code you posted so we know what result looks like.

I just ran this code calling `result = new FeatureSet(FeatureType.Point)` beforehand and got the correct Fid.

Fid should never return null. It may return -1 if the feature was not added to a FeatureSet. 
What do you mean by wrong data?

**Comment by amitnkukanur** [comment]
1) If i dont do `result.IndexMode = true;` then i don't get points on map, only lines
2) I have called `result = new FeatureSet(FeatureType.Point)` already in program.

Wrong data means its returning -1,-2, which i am not able to understand.


1) initially `FeatureSet result= null;` is declared null
2) `result= new DotSpatial.Data.FeatureSet(FeatureType.Point);` 
3) i query database to get geometry as bytes.
4) `MemoryStream ms = new MemoryStream(tbytes);` this way i get memory stream

Then the code which is above

**Comment by jany-tenaj** [comment]
I used the following code to recreate your problem and got FID = 0 and the point was visible.

```
// create a memorystream to have data for ReadShape
            WKBWriter writer = new WKBWriter();
            var res = writer.Write(new Point(10, 20));
            MemoryStream ms = new MemoryStream(res);

            // create the FeatureSet
            var result = new FeatureSet(FeatureType.Point);
            result.IndexMode = true; // only do this if you called result = new FeatureSet directly before this, because otherwise the lists in result might get out of sync
            result.DataTable.Columns.Add("test", typeof(string));
            result.Name = "points";
            appManager.Map.MapFrame.Add(result); // add the FeatureSet to the map to be able to see the features we added

            Shape sh = WkbFeatureReader.ReadShape(ms);
            IFeature ifs = result.AddFeature(sh.ToGeometry());
            foreach (DataColumn column in result.DataTable.Columns)
            {
                ifs.DataRow.BeginEdit();
                ifs.DataRow[column.ColumnName] = "hello";
                ifs.DataRow.EndEdit();
            }

            // zoom to the layer to see the point that was added
```

So basically I can't see anything that could be wrong with your code. You'll either have to post some compileable code that lets me recreate your problem or you'll have to find your problem yourself.

**Comment by amitnkukanur** [comment]
I did as you suggested, now the FID is coming properly, Geometries are coming properly and am able to see the Point and Lines in Treeview, but the map displays nothing.

If i view in Immediate Window of Visual Studio it displays count as 2 in Map, but view is not coming.
I zoomed to farthest extent but also map has no data to display.

**Comment by amitnkukanur** [comment]
@jany-tenaj your post has helped me a lot. 
Thanks for guidance, the issue is resolved.
