### ISSUE TITLE
NET Standard version?

### ISSUE THREAD

**Issue by bdominguez** [DotSpatial/DotSpatial#1035]
We are really close on .NET Standard 2.0 release and this package is not compatible neither with the current versión that is 1.6.

It's a real problem because sometimes we want to make class libraries compatible with .NET Standard but we are tied to thid party packages that are not still compatible.

Any news?

**Comment by sindizzy** [comment]
I use DotSpatial with my ,NET4 projects, What issues are you running into?

**Comment by bdominguez** [comment]
I'm not having issues at all.

I'm saying that this package should support .NET Standard 1.6 (current) or 2.0 (released in september) because I want to target .NET Standard too but my package dependencies (like DOTSpatial) are preventing from doing it.

**Comment by bdominguez** [comment]
Now that .NET Standard 2.0 it's released do you have any news?

It's stopping me from being able to target .NET Standard 2.0 and I'm stuck on this.

**Comment by bdominguez** [comment]
I've done a simple test with the following projects:

DotSpatial.Serialization
DotSpatial.Projections
DotSpatial.NTSExtension
DotSpatial.Data

There are problems with classes in the following packages:

System.Drawing
System.ComponentModel.Composition
System.Data

There are packages that could help to fix some of this using:

https://www.nuget.org/packages/CoreCompat.System.Drawing.v2
https://www.nuget.org/packages/System.Composition

Also I think that DotSpatial uses some old APIs that should be refactored.

**Comment by tjgalama** [comment]
This issue is the only thing stopping me from using ASP.NET Core within my WebApps. 
Although .NET Standard 1.6 would be nice, I think the first priority is to fix this for .NET Standard 2.0.

**Comment by jany-tenaj** [comment]
Your welcome to fix this. Otherwise this will have to wait till one of us has time for it.

**Comment by TranstecJasonD** [comment]
Should this be done in one branch, or can we do one branch per project? I created a test 2.0 project with Projections and it compiled fine. Did not run tests. .NET Standard is unlikely to apply to anything that references WinForms (?), so there may be only a few that can be converted.

**Comment by novikov-alexander** [comment]
@TranstecJasonD does library compiles under .NET Standart without any issues?

**Comment by TranstecJasonD** [comment]
Projections compiled fine. I also tried Positioning, which is the other project I use. That has numerous issues.

**Comment by JorgenEngenNapstad** [comment]
Hey guys,

Any progress regarding this issue?

**Comment by skiiasa** [comment]
Hey guys, any progress on this? or does anyone have any alternate package suggestions for .netcore?

**Comment by TranstecJasonD** [comment]
I've tried ArcGIS for Core. It works fine or better for projections but it's really slow if you have millions of points. I'm still using the Framework version of DotSpatial except for Projections, which I compiled to Standard.

**Comment by skiiasa** [comment]
do you have your Projections code pushed in github, can i have a look if you dont mind

**Comment by TranstecJasonD** [comment]
I don't. But as far as I remember, I didn't make any code changes. I just created a new project file:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>
</Project>
`

**Comment by skiiasa** [comment]
ok Thanks ill try

**Comment by jany-tenaj** [comment]
Non ui projects are .net standard 2.0 as of commit 7ac9bef37a84114a94243aa3e90ee5e30705e088
