### ISSUE TITLE
Question - Snapping on Points

### ISSUE THREAD

**Issue by laughinggirl** [DotSpatial/DotSpatial#1037]
Question:
Hi,

I have two points in map and I want to draw lines between two.
The problem is when I click on point, the line doesn't get clicked on point. 
I am trying to create a snap around it so that when I move mouse over point, it should detect point and help me to create line between two points.

Please suggest me how to do this using pseudo code.

**Comment by sindizzy** [comment]
some good examples here: https://dotspatial.codeplex.com/documentation

**Comment by jany-tenaj** [comment]
Take a look at the [AddShapeFunction](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Plugins.ShapeEditor/AddShapeFunction.cs) in connection with the [SnappableMapFunction](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Plugins.ShapeEditor/SnappableMapFunction.cs). It shows you how to do snapping.

You could even use the SnappableMapFunction.cs as base class for your own snapping MapFunction.

**Comment by amitnkukanur** [comment]
Hi,
Just a query.
If we create a object for AddShapeFunction, this will not come to overridden functions.
Any particular way to initialise the classes so that mousemove and mouseup is called.

**Comment by amitnkukanur** [comment]
@jany-tenaj thanks for the input
