### ISSUE TITLE
Question - Shape File to SpatialLite Database

### ISSUE THREAD

**Issue by laughinggirl** [DotSpatial/DotSpatial#1042]
Hi,

I have a shape file which has more than 10,000 points with approx 160 columns.
What am doing now is looping one by one and inserting to database, with geometry converted to bytes and stored.

Its taking lot of time to update to database the shape files. I humbly request you to suggest if any method is available in dotspatial that helps us to load shape file to database quickly.

**Comment by abhaymin** [comment]
just an advise: if you use "SQL Transaction" in sql based operation, the speed will increase in the insertion of records with a commit interval of 2000 or 5000 records per inserts.
