### ISSUE TITLE
API documentation for 1.9

### ISSUE THREAD

**Issue by Spe1993** [DotSpatial/DotSpatial#1043]
Where can I get help documentation for 1.9?If not now, when will it be?

**Comment by sindizzy** [comment]
Believe you can get it at GitHub. The CHM is what i use currently.
https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation
~AGP

**Comment by jany-tenaj** [comment]
There is no API documentation for 1.9 and we won't create any. What sindizzy pointed out is for 2.0.

But you can have a look at the 2.0 version. If you don't count the replacement of DotSpatial.Topology by DotSpatial.GeoAPI and DotSpatial.NetTopologySuite there shouldn't be to many differences between 1.9 and 2.0.
