### ISSUE TITLE
display bugs

### ISSUE THREAD

**Issue by leocalvis** [DotSpatial/DotSpatial#1048]
DotSpatial version: 2.0.0 6c78470

## bug 1

DotSpatial.GeoAPI is not in MovedTypes list (DotSpatial.Serialisazation) for load DotSpatial.Topology types from old dspx

## bug 2

bug for draw polygons with filter expression

### Steps to reproduce

1. load polygon shape
2. open Layer Properties
3. add filter on Values field who is always false (do not add new category)
4. ArgumentsNullException and the map does not redraw.

## bug 3

bug when DynamicVisibility is used with DynamicVisibilityMode.ZoomedIn 

### Steps to reproduce

1. add new group
2. add layer in the new group
3. open Layer Properties on Detailed Property tab
4. set DynamicVisibilityMode to ZoomedIn
5. set UseDynamicVisibility to True
6. Apply
7. The layer disappears (DynamicVisibilityWidth has no importance)

I can fix it.

**Comment by jany-tenaj** [comment]
@leocalvis Please explain bugs 1 and 2 more clearly. Please put each bug in its own issue. 

If you can fix it you can submit pull requests with your fixes after we have determined that your findings are really bugs.
