### ISSUE TITLE
.net Core 2.0 support?

### ISSUE THREAD

**Issue by derekmoc** [DotSpatial/DotSpatial#1056]
Any thoughts of targeting this more cross platform friendly target?  
Full .net builds including Windows.Forms can now reference Core 2.0 .dlls.  I got a windows form to call a Core 2.0 .dll just fine, just need to add 'netstandard2.0' it's TargetFramewok.

**Comment by jany-tenaj** [comment]
got some things using .netstandard2.0 and the other .net 6
