### ISSUE TITLE
Gridshift file throws missing exception after being read.

### ISSUE THREAD

**Issue by AdamGeomat** [DotSpatial/DotSpatial#1058]
### Steps to reproduce

1. Get https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Projections/Nad/GridShifts/a84_nat.zip and copy to GeogTransformGrids

2. 
            GridShift.InitializeExternalGrids();
            GridShift.ThrowGridShiftMissingExceptions = true;
            double[] xy = new double[2];
            xy[0] = 140.10;
            xy[1] = -34.10;
            string[] gname = new string[1];
            gname[0] = "@A84_NAT";
            GridShift.Apply(gname, false, xy, 0, 1);

3.Debug Nadtables.cs and see how .gsb file is being iterated.  

DotSpatial version: 2 and 1.9

### Expected behaviour
should return:
xy[0]=140.1013333
xy[1]=-34.098518

### Actual behaviour

Gridshift file missing exception error pops up, after disabling this exception it just returns the initial values for xy.

**Comment by jany-tenaj** [comment]
Did you have a look at the [Grid-Shifts](https://github.com/DotSpatial/DotSpatial/wiki/Grid-Shifts) wiki entry?

**Comment by AdamGeomat** [comment]
Yes, setting GridShift.ThrowGridShiftMissingExceptions = false; stops the error but doesn't give the correct output as explained above.

**Comment by AdamGeomat** [comment]
I debugged this further,it shows ll.Lambda = 8639.379797, ll.Phi = -1853.5396 in radian which is not correct! Can any one please help with this? I need to convert between AGD84 and WGS84. Appreciate any response!

**Comment by jany-tenaj** [comment]
fixed by #1059
