### ISSUE TITLE
Required .NET Version

### ISSUE THREAD

**Issue by seanfrisbey** [DotSpatial/DotSpatial#1062]
I have been having some troubles in the application we're using DotSpatial with. I updated from .NET 4.0 to .NET 4.5.1, and the issue went away. I have no issue updating to the latest .NET, but I would like to hopefully verify that this could be causing the problem. I was getting a crash referencing clr.dll (.NET) version 4.0.30319.

**Comment by jany-tenaj** [comment]
DotSpatial is based on .Net 4.0. 

As 

> I was getting a crash referencing clr.dll (.NET) version 4.0.30319.
does not tell us anything specific we can't say where your crash comes from.
