### ISSUE TITLE
Projection Systems - Question

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1065]
Hi,

Just a small question i had regarding projection systems.
Under which object will i get to set the projection to DoNothing.

Regards,
Amit

**Comment by sindizzy** [comment]
What exactly does that mean? Can you describe an example?

**Comment by amitnkukanur** [comment]
Please find the below snapshot which i was referring to.
How to set to do nothing
![capture](https://user-images.githubusercontent.com/25892886/30770957-eae0fa46-a05a-11e7-9128-a5c852cba4e3.JPG)

**Comment by sindizzy** [comment]
try

            dsMap.ProjectionModeDefine
            dsMap.ProjectionModeReproject
