### ISSUE TITLE
WKTReader utility?

### ISSUE THREAD

**Issue by bmoregeo** [DotSpatial/DotSpatial#1066]
DotSpatial version: 1.9

### Feature description

I see that there is a WkbReader, WkbWriter, and WktReader. Am I being dense it not being able to locate a WktReader? I have a polygon wkt string that I would like to convert to a polygon dotspatial object.

Thanks!

**Comment by jany-tenaj** [comment]
All Wkt and Wkb Readers and Writers are [here](https://github.com/DotSpatial/NetTopologySuite/tree/ds_master/NetTopologySuite/IO).

**Comment by am2222** [comment]
@jany-tenaj  Hi,
Is there any 2 version? As I noticed the latest release is 1.9.

**Comment by jany-tenaj** [comment]
@am2222 Check the links section of the [main page](https://github.com/DotSpatial/DotSpatial). This as well as the code in the master branch refers to DotSpatial 2.0.
