### ISSUE TITLE
Undo Redo - Question

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1067]
Hi All,

Is there any option for undo/redo in dotspatial, if there please suggest possible ways to implement.

Regards,
Amit

**Comment by jany-tenaj** [comment]
Unless you count the undo/redo for the view extent changes there is no undo/redo in DotSpatial. If you want to implement this you'll have to keep track of the different things you want to be able to undo yourself. The process could look like this for example:

- Create a state object of the state you want to be able to undo
- Put it into the undo-list
- Change the state

If you want to undo it:
- put the changed state into the redo-list
- replace the changed state with the state from the undo-list 

If you want tot redo it:
- put the current state into the undo-list
- replace the current state with the state from the redo-list

**Comment by amitnkukanur** [comment]
Lets consider this scenario...
1) I create a Node(Point)
2) I create a second node.

now if i want to undo, we need to delete the 2 node, if we put the changed state from undo-list then am afraid dotspatial map do not allow write data because `map.canWrite` is false.

**Comment by jany-tenaj** [comment]
1. You create a point and add it to your point layer.
2. You create an undo state that contains the data of the point you just created and the information to which layer the point was added.
3. You add this state to your undo list.

On Undo you 
1. Take the state from the undo list.
2. Find the point from the layer that equals the point from the state.
3. Remove the point from the layer.
4. Add the state to the redo list.

As far as I know this has nothing to do with Map.CanWrite. It just has to do with the layer you add and remove the point from.

**Comment by amitnkukanur** [comment]
Ok, let me check on this.

**Comment by amitnkukanur** [comment]
@jany-tenaj you have any implememted snippet or pseudo which might be helpful.
