### ISSUE TITLE
Apply raster symbolizer on gdalimage

### ISSUE THREAD

**Issue by am2222** [DotSpatial/DotSpatial#1068]
Hi,
I have tried to load an image manually in map control. I can now read a tiff image using gdal, here is my code

```
>             DotSpatial.Data.Rasters.GdalExtension.GdalImage g = new DotSpatial.Data.Rasters.GdalExtension.GdalImage(@"E:\Personal\Project\Sebal\dem\dem.tif");
> map1.MapFrame.Layers.Add(g);
```

well it works and loads gdal driver, But it does not show anything in map, It seems there must be some symbolizer applied on map, But I could not figure out how to do it, Can some one pleas hep me?thanks

**Comment by am2222** [comment]
well I tried this one, It seems it can produce raster symbolizer but again nothing is shown

```
`DotSpatial.Data.Rasters.GdalExtension.GdalRasterProvider gr = new DotSpatial.Data.Rasters.GdalExtension.GdalRasterProvider();
            IRaster g= gr.Open(@"E:\Personal\Project\Sebal\dem\dem.tif");




            IMapRasterLayer mRas = new MapRasterLayer(g);
            RasterSymbolizer rSym = new RasterSymbolizer();
            rSym.Scheme = new ColorScheme(ColorSchemeType.Glaciers, g);
            mRas.Symbolizer = rSym;

            map1.MapFrame.Layers.Add(g);`
```

**Comment by jany-tenaj** [comment]
Can you see the image if you load your tif file via Map.AddLayers()?

If this works you might be better of using Map.AddLayer(fileName) instead of trying to load it manually.

If it doesn't work DotSpatial might have a problem loading the file for one reason or another. If this is a case it would be nice if you'd upload the file so we can check whether we can fix the problem.

**Comment by am2222** [comment]
@jany-tenaj  thanks for your reply,
using this code I could load image 
```
    DotSpatial.Data.Rasters.GdalExtension.GdalRasterProvider gr = new DotSpatial.Data.Rasters.GdalExtension.GdalRasterProvider();
            IRaster g= gr.Open(@"E:\Personal\Project\Sebal\dem\dem.tif");
            map1.Projection = g.Projection;
            IMapRasterLayer mRas = new MapRasterLayer(g);
            RasterSymbolizer rSym = new RasterSymbolizer();
            rSym.Scheme = new ColorScheme(ColorSchemeType.Glaciers, g);
            mRas.Symbolizer = rSym;

            map1.MapFrame.Layers.Add(g);
```

but It has some bugs which does not show image fully in different zooms.

**Comment by jany-tenaj** [comment]
I think what you're seeing is related to #824.

**Comment by am2222** [comment]
@jany-tenaj  yes exactly
