### ISSUE TITLE
Draw Line with out map refresh

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1071]
Hello
i see the measure and shape editor plugin on both when drawing line just line position have refresh but when i draw line with line string full map refresh...
i try to understand how is that work .... may u explain me the logic of code ?
thank you

**Comment by DavisMillier** [comment]
Dear @jany-tenaj 
i have class that inherit from mapfunction
i wrote some codes in 
 protected override void OnMouseMove(GeoMouseArgs e)
{
}
but is not handle !
what should i do ? :(

**Comment by jany-tenaj** [comment]
How am I supposed to know based on the info you're giving?

Explain more clearly what you want your code to and what it currently does and post the code so I can see what you're talking about.

**Comment by DavisMillier** [comment]
For first step
How can write my own map function ?
How can i active my own map function when i click on button ?
