### ISSUE TITLE
FID becoming -1

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#1075]
Hi,

I was trying to create a copy of my existing IFeature.

I have three options, 
 a) IFeature.Copy()
 b)IFeature.CopyAttributes()
 c) IFeature.Clone()

all three are doing their respective jobs, but the problem am facing is the moment IFeature is copied, FID becomes -1 or exception is thrown which is wrong.

Please suggest how to resolve.

Rgds,
Amit

**Comment by jany-tenaj** [comment]
The FID of your feature becomes -1 because the copied feature is no longer contained by a FeatureSet. As soon as you add it to a FeatureSet it should have a correct FID again.

**Comment by amitnkukanur** [comment]
Thanks for info.

I did as you suggested and FID is coming, but there is mismatch in original FID and copied FID.
I am more interested in retaining same original FID not updated one.


Regards,
Amit

**Comment by jany-tenaj** [comment]
I have no idea what you're trying to do. But to work with the original FID you'd have to use the original feature not a copy.

**Comment by amitnkukanur** [comment]
ok
