### ISSUE TITLE
Plate Carree projection (EPSG: 32662) not found

### ISSUE THREAD

**Issue by pergerch** [DotSpatial/DotSpatial#1078]
DotSpatial version: DotSpatial.Projections 1.9.0

### Expected behaviour

`ProjectionInfo.Open(@"data/dataset_32662.prj");`
or
`ProjectionInfo.FromEsriString("PROJCS[\"WGS_1984_Plate_Carree\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Plate_Carree\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],UNIT[\"Meter\",1.0]]");`

should map to Plate Carree projection or at least to 
`KnownCoordinateSystems.Projected.World.EquidistantCylindricalworld`
which is an alias.

### Actual behaviour

DotSpatial.Projections.ProjectionException: 'Projection Not Found'

### Fix

See [my fork](https://github.com/pergerch/DotSpatial/commits/master) for the fixes. Also hosting an updated nuget package on [myget](https://www.myget.org/feed/pergerch-iiasa/package/nuget/DotSpatial.Projections).

**Comment by sindizzy** [comment]
I would love this fix in the latest build.

**Comment by sindizzy** [comment]
This still doesn't work. In the demo map I add a point shapefile and then change projection to Plate Carree. I get an exception in ConvertToProjected due to the Transform being Null.
