### ISSUE TITLE
Plugins/WFSClient: Feature fetching fails on systems w NumberFormatInfo.NumberDecimalSeparator != '.'

### ISSUE THREAD

**Issue by MatthiasSchilder** [DotSpatial/DotSpatial#1081]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce
0. If not already, set system locale through control panel to one with NumberFormatInfo.NumberDecimalSeparator != '.' (i.e. german, in Germany, ',' is used) or only set the decimal seperator to something other than '.'.
1. Open DemoMap.
2. Open Extensions -> WFS.
3. Connect to http://geoserv.weichand.de:8080/geoserver/wfs?SERVICE=WFS&REQUEST=GetCapabilities&version=1.1.0.
4. Select layer bayern_ex, field geom.
5. Click open.
6. Close projection dialog (doesn't matter), close WFS dialog.
7. Open Attribute Table Editor for the new layer.

DotSpatial version: 
2.0.0-rc1

### Expected behaviour

1 feature should be fetched from the WFS. Attribute Table Editor should contain 1 feature.

### Actual behaviour

No features are fetched. Table is empty.
This is because of parsing of coordinates from the XML-Response-Stream fails because of a System.FormatException (see attached screenshot). I propose to extend the Convert.ToDouble-calls in WFSClient by CultureInfo.InvariantCulture.

![screenshot 2017-10-25 20 17 40](https://user-images.githubusercontent.com/313898/32017509-3e20d7a0-b9c7-11e7-88f4-c48b0a63c43b.png)

**Comment by MatthiasSchilder** [comment]
See my pull request #1082.

**Comment by jany-tenaj** [comment]
Fixed in #1082.

@MatthiasSchilder Thanks for submitting this fix.
