### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by MarcDenman** [DotSpatial/DotSpatial#1086]
It looks like within the Links section of the Readme.md there are a couple typos.

`Continious integration build` should be  `Continuous integration build`
`[Continiuos Integration builds Nuget feed](https://ci.appveyor.com/nuget/dotspatial)` should be `[Continuous Integration builds Nuget feed]()https://ci.appveyor.com/nuget/dotspatial`

I would have created a PR but after reading the contributing.md I am posting here instead

**Comment by jany-tenaj** [comment]
Hey, thanks for point this out.

For such a small thing you could have simply provided a PR. The way pointed out in the contributing.md makes more sense for bigger issues.
