### ISSUE TITLE
Migrating from 1.7 to 2.0 Questions

### ISSUE THREAD

**Issue by tlillys** [DotSpatial/DotSpatial#1087]
Novice geospatial programmer migrating a large code using 1.7 to 2.0 and running into a variety of issues.   Not sure if this is the correct venue to ask them.  Please advise

Is there any guidance out there that would help a migration from 1.7 to 2.0?  I read some brief tips in the Wiki for the jump from 1.9 to 2.0.  Anything addressing 1.7 to 1.9?

I have been formulating changes as I go using the DotSpatial documentation, but not 100% the changes will work just because Visual Studio says its happy with it.  There are a lot of changes to make, but similar ones are coming up so I've collected the major ones.

1) Checking intersection between to polygon features - I ran into a similar problem with a Coordinate intersecting a polygon Feature - my solution was to create an Envelope from the Coordinate and use the IFeature.Intersects() method.  How is this accomplished with two polygon Features?

2) Getting the intersection or difference between to polygon features -  1.7 code used 
`feature1 = feature2.Intersection(feature3);` 
Migrated to 
`featrue1 = feature2.Intersection(feature3.Geometry);`
Will this generate the same result both Intersection() and Difference()?

3) Area of polygon Feature - The 1.7 code used the feature.Area() method.  My solution with 2.0 was to use DotSpatial.Plugins.Taudem.Utils.AreaOfPart(feature,0);  Is this correct?  Is there a "better" approach?

4) Centroid of polygon feature - IFeature.Centroid() is no longer available - migrated to IFeature.Geometry.Centriod

Thanks
Ted

**Comment by jany-tenaj** [comment]
Hey Ted,

I don't think the differences between 1.7 and 1.9 will cause you ay trouble.

The problems you pointed out come from the fact that Feature no longer inherits from Geometry so you can't apply Geometry functions tho Features any more. So basically if your missing something from Feature check out whether you can find it in Feature.Geometry.

1. You should be able to get the intersection of two polygons via feature1.Geometry.Intersection(feature2.Geometry).

2. If I remember correctly in both cases you should get a new feature with the intersection as geometry.

3. Again Feature no longer contains the Geometry methods. So simply switch to feature.Geometry.Area() and everything works.

4. That's the right way to go about it. ^^

Just add any other questions you're stumbeling on here.

**Comment by tlillys** [comment]
Thanks jany-tenaj!
Here's another - Used to use properties of Feature.Envelope to get the minimum and maximum X and Y of the Feature (e.g., `aFeature.Envelope.Minimum.X`).  Found MinX, MinY, et al, with Extent class but not sure how to get from Feature to Extent.
Ted

**Comment by jany-tenaj** [comment]
This was moved to Feature.Geometry also. Check out Feature.Geometry.EnvelopeInternal.Minimum.

In case you need the extent for a Feature envelope just use Feature.Geometry.EnvelopeInternal.ToExtent().

**Comment by tlillys** [comment]
Not sure how to solve this problem.  I have a method which converts an Extent from one ProjectionInfo to another by first converting bounding corners of the Extent to Coordinates and then re-projecting each Coordinate.  The problems with the current approach are the BottomLeft() and TopRight() methods don't exists for IEnvelope in 2.0.  The two methods are given below:

`public static Extent ConvertExtent(Extent extent, ProjectionInfo pStart, ProjectionInfo pEnd)`
`// Convert the projection of an extent from pStart to pEnd`
`        {
            Coordinate ll = ConvertCoordinate(extent.ToEnvelope().BottomLeft(), pStart, pEnd);
            Coordinate tr = ConvertCoordinate(extent.ToEnvelope().TopRight(), pStart, pEnd);
            return new Envelope(ll, tr).ToExtent();
        }
`
`public static Coordinate ConvertCoordinate(Coordinate coord, ProjectionInfo pStart, ProjectionInfo pEnd)`
`// Convert coordinate from one projection (pStart) to another (pEnd)`
`        {
            double[] xy = new double[2];
            xy[0] = coord.X;
            xy[1] = coord.Y;
            double[] z = new double[1];
            z[0] = 1;
            Reproject.ReprojectPoints(xy, z, pStart, pEnd, 0, 1);
            return new Coordinate(xy[0], xy[1]);
        }
`

**Comment by jany-tenaj** [comment]
This should do the same without having to depend on Envelope.

```
Coordinate coordMin = ConvertCoordinate(new Coordinate(extent.MinX, extent.MinY), pStart, pEnd);
Coordinate coordMax = ConvertCoordinate(new Coordinate(extent.MaxX, extent.MaxY), pStart, pEnd);

return new Extent(coordMin.X, coordMin.Y, coordMax.X, coordMax.Y);
```

**Comment by tlillys** [comment]
Not strictly a DotSpatial question, but is there documentation on GeoAPI and NetToplogySuite?  I see XML files that have information on classes and methods - is there a convenient way to view/search that information?

**Comment by jany-tenaj** [comment]
You could build a doc file from the [sandcastle file](https://github.com/DotSpatial/NetTopologySuite/tree/ds_master/Sandcastle) but I didn't see any doc file that could be downloaded and we didn't build one when we forked it.

**Comment by tlillys** [comment]
Thanks @jany-tenaj , appreciate your help.

Here is my next puzzler.  It looks like the old code is getting the length of a polyline feature:
`            foreach (Feature f in ifsNewFlowlines.Features)`
`            {`
               ` MultiLineString aline = new MultiLineString(f.BasicGeometry);`
                `StreamLengthInKm = aline.Length;`
                `StreamLengthInKm = StreamLengthInKm / 1000;`
                `f.DataRow["LENGTHKM"] = StreamLengthInKm;`
            `}`
The new constructor for MultiLineString is different and not sure how to get the arguments correctly.
TIA

**Comment by jany-tenaj** [comment]
I think your code would have to look like this to create a new MultiLineString from the given Geometry.

```
foreach (Feature f in ifsNewFlowlines.Features)
            {
                var lines = new List<ILineString>();

                for (int i = 0; i < f.Geometry.NumGeometries; i++)
                {
                    var geo = f.Geometry.GetGeometryN(i) as ILineString;
                    if (geo != null) lines.Add(geo);
                }

                if (lines.Count > 0)
                {
                    MultiLineString aline = new MultiLineString(lines.ToArray());
                    StreamLengthInKm = aline.Length;
                    StreamLengthInKm = StreamLengthInKm / 1000;
                    f.DataRow["LENGTHKM"] = StreamLengthInKm;
                }
            }
```

This only works if your geometries are ILineStrings. If they are polygons or points you won't get a length.

If your geometries are ILineStrings anyway you should get the same result from f.Geometry.Length without having to create a new MultiLineString.

**Comment by tlillys** [comment]
The geometries are always polylines (similar to ILineStrings?) for this FeatureSet

**Comment by tlillys** [comment]
Another conversion problem.  I was able to address the issues on the right hand side, but the assignment itself has me stumped.
Original line where f is an IFeature:
`f.BasicGeometry.Coordinates = DotSpatial.Topology.CoordinateArrays.RemoveRepeatedPoints(DotSpatial.Topology.Simplify.TopologyPreservingSimplifier.Simplify((IGeometry)f.BasicGeometry, (Double)1.0).Coordinates);`

The updated line:
`f.Geometry.Coordinates = CoordinateArrays.RemoveRepeatedPoints(NetTopologySuite.Simplify.TopologyPreservingSimplifier.Simplify((IGeometry)f.Geometry, (Double)1.0).Coordinates);`
The assignment to Coordinates is the problem.

**Comment by tlillys** [comment]
Another conversion problem.  I was able to address the issues on the right hand side, but the assignment itself has me stumped.
Original line where f is an IFeature:
`f.BasicGeometry.Coordinates = DotSpatial.Topology.CoordinateArrays.RemoveRepeatedPoints(DotSpatial.Topology.Simplify.TopologyPreservingSimplifier.Simplify((IGeometry)f.BasicGeometry, (Double)1.0).Coordinates);`

The updated line:
`f.Geometry.Coordinates = CoordinateArrays.RemoveRepeatedPoints(NetTopologySuite.Simplify.TopologyPreservingSimplifier.Simplify((IGeometry)f.Geometry, (Double)1.0).Coordinates);`
The assignment to Coordinates is the problem.

**Comment by jany-tenaj** [comment]
Assigning Geometry.Coordinates is no longer possible because NTS made the Coordinates array readonly.
If you want to change the geometry you have to build a new geometry from the changed coordinates and assign it to f.Geometry.

**Comment by HyperDeeps** [comment]
Hello,

If my program is working fine with DotSpatial 1.7 is necessary to migrate to 1.9 or 2.0 ?

What is better in this version ?

1.7 is stable for me.

**Comment by jany-tenaj** [comment]
If everything works for you, you don't have to switch.
You can see the changes for 2.0 in the [changelog](https://github.com/DotSpatial/DotSpatial/blob/master/Changelog.md).
For the older versions you can see the changes on [Codeplex](https://dotspatial.codeplex.com/releases/view/621128).

**Comment by tlillys** [comment]
Something similar to my previous question on Geometry.Coordinates.  The 1.7 code I'm porting had the following statement:

`lineFeature.Coordinates.Add(coord);`

How do I go about appending a coordinate to the array of coordinates and then assigning them to the Feature Geometry?

**Comment by jany-tenaj** [comment]
I went and added all the coordinates from the geometry to a List then added the new coordinate to the List. Then I converted the List back to array and used this array to create a new geometry that I assigned to Feature.Geometry.

**Comment by tlillys** [comment]
Thanks @jany-tenaj.  Is it necessary to know what type of geometry to create?  Line, polygon, etc.?

**Comment by jany-tenaj** [comment]
Yes you need to know what type of geometry you have to create. 
For polygons you'll have to handle each shell and hole seperately. Don't put them all in one list because you can't use that list to create a polygon from it. For lines or multipoint geometrys a single list should be enough.

**Comment by tlillys** [comment]
Looking for DotSpatial.Plugins.Ribbon in the current version.  Where might I find it.
Thanks
Ted

**Comment by jany-tenaj** [comment]
It doesn't seem to exist.

**Comment by tlillys** [comment]
Was it incorporated elsewhere? I have to see what was being used in the previous version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
