### ISSUE TITLE
LoadExtensions() crash

### ISSUE THREAD

**Issue by ekramer121** [DotSpatial/DotSpatial#1088]
### Steps to reproduce

1. Create a winforms app.
2. Wire up the application manager, header, statusbar, toolbars, menu bar, map, legend and so forth
3. Start application and call applicationManager.LoadExtensions(); after InitializeComponents() in form.

DotSpatial version: 1.9

### Expected behaviour
I assume that the form should load correctly and be usable.

### Actual behaviour

The application crashes at LoadExtensions() with the stack trace as noted below. Looking in the code repository at MenuBarHeaderControl.cs:line 284 the offending line is just:             _tsPanel.Controls.Clear();

Presumably either the _tsPanel itself is null, or the Controls collection is null. Looking around I think the problem is that I am not using a toolstrip container, therefore there are no toolstrippanels. However the crash itself doesn't give much in the way of info to help with it. I also don't recall seeing anything about tool strip containers in the examples I have come across. 

I don't know if this will help or not. But I thought I'd report it.

   at DotSpatial.Controls.Header.MenuBarHeaderControl.LoadToolstrips() in g:\TeamCity\buildAgent\work\8dcaae3a01f0640d\Trunk\DotSpatial.Controls\Header\MenuBarHeaderControl.cs:line 284
   at DotSpatial.Controls.SpatialHeaderControl.ApplicationManagerOnExtensionsActivated(Object sender, EventArgs eventArgs) in g:\TeamCity\buildAgent\work\8dcaae3a01f0640d\Trunk\DotSpatial.Controls\SpatialHeaderControl.cs:line 58
   at DotSpatial.Controls.AppManager.OnExtensionsActivated(EventArgs ea) in g:\TeamCity\buildAgent\work\8dcaae3a01f0640d\Trunk\DotSpatial.Controls\AppManager.cs:line 439
   at DotSpatial.Controls.AppManager.LoadExtensions() in g:\TeamCity\buildAgent\work\8dcaae3a01f0640d\Trunk\DotSpatial.Controls\AppManager.cs:line 411
Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by sindizzy** [comment]
Here is what has worked for me:
1. Create a WinForm application and do NOT add any controls. It should be a blank form.
2. Add a single DotSpatial AppManger control to your form. This control is not visible in the form at run time.
3. Add this code:

```
'if you are using the AppManager then DO NOT add any controls. All you need is the Form and the AppManager.
Imports System.ComponentModel.Composition
Imports System.Linq
Imports DotSpatial.Data
Imports DotSpatial.Controls
Imports DotSpatial.Symbology
Imports System.Drawing.Drawing2D

Partial Public Class Form1
    Inherits Form
    <Export("Shell", GetType(ContainerControl))> _
    Private Shared Shell As ContainerControl
    Public Sub New()
        ' This call is required by the designer.
        InitializeComponent()

        ' Add any initialization after the InitializeComponent() call.
        If DesignMode Then Return
        Shell = Me
        AppManager1.LoadExtensions()
    End Sub

End Class
```
