### ISSUE TITLE
Position buffer question

### ISSUE THREAD

**Issue by ekramer121** [DotSpatial/DotSpatial#1092]
This is more a question than anything else. I'm just not sure if this is the correct place to ask. If it isn't, then I apologize in advance.

Essentially I have a given position (in my test case it is Disney World) in latitude/longitude and I want to create an X meter circle or buffer around it and get the points that make up this buffer. Googlling seems to reveal that it should be as simple as creating a Point for the lat/long coordinate and calling the 'Buffer()' method.  Unfortunately the results I'm getting back aren't making any sense. They are not in lat/lon and when i try to reproject them I get different numbers and a lot of NaN responses but no lat/lon coordinates. 

`
var precisionModel = new PrecisionModel(PrecisionModelType.Floating);
var factory = new GeometryFactory(precisionModel, 4326);

var position = new DotSpatial.Positioning.Position(new DotSpatial.Positioning.Latitude(dialog.CenterPoint.Y), new DotSpatial.Positioning.Longitude(dialog.CenterPoint.X));
var point = factory.CreatePoint(new Coordinate(position.Longitude.DecimalDegrees, position.Latitude.DecimalDegrees));
var buffer = point.Buffer(500);

var bufferFeatureSet = new FeatureSet();
var bufferFeature = bufferFeatureSet.AddFeature(buffer);
bufferFeatureSet.Reproject(KnownCoordinateSystems.Geographic.World.WGS1984);
bufferFeatureSet.InvalidateVertices();

`

I suppose part of the problem must be that I don't know what the projection is for the Buffer() call. So trying to reproject it to another is fruitless. Can anyone kick me in the right direction here?

**Comment by sindizzy** [comment]
The buffer is in the units of the projection. In this case it's degrees. What you need to do is do your buffering in a projection like Equidistant Azimuthal. First take your point and reproject to the EA projection. Then create your buffer. The unit for EA should be meters.
