### ISSUE TITLE
there is no LayerManager control in VS2015?

### ISSUE THREAD

**Issue by qq2898** [DotSpatial/DotSpatial#1097]
I have use Dotspatial 1.9 in VS2015, and add items for toolbox, but after add dotspatial.controls.dll, there is no LayerManager shows,while I tried in Sharpdevelop, it shows in tools. what's the matter?

**Comment by jany-tenaj** [comment]
As far as I can tell LayerManager resides in DotSpatial.Symbology.dll. I'm not sure why you expect it to show up when you load DotSpatial.Controls.dll.
