### ISSUE TITLE
Feature Hide On zoom In

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1100]
hello
when i zoom in point feature hide that label just shown
when zoom out it show again
what is the problem ?

**Comment by sindizzy** [comment]
check label visibility options.

**Comment by DavisMillier** [comment]
sry @sindizzy ,thank you for answer but i explain problem very bad ...
when i zoom after some zoom in point feature hide .... but label is shown
when i zoom back (zoom out) point feature show again !

**Comment by sindizzy** [comment]
no code or example given so could be anything.
