### ISSUE TITLE
Move Vertex and Select Line

### ISSUE THREAD

**Issue by Veys42** [DotSpatial/DotSpatial#1101]
Hello Everyone,
I want to move vertex on Polygon.Hovewer, I didnt find any solution. I dont understand how ShapeEditor is used. Please Help me.. Could anyone give me any example please ?

**Comment by sindizzy** [comment]
https://dotspatial.codeplex.com/documentation

**Comment by amitnkukanur** [comment]
Its already present in dotspatial

**Comment by Veys42** [comment]
I have found how vertex is moved.

MoveVertexFunction m = new MoveVertexFunction(map1);
            for(int i = 0; i < map1.GetFeatureLayers().Count(); i++)
            {
                if(map1.GetFeatureLayers().ElementAt(i).IsSelected == true)
                {
                    m.Layer = map1.GetFeatureLayers().ElementAt(i);
                    break;
                }
            }

            map1.Cursor = Cursors.Hand;

            map1.MapFunctions.Add(m);
            m.Activate(); 

 Have to I select only one layer  ? and I want to select line on polygon. I wonder whether it's possible or not.

**Comment by sindizzy** [comment]
Check out the documentation to check for the geometry type. You can also determine what layer you want by checking the properties of each layer in your loop. Maybe based on layer name or layer feature count or layer source.
