### ISSUE TITLE
Creating a Featureset from polygon error!

### ISSUE THREAD

**Issue by htekin42** [DotSpatial/DotSpatial#1103]
I am new to Spatial Programming and DotSpatial. 

I am trying to create shapefile with this code
`using DotSpatial.Data;
using DotSpatial.Topology;

        private void button1_Click(object sender, EventArgs e)
        {
            Random rnd = new Random();
            Polygon[] pg = new Polygon[100];
            Feature f = new Feature();
            FeatureSet fs = new FeatureSet(f.FeatureType);
            for (int i = 0; i < 100; i++)
            {
                Coordinate center = new Coordinate((rnd.Next(50) * 360) - 180, (rnd.Next(60) * 180) - 90);
                Coordinate[] coord = new Coordinate[50];
                for (int ii = 0; ii < 50; ii++)
                {
                    coord[ii] = new Coordinate(center.X + Math.Cos((ii * 10) * Math.PI / 10), center.Y + (ii * 10) * Math.PI / 10);
                }
                coord[49] = new Coordinate(coord[0].X, coord[0].Y);
                pg[i] = new Polygon(coord);
                fs.Features.Add(pg[i]);
            }
            fs.SaveAs("C:\\Temp\\test.shp", true);
        }`

it gives me error on fs.Features.Add(pg[i]);

It says  "cannot convert from 'DotSpatial.Topology.Polygon' to 'DotSpatial.Data.IFeature'	

I am using DotSpatial 2.0

Thanks

**Comment by jany-tenaj** [comment]
You're not using 2.0. 2.0 doesn't contain DotSpatial.Topology.

Use fs.Features.Add(new Feature(pg[i])); to create a feature from your polygon, which can be added to the feature list.

**Comment by htekin42** [comment]
Sorry. I am using DotSpatial 1.9 

I added the fs.Features.Add(new Feature(pg[i])); but it still gives me error and it gives error "cannot convert from 'DotSpatial.Topology.Polygon' to 'DotSpatial.Data.Shape'".

Thanks

**Comment by jany-tenaj** [comment]
Consider using DotSpatial 2.0 instead of 1.9. There the suggested line works.

In 1.9 you might have to write it like this: `fs.Features.Add(new Feature(pg[i] as IBasicGeometry));` but I'm not sure as I don't have a 1.9 system any longer to test this.

**Comment by jany-tenaj** [comment]
@htekin42 can we close this?

**Comment by htekin42** [comment]
Yes I solved the problem. Thanks
