### ISSUE TITLE
SetSelectable Plugin Not Included in Release Build

### ISSUE THREAD

**Issue by PJ-Thompson** [DotSpatial/DotSpatial#1106]
Hello:

It appears that the SetSelectable plugin is not included in the release build.  Looks like the wrong OutputPath is specified for the release build of DotSpatial.Plugins.SetSelectable.  When I recompile DotSpatial from source, the plugin is available locally and appears to work fine.

**OutputPath** is set to _“bin\Release\”_ in _DotSpatial.Plugins.SetSelectable.csproj_ for the release build.  If unintentional, modifying to _“..\bin\Release\DotSpatial.Plugins.SetSelectable\”_ would correct this behaviour.  Might be helpful for users who are only working with the release builds.

Love version 2.0, keep up all the great work,

Pete

**Comment by jany-tenaj** [comment]
Thanks for letting us know. Nice to know you like version 2.
