### ISSUE TITLE
what is the proper way of actualization of feature layer based on attribute update ?

### ISSUE THREAD

**Issue by fastfoot** [DotSpatial/DotSpatial#1109]
what is the proper way of actualization of feature layer based on attribute update ? how to cope with changing of few feature's attributes on a layer with huge number of objects ? ( how to prevent of full redrawing ? )

**Comment by jany-tenaj** [comment]
The only way I know not to redraw everything is to add the region you want to redraw. This could be done via [Map.RefreshMap(Rectangle clipRectangle)](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Controls/Map.cs#L958). You'd have to pass the region of the feature you updated. If there is more than one feature you'd have to call the method for each feature.

You could also check whether [`MapFrame.Initialize(List<Extent> regions)`](https://github.com/DotSpatial/DotSpatial/blob/48e022151f92834572a95efdbada45b5e64d9488/Source/DotSpatial.Controls/MapFrame.cs#L687) works for you.
You could hand it the regions of all the features whose attributes were updated.

**Comment by fastfoot** [comment]
thx, 
but I think my case is little different. Updates of attributes comes to my app asynchronously ( ie by websocket ) , then I need to make symbol on map refreshed according to new values of attribute ( just recalculate of category and redraw it on the map). the same in case of updates of location of objects, how to update location of single object without refreshing whole layer or region ( because it may contain a lot of objects )

**Comment by jany-tenaj** [comment]
There is only the possibility to redraw everything or by region. So either figure out the regions of the features whose attributes you updated or redraw everything.

The second case is a little harder. You'll have to remember the old location of your updated object as well as the new location and redraw both to make sure the object is no longer shown in the old place but shown in the new one.

**Comment by fastfoot** [comment]
clear, thx,
