### ISSUE TITLE
Question : How can I select a point feature without having to click in the exact center?

### ISSUE THREAD

**Issue by jaehongy88** [DotSpatial/DotSpatial#1110]
DotSpatial version: 1.9

Hi, everyone
I have two questions. 
1st : How can I select a point feature without having to click in the exact center?
I want to specify selectable region.  

2nd : When I select a feature, I'd like to select only one feature that exists on top layer.
Please suggest how to resolve.

Kind regards,
Jaehong

**Comment by sindizzy** [comment]
Have you tried a spatial search over the coordinates that are clicked?

**Comment by jaehongy88** [comment]
hello sindizzy, thanks for the reply. 
If spatial search is about exploring all of the Polygon, Polyline, Point features present in a coordinate, 
I have naver tried. because this approach has naver been thought about.
If you don't mind, Can you give me an example code(C#) of your proposed method? plz.. help me.
