### ISSUE TITLE
LineString Offset

### ISSUE THREAD

**Issue by htekin42** [DotSpatial/DotSpatial#1111]
Dear All,

I have a Linestring and I want to make offset it to 10m right and 10m left and get the Linestring to make some calculation according to new lines. But when I check the LineString.offset method. It is not implemented yet. How can I do it? Thanks

I am using DotSpatial 1.9 on my current Project and I will going to use it little bit more before implementing the DotSpatial 2.0

Thanks

**Comment by jany-tenaj** [comment]
Can you add an image that describes what exactly you are trying to do?

**Comment by htekin42** [comment]
![screenshot_2018-01-24-19-33-34](https://user-images.githubusercontent.com/10863737/35344182-8769364c-013d-11e8-8393-4c18803e92a1.jpg)
Here is what I want to do. I decleare linestring with 600-700 points and I want to offset it. 
Thanks

**Comment by jany-tenaj** [comment]
Based on this I'd say just make a copy of the original linestring and add/ subtract 10 m to each points x value to get your new lines.

**Comment by htekin42** [comment]
They are only like this I have different set of data and they have different angles. I have to make calculations to shift it 90 degrees and 270 degrees position.

**Comment by jany-tenaj** [comment]
I'm not sure what your problem is. As far as I understand it, shifting 90 degrees would mean to add something to the x values of your points and shifting 270 degrees would mean to subtract something from the x values of your points.

If you do this for all the points of your lines it shouldn't make a difference what angles your lines use because they get moved as a whole.

**Comment by htekin42** [comment]
I need to do something like this

![image](https://user-images.githubusercontent.com/10863737/35387195-d163e894-01df-11e8-8667-fd851670f912.png)

I create Linestring and I need to offset each linesegment in linestring for a specific distance. I mean original line segment to offset one distance should be what I want. not the pint

**Comment by jany-tenaj** [comment]
Based on this explanation I'd say check out [Buffer](https://github.com/DotSpatial/GeoAPI/blob/ds_master/GeoAPI/Geometries/IGeometry.cs#L183).

With the following code you'll get a one sided buffer of your line that consists of your original line the offset line and 2 lines that link your old and new line. You'd only have to remove the parts you don't need.

 ```
 Dim para As IBufferParameters = New BufferParameters With {
                        .EndCapStyle = EndCapStyle.Flat,
                        .IsSingleSided = True,
                        .JoinStyle = JoinStyle.Mitre
                    }

Dim newGeo As IGeometry = feature.Geometry.Buffer(10, para)
```

You could also remove the IsSingleSided to get both offset lines at once.

**Comment by jany-tenaj** [comment]
@htekin42 can we close this?

**Comment by htekin42** [comment]
I could not solve this problem. I am using C# and I could not find the IBufferParameters. Thanks

**Comment by jany-tenaj** [comment]
Have you included DotSpatial.GeoApi in your form?

**Comment by htekin42** [comment]
Yes, I added the GeoAPI but when I tried to write IBufferParameter, it gives error and also it gives error for buffer

**Comment by jany-tenaj** [comment]
Sorry, I just saw, that you wrote that you were still using DotSpatial 1.9. GeoAPI was added in 2.0, so it makes sense you can't find anything.

In 1.9 you could use feature.Buffer(10) to create a buffer, but you can't set the parameters from above.

**Comment by htekin42** [comment]
Ok. I got it jany. Thanks.
Also I have an issue #1122 and couldn’t find anything? Do you know anything about filtering?

**Comment by jany-tenaj** [comment]
Sorry but I've got no idea.
