### ISSUE TITLE
zoom to layer

### ISSUE THREAD

**Issue by jorgedy** [DotSpatial/DotSpatial#1113]
hello everyone. I have a problem with my thesis. please help me. 
I used dotspatial for displaying a shapefile, now my problem is I want to zoom a specific layer like in tools that there is a zoom to layer button. what is the code in zoom to layer? I am using vb.net . please help me

**Comment by jany-tenaj** [comment]
Check out the [ZoomToLayer](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Controls/DefaultMenuBars.cs#L568) method.

**Comment by jorgedy** [comment]
hello thanks for the reply. but i am using vb.net windows form. can you convert this code to vb.net? please i help.

  private void ZoomToLayer(IMapLayer layerToZoom)

        {

            const double Eps = 1e-7;

            Envelope layerEnvelope = layerToZoom.Extent.ToEnvelope();



            if (App.Map.MapFrame.ExtendBuffer)

            {

                layerEnvelope.ExpandBy(layerEnvelope.Width, layerEnvelope.Height);

            }



            if (layerEnvelope.Width > Eps && layerEnvelope.Height > Eps)

            {

                layerEnvelope.ExpandBy(layerEnvelope.Width / 10, layerEnvelope.Height / 10); // work item #84

            }

            else

            {

                double zoomInFactor = 0.05; // fixed zoom-in by 10% - 5% on each side

                double newExtentWidth = App.Map.ViewExtents.Width * zoomInFactor;

                double newExtentHeight = App.Map.ViewExtents.Height * zoomInFactor;

                layerEnvelope.ExpandBy(newExtentWidth, newExtentHeight);

            }



            App.Map.ViewExtents = layerEnvelope.ToExtent();

        }



        /// <summary>

        /// Zoom to the currently selected layer

        /// </summary>

        /// <param name="sender">Sender that raised the event.</param>

        /// <param name="e">The event args.</param>

        private void ZoomToLayerClick(object sender, EventArgs e)

        {

            var layer = App.Map.Layers.SelectedLayer;

            if (layer != null)

            {

                ZoomToLayer(layer);

            }

        }

**Comment by jorgedy** [comment]
gotcha! thank you so much jany.. my thesis now is working love yah'!
