### ISSUE TITLE
SHAPEFILE 3D

### ISSUE THREAD

**Issue by maurizio737** [DotSpatial/DotSpatial#1115]
**This is a simple code to create a Point in 3D on .shp, 
but the Shape that creates is in 2D without the Z, what is wrong?**

    FeatureSet fs = new FeatureSet(FeatureType.Point);
    Point Pt = Point(1, 2, 3);
    Feature f = new Feature(Pt);
    fs.Features.Add(f);
    fs.SaveAs(@"C:\Example.shp", true); # #

**Comment by sindizzy** [comment]
What other FeatureTypes are there? You have to specifically build a 3D shapefile before you can populate it.

**Comment by jany-tenaj** [comment]
Add fs.CoordinateType = CoordinateType.Z as second line.

**Comment by maurizio737** [comment]
Thanks
