### ISSUE TITLE
Problems with Sqlite and ReflectionHelper in DotSpatial.Serialization

### ISSUE THREAD

**Issue by UliEgger** [DotSpatial/DotSpatial#1116]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Development of application using both SQLite and DotSpatial
2. Use DotSpatialSerialization to serialize or deserialize objects
3. Use SQLITE Create Table Command
4. A failure occurs, saying that the table aready exists, which is not true

DotSpatial version: 

### Expected behaviour

There should be no side effects on sqlite

### Actual behaviour

See Point No. 4 in Repro

![grafik](https://user-images.githubusercontent.com/8180924/35507293-87c1f90a-04ec-11e8-90f9-f0fa721698b0.png)

I debugged into the DotSpatial code and commeted sections until I found that it is class RelectionHelper, used by SerializationMap that causes the problem.

My suggestion is that SerializationMap instances must be added manually to the static map instead of using ReflectionHelper.

Alternatively, we could use a white list in ReflectionHelper, where it can be defined in which assemblies derived types of SerializationMap might occur.

**Comment by jany-tenaj** [comment]
What version of DotSpatial are you using?

Check out DotSpatial.Plugins.SpatiaLite in the master branch. I know layers created with this plugin can be serialized into dspx files. 

If you continue to have the problem please post the code you use to cause your error so we'll be able to recreate it.

**Comment by UliEgger** [comment]
We are using an own fork of DotSpatial with version number 2.0.0

Do you mean we should use another technology to serialize layer properties ?
We want to store layer properties in a string that we can store in the database.

We have fixed the problem in our fork. We would also like to share the change if there is any interest.

Currently, we do not use any class derived from SerializationMap. So we can avoid having the static constructor in SerializationMap. If we would add any SerializationMap, we'd have to do it by our code, using a new static method e.g. 

public static void SerializationMap.AddSerializationMap(SerializationMap map)

This would be our proposal how to do it in general.

**Comment by jany-tenaj** [comment]
If you build your own layer/featureset to load SQLite data into DotSpatial I'm suggesting you make sure it works the same way the other layers changed in [Expanded dxf file loading and dspx deserialization #1061](https://github.com/DotSpatial/DotSpatial/pull/1061) work. Those were all layers that had problems with deserialization.

**Comment by UliEgger** [comment]
We are not using DotSpatial.Serialization to write to the Sqlite database. We only use it to store the layer properties that the user specifies in order to make these properties permanent. So we create a string via an Xml document. Here is the code how we create the XmlDocument. The failure of the Sqlite database is a pure side effect.


        protected XmlDocument GetLayerDefinition(IEnumerable<ItwhFeatureLayer> featureLayers)
        {
            
            var serializer = new XmlSerializer();
            var layoutXmlDoc = new XmlDocument();
            var root = layoutXmlDoc.CreateElement("ItwhLayerDefinition");
            layoutXmlDoc.AppendChild(root);
            
            foreach (var l in featureLayers)
            {
                var element = layoutXmlDoc.CreateElement("FeatureLayer");
                element.SetAttribute("Name", l.Name);
                element.SetAttribute("Symbology", serializer.Serialize(l.Layer.Symbology));
                element.SetAttribute("VisibilityMode", serializer.Serialize(l.Layer.DynamicVisibilityMode));
                element.SetAttribute("VisibilityWidth", serializer.Serialize(l.Layer.DynamicVisibilityWidth));
                element.SetAttribute("UseDynamicVisibility", serializer.Serialize(l.Layer.UseDynamicVisibility));
                element.SetAttribute("ShowLables", serializer.Serialize(l.Layer.ShowLabels));
                if (l.Layer.LabelLayer != null)
                {
                    element.SetAttribute("LabelSymbology", serializer.Serialize(l.Layer.LabelLayer.Symbology));
                    element.SetAttribute("LabelVisibilityMode",
                        serializer.Serialize(l.Layer.LabelLayer.DynamicVisibilityMode));
                    element.SetAttribute("LabelVisibilityWidth",
                        serializer.Serialize(l.Layer.LabelLayer.DynamicVisibilityWidth));
                    element.SetAttribute("LabelUseDynamicVisibility",
                        serializer.Serialize(l.Layer.LabelLayer.UseDynamicVisibility));
                }
                root.AppendChild(element);
            }
            return layoutXmlDoc;
        }

**Comment by jany-tenaj** [comment]
Based on the facts you've posted I have no idea what you're talking about.

What is the problem ReflectionHelper causes?

Can you give a complete test case that explains your problem?

**Comment by UliEgger** [comment]
I have no explanation for the mechanism. I only experimentally digged down into the DotSpatial code, commenting certain passages until at the end I found avoiding ReflectionHelper finally solved my problem.

The problem it causes is a wrong behaviour of the SQLite database engine.
In our case, this showed up when using the SQL command ADD TABLE.

Unfortunately I do not have a small example application to show the problem.

My suggestion would be that SerializationMap does not automatically scan all assemblies for derived classes but it should be the responsiblity of the develper who creats a derived class to create the instance himself and add it to the Mapping via a suitable static method of SerializationMap.

**Comment by jany-tenaj** [comment]
We could try teamviewer.

**Comment by UliEgger** [comment]
ok, do you want to call me via skype (uli.egger@posteo.de) or my landline phone 076148087174 ?

**Comment by jany-tenaj** [comment]
Based on the teamviewer session we can say that changing the DotSpatial code doesn't make sense.

**Comment by UliEgger** [comment]
Hi Jany,

by experimentally limiting the dlls scanned by ReflectionHelper, I found the reason of the failure in our installation. We have some of the dll files as a duplicate in a subfoder. As soon as ReflectionHelper walks through such a duplicate, the failure is there. So then I think we need to change our installation.

Thank you very much,
Uli

**Comment by jany-tenaj** [comment]
@UliEgger Good to know you found it.
