### ISSUE TITLE
Load shape file with thread in back ground

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1117]
Hello dear
I need to know how can i load SHP file with Thread ?
I have 10 shp file in hard driver when i run application it is make delay to run application
Any idea about my problem ?

**Comment by DavisMillier** [comment]
Hello @jany-tenaj 
Can you help me about this ?
And i need to load map layer after application load completely

**Comment by MatthiasSchilder** [comment]
> I need to know how can i load SHP file with Thread ?

`        public static void LoadShapefileInBackground()
        {
            BackgroundWorker bgw = new BackgroundWorker();
            bgw.DoWork += BgwOnDoWork;
            bgw.RunWorkerAsync();
            bgw.RunWorkerCompleted += Bgw_RunWorkerCompleted;
        }

		private static void Bgw_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
        {
            // Create a FeatureLayer with the FeatureSet as datasource
        }

        private static void BgwOnDoWork(object sender, DoWorkEventArgs doWorkEventArgs)
        {
            FeatureSet fs = DataManager.DefaultDataManager.OpenFile(PATH_TO_SHAPEFILE)
                as IFeatureSet;
        }`
> And i need to load map layer after application load completely

This has nothing to do with DotSpatial. It depends heavily on how your whole application is designed and what you consider a 'completed load'. You may be able to use one of the events the .NET-Framework provides, like Form.Load, or set up a custom Event + EventHandler, which is fired by your code after your work-intensive initialization tasks are performed and then starts the task in a BackgroundWorker, as described above.

**Comment by VectorZita** [comment]
Although late to the discussion, I don't see why you cannot do that with the background worker. In your posted code, inside the BgwOnDoWork function, after you load the FeatureSet, you can pass it on as:
**doWorkEventArgs.Result = fs;**

And then, in the **Bgw_RunWorkerCompleted** function, you have it in **e.Result** as an object, so you can do whatever you want with it. I am not sure if you had a different problem. These custom-made event arguments of BackgroundWorker are precisely created for this reason, to pass on results from the worker thread to the current thread safely.

It should be noted, however, that there are better alternatives, but I don't think a BackgroundWorker would be bad for this example.
