### ISSUE TITLE
DotSpatial map not inside DotSpatial.Controls

### ISSUE THREAD

**Issue by gilbertoguedes** [DotSpatial/DotSpatial#1118]
I'm trying to install DotSpatial using c# WinForm, to take a look to the Map control. I've installed DotSpatial.Controls using nuget from VS. Instalation succesfull. Added inside my toolBar the DotSpatial.Control.dll wich is inside ../bin/debug folder, but, just 3 controls are added: AppManager, SpatialDockManager, SpatialHeaderControl.

Why Map control is not there?

Thanks in advance.

DotSpatial version: 1.9

**Comment by jany-tenaj** [comment]
This sounds like you expect Map to show up in the Toolbox. Don't know why, but it seems nobody exposed it, so it won't show up there. But you can still create a Map object by code.

**Comment by thyoon** [comment]
Before I read your comment I  First Added inside my toolBar the DotSpatial.Control.dll wich is inside myProjectName/packages/.. then just 3 controls are added: AppManager, SpatialDockManager, SpatialHeaderControl.
When I Added  DotSpatial.Control.dll inside ../bin/debug folder All control appear. Thank you.
