### ISSUE TITLE
Where could I find the DotSpatial Documentation?

### ISSUE THREAD

**Issue by gilbertoguedes** [DotSpatial/DotSpatial#1120]
DotSpatial Documentation is redirecting me to https://archive.codeplex.com/?p=dotspatial.

Where could I find the Documentation, examples or tutorials?

**Comment by jany-tenaj** [comment]
Have a look at the [Examples](https://github.com/DotSpatial/DotSpatial/tree/master/Source/Examples) and [Documentation](https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation) for the current version.

On Codeplex you can download the archive and check out its wiki folder.
