### ISSUE TITLE
Dotspatial UTM Coordinate usage

### ISSUE THREAD

**Issue by htekin42** [DotSpatial/DotSpatial#1124]
Hi everybody,

I am asking too much question here because I am new to Spatial data and Dotspatial. 

I need to make some calculations and I am using UTM coordinates. How should I decleare the coordinate with UTM. 

Coordinate coor1 = new Coordinate (x,y);

or 

Coordinate coor1 = new Coordinate (y,x);

Thanks

**Comment by jany-tenaj** [comment]
x comes first
