### ISSUE TITLE
After add App Manager I get Error message box

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1127]
Hello
I need to load *.adf file ...so i read some document that show me i should add appmanager
when i add this module i get some message box like error
1 - Download a ribbon Extension....
2 - no header control was avaliable , but we couldn't download ribbon ....
3 - a idockmanager extension must be included ...
4 -iheader control extension must be included
5 -istatus control extention must be included

do you have anyway to add other extension for file with out use app manager ?

**Comment by jany-tenaj** [comment]
Make sure the Form you added the AppManager to contains [this code](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DemoMap/MainForm.cs).
