### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by snahdog** [DotSpatial/DotSpatial#1133]
How should Dotspatial be cited in an academic paper? Thank you.

**Comment by danames** [comment]
DotSpatial itself hasn't been introduced in an academic publication,
however we have generally cited other work that makes use of it, as well as
it's original MapWindow beginnings, for example:

Ames, Daniel P., Christopher Michaelis, and Ted Dunsford. "Introducing the
MapWindow GIS project." *OSGeo Journal* 2, no. 1 (2007).

Ames, Daniel P., Christopher Michaelis, Allen Anselmo, Lailin Chen, and
Harold Dunsford. "MapWindow GIS." In *Encyclopedia of GIS*, pp. 633-634.
Springer US, 2008.

Ames, Daniel P., Jeffery S. Horsburgh, Yang Cao, Jiří Kadlec, Timothy
Whiteaker, and David Valentine. "HydroDesktop: Web services-based software
for hydrologic data discovery, download, visualization, and analysis."
*Environmental
Modelling & Software* 37 (2012): 146-156.

Cao, Yang, and Daniel P. Ames. "A strategy for integrating open source GIS
toolboxes for geoprocessing and data analysis." (2012).

Cao, Yang, and Daniel P. Ames. "Development and Implementation of an
Extensible Interface-Based Spatiotemporal Geoprocessing and Modeling
Toolbox." In *AGU Fall Meeting Abstracts*. 2011.

Of course you can also cite the Github repository as a URL citation
depending on if your journal accepts such citations.

Hope this helps.

- Dan

**Comment by snahdog** [comment]
Thank you.
