### ISSUE TITLE
what's the difference between Dotspatial and MapWinGIS?

### ISSUE THREAD

**Issue by qq2898** [DotSpatial/DotSpatial#1135]
thet are both updating, but what's the difference? how to choose?

**Comment by jany-tenaj** [comment]
MapWinGIS is a C++ based ActiveX Control that can be added to a Windows Form in Visual Basic, C#, Delphi, or other languages that support ActiveX.

DotSpatial is a C# based GIS library for .NET applications.

No idea about the functional differences because I don't use MapWinGIS.
