### ISSUE TITLE
How do I install DotSpatial in an "Offline Environment"?

### ISSUE THREAD

**Issue by Talons014** [DotSpatial/DotSpatial#1136]
Hello,
We switched from ESRI to DotSpatial 2 years ago.  The programmer assigned the software has since left and now we need to modify the program for new things because the old one can no longer read our *.dspx file and load the *.jp2(s) after loading *.shp files.

We are in a CLASSIFIED environment and as such, have no direct internet connectivity from our system.  After going through a lot of the DotSpatial source code and tracing through to see what happens, I believe the whole thing was not installed correctly in the first place.

I would like to start over by installing the product (correctly) first and then proceeding.  I have followed the links from GitHub to CodePlex and back regarding the documentation, but they are circular.

My question(s):
1) How do I install ALL of the product in my internet-less environment?  I do not want the system saying "Going to get a ribbon..." because it will NEVER find one.
2) What do I actually need to get from GitHub to use in the NuGet manager (I have set up an offline repository for packages and that seems to work fairly well)?
3) The way I have the system setup right now, it seems to load ALL of the plugins, "Windows Extensions" and such and I don't believe I need all of that support for what we do here.  I need *.shp, *.jp2 and some other raster file support types.  What am I doing wrong?  (See question #1)

Thanks in advance for answers that work!
Talons014

**Comment by DavisMillier** [comment]
Hi , Solution from StackOverFlow
> 

Menu Tools → Options → Package Manager

Enter image description here

Give a name and folder location. Click OK. Drop your NuGet package files in that folder.

Go to your Project, right click and select "Manage NuGet Packages" and select your new package source.

Enter image description here

Here is the [documentation](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview).


Or you can download release file and use DLL file Directly
