### ISSUE TITLE
How to create features in Polyline shapefile by mouse click?

### ISSUE THREAD

**Issue by qq2898** [DotSpatial/DotSpatial#1139]
I use dotspatial 2.0 and study the tutor4 for shapefile and attribute operation. but it is to create polyline or polygon feature, I don't know how to do, may be the Interface has been modified?
for example, "lineFeature.Coordinates.Add(coord); " 
the tutor4's code snippest is:
                          //first time left click - create empty line feature
                            if (firstClick)
                            {
                                //Create a new List called lineArray.                          
                                //This list will store the Coordinates
                                //We are going to store the mouse click coordinates into this array.
                                List<Coordinate> lineArray = new List<Coordinate>();

                                //Create an instance for LineString class.
                                //We need to pass collection of list coordinates
                                LineString lineGeometry = new LineString(lineArray);

                                //Add the linegeometry to line feature
                                IFeature lineFeature = lineF.AddFeature(lineGeometry);

                                //add first coordinate to the line feature
                                lineFeature.Coordinates.Add(coord); // how-to-do-this-statement?**
                                //set the line feature attribute
                                lineID = lineID + 1;
                                lineFeature.DataRow["LineID"] = lineID;
                                firstClick = false;
                            }
                            else
                            {
                                //second or more clicks - add points to the existing feature
                                IFeature existingFeature = lineF.Features[lineF.Features.Count - 1];
                                existingFeature.Coordinates.Add(coord);

                                //refresh the map if line has 2 or more points
                                if (existingFeature.Coordinates.Count >= 2)
                                {
                                    lineF.InitializeVertices();
                                    map1.ResetBuffer();
                                }
                            }

**Comment by MatthiasSchilder** [comment]
The tutorial you're using seems to be fairly old. Looks like it uses DotSpatial 1.0.

It is not possible any more to modify the geometry this way. The geometry of a feature is exposed through a property Geometry, which also has a property Coordinates, but this is an array of type Coordinate[]. This does not allow to add new coordinates.

If you want to achieve such a behaviour, keep a List<Coordinate> which is grown by one Coordinate with each mouseclick, then recreate the geometry after each click and assign it to the feature, somehow like this:

`            FeatureSet lineFeatureSet = new FeatureSet(FeatureType.Line);

            List<Coordinate> coordList = new List<Coordinate>
            {
                new Coordinate(0, 0),
                new Coordinate(10, 10)
            };
          
            // initial feature creation
            var lineFeature = lineFeatureSet.AddFeature(
                new LineString(
                    coordList.ToArray()));

            // mouse click occurs here and adds a new Coordinate to your Coordinate-list
            coordList.Add(new Coordinate(20, 20));

            // create a new LineString with all of the coordinates
            lineFeature.Geometry = new LineString(coordList.ToArray());`

**Comment by liangzhq** [comment]
use MapFunction 
https://www.cnblogs.com/kogame/p/12330628.html#4500729
