### ISSUE TITLE
Error on OpenFile with special SPHERIOD string

### ISSUE THREAD

**Issue by hajvaz** [DotSpatial/DotSpatial#1142]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. shapefile has this SPHERIOD string "SPHEROID[\"Bessel 1841 [EPSG ID 7004]\",6377397.155,299.1528128]]"
2. the problem in this string is "[EPSG ID 7004]"

```
        public void ParseEsriString(string esriString)
        {
            if (esriString.Contains("SPHEROID") == false) return;
            int iStart = esriString.IndexOf("SPHEROID", StringComparison.Ordinal) + 9;
            int iEnd = esriString.IndexOf("]", iStart, StringComparison.Ordinal);
            if (iEnd < iStart) return;
            string extracted = esriString.Substring(iStart, iEnd - iStart);
            string[] terms = extracted.Split(',');
            _name = terms[0];
            _name = _name.Substring(1, _name.Length - 2);
            _equatorialRadius = double.Parse(terms[1], CultureInfo.InvariantCulture);
            InverseFlattening = double.Parse(terms[2], CultureInfo.InvariantCulture);

            //added by jirikadlec2 - set the 'knownEllipsoid' to the name if possible
            _knownEllipsoid = Proj4Ellipsoid.Custom;
            foreach (Proj4Ellipsoid proj4ellps in _proj4Names.Keys)
            {
                if (proj4ellps.ToString() == _name)
                {
                    _knownEllipsoid = proj4ellps;
                    break;
                }
            }
        }
```

the following line causes the error
 _equatorialRadius = double.Parse(terms[1], CultureInfo.InvariantCulture);

because iEnd is not calculated correctly
 **int iEnd = esriString.IndexOf("]", iStart, StringComparison.Ordinal);** 
it does not except a second "]" in the SPHERIOD string

DotSpatial version: 1.9

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by hajvaz** [comment]
possible fix ?
 int iEnd = esriString.IndexOf(**"]]"**, iStart, StringComparison.Ordinal);
it is ok to except this "]]" on the end of the SPHERIOD section?

**Comment by MatthiasSchilder** [comment]
I looked in the standard for well-known text representation of coordinate reference systems [1], and I'm not completely sure if this would work in any case.

Maybe a more robust solution would be to search the first occurence of '[' after SPHEROID, than iterate over the string's characters and count the occurence of the follwing '[' and ']'. The first ']' which has no corresponding '[' should be at the end-index of the SPHEROID-substring.


[1] http://docs.opengeospatial.org/is/12-063r5/12-063r5.html

**Comment by hajvaz** [comment]
Thank you for the quick response. Yes, this fix is much more robust and the problem is gone :+1:
