### ISSUE TITLE
Add a Make Valid function

### ISSUE THREAD

**Issue by bladeoflight16** [DotSpatial/DotSpatial#1144]
### Feature description

When programmatically dealing with geometries that may be invalid, it's useful to have a function that guesses at how to correct the problem. For example, PostGIS has [`ST_MakeValid`](https://postgis.net/docs/ST_MakeValid.html) and there's [`SqlGeometry.MakeValid`](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.types.sqlgeometry.makevalid.aspx). These functions both make a best effort at correcting problems with an invalid geometry and generating a valid one with the same vertices. This allows the program to offer the user a corrected version for review or to attempt to continue with some operation over a set of geometries (such as unioning several).

These functions are particularly useful for fixing self-intersecting rings in polygons and fixing polygon parts that aren't actually closed rings. The latter usually results into conversion to a geometry collection containing a mix of (multi)polygons, linestrings, and points.

For a potential reference implementation, [here](https://github.com/postgis/postgis/blob/svn-trunk/liblwgeom/lwgeom_geos_clean.c) is PostGIS's implementation of `ST_MakeValid`.

It is not expected that these functions always work perfectly and are exactly correct about what the shape was intended to be, but the two functions I mentioned above certainly handle the most common problems very well.

**Comment by MatthiasSchilder** [comment]
DotSpatial uses geometries from NetTopologySuite. Maybe it would be more convenient to make your proposal there? They already have at least some utils to check different geometry types for their validity.

**Comment by jany-tenaj** [comment]
as far as I know something like this exists in NTS.
