### ISSUE TITLE
Bug in StatePlaneNad83Feet projections

### ISSUE THREAD

**Issue by AdamGeomat** [DotSpatial/DotSpatial#1146]
### Steps to reproduce

1. Convert a wgs84 long/lat source coordinate to any stateplane nad83 feet
2.Convert the same point to stateplane nad83 (meter)
3.First conversion always is around a feet or two off but second conversion is accurate

I tried NAD1983StatePlaneMontanaFIPS2500Feet and NAD1983StatePlaneMontanaFIPS2500 as well as others in Feet and Meter and got the same discrepancy in results.

DotSpatial version: 2.0

Further investigation showed this issue was related to the Feet and FeetIntl unit conversion. NAD1983StatePlaneMontanaFIPS2500Feet and NAD1983StatePlaneMontanaFIPS2500FeetIntl has different categories and unit conversion, so this no longer is a bug.

**Comment by mogikanin** [comment]
So we can close it, @AdamGeomat ?
