### ISSUE TITLE
How can work with attribute on another layer

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1147]
Hello
I need to know,How can i get attribute value in custom layer and coordinate ?
May you help me about it ?

**Comment by MatthiasSchilder** [comment]
Can you please describe your question a little more precisely? What do you mean by "custom layer" and "another layer"? 

In general, a FeatureLayer has a property FeatureSet; this FeatureSet has a property of typ IFeatureList, which contains the features belonging to this lable. Each individual Feature in this list has a property **Geometry** (i.e. for a MapPointLayer this gives you a POINT-object) and a Property DataRow, which holds the attributes belonging to the feature.
