### ISSUE TITLE
Problem with getpixel() in c# and dotspatial

### ISSUE THREAD

**Issue by mostafahadizadeh1991** [DotSpatial/DotSpatial#1149]
Hi
I use a gray image that getpixel() command should give me the low number for black region and high value for white region. But don't work finely for me and give me incorrect value for every region.
I use this code with dotspatial :

```
public partial class formMain : Form
{

    Bitmap b = new Bitmap(@"F:\Hrit1\MSG1MostO.bmp");

    private void mapMain_MouseMove(object sender, System.Windows.Forms.MouseEventArgs e)
    {

        Coordinate c= mapMain.PixelToProj(new System.Drawing.Point(e.X , e.Y ));

        int pixel = Convert.ToInt32(c.X);
        int line = Convert.ToInt32(c.Y);
        if (line < 0 || pixel < 0 || line > 850 || pixel > 1145)
        {
            line = 0;
            pixel = 0;
        }

        Color col = b.GetPixel(pixel, line);

        textBox1.Text = col.ToString();

}
  }
```

ANYONE CAN HELP ME??

**Comment by MatthiasSchilder** [comment]
PixelToProj gives you coordinates in the coordinate reference system of your map. In nearly every case in a real-world situation, those are not in the range 0 - something. If you want to get the location in pixels where the user placed the mouse cursor, just use the data from MouseEventArgs. Maybe you should consider another approach, what you are planning to do does not looks very robust to me, it will fail if the window size changes, etc.

**Comment by Khamirak** [comment]
@MatthiasSchilder  do you have any better idea for extract pixel value of images in dotspatial?
Before I use a code "[https://github.com/DotSpatial/DotSpatial/issues/1148]" to readout or extract pixel value from shape file in dotspatial. Is there any way to do with image files? 
I'm very pleasure to help me.

**Comment by MatthiasSchilder** [comment]
> to readout or extract pixel value from shape file in dotspatial

Per definition, a shapefile is made of vector data and has no pixels.

>  Is there any way to do with image files?
Reading with GetPixel is the correct way, but you need to compute the pixel coordinates correctly to access the individual pixels. In your sample, this is not the case. I described a way how it may work, though this may be not a good one, this the concept sounds flawed.

Another way would be to create a georeferenced image from your bitmap and add it as a MapImageLayer to your map. You may be able to access the pixel values through properties of the MapImageLayer (use Buffer / BufferRectangle / BufferExtents) in a more convenient way, than. I didn't do that by myself yet, but it sounds possible.
