### ISSUE TITLE
Draw rectangle on Dotspatial c#

### ISSUE THREAD

**Issue by mostafahadizadeh1991** [DotSpatial/DotSpatial#1152]
I find c# code that can draw polygon.
I want to draw rectangle. But I have problem
anyone can help me?
``
private void mapMain_MouseClick(object sender, System.Windows.Forms.MouseEventArgs e)
        {

            if (e.Button == MouseButtons.Left)
            {
                //left click - fill array of coordinates
                Coordinate coord = mapMain.PixelToProj(e.Location);

                if (polygonmouseClick == true)
                {
                    if (firstClick == true)
                    {

                        //Creat a list to contain the polygon coordinates
                        List<Coordinate> polygonArray = new List<Coordinate>();

                        //Create an instance for LinearRing class.
                        //We pass the polygon List to the constructor of this class
                        LinearRing polygonGeometry = new LinearRing(polygonArray);

                        //add polygonGeomety instance to polygonFeature
                        IFeature polygonFeature = polygonF.AddFeature(polygonGeometry);

                        //add first coordinate
                        polygonFeature.Coordinates.Add(coord);

                        //add to the list of coordinates
                        xCoordinates.Add(coord.X);
                        yCoordinates.Add(coord.Y);

                        //set the polygon feature attribute
                        polygonID = polygonID + 1;
                        polygonFeature.DataRow["PolygonID"] = polygonID;
                        firstClick = false;

                        //Add volume data column 
                        polygonFeature.DataRow["Volume"] = 0;

                    }
                    else
                    {
                        //second or more clicks-add points to the existing feature
                        IFeature existingFeature = (IFeature)polygonF.Features[polygonF.Features.Count - 1];

                        existingFeature.Coordinates.Add(coord);

                        //add to the list of coordinates
                        xCoordinates.Add(coord.X);
                        yCoordinates.Add(coord.Y);

                        //refresh the map if line has 2 or more points
                        if (existingFeature.Coordinates.Count != 0)
                        {
                            //refresh the map
                            polygonF.InitializeVertices();
                            mapMain.ResetBuffer();
                        }
                    }
                }

            }
        }

        private void mapMain_MouseDoubleClick(object sender, MouseEventArgs e)
        {

            if (polygonmouseClick == true)
            {
                //get polygonGeomety instance of existing polygonFeature
                IFeature polygonFeature = polygonF.GetFeature(0);

                //add first coordinate
                Coordinate coord = polygonFeature.Coordinates[0];
                polygonFeature.Coordinates.Add(coord);

                polygonF.InitializeVertices();
                mapMain.ResetBuffer();

                //add first coordinate to the list
                xCoordinates.Add(coord.X);
                yCoordinates.Add(coord.Y);

                //we add new feature
                //Creat a list to contain the polygon coordinates
                List<Coordinate> polygonArray = new List<Coordinate>();
                for (int i = 0; i < 4; i++)
                {
                    polygonArray.Add(new Coordinate(xCoordinates[i], yCoordinates[i]));
                   
                }

                //Create an instance for LinearRing class.
                //We pass the polygon List to the constructor of this class
                LinearRing polygonGeometry = new LinearRing(polygonArray);
                DotSpatial.Topology.Polygon polygon = new Polygon(polygonGeometry);

                //add polygonGeomety instance to polygonFeature
                IFeature polygonFeatureNew = polygonFNew.AddFeature(polygon);

                FeatureType ft = polygonFNew.FeatureType;

                polygonFNew.SaveAs("polygonF.shp", true);

                polygonmouseClick = false;
                mapMain.Cursor = Cursors.Arrow;
            }

        }
		
		
        private void btnCreateFillPolygon_Click_1(object sender, EventArgs e)
        {
            if (polygonLayer != null)
            {
                mapMain.Layers.Remove(polygonLayer);
                polygonLayer = null;

                //reset everything
                polygonF = new FeatureSet(FeatureType.Polygon);
                polygonFNew = new FeatureSet(FeatureType.Polygon);

                //the id of the polygon
                polygonID = 0;

                //the x coordinates
                xCoordinates = new List<double>();
                //the y coordinates
                yCoordinates = new List<double>();
            }

            //change the mouse cursor
            mapMain.Cursor = Cursors.Cross;

            //set shape type
            shapeType = "polygon";

            //set the polygon projection to the maps
            polygonF.Projection = mapMain.Projection;

            //initialize attribute table
            DataColumn column = new DataColumn("PolygonID");
            DataColumn volume = new DataColumn("Volume");

            if (!polygonF.DataTable.Columns.Contains("PolygonID"))
            {
                polygonF.DataTable.Columns.Add(column);
            }

            if (!polygonF.DataTable.Columns.Contains("Volume"))
            {
                polygonF.DataTable.Columns.Add(volume);
            }

            //add the polygon to the map layer
            polygonLayer = (MapPolygonLayer)mapMain.Layers.Add(polygonF);

            //polygon symbology
            PolygonSymbolizer symbol = new PolygonSymbolizer(Color.White);
            polygonLayer.Symbolizer = symbol;

            polygonLayer.LegendText = "Polygon";

            MessageBox.Show("Click on the map to draw a ploygon. Double click to stop drawing.");

            //intializes drawing polygon mode
            firstClick = true;

            polygonmouseClick = true;
        }

**Comment by MatthiasSchilder** [comment]
What is your problem with the code? Please provide as much information as possible, i.e. if an exception is thrown, etc. and present your problem with a minimum working example (the minimal amount of code which shows the problem).

**Comment by Khamirak** [comment]
How can I change this code to work for drawing rectangle?
My main question is how to draw rectangle in map region of Dotspatial?
I cant change above code to draw rectangle. Can you help me?

**Comment by MatthiasSchilder** [comment]
Please regard this is primarily an issue tracker for DotSpatial. This platform is not suited for general advice on programming. Please try it yourself and ask a more specific question, if you struggle in the process.

Your example provides everything you need to achieve the behaviour you want. The neccessary changes are relatively minor. You can presume that a rectangle is just a special type of polygon with 4 vertices and interior angles of 90°. A rectangle can also be defined by 2 vectors or 3 points of user input.
