### ISSUE TITLE
Get Attribute Closest Point in polygon layer

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1153]
Hello
I want to Get Attribute "Elevation" in 1 Polygon layer ("Contour") on selected position.
May you help me about it ?

**Comment by DavisMillier** [comment]
Any Idea about elevation extraction on point ?

**Comment by MatthiasSchilder** [comment]
You may take a look at MapFunctionIdentify.cs and FeatureIdentifier.cs in the project DotSpatial.Controls. A function which is somewhat similar to your requirements is implemented there (selecting a feature by mouse click and show its attributes in a dialog).
