### ISSUE TITLE
Polygon layer with categories does not draw all polygons to be drawn in case categories do not cover all features

### ISSUE THREAD

**Issue by UliEgger** [DotSpatial/DotSpatial#1154]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Start DemoMap.exe
2. Load Shapefile contained in zip file attached as a new layer
3. Open layer properties for the layer
4. Select Unique values and Field "Strasse"
5. Apply changes
6. All polygons are drawn 
7. Remove first category and apply changes
8. Result: Many polygons are missing, not only those of the first category that has been removed

DotSpatial version: 

### Expected behaviour

All polygons that fullfill the queries in the remaining categories should be drawn

### Actual behaviour

See number 8 in Reproduction

[0_Shapefiles.zip](https://github.com/DotSpatial/DotSpatial/files/1942738/0_Shapefiles.zip)

**Comment by UliEgger** [comment]
[DotSpatialBugPolygonLayerWithCategories.zip](https://github.com/DotSpatial/DotSpatial/files/1942739/DotSpatialBugPolygonLayerWithCategories.zip)

**Comment by UliEgger** [comment]
I already have the bug fixed in our local DotSpatial fork, the reason ist that in MapPolygonLayer.DrawPaths in the foreach loop ofer the paths, in case category == null, the method returns instead of continueing to the next path.

**Comment by jany-tenaj** [comment]
Please create a pull request.

**Comment by UliEgger** [comment]
It seems to be fixed in the master branch already.
So I close this issue.
