### ISSUE TITLE
Latitude Longitude to Layer Projection

### ISSUE THREAD

**Issue by Chancelish** [DotSpatial/DotSpatial#1155]
This isn't bug, it's just a question. 

DotSpatial version: 1.9

I'm working on a GIS application that we are using to survey roads and signs for local cities and counties, one feature we need to have is the ability to add a new point (from simple latitude, longitude) to a point shapefile with an arbitrary projection. 

The code I am using looks like this:

```
private void addPoint(double lat, double lon)
{
    MapPointLayer mpl = (MapPointLayer)Layer;
    double[] xy = { lat, lon};
    double[] z = { 0 };
    DotSpatial.Projections.Reproject.ReprojectPoints(xy, z, DotSpatial.Projections.KnownCoordinateSystems.Geographic.World.WGS1984, mpl.Projection, 0, 1);
    DotSpatial.Topology.Point newPoint = new DotSpatial.Topology.Point(xy[0], xy[1]);
    DotSpatial.Data.IFeature np = mpl.DataSet.AddFeature(newPoint);
    \\apply project specific properties to new feature
    mpl.DataSet.Save();
}
```

This code results in a latitude, longitude of infinity, NaN respectively. Clearly, it is wrong. Other suggested solutions both here and on the GIS stackexchange have not been helpful. What is the correct way to convert a lat/lon coordinate to the established projection of the layer?

**Comment by Chancelish** [comment]
mpl is the reference to the FeatureLayer used by our signs module cast to a MapPointLayer. I don't know if that cast is really necessary.

Right now the layer is creating from an existing shapefile.

**Comment by MatthiasSchilder** [comment]
Please provide the value of the property mpl.Projection. The property should be of type ProjectionInfo. Alternatively, you may also upload the shapefile, especially with the associated prj-file, which contains the target projection for your conversion.

**Comment by Chancelish** [comment]
I don't know what mpl.projections is, but based on the coordinates of the points when inspected it appears to use some sort of Easting Northing.

**Comment by MatthiasSchilder** [comment]
Can you please check if there is a file with file extension .prj in the directory where your shapefile exists? If yes, please open it with a text editor and provide its content here.

**Comment by Chancelish** [comment]
Sorry for the slow response, I was just heading home when this issue got pick up, this is what the .prj file has:
```
PROJCS["UTM Zone 12, Northern Hemisphere",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["false_easting",500000.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",-111.0],PARAMETER["scale_factor",0.9996],PARAMETER["latitude_of_origin",0.0],UNIT["Meter",1.0]]
```

The value of mpl.Projection appears to be set when inspected in the debugger, but I don't understand the properties that the objects.

**Comment by MatthiasSchilder** [comment]
The value of mpl.Projection is create from the prj-string you just posted, so I think, I have the neccessary information know. I'll take a look at it and will try to give you an update on this issue within the next few hours.

**Comment by MatthiasSchilder** [comment]
Please just switch lat/lon in your initialization of xy-array. Longitude increases/decreases, when you walk around the globe equator, so this is the property which translates to 'easting' of projected coordinate systems, or simply spoken, X in a cartesian coordinate system.

I created a small test program, which reprojects correctly for a given test-point in Utah in WGS 84 to NAD83 / UTM 12N

```
        static void Main(string[] args)
        {
            // WGS84-coords of a point in Utah
            double lat = 39.154210, lon = -111.627673;
            var sourceProjection = KnownCoordinateSystems.Geographic.World.WGS1984;

            var targetProjection = ProjectionInfo.FromEsriString( 
                "PROJCS[\"UTM Zone 12, Northern Hemisphere\",GEOGCS[\"NAD83\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS 1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"false_easting\",500000.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",-111.0],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"latitude_of_origin\",0.0],UNIT[\"Meter\",1.0]]\r\n");

            double[] xy = { lon, lat };
            double[] z = { 0 };
            DotSpatial.Projections.Reproject.ReprojectPoints(xy, z, sourceProjection, targetProjection, 0, 1);

            Debug.WriteLine($"Easting: {xy[0]} Northing: {xy[1]}");
        }
```

**Prints**: "Easting: 445766,648503065 Northing: 4334077,23153129"

I also did a quick validation with a government-operated online coordinate conversion service, and got very similar results (see screenshot).

![image](https://user-images.githubusercontent.com/313898/39378947-163551ca-4a5a-11e8-8215-be2ec6d479b6.png)

**Comment by Chancelish** [comment]
That's It, it works perfectly! Although, I'm surprised it was something so simple. Thank you for helping me better understand world coordinate systems!
