### ISSUE TITLE
Reprojection accuracy

### ISSUE THREAD

**Issue by MjolnirPants** [DotSpatial/DotSpatial#1163]
I'm seeing a very large disconnect between the reprojections done in dotspatial and known accurate reprojections when converting coordinates from the NAD83 SPC, zone 0901 to WGS84. 

The code I'm using is as follows:
`double[] pnts = { 1427258.433, 499380.46 };`
`ProjectionInfo piFrom = KnownCoordinateSystems.Projected.StatePlaneNad1983.NAD1983StatePlaneFloridaEastFIPS0901;`
`ProjectionInfo piTo = KnownCoordinateSystems.Geographic.World.WGS1984;`
`Reproject.ReprojectPoints(pnts, new double[] { 0 }, pStart, pEnd, 0, 1);`

The final values of pnts[] are 25.6886995259671, -78.6588792546376, instead of 28.2592075, -81.4870398, as they should be. 
I've checked the reprojection at both earthpoint.us and ngcc.noaa.gov, and they're in agreement with each other, and in disagreement with DotSpatial.
Setting the input coordinate system using the esri string does not help.
Converting US survey feet to meters does not improve accuracy.

DotSpatial version: 
2.0 (commit 91df60adc90c6bcbc5f2a12080b1eec38858e6c5 from 2017/09/14)

**Comment by MatthiasSchilder** [comment]
Executing your code sample gives me a different result:
![image](https://user-images.githubusercontent.com/313898/40241831-4517550c-5abc-11e8-927a-5cef17c5f058.png)

Furthermore, can you clarify how to use the online services you posted? One of the links does not work, and on the other page I wasn't able to find the correct tool.

**Comment by MjolnirPants** [comment]
Sorry, I assumed anyone working with or on dotspatial -specifically with the state plane system- would be familiar with those sites. The tools are located at http://www.earthpoint.us/StatePlane.aspx and https://www.ngs.noaa.gov/NCAT/. Usage should be self-explanatory.

I don't understand how executing the code I provided gives you a different result unless you're using a different build, but your longitude is even more inaccurate than mine, while your latitude is much more accurate.
Here's a before:
![image](https://user-images.githubusercontent.com/39408353/40242585-033bc99a-5a8c-11e8-84b9-40d65a05d612.png)

and after:
![image](https://user-images.githubusercontent.com/39408353/40242512-db808490-5a8b-11e8-849c-7ffb354238d1.png)

**Comment by MatthiasSchilder** [comment]
Please take a look at my edit. I noticed I'm using a version with some
changes from pull request #1059. Those changes were necessary to use
DatumTransforms in Germany with grid shift tables. This feature was heavily
flawed and may contain additional bugs. The code which was changed also
applies to DatumTransforms between Nad83<->WGS84.

MjolnirPants <notifications@github.com> schrieb am Fr., 18. Mai 2018, 17:15:

**Comment by MatthiasSchilder** [comment]
I now did a conversion with [1] and got nearly exact those values, my modified DS-version with fixes for GsbNadTable.cs gives me:
![image](https://user-images.githubusercontent.com/313898/40246410-f41e3adc-5ac8-11e8-9cfe-84febd8d0bf7.png)
![image](https://user-images.githubusercontent.com/313898/40246429-0194877a-5ac9-11e8-8efa-dfebcc2d4f1a.png)



[1] http://www.earthpoint.us/StatePlane.aspx

**Comment by MjolnirPants** [comment]
You're entering the input as meters, but it should be US survey feet for the state plane system. But it leads me to believe I might get something accurate if I convert to meters before doing the reprojection (which I had thought of before, but didn't work).
I'm implementing the changes from your pull request and I'll let you know if I can get an accurate result after.

**Comment by MatthiasSchilder** [comment]
Ah ok, you didn't provide information if those coords are in feet or meet when I asked before.

Looks like the problem is in ReprojectPoints(...). Reprojection is always done in meters. There is a factor to convert from an arbitrary unit to meters, but it is always set to source.Unit.Meters, which equals 1. Converting your feet coords to meters, doing your reprojection, and converting back should work.

```
public static void ReprojectPoints(double[] xy, double[] z, ProjectionInfo source, double srcZtoMeter, ProjectionInfo dest, double dstZtoMeter, IDatumTransform idt, int startIndex, int numPoints)
        {
            **double toMeter = source.Unit.Meters;**

            // Geocentric coordinates are centered at the core of the earth.  Z is up toward the north pole.
            // The X axis goes from the center of the earth through Greenwich.
            // The Y axis passes through 90E.
            // This section converts from geocentric coordinates to geodetic ones if necessary.
            if (source.IsGeocentric)
            {
                if (z == null)
                {
                    throw new ProjectionException(45);
                }
                for (int i = startIndex; i < numPoints; i++)
                {
                    **if (toMeter != 1)
                    {
                        xy[i * 2] *= toMeter;
                        xy[i * 2 + 1] *= toMeter;
                    }**
                }
                GeocentricGeodetic g = new GeocentricGeodetic(source.GeographicInfo.Datum.Spheroid);
                g.GeocentricToGeodetic(xy, z, startIndex, numPoints);
            }
```

**Comment by MatthiasSchilder** [comment]
Even if I enter your input points as feet, the result from [1] is what DotSpatial gave you in the first place. Maybe I'm too dumb to understand your problem. I'm out.

![image](https://user-images.githubusercontent.com/313898/40247007-2e01e68e-5acb-11e8-863b-c280d685289b.png)

**Comment by MjolnirPants** [comment]
You're entering the coordinate in the wrong fields: X is Easting and Y is Northing, you are entering the Northing as Y and Easting as X. I didn't notice it in your first screencap, though it was there. Thanks anyways.

**Comment by MatthiasSchilder** [comment]
Then you did it the wrong way in your sample code, too:
double[] pnts = { 1427258.433, 499380.46 };

pnts[0] should be the X component, pnts[1] should be Y component... thats why the first parameter of ReprojectPoints is named 'xy'..

**Comment by MjolnirPants** [comment]
You are correct, the sample is switched around from the original code. The order is reversed in my project.

**Comment by MatthiasSchilder** [comment]
Solution seems to be super easy. Use 
KnownCoordinateSystems.Projected.StatePlaneNad1983**Feet**.NAD1983StatePlaneFloridaEastFIPS0901**Feet;**

instead of

KnownCoordinateSystems.Projected.StatePlaneNad1983.NAD1983StatePlaneFloridaEastFIPS0901;

The next time you file an issue, please document a little bit more clear which value corresponds to which parameter, which units those values are in, etc. 

I get the values you expect now: 
![image](https://user-images.githubusercontent.com/313898/40250688-6151e762-5ad7-11e8-9dc4-8888862a35b3.png)

**Comment by MjolnirPants** [comment]
Re-downloading and recompiling the libraries (after implementing the changes in your pull request to no avail) is what ended up correcting my issue.

For the record, I specified what units I was using in the last line of my initial post, where I also specified that changing units to meters didn't help.
