### ISSUE TITLE
Change Category Symbology

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1165]
Hello
I set a category symbology as pictureSymbol on feature when added to map
know some times I need to change symbol image
how can I get it and edit it by feature ?
I can get feature by name or id
thanks in advance

**Comment by sindizzy** [comment]
What code do you have now?

**Comment by DavisMillier** [comment]
`            _pointScheme = Mpl.Symbology;

            switch (ftype)
            {
                case "car":
                    _pointSymbol = new PictureSymbol(car, 25);
                    break;
                case "bus":
                    _pointSymbol = new PictureSymbol(bus, 30);
                    break;
                case "bus-station":
                    _pointSymbol = new PictureSymbol(bus-station, 25);
                    break;
                default:
                    _pointSymbol = new PictureSymbol(car, 25);
                    break;
            }
            _pointCat = new PointCategory(_pointSymbol);
            _pointCat.Symbolizer.ScaleMode = ScaleMode.Simple;
            _pointCat.FilterExpression = "[fID]='" + _pointFeature.DataRow["fID"] + "'";
            _pointScheme.AddCategory(_pointCat);
            Mpl.ApplyScheme(_pointScheme);
            _pointCat.LegendText = _pointFeature.DataRow["Label"].ToString();
            LabelSymbolizer lblSymbolizer = new LabelSymbolizer
            {
                FontFamily = "Tahoma",
                FontColor = Color.Black,
                BackColorEnabled = true,
                BackColor = Color.FromArgb(25, Color.WhiteSmoke),
                BorderVisible = true,
                FontSize = 8,
                LabelPlacementMethod = LabelPlacementMethod.Center,
                Orientation = ContentAlignment.MiddleRight,
                PreventCollisions = false,
                OffsetX = 15,
                OffsetY = 0
            };
            Mpl.ShowLabels = true;
            Mpl.AddLabels("[Label]", string.Empty, lblSymbolizer, string.Empty);
            Mpl.DataSet.InitializeVertices();
            Mpl.AssignFastDrawnStates();`

I use that code …If it have any problem please assist to me for better code

and tell me how can I get cat and change cat picture in next time

**Comment by MatthiasSchilder** [comment]
The GIS-way of achieveing your goal would be to create one PointCategory per different image/icon you want to show on your layer. Give each of those PointCategories a FilterExpression then, which filters on a different value of a given feature attribute, which allows you to tell your different features apart, for example with an enum.

Something like this:
```
_pointCatCar = new PointCategory(_pointSymbolCar);
_pointCatPlane= new PointCategory(_pointSymbolPlane);

_pointCatCar.FilterExpression = "[featureType]='car'";
_pointCatPlane.FilterExpression = "[featureType]='plane'";
```

If each of your features has a attribute named "featureType" with values matching the hard-coded strings above, those PointCategory-visualizers with different icons are used automatically.

**Comment by DavisMillier** [comment]
Hello
I do that but now i need to have angle for each feature
How can i set different angle for each features ?(Rotate feature picture by angle)

Thank you

**Comment by sindizzy** [comment]
The symbolizer has an angle. Otherwise cycle through each feature and assign it an angle.

**Comment by DavisMillier** [comment]
Thank you for response 
I can not understand what should i do !
May you help me more ?

**Comment by sindizzy** [comment]
Here is a sample:

```
                'the first category should be the default
                Dim def As New PointCategory(Color.Blue, DotSpatial.Symbology.PointShape.Triangle, 8)   'blue triangle
                def.FilterExpression = "[PNTTYP] = 'Z'"                                                'only for points with type = "Z" 
                def.LegendTextReadOnly = True
                def.LegendText = "Waypoint"
                def.Symbolizer.SetOutline(Color.Transparent, 0)                                         'outer outline gets zero width to make invisible
                def.Symbolizer.Symbols(0).Angle = -90                                                   'orient triangle pointing up

```
