### ISSUE TITLE
How to reproject using gridfile

### ISSUE THREAD

**Issue by Lemmes** [DotSpatial/DotSpatial#1169]
Question:
I'm trying to convert coordinates from **Gauß-Krüger (DHDN GK3)** to **UTM32** using the official gridfile _BWTA2017.gsb_ (supplied by the German surveying authority _Landesamt für Geoinformation und Landentwicklung Baden-Württemberg_. 
Here's the proj4 cs2cs command line that does it for me (returns correct results). 
` cs2cs +proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel +nadgrids=.\BWTA2017.gsb +units=m +to +proj=utm +ellps=GRS80 +nadgrids=@null +zone=32 < koordinaten.txt > koordinaten_transformiert.txt `
Unfortunately following code returns wrong coordinates, so something must be wrong with my method.
```csharp
const string proj4stringGK = @"+proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel +nadgrids=C:\UTM-Transformation\Baden-Württemberg\Grid\BWTA2017.gsb +units=m +no_defs";
const string proj4stringUTM32 = @"+proj=utm +ellps=GRS80 +nadgrids=@null +zone=32";

GridShift.InitializeExternalGrids(@"C:\UTM-Transformation\Baden-Württemberg\Grid", false);
ProjectionInfo quelle = ProjectionInfo.FromProj4String(proj4stringGK);
ProjectionInfo ziel = ProjectionInfo.FromProj4String(proj4stringUTM32);

var gkPunkte = new double[] { 3456711.57, 5423083.85 };
Reproject.ReprojectPoints(gkPunkte, new double[] { 0.0 }, quelle, ziel, 0, 1);

Console.WriteLine($"Ost: {gkPunkte[0]} Nord: {gkPunkte[1]}");
```
It outputs: ` Ost: 456723,618349022 Nord: 5421468,62059541 ` while the correct result would be something along  ` Ost: 456653,47 Nord: 5421354,08 `
I **think** the culprit might be that `GeographicInfo.Datum.DatumType` of the target system is `DatumType.Unknown` so that the code returns in `Projections.Reproject.DatumTransform()` in line 247 of `Reproject.cs` before applying any grid shift but I have no idea what to do instead to instantiate the target correctly.

Any help would be appreciated.

**Comment by MatthiasSchilder** [comment]
You have at least two different choices for UTM zone 32 here in Germany:

EPSG 25832: ETRS89 / UTM zone 32n
EPSG 32632: WGS84 / UTM zone32n

If you initialize your ProjectionInfo object through 

`ProjectionInfo.FromEpsgCode(id);`

your destination projection has a correct Geo-CRS, and therefore a DatumType, set.

**BUT**:
In our application, we're using transformations between DHDN / Gauss-Krüger and both variants of UTM zone 32 with BETA2007.gsb (I assume it is very similar to BWTA2007). We noticed there is a handful of bugs in the way, DotSpatial works with GsbNadTables. We fixed those and made them available in pull-request #1059 (Multiple Changes on handling of GsdNadTable ). In our opinion, those changes are crucially important, if you want to use BETA2007.gsb (and probably BWTA2007). Otherwise, you get totally wrong results.

**Comment by Lemmes** [comment]
Hi Matthias, 
thanks for your comment. 
I applied your code changes (both from your pull-request and from your comment) but `GridShift.Apply(...)` exits early in line 67 of *GridShift.cs* in 
`if (!_shift.Tables.TryGetValue(name, out tableLazy)) continue;`, as the value for entry `BWTA2017` is apparently not initialized yet. I don't understand when or where `Lazy<NadTable>`gets initialized. Any hints?

**Comment by Lemmes** [comment]
Hi Matthias,

using your snippet eventually returns the right coordinates - thanks for your assistance!
Now - it'd be fine if the maintainers of the project could check and incorporate your pull requests.

Have a nice day, Bernd

**Comment by MaSchue1** [comment]
I am trying to transform coordinates from EPSG:31467 to EPSG:4326, so far no problem.

Using grid files BETA2007 or HeTa2010 has no effect. I tried both (Mattias and Bernds) solutions. Debugging  shows, that the method TryGrid returns fals, even if the coordinates fits the grid.

another issue is, if there is one subgrid, it seeems to be ignored.

if (table.SubGrids != null && table.SubGrids.Count > 1)

Any help would be appreciated.

**Comment by MatthiasSchilder** [comment]
@MaSchue1 I assume you didn't incorporate the changes from my pull request #1059 (as described above). Those were crucial for using BETA2007 sucessfully.

**Comment by MaSchue1** [comment]
> @MaSchue1 I assume you didn't incorporate the changes from my pull request #1059 (as described above). Those were crucial for using BETA2007 sucessfully. The line of code you cite looks slightly different to my PR code (which is, of course, not the cause for the problems, but a hint you're not using the same code as Bernd and I do)

@MatthiasSchilder Hi Matthias, yes, you are right, I am sorry! Now it delivers much better results, but still 1m inaccuracy compared to google maps, is it google or the transformation?

![image](https://user-images.githubusercontent.com/78433087/107777157-c7114900-6d42-11eb-8b43-91eb08ee0186.png)

**Comment by MatthiasSchilder** [comment]
@MaSchue1 I'm always using [1] for doing reference calculations for comparision with DotSpatial. For transformations from DHDN/GaussKrueger to ETRS89/UTM, DotSpatial's results match those of the Geodatenzentrum with millimeter precision, so yes, possibly Google does something different, probably using a different datum transform approach.

[1] http://sg.geodatenzentrum.de/web_coordtrans/

**Comment by MaSchue1** [comment]
> @MaSchue1 I'm always using [1] for doing reference calculations for comparision with DotSpatial. For transformations from DHDN/GaussKrueger to ETRS89/UTM, DotSpatial's results match those of the Geodatenzentrum with millimeter precision, so yes, possibly Google does something different, probably using a different datum transform approach.
> 
> [1] http://sg.geodatenzentrum.de/web_coordtrans/

@MatthiasSchilder This helped a lot! working exactly! Thank you very much!
