### ISSUE TITLE
Help with Pull Requests

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1171]
Not sure if someone can help me but I have been trying to contribute with GitHub Desktop. I viewed some videos on how to make pull requests but not sure I get how to do it properly. I did my code changes on my desktop but it seems like I only have one pull request with various commits. How do I make individual pull requests instead of only one with multiple commits?

**Comment by jany-tenaj** [comment]
I haven't done this myself yet but I think you have to create one branch for each issue and create a pull request from there to DotSpatial.Master. This seems to be the way @MatthiasSchilder went about it.

If you push everything into your master and then create a pull request to DotSpatial.Master you get the effect you've got now.

**Comment by sindizzy** [comment]
Oh wow? Really? One branch for each issue seems like a waste of resources. Ok Ill try to give that a shot.

**Comment by jany-tenaj** [comment]
You can delete the branch after the fix is accepted and merged.

**Comment by sindizzy** [comment]
Yes but doesn't that mean cloning and downloading the branch every time I want to suggest a fix?

**Comment by sindizzy** [comment]
@jany-tenaj I have a pull request with 4 commits. Hopefully the devs can take a look soon. I would like to contribute more now that I know the process. Many thanks.

**Comment by jany-tenaj** [comment]
I think there is a way to switch between branches in VS without having to download the whole source code again. I haven't tried it because I like having the source code once for each fix.

I can't promise that I can take a look, because I have a 4 month old baby taking up all my time. But you'll have to split your pull request before we can commit it.

In the current condition if later on we find that one of your fixes doesn't work as expected we'd have to revert everything you added. We furthermore can't refuse one of your fixes and accept another this way.

**Comment by MatthiasSchilder** [comment]
> Yes but doesn't that mean cloning and downloading the branch every time I want to suggest a fix?

Just to be sure: you don't have to clone a working copy for every fix-branch you want to create. Clone a working copy once, create a local branch for your first fix, develop your fix and push your new branch with your fix to your github origin. Then, create a pull request, and get your fix pulled in. In your working copy, you can now switch back to master or just create a new branch for your next fix. I don't know Github Desktop, but switching with git bash or Tortoise-git it totally easy and will take only a few seconds in this situation. Branching locally does not duplicate your working copy.

**Comment by sindizzy** [comment]
Ahhh I see now. Let me give that a shot. If that is the case then maybe I can delete my current pull and redo it with as a split into four separate pulls.

**Comment by sindizzy** [comment]
So not sure what's the next step. Here is what I have done so far:

1. Cloned the project to my desktop
2. Created a branch for my fix
3. Developed my fix
4. Committed the fix to my branch
5. Publish my branch.

On step number 5 I get this error in GitHub Desktop

"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

**Comment by sindizzy** [comment]
Ok I think I had some of this wrong. New to GitHub so it was a challenge. Please check my pull request at https://github.com/DotSpatial/DotSpatial/pull/1244 Here is my revised process:

1. Go to **MY** fork of DotSpatial on the GitHub webpage and clone that repo to my desktop
2. Create a branch for my fix
3. Develop my fix in Visual Studio
4. Commit the fix in GitHub Desktop
5. Publish the branch in GitHub Desktop
6. Go to the original GitHub DotSpatial webpage. This is the original repo and NOT your personal fork
7. Click on "Compare & pull request". confirm you are merging from your personal fork/branch into the DotSpatial master

That seems to work so I have done it correctly. I will do another fix/branch later today and see how that goes. Please revise my process and pull request and make any suggestions. I hope that after making 4 or 5 of these fixes that perhaps there could be a push for a 2.1 release.

**Comment by sindizzy** [comment]
@jany-tenaj @MatthiasSchilder 
Ok here is my second pull request following the above procedure https://github.com/DotSpatial/DotSpatial/pull/1245

**Comment by sindizzy** [comment]
My third pull request https://github.com/DotSpatial/DotSpatial/pull/1246

**Comment by sindizzy** [comment]
Fourth pull request https://github.com/DotSpatial/DotSpatial/pull/1248

**Comment by sindizzy** [comment]
Fourth pull request Pull request: https://github.com/DotSpatial/DotSpatial/pull/1249

**Comment by sindizzy** [comment]
Fifth pull request (and on Christmas Day) https://github.com/DotSpatial/DotSpatial/pull/1251

**Comment by sindizzy** [comment]
Sixth pull request https://github.com/DotSpatial/DotSpatial/pull/1252

**Comment by sindizzy** [comment]
Sixth pull request https://github.com/DotSpatial/DotSpatial/pull/1253
I think that's it for now. I have one other issue I am going to look at which could be related to one of my pull requests. That will come later in the week.

**Comment by sindizzy** [comment]
Seventh pull request https://github.com/DotSpatial/DotSpatial/pull/1254
