### ISSUE TITLE
Dotspatial/GeoAPI/NetTopologySuite and WKT confusion

### ISSUE THREAD

**Issue by eiredrake** [DotSpatial/DotSpatial#1174]
Not a bug, just a question.

I've been using DotSpatial's Topology stuff for a while now. But I'm a bit confused when it comes to which set of objects I should be using. Originally I was working in framework 4.6.x but I'm working on a core 2.x version right now. So seems like a good time to ask this question that's been confusing me for a while.

basically I have various geometries (mostly points and multipolygons) stored as WKT and I want to reconstitute them into usable classes and do things with them.  Such as adding or removing points, convex and concave hulls, putting the shames on maps and so forth.

But there at least three sets of the various objects. For example DotSpatial.Topology has it's own IPolygon interface and Polygon implementation. But there is also the GeoAPI.Geometries.IPolygon interface, with the implementation apparently being in NetTopologySuite.Geometries.Polygon. I have a class that someone wrote that converts between the various GeoApi geometries to DotSpatial Geometries. But seems like there are too many classes floating around.

The WTK reader is in NetTopologySuite.IO and it's Read method takes a well known text string and puts out a GeoAPI.Geometries.IGeometry which I then need to convert to DotSpatial.Topology objects.

and there of course is a Geometry factory for DotSpatial, another one in NetTopologySuite.Geometries.

Should I just stop using DotSpatial and use the NetTopologySuite/GeoAPI combination? or is there another alternative to having to convert objects between the two sets of interfaces/implementations? How do these sets of objects relate to each other?

**Comment by jany-tenaj** [comment]
You're still using DotSpatial 1.9 or earlier. There we had DotSpatial.Topology which was an old version of NetTopologySuite. In 2.0 we removed DotSpatial.Topology and included GeoAPI and NetTopologySuite.

So if you switch to 2.0 you don't have everything twice anymore but you might have to change some of your code to work with the new design.

Also check out #1087 and the [wiki entry for Switching from 1.9 to 2.0](https://github.com/DotSpatial/DotSpatial/wiki/Switching-from-DotSpatial-1.9-to-2.0).
