### ISSUE TITLE
Adding Multi Attribute data

### ISSUE THREAD

**Issue by GrahamJohnCook** [DotSpatial/DotSpatial#1178]
Hi

We have an AutoCAD plugin that places and quantifies planting.  Area, Linear and Point based.  I’m creating an export utility to export to shp file but my knowledge of shape files is limited.  If I use area planting as an example which conveniently fits in with polygon shape files.

Area planting can be based on a single plant or a “Mix” of plants.  Creating a shape file for single planting is not a problem, I create the polygon shape and then create and populate attributes to that shape similar to:

Species: Abelia floribunda
Height: 20-30cm
RootCondition: C
Quantity: 16

Those attributes then show up against the associated shape.

My problem / question is with plant Mixes.  A mix will contain more than one plant type, for example:

Mix Name: Hedge Mix

Species: Abelia floribunda
Height: 20-30cm
Centres: 50cm
RootCondition: C
Percentage: 40%
Quantity: 16

Species: Corylus colurna
Height: 200-300cm
Centres: 70cm
RootCondition: B
Percentage: 60%
Quantity: 10

Etc.

I only seem to be able to add one row of attribute data to each polygon feature.

Do I need to create a separate polygon for every plant instance within the mix thus resulting in multiple versions of the same shape one drawn over the other?  Or is there a better way?

**Comment by jany-tenaj** [comment]
The only other way that comes to mind would be to write all your data into the datarow or create another set of columns for your second species. Both don't seem to be good solutions.

So I'd say creating two polygons would be the best way to go.
