### ISSUE TITLE
[Question] Can I generate points between to points?

### ISSUE THREAD

**Issue by opcodewriter** [DotSpatial/DotSpatial#1186]
Given two locations (latitude, longitude) does DotSpatial have a function which generates intermediary points between the two locations?

**Comment by sindizzy** [comment]
Are you looking for a geodesic path between the points? I haven't really found a way to do it with DotSpatial but I have experimented with GeoLib and Gavaghan (both open source). I have samples at work if interested.

**Comment by opcodewriter** [comment]
I will try to explain it better.
Given location1 (Longitude, Latitude), location 2(Longitude, Latitude) and a distance in meters between generated points, I need to generate a list of locations between location 1 and location 2.

**Comment by sindizzy** [comment]
Yes I understand the question but I think the thing I am asking is what kind of path do you want to take between the points. I will give you an extreme example: I have two points...one in new York and another in London. How do I create more points between them? Do you want to create a straight path as if you were to put a ruler on the monitor and with a marker just connect the two points? If so that will not follow the curvature of the earth. If you want to approximate the curvature then your path would be geodesic. On the other hand you may want to connect the two points via rhumb line. The question does become what kind of path do you want to simulate between the two points?

**Comment by VectorZita** [comment]
The short answer is that DotSpatial does not have any function to generate intermediate points between two locations, and this is not a lightweight problem to begin with. DotSpatial is for visualization and a fair degree of geometric calculations, which are, of course not the responsibility of the DotSpatial framework itself, rather as delegations to the geometry interfaces behind the scenes, except for some fundamental implementations for shapes.

The only easy (but of course not the most accurate) solution to the described problem is to reproject whichever coordinates are available between the two points to a nice projection (a conformal one would be ok if the distance between the points is not too large) set up somewhere in the vicinity of the points (try, for example, a suitable UTM zone. Then the intermediate points can be found by simple 2D geometry (like finding points between the straight line joining the two locations). These new points will then be reprojected back to the original Reference Frame (if necessary, of course) and they can serve their purpose thereafter.

If the distance is large, I would suggest an Azimuthal Equidistant projection centered at one of the points. Therefore, 2D geometry is still possible, but don't expect sub-meter precision, of course.

**Comment by sindizzy** [comment]
Purely my opinion but I believe any GIS should have a good geodesics library. To that end I use these two great libraries as an addendum to DotSpatial: [Gavaghan](http://www.gavaghan.org/blog/free-source-code/geodesy-library-vincentys-formula/) and [GeographicLib](https://geographiclib.sourceforge.io/html/NET/). The latter is a .NET wrapper to a C++ library. Both are open source and for larger distances between two points I prefer GeoLib. Would be great if one of these could be incorporated into DotSpatial.

**Comment by VectorZita** [comment]
Yes, it should! NETGeographicLib appears to be an excellent port and nothing will ever appear to be more accurate than GeographicLib in terms of algorithms. I am not very sure as to how incorporation into DotSpatial could be, though. Through plugins probably? Or perhaps exposing a Geodesics namespace, just as a Projection namespace exists with access to all there is to be for Projections, for example?

**Comment by jany-tenaj** [comment]
Currently I'd say we have enough open issues without including source code from yet another library that has to be maintained. So if you can find a way without having to add the source code your welcome to do this.

**Comment by sindizzy** [comment]
In my own projects I add the GeographicLib and then create some functions that take in points and projection info. Works pretty well. This was more a suggestion for the OP and for DotSpatial in general.

**Comment by sindizzy** [comment]
Here is what I do to create a geodesic path (or intermediate points) between two points. It uses GeographicLib to do the hard work. I hope this helps:

```
    ''' <summary>
    ''' Returns a list of DotSpatial.NetTopologySuite.Geometries.Points containing enough individual vertices that define a curved geodesic pathway
    ''' between the two points. All point values are assumed to be in terms of geographic latitude and longitude. The actual point calculation is 
    ''' done by GeographicLib but we use DotSpatial objects for input and output.
    ''' </summary>
    ''' <param name="ptStart">A DotSpatial Point in Lat/Lon where the curve starts</param>
    ''' <param name="ptEnd">A DotSpatial Point in Lat/Lon where the curve ends</param>
    ''' <param name="intervalDistInNm">A value indicating the delta distance (in NM) between intermediate vertices</param>
    ''' <returns>an array of DotSpatial Points that define a geodesic curve</returns>
    ''' <remarks>based on the example in the source code: \GeographicLib-1.48\dotnet\examples\VB\example-GeodesicLine.vb
    ''' with additional modifications by Abel G. Perez. This function has been tested in the area
    ''' of the US and works quite well when compared to similar functions in ESRI ArcGIS 9
    ''' but it may return erroneous data when the polyline crosses the poles, crosses the prime meridian,
    ''' or crosses the date line. Care should be employed when using this function and special attention
    ''' should be paid to its restrictions.
    ''' </remarks>
    Public Function GeodesicPointListDs(ByVal ptStart As Point, ByVal ptEnd As Point, ByVal intervalDistInNm As Double) As List(Of Point)
        Try
            'create a new list of points
            Dim ptList As New List(Of Point)

            'assume a WGS84 datum
            Dim geod As Geodesic = New Geodesic ' WGS84
            ''---or alternatively
            'Dim a As Double = Constants.WGS84.MajorRadius
            'Dim f As Double = Constants.WGS84.Flattening
            'Dim geod As Geodesic = New Geodesic(a, f) ' WGS84
            Dim s12 As Double, azi1 As Double, azi2 As Double
            Dim a12 As Double = geod.Inverse(ptStart.Y, ptStart.X, ptEnd.Y, ptEnd.X, s12, azi1, azi2)
            Dim line As GeodesicLine = New GeodesicLine(geod, ptStart.Y, ptStart.X, azi1, Mask.ALL)
            'alternatively Dim line As GeodesicLineExact = geod.Line(ptStart.Y, ptStart.X, azi1, Mask.ALL)

            'define the interval in meters
            Dim intervalInMeters As Double = intervalDistInNm * 1852  'interval in meters

            'calculate the number of points required to cover the segment
            Dim numPnts As Integer = CInt(Math.Ceiling(s12 / intervalInMeters))

            'use intervals of equal length
            intervalInMeters = s12 / numPnts
            Dim xLon As Double, yLat As Double, pt As Point
            For i As Integer = 0 To numPnts
                line.Position(i * intervalInMeters, yLat, xLon)
                'Debug.Print(String.Format("i: {0} Longitude: {1} Latitude: {2}", i, xLon, yLat))

                pt = New Point(xLon, yLat)
                ptList.Add(pt)
            Next i

            'success so return list of points
            Return ptList
        Catch ex As Exception
            Debug.Print(ex.ToString)
            DisplayException(ex)
            Return Nothing
        End Try
    End Function
```
