### ISSUE TITLE
Add plugin to custom form

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1187]
DotSpatial version: 2.0

My app is completely customized so I don't use the built in toolbar. However I do want to add the Measurement plugin to my app and link it to a button. I've been looking for samples but haven't really found any. I know you have to put the DLLs in the Plugin folder but from there how do I tie it in with a button on my form?

**Comment by sindizzy** [comment]
The workaround I have come up with is as follows:
Use the standard App Manager that will add the standard controls. After that has been initialized in Form Load I then look for the SpatialDockManager, SpatialStatusStrip, and ToolStripPanel controls and I hide them. I then look for the ToolStrip control with the name "Map Tool" and the ToolStripButton with Text = "Measure". Once I have that control I can then use the tsb.PerformClick anywhere I want to display the Measure dialog.

It works but it seems like a huge hack just to tap into plugin functionality. I think this is a good case to consider when updating the framework in that some developers already have established GUIs. Adding plugin functionality to already existing controls should be considered. Or I should say please, please consider the custom form during development.

**Comment by DavisMillier** [comment]
I have same work , but i just add measure as dll to reference and call dialog form it work fine
