### ISSUE TITLE
How i can add map legend in DotSpatial?

### ISSUE THREAD

**Issue by kloop1996** [DotSpatial/DotSpatial#1189]
I need add to my app legend like this:

![default](https://user-images.githubusercontent.com/12211835/42997124-48833664-8c1e-11e8-85bc-c095faaa6f0e.PNG)

But i can`t find a simple way to achieve this by DotSpatial framework.
Can anyone have a good solution for issue?

**Comment by sindizzy** [comment]
Did you try the scalebar from plugins?

**Comment by sindizzy** [comment]
Then you need a Print Layout. That's more of a presentation type of interface.
