### ISSUE TITLE
Both features updates if anyone one of them updated

### ISSUE THREAD

**Issue by sprashant80** [DotSpatial/DotSpatial#1191]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Create new features
2. Add datarow using featureset
3. Add few data to datarow and assign to respective features
4. once feat2 receives data from datarow object, feat1 itemarray also reflected same values assigned to feat2. 

Feature feat1 = new Feature();
Feature feat2 = new Feature();

feat1.DataRow = (feat.ParentFeatureSet).DataTable.NewRow();
feat2.DataRow = (feat.ParentFeatureSet).DataTable.NewRow();

//Now Add data to features
object[] _firstpipeRow = feat.DataRow.ItemArray;
_firstpipeRow[(int)WDSEnums.eConduitParameters.Name] = _conduitName1;
_firstpipeRow[(int)WDSEnums.eConduitParameters.ID] = _idforpipe;

feat1.DataRow.ItemArray = _firstpipeRow;
            

object[] _secondpipeRow = SelectedPipeFeature.DataRow.ItemArray;
_secondpipeRow[(int)WDSEnums.eConduitParameters.Conduit_Name] = _conduitName2;
_secondpipeRow[(int) WDSEnums.eConduitParameters.Conduit_ID] = _idforpipe + 1;
_secondpipeRow[(int)WDSEnums.eConduitParameters.Length] = feat2.Geometry.Length;

feat2.DataRow.ItemArray = _secondpipeRow;
// At this step, feat1 itemarray and feat2 itemarray exactly the same which I'm not expecting.

DotSpatial version:  2.0.414

### Expected behaviour

I believe feat1 & feat2 are different entities hence data assigned to feat1 and feat2 should update another feat.

**Comment by jany-tenaj** [comment]
What are feat and SelectedPipeFeature? Might those be the same?

**Comment by sprashant80** [comment]
Yes both are different.....

However, If I update _secondPipeRow.Name then _firstpipeRow.Name also updated..... Which I believe it should not happen.
