### ISSUE TITLE
System.OutOfMemoryException with ReadBytes

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1194]
I use DotSpatial to process a collection of data, then clear it from the map, and load another collection of data. Just recently I started seeing the exception below. Could it be that I am not clearing something properly from the map? Maybe I am not disposing of the current layers properly? What are some of the things i could look at to troubleshoot?

```
Message: Exception of type 'System.OutOfMemoryException' was thrown.
Source: mscorlib
Target Method: [mscorlib]System.IO.BinaryReader::ReadBytes()
Help Link: 

Stack Trace:
=======================================================
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at DotSpatial.Data.AttributeTable.SupplyPageOfData(Int32 lowerPageBoundary, Int32 rowsPerPage)
   at DotSpatial.Data.Shapefile.GetAttributes(Int32 startIndex, Int32 numRows)
   at DotSpatial.Data.FeatureSet.SelectIndexByAttribute(String filterExpression)
   at DotSpatial.Symbology.LabelLayer.CreateIndexedLabels()
   at DotSpatial.Symbology.LabelLayer.CreateLabels()
   at DotSpatial.Symbology.LabelLayer.set_Symbology(ILabelScheme value)
   at MyApp.LoadPointShapefile(String shpfPathAndName)
```

**Comment by MatthiasSchilder** [comment]
Yep, looks like there is some sort of problem. I wrote a small demo program, which adds and removes layers to/from the map repeatedly. If a MapLabelLayer is involved, memory consumption rises steadily. If there is only a feature layer, memory consumption is quite stable.

![image](https://user-images.githubusercontent.com/313898/44977236-cd8f1a00-af67-11e8-85f2-94645c132fd4.png)

**Comment by jany-tenaj** [comment]
We had this problem with other layers before. Seems we oversaw this one when we fixed the others. If one of you has time to take at look at it feel free.

**Comment by sindizzy** [comment]
Where would I start to look for what was done with other layers? This one affects me as I load and reload layers with labels quite a bit in my process.

**Comment by VectorZita** [comment]
-How many features do the layers that you are loading contain? Are they on the order of hundreds or thousands, or???

-When you say a MapLabelLayer is involved, how "much" involved is it? I mean, do you draw the labels on the map or not? The way I expect this to be is that when you don't actually visualize the labels, you shouldn't have a big memory problem. When you show them and **then** remove the layer, there might be a problem, but I am not sure as to how big it is.

I was not able to reproduce the dramatic increase shown in the snapshot above (like ~380MB), I could only see a small increase in the tens of MBs after about 50 adding and removing the same feature layer (of ~6500 features) while creating its label layer and even drawing it in the meantime. I already think I know where to attribute this small increase, but I am curious as to what was used that increased the memory overhead to 380MB (how many iterations etc.)

Thank you for the information, maybe we can get down to this problem soon!

**Comment by sindizzy** [comment]
I have about 7 layers that I would consider static with hundreds of features per layer. One is a point layer and always displays labels. For each process I then add 6 new layers with 3 of them being points. The point layers get labels all the time. The new layers probably have hundreds of features.

On to the next process, I then clear ALL layers and re-add them. I do this because the map projection could change and there is a reprojection issue with DotSpatial that I posted about here https://github.com/DotSpatial/DotSpatial/issues/1104 and here https://github.com/DotSpatial/DotSpatial/issues/1199
This continues about 30 to 50 times.

**Comment by VectorZita** [comment]
Hundreds should not be an issue, really... which is strange!

Moving on to the next potential problem, are the involved shapefiles that you load very large? How much do they "weigh" in MB?

It could be the case that a relatively small dataset (in terms of total features) is accompanied by a huge data table with dozens of attributes per feature. What technically happens when label layers are involved, which does not happen while simply manipulating feature layers without tampering with labels, is that the attributes are loaded/supplied by the file upon demand (FillAttributes is eventually called). Could it be that you are manipulating datasets that contain numerous attributes per feature?

**Comment by sindizzy** [comment]
Each shapefile has no more than 15 attribute fields so not very big. However, I haven't seen the issue in a while now. The user who reported it said the Recycle Bin was full with about 2GB of temp data. My app does recycle all the temp files after each process. I wonder if the app itself was just pegging the ram trying to recycle files while the bin was full. He emptied the bin and set a limit of 40MB on it and I think this has resolved it. Is that a possible source of memory issues?

**Comment by VectorZita** [comment]
I am still a bit troubled by the example of @MatthiasSchilder above, which shows a rather dramatic leak of 350+ MBs. The only plausible issue I can come up with right now is that some kind of exception was occurring upon attempting to recycle files, which prevented the "cleanup" from occurring, thus leaving the data in memory. Of course, I have no idea about your architecture, so you will have to check this out for yourself. Although not the only way to have memory leaks, I cannot think of anything else right now and this is, technically speaking, the "golden standard" of memory leaks (exceptions without finally blocks for cleanup).

Apart from that, DotSpatial has some very minor GDI object temporary leaks (such as the Caches object in the MapLabelLayer, which never disposes its Fonts, Pens and Brushes, though they are very few, so it does not have a measurable impact in the long run). I have confirmed that adding and removing a MapLabelLayer to the map directly ends up consuming a lot more memory indeed, while simple feature layers, which are accompanied by a normally created and active LabelLayer do not take up that much after about the same number of add-remove operations. Still looking into it.

**Comment by sindizzy** [comment]
Ok thank you for the info. I have talked to several users and they state that after capping the Recycle Bin size and me implementing a "permanent delete" rather than recycle in my app the issue has not resurfaced.

**Comment by VectorZita** [comment]
No problem! On a side note, @MatthiasSchilder, I would like to know whether you added/removed the MapLabelLayers directly in your code for the test referenced above, because I could not directly reproduce the behavior in a number of tests and such a problem would be a significant issue. Is it possible to share your demo code?

Thank you in advance!
