### ISSUE TITLE
custom extension call

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1200]
Hello
How can i call custom Extension for example gdal ?
I use appmanager but it load all extension and add some control to my application .
and how can i use progress handler i need to show splash page when loading larg file size.
Thanks

**Comment by sindizzy** [comment]
Search under my name as i think I had posted a simple way to add the extension without loading the pre-formatted controls.

**Comment by DavisMillier** [comment]
@sindizzy  i can not found any thing !
My you help me more ?
and about progress handler 
i need to show splash page while loading new layer
Thanks

**Comment by sindizzy** [comment]
here is what I use

```
            'load extensions (needed to load ADF raster files)
            If Not DesignMode Then
                '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
                'create controls in memory so we dont have to add them to the Form
                '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
                'Being able to load extensions (including DataProviders) requires a DockManager, HeaderControl, and ProgressHandler
                Dim dm As New SpatialDockManager
                appmgrMain.DockManager = dm
                Dim hc As New SpatialHeaderControl
                appmgrMain.HeaderControl = hc
                Dim ss As New SpatialStatusStrip
                appmgrMain.ProgressHandler = ss 'this can be a statusstrip
                'appmgrMain.Map = dsMapMain

                Shell = Me
                appmgrMain.LoadExtensions()
                'appmgrMain.ActivateExtensionsExclusively({"DotSpatial.Data.Rasters.GdalExtension"})

                For Each ext As Extension In appmgrMain.Extensions
                    Debug.Print("Name={0} AssemblyQualifiedName={1} Version={2}", ext.Name, ext.AssemblyQualifiedName, ext.Version)
                Next ext
            End If
```

**Comment by DavisMillier** [comment]
@sindizzy Thank you for answer it's right but when i wrote
`var hc = New SpatialHeaderControl();
appmgrMain.HeaderControl = hc;`

i get null object error on
                `appmgrMain.LoadExtensions()`
line

**Comment by sindizzy** [comment]
https://github.com/DotSpatial/DotSpatial/issues/1088

**Comment by sindizzy** [comment]
Maybe you an post your solution to this issue so that others can benefit.
