### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by BurkhartS** [DotSpatial/DotSpatial#1201]
Hi All,
as the documentation on Codeplex is no longer available, where to find a documentation for dotspatial?

Cheers
Burkhart

**Comment by sindizzy** [comment]
https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation

**Comment by BurkhartS** [comment]
Hi sindizzy,

thank you. I saw this file but it showed no information at all....
...works out that this file can't be used from a network drive, so starting it locally everything is okay

Cheers
Burkhart

**Comment by MatthiasSchilder** [comment]
> ...works out that this file can't be used from a network drive, so starting it locally everything is okay

This is known behaviour and happens with all .chm files on Windows operating systems.
