### ISSUE TITLE
Calculation of translation param in InRamImageData.GetBitmap is defective

### ISSUE THREAD

**Issue by MatthiasSchilder** [DotSpatial/DotSpatial#1203]
*IF BUG, INCLUDE THIS PART:*

If you use a web map service within a project, which has a coordinate system where coordinate values have more significant digits than a float may handle (for example EPSG 4647; 8 digits ahead of the decimal point, 3 or 4 after), you may notice the WMS-map in the background moves a few units relatively to content in the foreground (for example, features from a shapefile), every time the view extents change. The drift is variable and usually very small (< 10 CRS units).

![image](https://user-images.githubusercontent.com/313898/44914358-4d32a400-ad30-11e8-8d4d-2c490c6462b7.png)
![image](https://user-images.githubusercontent.com/313898/44914392-62a7ce00-ad30-11e8-8d7f-0530b6b6a00a.png)

Also you may notice, there is some space at the sides of the map control, which should be filled with the map image, but isn't.

![image](https://user-images.githubusercontent.com/313898/44914672-38a2db80-ad31-11e8-9fe9-4dd4d433528d.png)
![image](https://user-images.githubusercontent.com/313898/44914716-55d7aa00-ad31-11e8-8542-a228dc0a9eea.png)

### Steps to reproduce

Due to confidentiality constraints, I'm unfortunately not able to provide the shapefile or WMS data.

1. Load a shapefile with POINT features. Features should have coordinates in a projected coordinate system, where coordinate values have many significant digits.
2. Connect to a WMS, which has data available within the extents of the shapefile.
3. Zoom and pan. You may notice that after each update of the WMS map, there is some drift between foreground and background layers.

DotSpatial version: HEAD of master

### Expected behaviour

A WMS-map in the background shouldn't move relatively to some foreground content.

### Actual behaviour

There should be no variable drift between foreground content and a background WMS-map.

**Comment by MatthiasSchilder** [comment]
I think this is due to a bug in InRamImageData.GetBitmap. Because the matrix constructor in line 248 expects float params, all calculations in before are executed in float. This leads to a loss of precision for l and t, which causes wrong values for xShift / yShift. Simple solution seems to be to avoid the cast to float for l and t and cast only after the subsequent division, when values are small enough to be represented precisely with a float. I will open a pull request soon.

![image](https://user-images.githubusercontent.com/313898/44915592-a9e38e00-ad33-11e8-878c-9d6984d7cb86.png)

**Comment by MatthiasSchilder** [comment]
@jany-tenaj I'll take a look at it.

**Comment by MatthiasSchilder** [comment]
@jany-tenaj You were right. Fixed the other occurrences, too. It's contained within the pull request.

Besides, AppVeyor builds fail since commit 93a73d6bb4bc328ceab36c759b204a6312bea6e8. It looks like AppVeyor does not accept pattern matching feature of C# 7 in LayoutLegend?

**Comment by MatthiasSchilder** [comment]
@jany-tenaj Looks like the above fix is only part of the problem; it makes only the small white borders go away, a little misplacement is still there. Please wait with applying the pull request.

**Comment by jany-tenaj** [comment]
Just let me know when you're done. Having that fixed would be sweet. I think there are some other issues running around that might get fixed by this.

**Comment by MatthiasSchilder** [comment]
@jany-tenaj I think the pull request can be applied now. The rest of the issue was a false positive caused by wrong usage. Can you give me a hint which issues may be related to this one?

**Comment by jany-tenaj** [comment]
Have a look at #824.

**Comment by jany-tenaj** [comment]
@MatthiasSchilder did you have a look at issue 824?

**Comment by MatthiasSchilder** [comment]
@jany-tenaj Yes, back then. Hard to say, looks like it is related, but I wasn't able to reproduce it, because I wasn't able to find an appropriate ECW. However, I'd plead for merging it to master, because it definitely fixes a problem with 'other' background image data.
