### ISSUE TITLE
[Question] Can DotSpatial be used to crop GeoTIFF?

### ISSUE THREAD

**Issue by Gigas002** [DotSpatial/DotSpatial#1221]
Currently I use console version of MapTiler to crop GeoTIFFs to tiles, the input string looks like:

`-geodetic -nodata 0 0 0 -f png32 -o result/ -tms -resampling bilinear -srs "+proj=longlat +datum=WGS84 +no_defs" -zoom 8 12 source.tif`

Here's some tips about MapTiler's parameters:

- `-geodetic` sets output tiling system to WGS84;
- `-nodata 0 0 0` eliminates borders of multiple map sheets that are stitched together;
- `-f` sets output tile format;
- `-o `is output directory;
- `-tms` is tiling scheme OSGEO TMS (bottom-left origin), flipped Y axis as oppose to Google XYZ. This tiling scheme is defined as a standard for MBTiles;
- `-srs` is dataset projection;
- `-zoom` determines which layers of the tile pyramid will be generated;
- `source.tif` is an input GeoTIFF;

And here's the [link](https://maptiler.readthedocs.io/en/stable/) to full manual of MapTiler.

So, can this library crop GeoTIFFs like this? And also can it be used as a replacement for [GdalWarp](https://www.gdal.org/gdalwarp.html)?
Thanks in advance for your reply!

**Comment by sindizzy** [comment]
I assume a TIFF is a raster type so i would say you could load it in a map, then clip it, and save the results.
