### ISSUE TITLE
 DotSpatial2.0   make the layer annotation label is not display

### ISSUE THREAD

**Issue by xc398013967** [DotSpatial/DotSpatial#1223]
hello everyOne

When  I use DotSpatial2.0 ,I do not show when I make the layer annotation.

here is my  test demo，I drew a point, then assigned an attribute ID to the point, and then displayed the property ID.   But according to the following code, ID is not displayed：

 private void drawPoint()
        {
            Coordinate coor = new Coordinate(108.78, 34.44);
            NetTopologySuite.Geometries.Point pt = new NetTopologySuite.Geometries.Point(coor);
            MapPointLayer pl = new MapPointLayer();
            pl.Symbolizer = new PointSymbolizer(Color.Red, DotSpatial.Symbology.PointShape.Star, 50);
            AttributesTable at = new AttributesTable();
            at.AddAttribute("id", 10);
            Feature fea = new Feature(pt, null);
            fea.Attributes = at;
            pl.FeatureSet.AddFeature(fea.Geometry);
            //LabelSymbolizer labelSy = new LabelSymbolizer
            //{
            //    FontFamily = "Tahoma",
            //    FontColor = Color.Black,
            //    BackColorEnabled = true,
            //    BackColor = Color.Green,
            //    FontSize = 100,
            //    LabelPlacementMethod = LabelPlacementMethod.Center,
            //    Orientation = ContentAlignment.TopCenter,
            //    PreventCollisions = false,
            //    PriorityField = "id",
            //};
            MapLabelLayer lb = new MapLabelLayer(pl);
            //lb.Symbolizer = labelSy;
            lb.Symbology.Categories[0].Expression = "[FID]";
            lb.Symbology.Categories[0].Name = "nihao";
            lb.Symbolizer.Alignment = StringAlignment.Center;
            lb.Symbolizer.LabelPlacementMethod = LabelPlacementMethod.Centroid;
            lb.Symbolizer.Orientation = ContentAlignment.BottomCenter;
            pl.LabelLayer = lb;
            pl.ShowLabels = true;
            _map.MapFrame.DrawingLayers.Add(pl);
            _map.ViewExtents = new DotSpatial.Data.Extent(108.722938537598, 34.4265341, 108.795059204102, 34.4521255493164);
            _map.MapFrame.Invalidate();  
        }

**Comment by VectorZita** [comment]
Well, before delving too deep, let's tackle things one at a time. Based on the code in `MapFrame.Initialize(List<Extent> regions)` in the **MapFrame.cs** file, if you take a look at it you can see that the **InitializeLabels** function is called only for every layers in the **Layers** collection, **not** for the **DrawingLayers** collection.

Therefore, even if your code does the job, the map frame control (as it is currently built) doesn't draw labels for layers that are placed in the **DrawingLayers** collection.

Try placing the **pl** variable in **_map**.**MapFrame**.**Layers** and see if this solves your problem. Let us know how it goes.

**Comment by xc398013967** [comment]
@VectorZita   
Thank you very much for your answer.
I added my dot layer pl in _map. MapFrame. Layers, but did not show the dots added, so I set the initial range _map. MapFrame. Invalidate (List < Extent >); but I don't know how to write it here. Here's my code, but it doesn't show dots and annotations.

 public partial class Form1 : Form
    {
        private Map _map = null;
        public Form1()
        {
            InitializeComponent();
            _map = new Map()
            {
                Dock = DockStyle.Fill,
                FunctionMode = FunctionMode.Pan,
                Projection = KnownCoordinateSystems.Geographic.World.WGS1984,
            };
            this.Controls.Add(_map);
            drawPoint();
        }
        private void drawPoint()
        {
            Coordinate coor = new Coordinate(108.78, 34.44);
            NetTopologySuite.Geometries.Point pt = new NetTopologySuite.Geometries.Point(coor);
            MapPointLayer pl = new MapPointLayer();
            pl.Symbolizer = new PointSymbolizer(Color.Red, DotSpatial.Symbology.PointShape.Triangle, 30);
            pl.ShowLabels = true;
            _map.MapFrame.Layers.Add(pl); //here  add point  layer
            DataTable dt = new DataTable();
            dt.Columns.Add("id", typeof(int));
            pl.FeatureSet.DataTable = dt;
            DotSpatial.Data.Feature fea = new DotSpatial.Data.Feature(pt);
            DataRow row = dt.NewRow();
            row.SetField("id", 10);
            DotSpatial.Data.IFeature feature = pl.FeatureSet.AddFeature(fea.Geometry);
            feature.DataRow = row;
            IMapLabelLayer lableLayer = new MapLabelLayer();
            lableLayer.Projection = _map.Projection;
            ILabelCategory category = lableLayer.Symbology.Categories[0];// lableLayer.Symbology.Categories[0];// new LabelCategory();// lableLayer.Symbology.AddCategory();
            category.Expression = "[id]";
            lableLayer.CreateLabels();
            category.Symbolizer.HaloColor = Color.Green;
            category.Symbolizer.BorderColor = Color.Green;
            category.Symbolizer.BorderVisible = true;
            category.Symbolizer.BackColorEnabled = true;
            category.Symbolizer.FontStyle = FontStyle.Bold;
            category.Symbolizer.FontColor = Color.Black;
            category.Symbolizer.BackColor = Color.Green;
            category.Symbolizer.FontSize = 30;
            category.Symbolizer.Orientation = ContentAlignment.TopCenter;
            category.Symbolizer.Alignment = StringAlignment.Center;
            category.Symbolizer.PriorityField = "FID";
            List<Extent> listExtent = new List<Extent>();
            Extent extent = new Extent(108.722938537598, 34.4265341, 108.795059204102, 34.4521255493164);  //map view extent
            listExtent.Add(extent);
            _map.MapFrame.Initialize(listExtent);  //how  to write  here   
            _map.MapFrame.Invalidate();  
        } 
    }

**Comment by VectorZita** [comment]
Try this code and let me know if this works:
```
private void drawPoint()
{
    //Create the point you want to add:
    Coordinate coor = new Coordinate(108.78, 34.44);
    NetTopologySuite.Geometries.Point pt = new NetTopologySuite.Geometries.Point(coor);
    
    //Create the FeatureSet and let IT create the feature for you (so that it will be ready).
    IFeatureSet fs = new FeatureSet(FeatureType.Point);
    IFeature ft = fs.AddFeature(pt);

    //Apart from creating features, the FeatureSet also knows how to manage a DataTable.
    //So you can add columns THEREAFTER, no need to create the table yourself.
    fs.DataTable.Columns.Add("id", typeof(int));
    ft.DataRow["id"] = 56;

    //Let the FeatureSet know that its projection is the same as the map's.
    fs.Projection = _map.Projection;

    //This synchronizes the internal Features with the corresponding drawing equivalents (Shape classes).
    //This is more important that you know! You will almost always get errors if you don't call this after
    //any add/remove operations in a FeatureSet… sooner or later, that is!
    fs.InitializeVertices();

    //The map knows how to create a layer so let IT create the layer by adding the feature set.
    IMapFeatureLayer lyr = _map.Layers.Add(fs);

    //This is an extension method already included in DotSpatial. You could create the label layer
    //yourself **properly**, but for now, just trust their method, you will find out it has a few overloads
    //and you can control a lot of stuff from there anyway. This call here is just an example anyway.
    lyr.AddLabels("[id]", new Font(FontFamily.GenericMonospace, 12), Color.Black);

    //This is absolutely necessary to enable label drawing.
    lyr.ShowLabels = true;
}
```

Hopefully, this will do what you are trying to achieve, without even having to do anything in terms of invalidating etc. You can take it from there and ask again if you need anything. The main idea is that the classes of DotSpatial already undertake many **heavy** tasks, so that you can focus on the mere essentials.

**Comment by xc398013967** [comment]
@ VectorZita  
Thank you very much for your answer.
That's the answer I want，At the same time, I also know that my research on Dotspatail is too small. I will continue to do in-depth research.

**Comment by VectorZita** [comment]
Glad to know it helped you! I understand your position, most of us have already been there (except for the contributors, which really put their heart into this), you are at the feet of a significantly high mountain (not the highest there is, but I have come to admire the overall effort quite a lot). In any case, you've got to have a good plan of what it is that you want to use DotSpatial for. It is a very versatile framework offering quite robust functionality and a significant feature base, plus it is globally open to improvement.

If you need it for intricate data editing and mapping, it will definitely benefit you to get acquainted with the basics and dig down the codebase a bit! A fairly adequate documentation base exists to get you properly introduced, hopefully, you already have taken a good look at it. If you have any other problem, you can always post a question here.
