### ISSUE TITLE
Map Slow Problem

### ISSUE THREAD

**Issue by ghost** [DotSpatial/DotSpatial#1227]
Hello everyone, i am using dotspatial in my project. When i navigate with pan tool on Map, the Map moves slowly. Is there anything for faster?

**Comment by Veys42** [comment]
I have 4-5 layers. Some layers have about 250-300 polygon features. I am using onClick, onMouseMove events in Map. Furthermore, when i want to add layer to the Map, I am waiting about 5-6 seconds.

**Comment by sindizzy** [comment]
Comment out your event code and see if that speeds it up. If so then code it so when its in pan mode the code doesn't get executed.

**Comment by VectorZita** [comment]
I agree with @sindizzy. While your mouse button is down and you are **actively** panning, the map should not be slow, unless you are doing quite complicated stuff in **MouseMove**. If you could share some code or insight in what you are doing, it would help us identify the source of your problem. Apart from that, it is definitely something in your events that slows it down.
