### ISSUE TITLE
How to have a proper and recent nuget package ?

### ISSUE THREAD

**Issue by Kharente-Deuh** [DotSpatial/DotSpatial#1232]
Hey !

I just updated the packages i use thanks to nuget.org.
Then i have:
DotSpatial.Mono v1.9.0
DotSpatial.Projections v2.0.0-rc1
DotSpatial.Serialization v2.0.0-rc1
DotSpatial.Topology v1.9.0

The thing is that none of their version are the same, and because of that, Serialization 2.0.0-rc1 and Topology 1.9.0 can't work together.

Actually, Topology 1.9.0 uses a the class CloneableEM at a moment, and this class is in Serialization 1.9.0 but not in 2.0.0-rc1.

Is there a way to have all the assemblies aligned on the same version and can you publish the related Nuget packages?

Thanks :D

**Comment by sindizzy** [comment]
How about here:
https://github.com/DotSpatial/DotSpatial#links

**Comment by jany-tenaj** [comment]
You can use either the 1.9 nuget files or switch to 2.0 rc1. Check out the [switching guide](https://github.com/DotSpatial/DotSpatial/wiki/Switching-from-DotSpatial-1.9-to-2.0) if you want to use 2.0 rc1.

**Comment by Kharente-Deuh** [comment]
Thanks a lot, that's exactly what i wanted.
