### ISSUE TITLE
 Real-time loading and displaying GPS points with dotspatial 2.0, why the whole map is refreshed？

### ISSUE THREAD

**Issue by xc398013967** [DotSpatial/DotSpatial#1233]
Real-time loading and displaying GPS points with dotspatial 2.0 winform. Why does the whole map flicker and refresh every time a point is displayed in real time? How can I make the real-time point refresh display? Here is my demo.

 private IFeatureSet _fs= null;
        public IFeatureSet fs
        {   get {
                if (_fs== null)
                {
                    _fs= new FeatureSet(FeatureType.Point);
                    _fs.DataTable.Columns.Add("名称", typeof(string));
                }
                return _fs;  }
     set
            {  _fs= value;    }
        }
        private IMapFeatureLayer mapFeatureLayer
        {
            get
            {
                IMapFeatureLayer lyr = _map.Layers.Add(_fs);
                lyr.LegendText = "人员";
                lyr.ShowLabels = true;
                lyr.Symbolizer= new PointSymbolizer(Color.Red, DotSpatial.Symbology.PointShape.Triangle,12);
                ILabelSymbolizer ls = new LabelSymbolizer()
                {
                    OffsetY = 8,
                    Orientation = ContentAlignment.MiddleCenter,
                    ScaleMode = ScaleMode.Symbolic,
                    FontColor= Color.White,
                    FontSize= 8,
                };
                //lyr.AddLabels("[名称]", new Font(FontFamily.GenericMonospace, 8), Color.White);
                lyr.AddLabels("[名称]", "", ls, 1);
                return lyr != null ? lyr : null;
            }
        }
  NetTopologySuite.Geometries.Point pt = new NetTopologySuite.Geometries.Point(Convert.ToDouble(location[0]), Convert.ToDouble(location[1]));
            _fs.Projection = _map.Projection;
            if (_fs!= null && _fs.Features.Count > 0)
            {
                _fs.Features.Clear();
                _fs.UpdateExtent();
            }
            for (int i = _fs.Features.Count - 1; i >= 0; i--)
            {
                var item = _fs.GetFeature(i);
                if (item.DataRow[0].ToString() == name )
                {
                    userFs.Features.Remove(item);
                }
                userFs.UpdateExtent();
            }
            IFeature ft = _fs.AddFeature(pt);
            ft.DataRow["名称"] = message.user_name;
            _fs.InitializeVertices();

**Comment by sindizzy** [comment]
Try    

```
dsMap.SuspendLayout()
'do your things
dsMap.ResumeLayout()
```

**Comment by xc398013967** [comment]
@sindizzy   
According to the dsMap. SuspendLayout () method you provided, the whole map will still flicker, but the _map. MapFrame. DrawingLayers method will not flicker, but it will not display the annotation
