### ISSUE TITLE
How to render the sub-catchment and streamlines from the taudem plugin?

### ISSUE THREAD

**Issue by WindingWinter** [DotSpatial/DotSpatial#1235]
From [taudem command line guide](http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf), one can see that taudem is capable of computing the streamlines and the catchment /grid cells that drain to the streamline, as shown below:

![catchment_streamline](https://user-images.githubusercontent.com/13161574/49362977-58c0ad00-f71b-11e8-927f-e14d6f624f54.png)

Not sure what software was used, though. 

Given that dotspatial also support taudem as plugin, is it possible to render the streamlines and the catchments, as per above, on the DotSpatial.Controls.Map ( or other controls)?

Any guide/tutorial on how this can be done?

**Comment by sindizzy** [comment]
What about this https://github.com/DotSpatial/DotSpatial/blob/cf2b523ed00e67e42cd0d645a351b975772c4c38/Source/DotSpatial.Plugins.Taudem/Taudem5Exe/Help/index.html

**Comment by WindingWinter** [comment]
@sindizzy , the reference you gave has to do with how to use taudem, but I'm asking how to render the taudem output on `DotSpatial.Controls.Map`? 

They are two different things.
