### ISSUE TITLE
Layer display order does not work

### ISSUE THREAD

**Issue by xc398013967** [DotSpatial/DotSpatial#1238]
The dotspace2.0 loading Geoserver wms is a mapping, in added-and-point layer, Why does the WMS bottom map always stick to the top to hide the line and dot layers and adjust the layers order does not work?
 such as  
map.layers.add(wmsLayer);-------index 0
map.layers.add(pointlayer);-------index 1
map.layers.add(lineLayer); -------index 2

This is the layer class that loads GeoServer WMS？
 public abstract class ImageLayer : Layer, IMapLayer
    {
        public int ZoomLevel { get; set; }
        public Size WindowSize { get; set; }
        public ImageLayer(){ }
        public void DrawRegions(MapArgs args, List<Extent> regions, bool selected)
        {
            foreach (var region in regions)
            {
                if (region.Width <= 0 || region.Height <= 0)
                    continue;
                if (WindowSize.Width <= 0 || WindowSize.Height <= 0 || ZoomLevel <= 0)
                    continue;
                var bmp = GetBitmap(region);
                if (bmp == null)
                    continue;
                args.Device.DrawImage(bmp, 0, 0);
            }
        }
        protected virtual Image GetBitmap(Extent e)
        {
            try
            {
                string url = GetURL(e);
                Console.WriteLine(url);
                using (WebClient client = new WebClient())
                {
                    client.Proxy = null;
                    byte[] data = client.DownloadData(url);
                    if (data.Length < 400)
                    {
                        var text = Encoding.GetEncoding("UTF-8").GetString(data);
                        Console.WriteLine(text);
                        return null;
                    }
                    using (MemoryStream ms = new MemoryStream(data))
                    {
                        return new Bitmap(ms,true);
                    }
                }
            }
            catch
            {
                return null;
            }
        }

**Comment by sindizzy** [comment]
Have you tried loading them the reverse way?

**Comment by xc398013967** [comment]
@sindizzy   
I've tried loading them the reverse way, but it's still covered.

**Comment by sindizzy** [comment]
How about if you put them in Map Groups.

**Comment by xc398013967** [comment]
@sindizzy   
Add three layers to MapGroup as you suggest, but the order of layers still doesn't work. The bottom image WMS will also cover the Map Feature Layer layer. Can you provide an example? Did I write it incorrectly?
