### ISSUE TITLE
DotSpatial.Controls V1.9 does not include the SpatialToolstrip toolbox item

### ISSUE THREAD

**Issue by pan054** [DotSpatial/DotSpatial#1240]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Nuget V1.9 DotSpatial.Controls 
2. Open the DotSpatial.Controls Toolbox item, using a VB.Net WinForms app, VS 2017, Win 10 Pro
3. Or with locally compiled DS code: manually add a DotSpatial.Control toolbox and add controls via Choose item contex menu option.

DotSpatial version: 
V1.9, (both Nuget and locally compiled versions)
### Expected behaviour

A SpatialToolstrip control available in the toolbox

### Actual behaviour
Tell us what happens instead
The SpatialToolstrip control is missing

Can you also include a screen shot?

![image](https://user-images.githubusercontent.com/45922440/50118417-51f97480-029b-11e9-9c37-fd44a77a105a.png)

![image](https://user-images.githubusercontent.com/45922440/50118452-6fc6d980-029b-11e9-897b-f3454c187520.png)

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by sindizzy** [comment]
Take a look at this post https://github.com/DotSpatial/DotSpatial/issues/1232

**Comment by pan054** [comment]
Good morning sindizzy,
Good to see that there are still some real FORTRAN people around, it was my first language.
Anyway, I have been VERY careful not to mix DS versions.  Maybe don't really understand why you sent me to that post?

**Comment by jany-tenaj** [comment]
I think someone did hide the toolstrip in 1.9. Try using the latest master, if it was hidden it should be visible again.

**Comment by pan054** [comment]
Thanks. Yes, I alreadyusing the rc, and it is back in that version.
