### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by erikjl** [DotSpatial/DotSpatial#1250]
Haven't found any "getting started' docs that addresses these issues, so any help would be much appreciated!

**Comment by jany-tenaj** [comment]
Check out the [DemoMap](https://github.com/DotSpatial/DotSpatial/tree/master/Source/DemoMap) project. It shows you the base you need to get your program running.

If possible start with the current master and not 1.9.

**Comment by erikjl** [comment]
Is there any documentation aside from the examples?

**Comment by sindizzy** [comment]
Try this https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation

**Comment by sindizzy** [comment]
and this https://github.com/DotSpatial/DotSpatial/tree/master/Source/Examples

**Comment by erikjl** [comment]
Ok thank you!
