### ISSUE TITLE
Conversion differences compared to .gov

### ISSUE THREAD

**Issue by RayInPA** [DotSpatial/DotSpatial#1257]
This is either a bug or a request for explanation from someone who knows more, as my knowledge here is quite limited.

DotSpatial conversions differ from conversion on the .gov conversion tool.

### Steps to reproduce

1.  Use this site, https://tagis.dep.wv.gov/convert/ , convert from NAD83 to WGS84
2.  Example:  35.088546,-93.550596 converts to 35.0885524,-93.5506028
3.  In DotSpatial, 35.088546,-93.550596 converts to 35.088546,-93.550596.  Or, that is, it calculates back to the original values that were inputted.

### Expected behaviour

I believe I should expect the converted values to match the government website's conversion values.

### Actual behaviour

It appears to go through calculations but land back at the original input values instead of converted values.  Is DotSpatial incorrect, or is it the .gov tool that is?

**Comment by MatthiasSchilder** [comment]
Could you try out the changes proposed in #1059 ? May be due to errors with handling of DatumTransforms, where gridshifts are used. Those fixes helped other users with similar problems. I'd advocate the pull request would be merged to master, because there are some serious bugs.

**Comment by RayInPA** [comment]
I tried out the code at https://github.com/DotSpatial/DotSpatial/pull/1059 and the results were the same.  The truth is that I'm not entirely sure how to validate what the right conversion is.  I'm _assuming_ the .gov site is accurate, but how would I even verify that?

**Comment by MatthiasSchilder** [comment]
You could try to perform a similar conversion with for example QGIS or ArcGIS to get another reference. 

By the way, the hint in your converter

"NAD83(1986) is the original realization of NAD83, which is practically identical to the original WGS84."

may be of interest. May be an explanation for the values DotSpatial produces. Maybe they are working with slightly different definitions.

**Comment by sindizzy** [comment]
Tatuk GIS has a free coordinate conversion tool. Give that a shot.

**Comment by jany-tenaj** [comment]
Closed because user didn't respond.
