### ISSUE TITLE
How to add scale on map

### ISSUE THREAD

**Issue by moumed** [DotSpatial/DotSpatial#1258]
Please someone to tell me how to add a scale Bar on the map in Dot spatial ?
I didn't find a solution of this in Dot Spatial's Documentation !

**Comment by sindizzy** [comment]
Scale bars are a component of the Print Layout. Have you taken a look at the scale bar plugin?

**Comment by moumed** [comment]
I don't need it for printing but to set it in the map and manage date according to the scale bar ..


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : "Abel G. Perez" <notifications@github.com> Date : 07/01/2019  01:02  (GMT+01:00) À : DotSpatial/DotSpatial <DotSpatial@noreply.github.com> Cc : moumed <moumed2810@gmail.com>, Author <author@noreply.github.com> Objet : Re: [DotSpatial/DotSpatial] How to add scale on map (#1258) 
Scale bars are a component of the Print Layout. Have you taken a look at the scale bar plugin?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DotSpatial/DotSpatial","title":"DotSpatial/DotSpatial","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DotSpatial/DotSpatial"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sindizzy in #1258: Scale bars are a component of the Print Layout. Have you taken a look at the scale bar plugin?"}],"action":{"name":"View Issue","url":"https://github.com/DotSpatial/DotSpatial/issues/1258#issuecomment-451787975"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DotSpatial/DotSpatial/issues/1258#issuecomment-451787975",
"url": "https://github.com/DotSpatial/DotSpatial/issues/1258#issuecomment-451787975",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jany-tenaj** [comment]
Try the scalebar plugin.

**Comment by abdallaho98** [comment]
> Try the scalebar plugin.
Can you explain More how to do that i've that problem and i didn't find a solution 
i need to add the scale so can you post a Simple code or something more helpful

**Comment by sindizzy** [comment]
Looks like the code allows you to add it only to a layout. But you can take a look at the code here and implement it yourself: DotSpatial.Controls\LayoutScaleBar.cs

**Comment by jany-tenaj** [comment]
@sindizzy The ScalebarPlugin is not for layout. It adds a scaling combobox to the toolbar of the main form.

**Comment by sindizzy** [comment]
Somewhere a graphic of a scalebar is added to the form so not sure where that is at.
