### ISSUE TITLE
netcore support

### ISSUE THREAD

**Issue by devel0** [DotSpatial/DotSpatial#1259]
### Steps to reproduce

1. create a dotnet project `dotnet new console -n test`
2. enter the project `cd test`
3. add nuget package `dotnet add package DotSpatial.Projections --version 2.0.0-rc1`
4. exec build `dotnet build`

DotSpatial version: 2c2302778278e61a01143b1ea6c8126a3ae8198e

### Expected behaviour

compatibility on net standard

### Actual behaviour

```
warn : Package 'DotSpatial.Projections 2.0.0-rc1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
```

### Feature description

Currently I copied DotSpatial.Projections sources to [another repository](https://github.com/devel0/netcore-proj) to adapt for use with dotnet.
I wondering if DotSpatial.Projections could enabled to generate only a Net Standard dll so that it can be used even from NET Framework referencing assemblies directly using packages from DotSpatial instead to build my own.

You can try NET standard version by adding following packages to a net framework project

```
Install-Package netcore-proj -Version 1.0.0-CI00004 -Source https://www.myget.org/F/devel0/api/v3/index.json
```

Follows major changes to the DotSpatial.Projections:
- removed Properties folder
- [changed csproj](https://github.com/devel0/netcore-proj/blob/d2a25ef304105d753c338ee2565bc46b4fe7169f/DotSpatial.Projections/netcore-proj.csproj) to generate netstandard and embed resource `datums.xml.ds`. Note that I used different name to avoid upgrade hint on myget same package name that already exists.
- handle [resource name](https://github.com/devel0/netcore-proj/blob/d2a25ef304105d753c338ee2565bc46b4fe7169f/DotSpatial.Projections/DatumsHandler.cs#L23-L25) respect framework mangling used

**Comment by sindizzy** [comment]
I think if you have a proposal for tweaking the code you can do a pull request.

**Comment by devel0** [comment]
I know, but the problem for me is that there are some package deployment actions that I can't verify, would be better if someone that have hands on this project nuget packages makes a working copy transition test with:
- transform DotSpatial.Projections to net standard
  - csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="XML/datums.xml.ds" />
    </ItemGroup>
</Project>
```
-
  - remove Properties folder
  - [change embedded assembly string](https://github.com/devel0/netcore-proj/blob/master/DotSpatial.Projections/DatumsHandler.cs#L23-L28) referencing depending on the framework
```cs
var resourceName = "netcore-proj.XML.datums.xml.ds";
if (!RuntimeInformation.FrameworkDescription.StartsWith(".NET Framework"))
  resourceName = "netcore-proj.datums.xml.ds";
```
- doublecheck everything works with existing **unit tests**

**Comment by mg-patrickp** [comment]
I've been using this package for several years in traditional net framework projects.
It's indeed unfortunate that it's not compatible yet with net core projects.

**Comment by Dzoukr** [comment]
Hello, please is there any update on .netstandard2.0 support?

**Comment by devel0** [comment]
don't know if this can help, but I published the netcore-proj ( only projection part of dotspatial ) synced with 09 jan 2019 master branch, available [here](https://www.nuget.org/packages/netcore-proj/) with fork [here](https://github.com/devel0/netcore-proj)

**Comment by Dzoukr** [comment]
Thanks @devel0, I'll give it a spin!

**Comment by abelykh0** [comment]
Please make this a priority. Microsoft is releasing .Net 6 in November 2021, which will essentially make .Net Framework obsolete.

**Comment by jany-tenaj** [comment]
Currently working on .net 6 release.
