### ISSUE TITLE
Reprojection Warning

### ISSUE THREAD

**Issue by robertatepsoft** [DotSpatial/DotSpatial#1260]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Create a Map using projection "GDA_1994_MGA_Zone_55"
2. Add a layer from a SHP file using the same projection using Map.AddLayer(filename)
3. Receive a warning dialog that the layer is a different projection from the map and will be re-projected.

DotSpatial version: 1.9.0.0

### Expected behaviour

The layer should be added to the map without the warning dialog

### Actual behaviour

I receive a warning dialog

Can you also include a screen shot? Yes

![projection](https://user-images.githubusercontent.com/30308610/51587687-4a2d8f80-1f2d-11e9-97e7-97912f48ab16.png)

**Comment by jany-tenaj** [comment]
Please try 2.0. If the problem still exists please upload your map and layer.

**Comment by robertatepsoft** [comment]
Having major issues rebuilding my project with 2.0. Visual Studio is saying various classes are not defined yet they are clearly referenced correctly. Might have to try building a smaller demo app just to test the projection warning issue and revert to 1.9 for my project.

**Comment by robertatepsoft** [comment]
The build problem appears to be because I was targeting .NET 4.5.0. Re targeting to 4.5.2 fixed that. However, migrating to DotSpatial V2.0 did not fix the re-projection warning. I will attempt to provide some test data to replicate the issue. For now though I can get around it by changing the Map.ProjectionModeReproject option to ActionMode.Always. Not ideal but it works.
