### ISSUE TITLE
ShapeIndices in the Dataset not initialized

### ISSUE THREAD

**Issue by sprashant80** [DotSpatial/DotSpatial#1266]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Add 3 types of shape files e.g. Point, Line and Polugon in same fashion
2. In Legend, right click on Node Layer, Select Labelling
3. Try to add any field related to shape file, change Font size, and position
4. Click on Ok

DotSpatial version: 
2.0.0.*
### Expected behaviour

Should display Label properly

Tell us what should happen

### Actual behaviour
Got an Exception in Dotspatial.Symbology.FeatureLayer.AssignFastDrawnStates() method.

I tried to debug the source code and found in AssignFastDrawnStates() method of Dotspatial.Symbology.FeatureLayer

at line no. 528, _drawnStates = new FastDrawnState[DataSet.ShapeIndices.Count];
shapeindices are not updated at first instance, but when we tried to click on DataSet & featureslookup to check count which is as expected. Then shapeIndices count will be reflected actual value.

Tell us what happens instead
Can you also include a screen shot?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DotSpatial.Symbology.FeatureLayer.AssignFastDrawnStates() in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Symbology\FeatureLayer.cs:line 620
   at DotSpatial.Symbology.FeatureLayer.set_DrawnStatesNeeded(Boolean value) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Symbology\FeatureLayer.cs:line 255
   at DotSpatial.Symbology.FeatureLayer.get_DrawnStates() in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Symbology\FeatureLayer.cs:line 226
   at DotSpatial.Controls.MapLabelLayer.DrawFeatures(MapArgs e, IEnumerable`1 features) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapLabelLayer.cs:line 1054
   at DotSpatial.Controls.MapLabelLayer.DrawFeatures(MapArgs args, List`1 features, List`1 clipRectangles, Boolean useChunks) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapLabelLayer.cs:line 358
   at DotSpatial.Controls.MapLabelLayer.DrawRegions(MapArgs args, List`1 regions, Boolean selected) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapLabelLayer.cs:line 454
   at DotSpatial.Controls.MapFrame.InitializeLabels(List`1 regions, MapArgs args, IRenderable layer) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapFrame.cs:line 1117
   at DotSpatial.Controls.MapFrame.Initialize(List`1 regions) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapFrame.cs:line 729
   at DotSpatial.Controls.MapFrame.Initialize() in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapFrame.cs:line 767
   at DotSpatial.Controls.MapFrame.Invalidate() in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Controls\MapFrame.cs:line 804
   at DotSpatial.Symbology.Forms.LabelSetup.OnChangesApplied() in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Symbology.Forms\LabelSetup.cs:line 167
   at DotSpatial.Symbology.Forms.LabelSetup.CmdApplyClick(Object sender, EventArgs e) in O:\Dotspatial-Master\20190219_dotspatial\DotSpatial\Source\DotSpatial.Symbology.Forms\LabelSetup.cs:line 447
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WDSApplication
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDSApplication.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v17.2
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.Utils.v17.2.DLL
----------------------------------------
WDS.Interface
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.Interface.DLL
----------------------------------------
DotSpatial.Controls
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Controls.DLL
----------------------------------------
DotSpatial.Data.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Data.Forms.DLL
----------------------------------------
WDS.FormsControl
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.FormsControl.DLL
----------------------------------------
WDSApplication.Common
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDSApplication.Common.DLL
----------------------------------------
WDS.Entities
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.Entities.DLL
----------------------------------------
DotSpatial.Symbology
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Symbology.DLL
----------------------------------------
DotSpatial.GeoAPI
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.GeoAPI.DLL
----------------------------------------
System.Windows.Forms.Ribbon35
    Assembly Version: 3.5.8.0
    Win32 Version: 3.5.8.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/System.Windows.Forms.Ribbon35.DLL
----------------------------------------
DotSpatial.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Data.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DotSpatial.Symbology.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Symbology.Forms.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DevExpress.Data.v17.2
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.Data.v17.2.DLL
----------------------------------------
DevExpress.XtraEditors.v17.2
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.XtraEditors.v17.2.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
DotSpatial.Extensions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Extensions.DLL
----------------------------------------
DotSpatial.Projections
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Projections.DLL
----------------------------------------
DotSpatial.Serialization
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Serialization.DLL
----------------------------------------
WDS.DBOperation
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.DBOperation.DLL
----------------------------------------
WDSApplication.Configuration
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDSApplication.Configuration.DLL
----------------------------------------
WDS.PIN
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.PIN.DLL
----------------------------------------
DevExpress.XtraBars.v17.2
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.XtraBars.v17.2.DLL
----------------------------------------
DevExpress.Dashboard.v17.2.Win
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.Dashboard.v17.2.Win.DLL
----------------------------------------
DevExpress.Office.v17.2.Core
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.Office.v17.2.Core.DLL
----------------------------------------
DevExpress.XtraCharts.v17.2.Wizard
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.XtraCharts.v17.2.Wizard.DLL
----------------------------------------
DevExpress.Dashboard.v17.2.Core
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.Dashboard.v17.2.Core.DLL
----------------------------------------
DevExpress.XtraRichEdit.v17.2
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.XtraRichEdit.v17.2.DLL
----------------------------------------
DevExpress.XtraRichEdit.v17.2.Extensions
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.XtraRichEdit.v17.2.Extensions.DLL
----------------------------------------
DevExpress.RichEdit.v17.2.Core
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.RichEdit.v17.2.Core.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
DevExpress.Images.v17.2
    Assembly Version: 17.2.4.0
    Win32 Version: 17.2.4.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DevExpress.Images.v17.2.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
WDS.MapControl
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.MapControl.DLL
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
DotSpatial.Modeling.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Modeling.Forms.DLL
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
WDS.GraphControl
    Assembly Version: 1.2.2.2
    Win32 Version: 1.3.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/WDS.GraphControl.DLL
----------------------------------------
Npgsql
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/Npgsql.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/System.ValueTuple.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.26606.05
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.0
    Win32 Version: 
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Npgsql.LegacyPostgis
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/Npgsql.LegacyPostgis.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
wContour
    Assembly Version: 1.6.1.0
    Win32 Version: 1.6.1.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/wContour.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
DotSpatial.NTSExtension
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.NTSExtension.DLL
----------------------------------------
DotSpatial.NetTopologySuite
    Assembly Version: 1.14.4.0
    Win32 Version: 1.14.4
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.NetTopologySuite.DLL
----------------------------------------
DotSpatial.Projections.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/DotSpatial.Projections.Forms.DLL
----------------------------------------
DotSpatial.Symbology.Forms.resources
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0
    CodeBase: file:///D:/Repositories/WDSApplication/trunk/Debug/en-US/DotSpatial.Symbology.Forms.resources.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by sindizzy** [comment]
If this happens during labeling can you try my branch and see if you see the same thing.

**Comment by sprashant80** [comment]
I tried but found different errors.

However, I resolve the issue time being by doing following changes in Dotspatial.Data.Featureset.cs

I found _shapeIndices checked as null object at multiple locations however, it is initialized but unable to trap to OnInitializeVertices() method. So, I added another condition to check count == 0 and resolve my issue

if (_shapeIndices == null || _shapeIndices.Count ==0) in 
public List<ShapeRange> ShapeIndices property @ line number 351

Request you to review the change and if acceptable then please add into respective branch.

**Comment by sindizzy** [comment]
Probably would be easier if you make a pull request. If you can post your files and how you label and I will see if I can replicate it.

**Comment by sprashant80** [comment]
Please refer attached file.

My changes reflected at line number 351.


[FeatureSet.zip](https://github.com/DotSpatial/DotSpatial/files/2894621/FeatureSet.zip)

**Comment by sindizzy** [comment]
I meant a sample shapefile.

**Comment by sprashant80** [comment]
[Test Data.zip](https://github.com/DotSpatial/DotSpatial/files/2896981/Test.Data.zip)

**Comment by sprashant80** [comment]
After long investigation I found DrawanStates is null object. If I click on DrawingFilter and check count of DrawnState then appropriate count assigned. I'm unable to understand, how to resolve this issue.

Please guide.....

private void DataSetFeatureRemoved(object sender, FeatureEventArgs e)
        {
            DrawingFilter?.DrawnStates.Remove(e.Feature);
        }

**Comment by sindizzy** [comment]
No errors for me

![image](https://user-images.githubusercontent.com/5298460/53289804-6c9b0e80-3760-11e9-98ae-7734988a7c80.png)
