### ISSUE TITLE
Map.Layers  add layer display order does not work

### ISSUE THREAD

**Issue by xc398013967** [DotSpatial/DotSpatial#1267]
map.layers.add(wmsLayer);-------index 0
map.layers.add(pointlayer);-------index 1
map.layers.add(lineLayer); -------index 2

0 for the base WMS, 1 and 2 layers for MapFeatureLayer, so that the base WMS will cover other layers, I would like to ask if there is a good solution, I flip the layer order does not work, using MapGroup also has not been solved, is where I write the wrong? Can you provide a solution demo?

**Comment by jany-tenaj** [comment]
dup #1238
