### ISSUE TITLE
ShapeIndices and FeaturesLookup doesn't match during Undo Redo Operation

### ISSUE THREAD

**Issue by sprashant80** [DotSpatial/DotSpatial#1268]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. I added 3 nodes in existing featureset
2. then update existing and newly added object alternatively
3. and perform undo and redo operation
4. Undo operation performed well
5. During Redo operation, I observed that featurelookup and shapeindices values doesn't reflect the count correctly. Featurelookup shoes proper count but shapeIndices doesn't.

### Expected behaviour
Both values should shows same count.

### Actual behaviour
During Redo operation, I observed that featurelookup and shapeindices values doesn't reflect the count correctly. Featurelookup shoes proper count but shapeIndices doesn't.

**Comment by VectorZita** [comment]
The most probable cause is that you forgot to call **FeatureSet.InitializeVertices()** after adding/removing features. This "re-synchronizes" the features and the shapes.

Can you confirm whether this is the case?
