### ISSUE TITLE
select polygons within bounding box and export to new shapefile

### ISSUE THREAD

**Issue by robcanoehunter** [DotSpatial/DotSpatial#1270]
please help....  I would like to select all polygons a specified rectangle, and export those selected to a new shapefile.  Given a specified coordinate 'pt' (through code, the user would not click on the screen). Either a box around the point (as shown in the image)  or a radius around the point. either way. 
I have searched and tried everything I could think of..  such as....

Dim coor As Coordinate = New Coordinate(Centroid(0), Centroid(1), 0)
Dim env As Envelope = New Envelope(coor)
env.ExpandBy(200)
Dim affected As Envelope = New Envelope(coor)
Dim featurelayers() = Map1.GetFeatureLayers
Dim stateLayer As IMapPolygonLayer
For Each lyr As IMapFeatureLayer In featurelayers
   If lyr.LegendText = "Land_Parcels2" Then
       stateLayer = CType(lyr, MapPolygonLayer)
       stateLayer.Select(env, env, affected, SelectionMode.Within)
       stateLayer.DataSet.SaveAs("d:\temp2.shp", True)
   end if
next

am i even on the right track here..  any help would be appreciated.

I have included an image to visually show what I would like to do...  
![LethbridgeBase-Model_002](https://user-images.githubusercontent.com/32304534/54766536-066ba500-4bc1-11e9-8d4b-553534af7516.jpg)

**Comment by sindizzy** [comment]
Take a look at the DemoMap source code. It has built-in functionality for a bounding box. You just have to follow the code for the "Select" button in the toolbar.
