### ISSUE TITLE
Draw Shape when ViewExtentChange

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1273]
Hello
I need to draw some shape with system.drawing library(I draw UTM GridLine) just when viewExtentChange ... i dont want redraw when any map.refresh or map.invalidate occurred...
Grid line was blink on every map invalidate or refresh ....
Any Idea ?
 Thanks.

**Comment by sindizzy** [comment]
Try https://github.com/DotSpatial/DotSpatial/issues/1224
