### ISSUE TITLE
How can DotSpatial be used with Xamarin Android?

### ISSUE THREAD

**Issue by peon73** [DotSpatial/DotSpatial#1274]
DotSpatial version: 
1.9.0 and 2.0.0-rc1

I tried to include DotSpatial.Projections from a Xamarin Android app, but it failed with both 1.9.0 and 2.0.0-rc1 versions. Error messages as below:

Error	NU1202	Package DotSpatial.Projections 1.9.0 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package DotSpatial.Projections 1.9.0 supports: net40-client (.NETFramework,Version=v4.0,Profile=Client)	

Error	NU1202	Package DotSpatial.Projections 2.0.0-rc1 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package DotSpatial.Projections 2.0.0-rc1 supports: net40-client (.NETFramework,Version=v4.0,Profile=Client)	

Is there any workaround with any of the above releases (1.9.0 and 2.0.0-rc1) or is it impossible to use DotSpatial from a Xamarin Android app?

Is there a reason for only supporting .NET 4.0 ?
Would it be difficult to compile and release a DotSpatial version also supporting "monoandroid81" ?

**Comment by sindizzy** [comment]
I think the project needs to be .NET Core compliant and don't think it is. You could also download the source and compile it yourself as you wish.

**Comment by jany-tenaj** [comment]
Today DotSpatial.Projections targets netstandard2.0 so you should be able to use it with android now.
