### ISSUE TITLE
Dotspatial load shapefile with query

### ISSUE THREAD

**Issue by geologone** [DotSpatial/DotSpatial#1277]
Good evening,
Can I load only a little set of data from a large shapefile with a query in dotspatial c#? I think something like "Definition query" of arcmap. 
Thank's Federico

**Comment by sindizzy** [comment]
fsWorld = FeatureSet.OpenFile(fileName)
            Dim featList As List(Of IFeature) = fsWorld.SelectByAttribute("[TYPE] IN ('B','F')")
            Dim fsNew As IFeatureSet = New FeatureSet(featList)
            fsNew.Projection = fsWorld.Projection

**Comment by geologone** [comment]
Thank You
