### ISSUE TITLE
Save and load shape layer problem

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1279]
Hello
i have save layer with FeatureSet.save() method and featureset.dataset.save method 
shape file was save right. when i load layer all feature show with out any problem .
but when i try to see attribute table i got error :
"Assertion failed length must be > 0 "
Some time i dont need to load layer , i try to use layer attribute table value to add same feature in another layer . i get null value. i was check feature in code it have X column but with out any value.
i drop dbf file to excel i can see value of column (but some column empty) .

what is my wrong ?any idea to save and load layer ?

**Comment by sindizzy** [comment]
You're going to have to show how you populate and save your FeatureSet.

**Comment by DavisMillier** [comment]
Hello @sindizzy 

`        
//Use this method on app load for create layer
public static void AddTargetPointLayer()
        {
            var targetPointAttib = new Dictionary<string, Type>
                {
                    {"ID", typeof(uint)}, 
                    {"TID", typeof(uint)},
                    {"Label", typeof(string)},
                    {"Type", typeof(string)}, //Car,Buss,MotorCycle
                    {"Course", typeof(double)},
                    {"Speed", typeof(double)},

                    
                };
            var addLayer = new AddMapLayers();
            addLayer.AddLayer(GeoMap, "FeatureLayer", "Point", FPointAttrib);
        }



        public IMapLayer AddLayer(IMap geoMap, string layerName, string featureTypeStr,
            Dictionary<string, Type> dataColumns)
        {
            _featureSet = new FeatureSet(FType(featureTypeStr));
            foreach (var item in dataColumns)
            {
                var column = new DataColumn(item.Key, item.Value);
                _featureSet.DataTable.Columns.Add(column);
            }

            _featureSet.Projection = geoMap.Projection;
            _featureSet.IndexMode = false; //TODO : Check For Improve

            var myLayer = geoMap.Layers.Add(_featureSet);
            myLayer.EditMode = true;
            foreach (var item in geoMap.Layers)
                if (item.LegendText == layerName)
                {
                    _isDuplicate = true;
                    break;
                }

            if (_isDuplicate)
            {
                myLayer.LegendText = geoMap.Layers.UnusedName(layerName);
                _isDuplicate = false;
            }
            else
            {
                myLayer.LegendText = !string.IsNullOrEmpty(layerName)
                    ? layerName
                    : geoMap.Layers.UnusedName("New Layer");
            }

            if (layerName == "FeatureLayer")
            {
                _pointSymbolizerShip = new PictureSymbol(car, 30);
                _pointSymbolizerSubmarine = new PictureSymbol(bus, 30);
                _pointSymbolizerLauncher = new PictureSymbol(motorCycle, 25);


                _pointCategoryCar = new PointCategory(_pointSymbolizerCar)
                {
                    FilterExpression = "[Type]='car'"
                };

                _pointCategoryBus = new PointCategory(_pointSymbolizerBus)
                {
                    FilterExpression = "[Type]='Bus'"
                };

                _pointCategoryMotorcycle = new PointCategory(_pointSymbolizerMotorcycle)
                {
                    FilterExpression = "[Type]='Motorcycle'"
                };

                _pointScheme = new PointScheme();
                _pointScheme.AddCategory(_pointCategoryCar);
                _pointScheme.AddCategory(_pointCategoryBus);
                _pointScheme.AddCategory(_pointCategoryMotorcycle);

                _pointCategoryShip.LegendText = "Car";
                _pointCategorySubmarine.LegendText = "Bus";
                _pointCategoryLauncher.LegendText = "Motorcycle";

                myLayer.Symbology = _pointScheme;
            }



            myLayer.DataSet.Name = myLayer.LegendText;
            myLayer.Reproject(geoMap.Projection);
            return myLayer;
        }

//this method use for add feature to layer
        public void StickFeature(Coordinate coord, List<object> param)
        {
            Mpl.EditMode = true;
            _pointFeature.DataRow["ID"] = _pointFeatureSet.NumRows();// Todo 
            _pointFeature.DataRow["TID"] = param[0];
            _pointFeature.DataRow["Label"] = UnusedName(param[1].ToString());
            _pointFeature.DataRow["Type"] = param[2];
            _pointFeature.DataRow["Course"] = param[3];
            _pointFeature.DataRow["Speed"] = param[4];



            _pointScheme = Mpl.Symbology;

 
            Mpl.ApplyScheme(_pointScheme);
            LabelSymbolizer lblSymbolizer = new LabelSymbolizer();
            lblSymbolizer.FontFamily = "Tahoma";
            lblSymbolizer.FontColor = Color.Black;
            lblSymbolizer.BackColorEnabled = true;
            lblSymbolizer.BackColor = Color.FromArgb(25, Color.WhiteSmoke);
            lblSymbolizer.BorderVisible = true;
            lblSymbolizer.FontSize = 8;
            lblSymbolizer.LabelPlacementMethod = LabelPlacementMethod.Center;
            lblSymbolizer.Orientation = ContentAlignment.MiddleRight;
            lblSymbolizer.PreventCollisions = false;
            lblSymbolizer.OffsetX = 15;
            lblSymbolizer.OffsetY = 0;
            Mpl.ShowLabels = true;
            Mpl.AddLabels("[Label], string.Empty, lblSymbolizer, string.Empty);

            Mpl.DataSet.InitializeVertices();
            Mpl.AssignFastDrawnStates();
            Mpl.Invalidate();

        }


//i use this code for save layer
                var nameGen = aa.Year + stMoth + stDay + "-" + stHour + stMinute + stSecond;
                Directory.CreateDirectory($"C:/Proj/last/{nameGen}");
                Mpl.FeatureSet.SaveAs($"C:/Proj/last/{nameGen}/Point.shp", true);
                Mpl.DataSet.Save();

// i use this code for get feature on save  layer and then add to my custom layer
// i use another way same as mpl.featureset.feature.addrange() but same result
                    FeatureSet fsMltl = FeatureSet.Open(filePath + "Line.shp") as FeatureSet;
                    
                    foreach (Feature p in fsMpl.Features.ToList())
                    {
                            try
                        {
                            List<object> param = new List<object>
                            {
                                id++,
                                String.IsNullOrEmpty(p.DataRow["Label"].ToString())
                                    ? "UnNamed"
                                    : p.DataRow["Label"].ToString(), //Name
                                Convert.ToString(p.DataRow["Type"]), // Type
                                Convert.ToDouble(p.DataRow["Course"]), //Course
                                Convert.ToDouble(p.DataRow["Speed"]), //Speed

                            };
                            StickFeature(p.Geometry.Coordinate.CoordinateValue, param);
                            
                        }
                        catch (Exception)
                        {

                        }

                    }

                    Mpl.ApplyScheme(Mpl.Symbology);


`



Thank you

**Comment by DavisMillier** [comment]
Hello @sindizzy 
Did you check my code?
Where is my wrong ?

**Comment by sindizzy** [comment]
Have you taken a look at the source code? Look at the ones called "Test" as there is some code to test most functions. https://github.com/DotSpatial/DotSpatial/tree/master/Source
