### ISSUE TITLE
Is the DotSpatial NetTopologySuite branch broken???

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1284]
So this has been driving my coworker and I nuts for a while. Maybe we don't understand how the DotSpatial NetTopologySuite branch is setup but seems like something just doesn't seem to work. At least we cant figure it out.

So we have the WKTWriter here:
https://github.com/DotSpatial/NetTopologySuite/blob/ds_master/NetTopologySuite/IO/WKTWriter.cs

and the GeoJsonWriter here:
https://github.com/DotSpatial/NetTopologySuite/blob/ds_master/NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON/GeoJsonWriter.cs

First question...is the GeoJsonWriter supposed to be double nested with the NetTopologySuite.IO path? The heierarchy doesnt make sense although the two namespaces are the same
`namespace NetTopologySuite.IO`
so that technically shouldn't be an issue.

However, when using the DotSpatial.NetTopologySuite.1.14.4 DLL in a project I can use the WKTWriter but the GeoJsonWriter is unavailable in that namespace.

Am I missing something?

**Comment by jany-tenaj** [comment]
As far as I remember we copied over the whole NTS and GeoAPI projects and made some small changes to have an NTS version that was able to replace DotSpatial.Topology.

No idea what NTS issues we copied over, too. Seems there were some fixes to GeoJson. As it seems they also moved it out of the NTS project afterwards.

**Comment by sindizzy** [comment]
Yeah I think what has happened is that there are modules separate from the NTS core. In this case GeoJson is in a separate module https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON. 

Looks to me like the DotSpatial branch merged them all together into one DLL. That would explain the double nested path of NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON in DotSpatial.

However if that is the case then why is the GeoJsonWriter class not available with the DotSpatial branch? It's in the current code but it just is not exposed for some reason.

**Comment by jany-tenaj** [comment]
We merged them like they were in Nts at the time. They moved them out afterwards.

**Comment by sindizzy** [comment]
I forked the DS NTS project. When I look at what was downloaded it looks to me like the projects are separate. In other words, the code as I downloaded it has a core DLL + module DLLs. Further there are two solutions...NetTopologySuite.sln and DSNetTopologySuite.sln.

Compiling NetTopologySuite.sln I get these DLLs
```
DotSpatial.GeoAPI.dll
DotSpatial.NetTopologySuite.dll
DotSpatial.Projections.dll
DotSpatial.Projections.Wrapper.dll
Microsoft.SqlServer.Types.dll
Mono.Security.dll
NetTopologySuite.IO.dll
**NetTopologySuite.IO.GDB.dll**
**NetTopologySuite.IO.GeoJSON.dll**
NetTopologySuite.IO.GeoTools.dll
NetTopologySuite.IO.MsSqlSpatial.dll
NetTopologySuite.IO.PostGis.dll
NetTopologySuite.IO.ShapeFile.dll
NetTopologySuite.IO.ShapeFile.Extended.dll
NetTopologySuite.IO.SpatiaLite.dll
NetTopologySuite.IO.SqlServer2008.dll
NetTopologySuite.IO.Tests.dll
NetTopologySuite.IO.TopoJSON.dll
NetTopologySuite.Lab.dll
NetTopologySuite.TestRunner.dll
NetTopologySuite.Tests.NUnit.dll
NetTopologySuite.Tests.Vivid.XUnit.dll
NetTopologySuite.Windows.Forms.dll
NetTopologySuite.Windows.Media.dll
Newtonsoft.Json.dll
Npgsql.dll
nunit.framework.dll
policy.2.0.Npgsql.dll
System.Data.SQLite.dll
System.Data.SQLite.Linq.dll
Test.NetTopologySuite.Windows.Forms.dll
```

Compiling DSNetTopologySuite.sln I get these DLLs:
```
DotSpatial.GeoAPI.dll
DotSpatial.NetTopologySuite.dll
```
It appears on the surface (at least to me) that the other DLLs were excluded from the DS build. The code is there in the DS fork but its never used.

So two questions: If I wanted to add the other IO modules where would I start? Also should the DS classes have a similar namespace as the DLL name? In this case the DLL name is DotSpatial.NetTopologySuite but the  namespace is just NetTopologySuite. Should that be changed to DotSpatial.NetTopologySuite?

**Comment by sindizzy** [comment]
I forked the DS NTS project. When I look at what was downloaded it looks to me like the projects are separate. In other words, the code as I downloaded it has a core DLL + module DLLs. Further there are two solutions...NetTopologySuite.sln and DSNetTopologySuite.sln.

Compiling NetTopologySuite.sln I get these DLLs
```
DotSpatial.GeoAPI.dll
DotSpatial.NetTopologySuite.dll
DotSpatial.Projections.dll
DotSpatial.Projections.Wrapper.dll
Microsoft.SqlServer.Types.dll
Mono.Security.dll
NetTopologySuite.IO.dll
**NetTopologySuite.IO.GDB.dll**
**NetTopologySuite.IO.GeoJSON.dll**
NetTopologySuite.IO.GeoTools.dll
NetTopologySuite.IO.MsSqlSpatial.dll
NetTopologySuite.IO.PostGis.dll
NetTopologySuite.IO.ShapeFile.dll
NetTopologySuite.IO.ShapeFile.Extended.dll
NetTopologySuite.IO.SpatiaLite.dll
NetTopologySuite.IO.SqlServer2008.dll
NetTopologySuite.IO.Tests.dll
NetTopologySuite.IO.TopoJSON.dll
NetTopologySuite.Lab.dll
NetTopologySuite.TestRunner.dll
NetTopologySuite.Tests.NUnit.dll
NetTopologySuite.Tests.Vivid.XUnit.dll
NetTopologySuite.Windows.Forms.dll
NetTopologySuite.Windows.Media.dll
Newtonsoft.Json.dll
Npgsql.dll
nunit.framework.dll
policy.2.0.Npgsql.dll
System.Data.SQLite.dll
System.Data.SQLite.Linq.dll
Test.NetTopologySuite.Windows.Forms.dll
```

Compiling DSNetTopologySuite.sln I get these DLLs:
```
DotSpatial.GeoAPI.dll
DotSpatial.NetTopologySuite.dll
```
It appears on the surface (at least to me) that the other DLLs were excluded from the DS build. The code is there in the DS fork but its never used.

So two questions: If I wanted to add the other IO modules where would I start? Also should the DS classes have a similar namespace as the DLL name? In this case the DLL name is DotSpatial.NetTopologySuite but the  namespace is just NetTopologySuite. Should that be changed to DotSpatial.NetTopologySuite?

**Comment by sindizzy** [comment]
Going through the code for the DS fork it is just very hard to understand how the whole thing is setup. I would like to contribute to add the modules but just don't know where to start. Any help appreciated.
