### ISSUE TITLE
Export Feature attribute from 1 layer and import to another layer

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1286]
Hello 
I was save some layer with feature. i can get feature coordinate and snap on other layer but when i try to get data from attribute table it return null but i can sense it have N column !
How can i read attribute data from loaded layer ?

**Comment by sindizzy** [comment]
Post your code.

**Comment by DavisMillier** [comment]
I found Bug , when i create attribute table with int data type column the column value not save in dbf file !
so when we load saved layer or use attribute table of that layer we get error ...

**Comment by sindizzy** [comment]
Post your code.
