### ISSUE TITLE
Real - time refresh highlights line elements, map refresh will appear on the caton

### ISSUE THREAD

**Issue by xc398013967** [DotSpatial/DotSpatial#1291]
Business requirements: receive webSocket messages in real time and highlight the red point on the map. When receiving webSocket messages in real time, the map will be sluggish. Using map.mapframe. Invalidate() or map.refresh () will have the same effect，Thanks

**Comment by sindizzy** [comment]
Every time you draw on the map it will repaint. Invalidate will also cause the map to repaint.

**Comment by xc398013967** [comment]
Any good solutions

**Comment by sindizzy** [comment]
Can you cache the data and update every 5 events or every 10 minutes?

**Comment by VectorZita** [comment]
How "congested" is your map otherwise (apart from the red point, which is, I assume, just a single feature)? There must be a reason why your map is running **that** slow.

**Comment by jany-tenaj** [comment]
You could repaint only a small area around the point instead of repainting the whole map.
