### ISSUE TITLE
knowning when to use ProjectionInfo.FromProj4String vs ProjectionInfo.FromEsriString

### ISSUE THREAD

**Issue by xobjects** [DotSpatial/DotSpatial#1292]
PROJCS["NAD_1983_2011_StatePlane_North_Carolina_FIPS_3200_Ft_US",GEOGCS["GCS_NAD_1983_2011",DATUM["D_NAD_1983_2011",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",2000000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-79.0],PARAMETER["Standard_Parallel_1",34.33333333333334],PARAMETER["Standard_Parallel_2",36.16666666666666],PARAMETER["Latitude_Of_Origin",33.75],UNIT["Foot_US",0.3048006096012192]]

When considering the above WKT, I need to build a ProjectionInfo using ProjectionInfo.FromProj4String instead of ProjectionInfo.FromEsriString which I typically use.

So that I don't have to hardcode a special check for this particular projection, is there a way to tell which to use?

**Comment by sindizzy** [comment]
try this gis.stackexchange.com/questions/129764/how-are-esri-wkt-projections-different-from-ogc-wkt-projections

**Comment by xobjects** [comment]
thank you (though way late)

**Comment by xobjects** [comment]
thank you (though very late)
