### ISSUE TITLE
What objects are borrowed from NetTopologySuite?

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1294]
DotSpatial version: 2.0

So I am looking to introduce some GeoJSON functionality into DotSpatial. From looking at the NTS fork https://github.com/DotSpatial/NetTopologySuite/tree/ds_master/NetTopologySuite.IO it looks like the code is already there but not exposed through the DotSpatial.NetTopologySuite library. Easy enough to slip that code into the existing project for NTS. 

After testing it, my question is this: Is the only object that DS borrows from NTS the Geometry object? It looks like NetTopologySuite.Feature and NetTopologySuite.FeatureCollection are not really converted or used anywhere in the DS code. The GeoJson code works only on NTS objects and am wondering the best way forward. Should we write a DotSpatial.Featureset to NetTopologySuite.FeatureCollection converter or just refactor the existing GeoJson code to overload with a DotSpatial.Featureset?

**Comment by jany-tenaj** [comment]
We're using NTS directly now so this should work out of the box.
