### ISSUE TITLE
When should I fork?

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1298]
So I am confused about forking and creating pull requests. I forked DS a while back to make some code updates. I've done some pull requests with no issues. When I want to create a new pull request today should I fork again or does my fork get updated with Git desktop?

**Comment by mudnug** [comment]
You can merge changes from DotSpatial into your fork. This brings your fork's master branch into sync with the upstream repository, without losing your local changes.

See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by sindizzy** [comment]
oic. i will try that.

**Comment by sindizzy** [comment]
If I sync my fork with the main branch will I lose all the pull requests that are in the queue that have not yet been approved?

**Comment by mudnug** [comment]
They're not lost. They are simply from older commits on your fork. You may feel you also want to update your branches & the PRs if there are conflicting changes. Github usually points out any conflicts on the PR page.

**Comment by sindizzy** [comment]
I did several and the PR page said the Changes document was problematic. I tried to fix it to no avail. So I deleted my PRs and now am just waiting to figure out how to fix them.
