### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by dpmcmlxxvi** [DotSpatial/DotSpatial#1300]
Looks like an interesting project but it appears it is no longer maintained, which begs a few questions:

- Is there a plan by the maintainers to start up again? 
- Is there a fork of this project that is maintained?

I haven't been able to find a similar project.

**Comment by sindizzy** [comment]
Its been stagnant for some time but it still is a great project. I've added several pull requests and just waiting for those to be accepted. I just tested another 2 fixes and hoping to add those pretty soon. My fork has some fixes which I thought were worthwhile.

**Comment by jany-tenaj** [comment]
As soon as I have some time again I'll have a look at the fixes that were added in the meantime.
