### ISSUE TITLE
A IDockManager extension must be included because a UI plugin was found

### ISSUE THREAD

**Issue by TongZhai** [DotSpatial/DotSpatial#1306]
I am trying to migrate my existing .net projects that are currently MapWindow4's plugins to use the DotSpatial DemoMap as host application. I've tried to setup my project to be a plugin using the `DotSpatial.Plugins.Taudem.Port/TaudemPlugin.vb` and `DemoPlugin/snapin.cs` as template, both compile without problem but when running they all ask for the following:

![image](https://user-images.githubusercontent.com/16242714/66097832-fb310300-e56d-11e9-8ad4-ad8074e03567.png)

![image](https://user-images.githubusercontent.com/16242714/66097843-0a17b580-e56e-11e9-89c2-86dde821c50d.png)

![image](https://user-images.githubusercontent.com/16242714/66097855-11d75a00-e56e-11e9-9123-0cdf38357f24.png)

Then it will just display a blank form. My plugin has its own user interface forms, I have my plugin compiled into `bin\Debug\Plugins\Baseflow` (`snapin.cs` as template) or `bin\Debug\Windows Extensions\Baseflow` (`TaudemPlugin.vb` as template). If I remove my plugin from either places, then it will run normally and load all of the existing DotSpatial plugins. I read that we have to implement those interfaces ourselves, but those two working example plugins don't seem to implement those interfaces at all and there is really no instruction as to how to implement those interfaces.

I am using DotSpatial 2.0. I would have used C# but the projects are in VB.Net

**Comment by TongZhai** [comment]
Ok, I've added the methods in those interfaces to my plugin for `IDockManager, IHeaderControl, and IStatusControl`, listed method stubs below:

 ```
Public Event ActivePanelChanged As EventHandler(Of DockablePanelEventArgs) Implements IDockManager.ActivePanelChanged
    Public Event PanelClosed As EventHandler(Of DockablePanelEventArgs) Implements IDockManager.PanelClosed
    Public Event PanelAdded As EventHandler(Of DockablePanelEventArgs) Implements IDockManager.PanelAdded
    Public Event PanelRemoved As EventHandler(Of DockablePanelEventArgs) Implements IDockManager.PanelRemoved
    Public Event PanelHidden As EventHandler(Of DockablePanelEventArgs) Implements IDockManager.PanelHidden
    Public Event RootItemSelected As EventHandler(Of RootItemEventArgs) Implements IHeaderControl.RootItemSelected

 Public Sub Add(panel As DockablePanel) Implements IDockManager.Add
        Throw New NotImplementedException()
    End Sub

    Public Sub Add(panel As StatusPanel) Implements IStatusControl.Add
        Throw New NotImplementedException()
    End Sub

    Public Sub Remove(key As String) Implements IDockManager.Remove
        Throw New NotImplementedException()
    End Sub

    Public Sub Remove(panel As StatusPanel) Implements IStatusControl.Remove
        Throw New NotImplementedException()
    End Sub

    Public Sub ResetLayout() Implements IDockManager.ResetLayout
        Throw New NotImplementedException()
    End Sub

    Public Sub SelectPanel(key As String) Implements IDockManager.SelectPanel
        Throw New NotImplementedException()
    End Sub

    Public Sub HidePanel(key As String) Implements IDockManager.HidePanel
        Throw New NotImplementedException()
    End Sub

    Public Sub ShowPanel(key As String) Implements IDockManager.ShowPanel
        Throw New NotImplementedException()
    End Sub

    Public Sub RemoveAll() Implements IHeaderControl.RemoveAll
        Throw New NotImplementedException()
    End Sub

    Public Sub SelectRoot(key As String) Implements IHeaderControl.SelectRoot
        Throw New NotImplementedException()
    End Sub

    Public Sub Progress(key As String, percent As Integer, message As String) Implements IProgressHandler.Progress
        Throw New NotImplementedException()
    End Sub
```

When run, it still complains about needing IHeaderControl extension like before.

**Comment by TongZhai** [comment]
After many tries, I think I see a pattern, that is a custom plugin can not be in its own separate project, which is what I need to just construct an "adapter" for each independent project to be loaded into dotspatial DemoMap project just like the TaudemPort project, but it keeps asking about the above interfaces even though I used exactly the same adapter as the examples.

**Comment by sindizzy** [comment]
There is a guide that shows you how to add the Plugins to your map. I am adding it here for your reference: [Developer Getting Started Guide.pdf](https://github.com/DotSpatial/DotSpatial/files/3686933/Developer.Getting.Started.Guide.pdf)

**Comment by TongZhai** [comment]
@sindizzy thanks for the guide, I read through the first chapter on Dotspatial project setup and understand that one would have to "link" to the docker control and header control, then the legend etc would be visible on the designer of the main form. This is what puzzles me, in the DemoMap project if I open the MainForm in designer, there is nothing and its 'appManager' is connected to nothing as shown below:

![image](https://user-images.githubusercontent.com/16242714/66164836-87d8d100-e601-11e9-9b24-b4ff651b294a.png)

But it can clearly handle standalone plugin such as the `DotSpatial.Plugins.Taudem.Port` plugin. So, when I use that DemoMap as the front end and try to add my projects as its plugin, do I need to explicitly add new HeadControl, Legend, DockManager? It certainly seems the "auto" UI design is built in to handle these, but only in DotSptial's own dev environment...

**Comment by TongZhai** [comment]
Now I see that the DotSpatial.Controls.AppManager that is part of those demo projects already has DockManager, HeaderControl, and StatusControl as its attribute, so perhaps that's why they are able to handle plugins and load the UI elements once the form is loaded. So, why would they still ask for those interfaces when loading other similar custom plugins?

**Comment by sindizzy** [comment]
Any plugin requires the AppManager.

**Comment by TongZhai** [comment]
I finally got one windows extension plugin to work, but I have to put project code inside DotSpatial/Source/ directory and load it into DotSpatial.sln to have it work, if I move DemoMap and my project outside into their own directory with the same logic connections, then it starts doing that complaining about the interface stuff... I would really appreciate if someone can come up with an example the have DemoMap as a standalone solution, then takes in standalone project as plugin. Is it possible? Have anyone tried this before? I am hard pressed to believe that nobody has tried this before if that's the case.

**Comment by TongZhai** [comment]
I managed to have the two modes of adding your own stuff into DemoMap as shown below:

![image](https://user-images.githubusercontent.com/16242714/66227817-fa9e8680-e6ab-11e9-9a38-91afe8dc2bb8.png)

But, it seems to confirm that in order to add one's own menu item to the main form, the code has to be part of the main program's project, which kinda defeat the purpose of developing independent plugin projects. Could the development team help confirm this, so I can make decision as to long term direction of my code migration. Thanks.

**Comment by jany-tenaj** [comment]
Check out the [getting started page](https://github.com/DotSpatial/DotSpatial/wiki/Getting-started) from wiki. This shows you how to use DotSpatial without having to include everything into the DotSpatial code.

**Comment by TongZhai** [comment]
@jany-tenaj Yes, I've done that. The issue that I am having is that I have a collection of projects that were "outside" of the main DotSptial solution, and it looks like I will have to manually recreate these projects inside the DotSpatial solution to have it "recognized" properly as in "being seen properly" by the `AppManager.AppLoadExtensions.CompositionContainer.ComposeParts` call. At first, I was hoping that I can keep those projects in their own place, simply construct the adapter that takes in the appManager and compile to either DotSpatial's plugins folder or Windows Extensions folder, then it will be "seen", but that approach failed after many trials. The only way to have this work is to have all codes as part of the DotSpatial solution and I mean they have to be "created" inside the DotSpatial solution, so you see that's a lot of work.

**Comment by sindizzy** [comment]
A bit difficult to understand what you mean by "outside projects". Are they just map projects or plug-in projects? Are you creating your own plug-ins?

**Comment by TongZhai** [comment]
Create my own plugin. Ok, say, you created a new DotSpatial solution, then you go "Add Existing Project" to add an existing project that you have someplace else, but it is on the same .net framework, you add it in, then you construct the 'XXXPlugin.cs' (or .vb) to inherit from 'Extension', then in the mainform of the custom project, you setup an 'initialize' routine to take in the main DotSpatial project's appManager etc. Then you can compile it to say bin\Debug\Windows Extensions\MyPlugin\ folder, it will compile, but when running, it will give you that missing IDockManager interface error, then quit the whole program.

**Comment by jany-tenaj** [comment]
@TongZhai  Ugh forgot to mention that you have to add the downloaded DotSpatial dlls to the folder your program was compiled to.

Furthermore make sure that the DotSpatial dlls you add to your project references don't get copied to your plugin folder. This may cause your error message, too, if I remember correctly.

**Comment by TongZhai** [comment]
@jany-tenaj Ok, I tried again with a really simple plugin project that is external to DotSpatial project tree and contains only a form and nothing else, then follow the same steps of building adapter and compile to windows extensions folder, and it worked. Now I will try to add in references to other projects to this plugin project and see if it will hold. Also, I did not have to copy the DotSpatial dlls to the output plugin folder. I do have a general question for confirmation: I've been compiling the DotSpatial solution from this repo, which will generate the latest DotSpatial dlls, right? I am a bit unclear about the mention of "downloaded DotSpatial dlls", could you help confirm that. Thanks.

**Comment by TongZhai** [comment]
@jany-tenaj Are you suggesting to put a copy of those DotSpatial dlls in each custom plugins' compile folder? That's a lot of duplicate files...

**Comment by sindizzy** [comment]
I think you should download only the binaries. Create a project to make a plugin and reference the DS DLLs. Once it compiles then you can use your Plugin in your distribution by placing it in the Plugins folder.

**Comment by TongZhai** [comment]
@sindizzy I am trying the binary only path. But this is for a much bigger project, we will need to be able to compile dotspatial as an open source project. Still I guess my question still stands, are the binaries compiled from the source in this repo, or not?

**Comment by TongZhai** [comment]
I just tried the getting started binary only approach, it all worked out until I add the simplelegend and simple map plugins into the bin\Debug\ compile folder as written in the wiki post, it says the following:

![image](https://user-images.githubusercontent.com/16242714/66429598-59cf0480-e9e6-11e9-8d1e-43f67f526996.png)
![image](https://user-images.githubusercontent.com/16242714/66429622-63586c80-e9e6-11e9-83e1-db932856627f.png)

So, the runtime is a window with menu, toolbar, and a map display without the legend. 

Then I tried to bring in the simple windows plugin and compile into this solution's bin\Debug\windows Extensions\myplugin\ folder, it says the same skipping message due to missing DotSpatial.Control.

**Comment by sindizzy** [comment]
Here is how my project is setup

![image](https://user-images.githubusercontent.com/5298460/66431937-a0bafb00-e9e2-11e9-9272-f38cd01d96e9.png)

**Comment by TongZhai** [comment]
Here is mine, looks the same as yours:
![image](https://user-images.githubusercontent.com/16242714/66432359-dfa17e80-e9eb-11e9-9620-c0bfb7fac992.png)

**Comment by TongZhai** [comment]
I think the problem I am faced with in part lies with the usage of the Manageable Extensibility Framework used in DotSpatial to load the extensions in the Windows Extensions folder. My plugin project has many support project that are referenced in the main plugin project, and I have all the support projects' references configured to copy local true to the main plugin project, which in turn is compiled into its own folder in the Windows Extensions' folder, but somehow the `ComposablePartCatalog` can't see any of its parts, whereas it can see the plugin part if it only has the main plugin dll. Any suggestion per my situation?

**Comment by jany-tenaj** [comment]
The dlls from appveyor get compiled after each commit so they are always compatible to the latest master code.

Not sure why including the SimpleLegend and SimpleMap caused those errors, I'd have to see the code. What your discribing is confusing.

I basically have my program set up the following way:

- I have a common debug folder for all projects, that looks like the image you posted.
- All the dlls I compile go into the main debug folder.
- Plugins go to the plugins folder of the debug folder.
- All dlls I need to reference in my projects come from the main debug folder.
- I have all references set to not copying the files.
- I used DotSpatial as a base solution because it was easier to remove the projects I didn't need and add my own projects instead of maintaining another solution.
  - This solution contains 18 DotSpatial projects, 5 DotSpatial plugins, 22 of my own projects of which one is the main program and 4 are plugins.

**Comment by TongZhai** [comment]
@jany-tenaj here is my whole solution as a [zip file](https://drive.google.com/open?id=1p_RP0-y3l-vzhh8iS3R16zOHaFek5IxU), it was done by following the instruction in the "getting started" wiki post. It simply wouldn't recognize those plugins. I am working on a Windows 10 x64 machine and I am using VS2019 professional.

**Comment by TongZhai** [comment]
I have had some success using the DotSpatial solution directly from the repository. I was able to load some small plugins and extensions into the DemoMap project and have them shown up in the interface. But I am still having trouble constructing windows extension from my projects. They compile fine, just won't show up in the interface. I isolated the problem to the `GetCatalog()` routine in `AppManager.cs`. Specifically, it is the following line of code:

`if (!DirectoryCatalogExists(catalog, dir)) TryLoadingCatalog(catalog, new DirectoryCatalog(dir));`

The `DirectoryCatalog(myPluginDirectory)` creates the `ComposablePartCatalog` object from myPluginDirectory. The problem is that it couldn't load the main extension assembly that has the extension adapter code. It can find the physical DLL file, just not loading its assembly into its `Assemblies` attribute. Hope this ring a bell with someone what has dealt with this issue before.

**Comment by jany-tenaj** [comment]
@TongZhai Can't download the zip file.

**Comment by TongZhai** [comment]
@jany-tenaj sorry, I used my company's drive that needs verification even though I already opened it for public access. Anyway, here is [another link to it](https://drive.google.com/open?id=19_4dXnDdxySEV-0svE-GBXKi58Iv20LY), thanks!

**Comment by jany-tenaj** [comment]
@TongZhai If I'm correct you copied the dlls that are in your main folder from the zip file but compiled the dlls from the plugin folder yourself or got them from somewhere else. If you copy the plugins from the zip folder you got the other dlls from everything works.

**Comment by TongZhai** [comment]
@jany-tenaj I don't know how that happened, I thought I was using dlls from the release zip file... Yes, once I copied the plugins from the release zip file, it is not complaining anymore, everything works. Thanks. Now, I am still faced with that same issue of bringing in existing projects from outside of this solution and that missing IDockManager interface error though. I've got one of my projects to show up as an extension, but it was recreated inside the DotSpatial solution, do you have some insight into the case where you already have this DotSpatial solution setup, like this one I sent you, then you just go "Add Existing Project" from another directory tree to have it compiled as a Windows Extensions or Plugins? Have you done that before? I mean not create everything from scratch.

**Comment by jany-tenaj** [comment]
This shouldn't be a problem. Just use the dlls from the zip file as a reference inside your extensions. If this doesn't help upload an example of your what you're trying to do to take a look at.

**Comment by TongZhai** [comment]
@jany-tenaj thanks for the tip. I think I am getting close to getting a hang on this. One more thing related to this, which is quite peculiar. I was able to build a windows extension that can be launched from the UI's Extensions menu. But when I made a code change, the whole plugin code failed to compile, meaning there is no DLL generated for it, however, when I run the Debug mode, it still loads a functioning plugin, the fact that it has that extension displayed in the menu means it is not loading from the Windows Extensions folder, it is reading it from somewhere else, so does DotSpatial's component reading has caching mechanism or something? I've tried to remove the whole plugin code, but it still can "find" it and display it when run in debug mode.

**Comment by TongZhai** [comment]
@jany-tenaj I'll answer my own question, in VS2019, I had to delete the whole bin\Debug folder, then repopulate it with DotSpatial dlls to get things back.

**Comment by TongZhai** [comment]
@jany-tenaj It looks like I have perhaps 20+ extensions to be added, if they all go into Windows Extensions, then the 'Extensions' menu will become really long, is there a way to break it into multiple menu items?

**Comment by jany-tenaj** [comment]
@TongZhai  So is everything working now. Can we close this?

**Comment by TongZhai** [comment]
@jany-tenaj Yes, I did get past most of the referencing issues by following the compilation folder structure as in the Release.zip. So, I'll close this one. Thanks for all the help.
