### ISSUE TITLE
DotSpatial with WPF 

### ISSUE THREAD

**Issue by yuna-jang** [DotSpatial/DotSpatial#1307]
Hi, I'm Yuna from Korea.
I'm doing a project which shows a map viewer with WPF, so trying to use DotSpatial library. 
I followed tutorial page, 'Getting started' in Wiki.
And adding a dlls of DotSpatial to toolbox did not works with WPF but Winform well.
The .Net Framework versions of my project were both 4.5.2.
How can I add DotSpatial tools to my tool box? 
Please help :-] ..........!

**Comment by WaterDesk** [comment]
Sample code to integrate DotSpatial with [Fluent.Ribbon](https://github.com/fluentribbon/Fluent.Ribbon)
`MainFrame` is a winform control which contains `DotSpatial.Controls.Map`
```
        private void RibbonWindow_Loaded(object sender, RoutedEventArgs e)
        {
            WindowsFormsHost host = new WindowsFormsHost();
            inpMainFrame = new MainFrame();
            inpMainFrame.ParentWindow = this;
            host.Child = inpMainFrame;
            grid_mainFrame.Children.Add(host);
        }
```
