### ISSUE TITLE
Extent of a Feature

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1309]
DotSpatial version: 2.0

So I am writing a function that requires the Extent of a FeatureSet as well as each individual Feature.

For FeatureSet it was easy. I just use FeatureSet.Extent

For Feature I have a question: I started out by using the logical choice...Feature.Geometry.Envelope. But this doesn't seem to have the MinX, MinY, etc parameters. After looking at the documenantion I see that there are two choices in the GeoAPI

![image](https://user-images.githubusercontent.com/5298460/67584029-648dd700-f712-11e9-91ef-0e6a184ea1a2.png)

One returns an IGeometry and the other returns an Envelope. What is the difference here? Isn't an Envelope by its nature a geometry? The wording of "Internal" is a mystery to me. What does it mean?

**Comment by jany-tenaj** [comment]
@sindizzy If you check you'll see that Envelope is not a geometry. 

The Envelope returning an IGeometry can return a point, a line or a polygon depending on the underlying geometry. The EnvelopeInternal will definitely return an Envelope in any case.

Why it's called internal you could ask the people at NetTopologySuite but I think they might send you over to JTS where the original code comes from.
