### ISSUE TITLE
installation packaging issue with failed references

### ISSUE THREAD

**Issue by TongZhai** [DotSpatial/DotSpatial#1310]
I was able to build a few plugins using the Release.zip file structure by referencing the DotSpatial Dlls in that folder and also by placing my plugins into the 'Plugins' and 'Windows Extensions' folders. They load up and run successfully in the development environment, but when I package up the whole folder (same structure as in the Release.zip), and place it on a separate machine and try to run the main application (e.g. DemoMap.exe), it keeps giving the following exception (I am not sure why it is referencing C:\projects\dotspatial\source..., as I don't have that any where on either the dev machine or install machine):

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotSpatial.Controls.OptionsForm..ctor(IMap map) in C:\projects\dotspatial\source\DotSpatial.Controls\OptionsForm.cs:line 31
   at DotSpatial.Controls.DefaultMenuBars.OptionsClick(Object sender, EventArgs e) in C:\projects\dotspatial\source\DotSpatial.Controls\DefaultMenuBars.cs:line 397
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3394.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DemoMap
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DemoMap.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DotSpatial.Controls
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Controls.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DotSpatial.Extensions
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Extensions.DLL
----------------------------------------
DotSpatial.Symbology
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Symbology.DLL
----------------------------------------
DotSpatial.Data
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Data.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3394.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
DotSpatial.GeoAPI
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.GeoAPI.DLL
----------------------------------------
DotSpatial.Modeling.Forms
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Modeling.Forms.DLL
----------------------------------------
DotSpatial.Data.Forms
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Data.Forms.DLL
----------------------------------------
DotSpatial.Projections
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Projections.DLL
----------------------------------------
DotSpatial.Serialization
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Serialization.DLL
----------------------------------------
DotSpatial.Symbology.Forms
    Assembly Version: 2.0.0.465
    Win32 Version: 2.0.0.465
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.Symbology.Forms.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
DotSpatial.NetTopologySuite
    Assembly Version: 1.14.4.0
    Win32 Version: 1.14.4
    CodeBase: file:///C:/Users/tong.zhai/Downloads/HydroToolboxDS/DotSpatial.NetTopologySuite.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Also, none of the plugins are showing up in the main application (below), even though those plugin/extensions' dlls are all in there:

![image](https://user-images.githubusercontent.com/16242714/67705518-8777ef80-f98d-11e9-8590-82d5f24a6c46.png)

**Comment by jany-tenaj** [comment]
Can you upload your zip file?

**Comment by TongZhai** [comment]
@jany-tenaj Here is the link to the [zip file](https://drive.google.com/open?id=1p8UEFN_s35Wo84BoZadLdV1HTwZYhsZN)

**Comment by jany-tenaj** [comment]
Hm, the structure looks good, but nothing works. But I don't get any errors either. If I copy the usgs plugin into a clean version of the downloadable Release.zip I get an usgs menu in demomap. But unfortunately this doesn't explain why nothing works.

I fear I'd have to take a look at the source files to help there. I think you have some errors in the way you reference things.

**Comment by TongZhai** [comment]
I think I can strip down the source to show the core theme of referencing scheme, I'll work out something, all of the DotSpatial references in the plugins are to DotSpatial.XX.Dll files in the bin\Debug\ folder and all are set to Copy Local False, and I can see their Version as 2.0.0.465. My plugin does relies on a number of other projects and inherits from others, and those are all referencing the DotSpatial Dlls in the same way. But why won't any of the canned plugins show up either? should I use nuget to get the DotSpatial references instead of the direct file reference?

**Comment by jany-tenaj** [comment]
I think the other plugins might not show up because your plugin throws an error on loading and the loading routine might stop after it. But as there is no error thrown this is only a guess.

**Comment by TongZhai** [comment]
@jany-tenaj Ok, I've installed the .net framework 4.7.2 on my testing machine, now it has the same version of .net as my development machine, but that official release is still behaving the same, not loading any official plugins/extensions and gives the same exception when clicking on menu items. Are there any additional steps need to be performed for the Release files to work or just the zip file is needed? I think I should get the Release files to work on my testing box, which will point to what's wrong.

**Comment by TongZhai** [comment]
@jany-tenaj Ok, I tried the official downloadable 'Release.zip' files on another regular windows 10 machine and it behaved exactly the same, not loading any plugins and gives exceptions when clicking anything. I think this is a systematic issue, how do one release dotspatial applications...

**Comment by TongZhai** [comment]
@sindizzy could you elaborate how did you run the DemoMap exe? I simply download the 'Release.zip' and unzip into my users\tong.zhai\downloads\Release\ folder, then tried to run there, I tried both run as me and admin, on 3 different windows 10 machines, they all behaved the same problematic ways.

**Comment by sindizzy** [comment]
So what I typically do is go to this link on the main page: https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master. Then unzip it and run DemoMap.exe. As you can see below the application is initialized with all the plugins and extensions

![image](https://user-images.githubusercontent.com/5298460/67894420-7a423880-fb26-11e9-8eca-33e33a616e83.png)

**Comment by TongZhai** [comment]
@sindizzy yep, just downloaded the Release.zip from your link and tried again exactly as you described, and it behaved exactly the same as before, no plugin/extension loaded and gives exception when clicking anything.

**Comment by sindizzy** [comment]
Could it be a virus scanner? Can you try it on a different network or turn off your AV for a couple minutes?

**Comment by TongZhai** [comment]
@sindizzy I also ran it on another personal windows 10 machine that has NO AV software, the same deal.

**Comment by sindizzy** [comment]
I'm running on Windows 7 x64 and x86. My experience with Windows 10 is that it doesn't have some of the .NET framework as default. But seem to remeber that was .NET 3.5 and not the 4.0 which I think DS is based on.

**Comment by TongZhai** [comment]
@sindizzy ok, so does it NEED .net 3.5? 'cuz I do have .net 3.5 on my development machine...

**Comment by sindizzy** [comment]
I run it at home on two Windows 10 computers no problem.

**Comment by TongZhai** [comment]
@sindizzy did you check if you have .net 35 on those two win10 boxes?

**Comment by sindizzy** [comment]
If you look at the source code you can see what version of .NET is required. You can even compile it to see where it exactly it is crashing.

**Comment by sindizzy** [comment]
If you look at any of the projects you will see something like this:

```
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>DotSpatial.Data</RootNamespace>
    <AssemblyName>DotSpatial.Data</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
```

**Comment by TongZhai** [comment]
@sindizzy @jany-tenaj Ok, I compiled the entire DotSpatial solution from scratch a while back and it seems that bin\Debug\ folder actually worked on my testing machine, as all of the DotSpatial stuff is actually compiled against .net 4.5.2. So, I am thinking that I either try to use the recompiled DotSpatial DLLs or could the Release be updated to at least .net 4.5.2? I am very much puzzled why the Release is still on .net 35?!

**Comment by TongZhai** [comment]
@sindizzy @jany-tenaj Also, I have not tried to use NuGet to get the DotSpatial packages in a project, so if I do that, will it actually pull in .net35 version or .net4 version?

**Comment by sindizzy** [comment]
Where are you getting that its based on .NET 3.5?

**Comment by TongZhai** [comment]
@sindizzy I guess I am just "guessing" based on the fact that you mentioned that windows 10 doesn't have the necessary .net3.5 (which is true on my testing machine) and that now my recompiled .net 4.5.2 DotSpatial solution's Debug folder actually worked on my testing machine. So, I guess just deduction... Anyway, this brings the central question how to best develop Dotspatial application, clearly using the Release.zip DLLs will have this problem, so either the Release can be updated to use .Net 4 or users such as me should just recompile the whole solution from scratch. Please note that we would really want to move away from anything that still relies on .net 35

**Comment by sindizzy** [comment]
I said it is possible but you have top confirm it. Look at the config files in the release you downloaded. It will tell you the target framework.

I don't have any issues with the current release on Windows 7 and Windows 10.

**Comment by TongZhai** [comment]
@sindizzy If you are referring to the target framework of the projects, they are all targeting to .net 4.5.2, Other than that I am not sure how to confirm the 'Release.zip' I downloaded whether they were compiled against .net 35? or any other versions of framework for that matter. Could you help elaborate a bit?

**Comment by sindizzy** [comment]
In the release you downloaded each DLL has a config file. Open that up in a text editor.

**Comment by TongZhai** [comment]
@sindizzy I see the following:

```
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="DotSpatial.Controls.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
        </sectionGroup>
    </configSections>
    <userSettings>
        <DotSpatial.Controls.Properties.Settings>
            <setting name="PackagesToRemove" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
                </value>
            </setting>
            <setting name="ExtensionsToRemove" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
                </value>
            </setting>
        </DotSpatial.Controls.Properties.Settings>
    </userSettings>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2"/></startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="DotSpatial.Extensions" publicKeyToken="4d9e49339a7d240c" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="DotSpatial.Projections.Forms" publicKeyToken="52099474f11b7ff0" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
So, it says startup targeting .net 4.5.2, then that means the 'Release.zip' is not for .net 35 then. That means .net 35 is not at fault here, there must be other reason why the Release doesn't work on our testing machine and a few other regular windows 10 machines...

**Comment by TongZhai** [comment]
@sindizzy please note that my application runs in the development environment without issue, so can't really "debug" the failure... Anyway, I am not even trying to get my plugin to work, just want the official Release to work...

**Comment by sindizzy** [comment]
Like I said, I don't have any issues on Win7 or Win10 so it must be something unique about your setup.

**Comment by TongZhai** [comment]
Well, I am just using the downloaded 'Release.zip' as is, so definitely doesn't have any custom setup at all. That leaves the OS environment as the potential cause. Here is my windows 10 spec:

![image](https://user-images.githubusercontent.com/16242714/67976290-2f8af400-fbec-11e9-8f8a-09d21c268192.png)

![image](https://user-images.githubusercontent.com/16242714/67976362-55b09400-fbec-11e9-838b-18d0da881384.png)

![image](https://user-images.githubusercontent.com/16242714/67976520-a0caa700-fbec-11e9-8218-15697b1c2e2c.png)

**Comment by TongZhai** [comment]
I've tried on two more computers, one win8.1 (has .net 4.5, no .net 3.5) and one win10 Home (has .net 4.8), from both computers, I downloaded the 'Release.zip' then unzip and run the DemoMap, same failures. I think this is a more universal issue...

**Comment by sindizzy** [comment]
Why don't I get the errors?

**Comment by sindizzy** [comment]
Windows 7 Enterprise x86: Demo Map using the WebMap extension

![image](https://user-images.githubusercontent.com/5298460/67988200-3e2dd700-fbfd-11e9-8762-28d035e2389d.png)

**Comment by TongZhai** [comment]
@sindizzy Well, Windows 7 is due to reach End Of Life (EOL) on 14 January 2020, so running it well on Win7 is good for now, but should start focus on the future that is Windows 10. Besides, it runs on your win7 and it doesn't run on all of the windows 10 computers I tried is a fact we all realize already, still not sure what your system has in terms of .net framework, pre-requisite software, development environment etc etc.

**Comment by jany-tenaj** [comment]
Maybe Windows Enterprise is the problem? I ran the Demomap from the Release.zip on a Windows 10 Pro V1903 without problems.
There is a .Net Framework Version 4.8.03752 installed.
No idea why but the path variable contains the path to the spatialite plugin folder of the folder that contained Demomap.

**Comment by sindizzy** [comment]
@jany-tenaj I had the opportunity to reload Windows 10 Pro x64 since my HDD crashed. Installed Chrome and Notepad++. Downloaded the reelase.zip, extracted it, and ran DemoMap. Surprisingly I got the same errors as @TongZhai . I made sure .NET Framework up to 4.7 was installed. I will double check again tonite and install 4.8.

**Comment by jany-tenaj** [comment]
@sindizzy  Check those path variables please.

**Comment by jany-tenaj** [comment]
Ok I think I solved the problem.

The Release.zip files is blocked because it was downloaded.
Right click on the Release.zip file, select "Properties", and click on the "Unblock" button.

If you extract the Release.zip file afterwards everything is working as expected.

@TongZhai can you do the same with your own file to get it working?

**Comment by TongZhai** [comment]
@jany-tenaj Yes, by unblocking the downloaded zip file first, the unzipped program runs correctly. I tried both the Release.zip and my own HydroToolbox.zip and they both worked normally. Thanks for the help resolving this. I think we can close this issue. Thanks.

**Comment by sindizzy** [comment]
Well that's odd. I thought that was only if downloaded with IE. I use Chrome for all my browsing needs. I will do the test though.

**Comment by sindizzy** [comment]
Yep I downloaded again and had to unblock the zip. I think this feature is part of Windows SmartScreen.
