### ISSUE TITLE
Tan of angle

### ISSUE THREAD

**Issue by mathias13** [DotSpatial/DotSpatial#1314]
This must be wrong?

https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.NTSExtension/Angle.cs
line 240

/// <summary>
        /// Returns the mathematical Tan of the angle specified
        /// </summary>
        /// <param name="value">The Angle to find the Tan of</param>
        /// <returns>Double, the Tan of the Angle</returns>
        public static double Tan(Angle value)
        {
            return Math.Sin(value.Radians);
        }

**Comment by sindizzy** [comment]
They will probably ask for a pull request. if you don't have that I can maybe try to do it.

**Comment by mathias13** [comment]
that would be nice, would save me some time

**Comment by mathias13** [comment]
https://github.com/DotSpatial/DotSpatial/pull/1320
