### ISSUE TITLE
attempt to create shape file from simple data

### ISSUE THREAD

**Issue by zdepp** [DotSpatial/DotSpatial#1315]
[Form1.zip](https://github.com/DotSpatial/DotSpatial/files/3873372/Form1.zip)

See CS file in attached zip. Referenced DOTSPATIAL.DATA version 4.0.30319 and DOTSPATIAL.GEOAPI version 4.0.30319 ... 

in code added using DotSpatial.Dat and using GeoAPI.Geometries . 

`FeatureSet fs = new FeatureSet(FeatureType.Polygon);
fs.DataTable.Columns.Add(new DataColumn("ID", typeof(int)));
fs.DataTable.Columns.Add(new DataColumn("Text", typeof(string)));
List<Coordinate> vertices = new List<Coordinate>();
vertices.Add(new Coordinate(11219035, 1542354));
vertices.Add(new Coordinate(11219035, 1542354 + 100));
vertices.Add(new Coordinate(11219035 + 100, 1542354 + 100));
vertices.Add(new Coordinate(11219035 + 100, 1542354 + 0));
Polygon geom = new Polygon(vertices);
fs.AddFeature(geom);`

problem on this line:
Polygon geom = new Polygon(vertices)

are you missing a reference... type or namespace Polygon not found...

?

**Comment by sindizzy** [comment]
try adding
using GeoAPI.Geometries
