### ISSUE TITLE
How could I save shapefile to MemoryStream?

### ISSUE THREAD

**Issue by AlexScigalszky** [DotSpatial/DotSpatial#1316]
Is there any way to save a new shapefile in a MemoryStream which was created without saving this file 
on a hard drive?

I create a FeatureSet and I want to return in a API Rest endpoint. In this case, i don´t need save it into disk.

**Comment by sindizzy** [comment]
Just create a FetaureSet as normal. Its already in memory and you don't save it to disk unless you want to.

**Comment by AlexScigalszky** [comment]
It´s what I did but it´s useless on API Rest endpoint because I need create a File and that is a Object.

**Comment by jany-tenaj** [comment]
Check out [ExportShapefilePackage](https://github.com/DotSpatial/DotSpatial/blob/cf2b523ed00e67e42cd0d645a351b975772c4c38/Source/DotSpatial.Data.Tests/ShapefileTests.cs#L72-L115).

**Comment by AlexScigalszky** [comment]
By one rason, I can´t found ExportShapefilePackage.

I use `DotSpatial.Data v1.9.0`

**Comment by sindizzy** [comment]
Try upgrading to 2.0.

**Comment by AlexScigalszky** [comment]
I´ts not avaliable for me. Y will try update my Visual Studio.

**Comment by sindizzy** [comment]
It's available to everybody.

**Comment by AlexScigalszky** [comment]
Thanks, I upgraded `DotSpatial.Data` to `v2.0.0-rc1` but I still recieve this error

```
'Shapefile' does not contain a definition for 'ExportShapefilePackage' and no accessible 
extension method 'ExportShapefilePackage' accepting a first argument of type 
'Shapefile' could be found (are you missing a using directive or an assembly reference?)	

```

The code witch give that error is this:
```
var original = (Shapefile)DataManager.DefaultDataManager.OpenFile("");
var package = original.ExportShapefilePackage();
```

**Comment by jany-tenaj** [comment]
use the package from the [Continious Integration builds Nuget feed](https://ci.appveyor.com/nuget/dotspatial)

**Comment by AlexScigalszky** [comment]
I don't know how use it. Am I need account in appveyor?

**Comment by jany-tenaj** [comment]
No you don't need an appveyor account.
Check out the [wiki entry](https://github.com/DotSpatial/DotSpatial/wiki/How-to-use-the-Continious-Integration-builds-Nuget-feed-with-Visual-Studio). I hope this helps.

**Comment by AlexScigalszky** [comment]
Thanks @jany-tenaj . I did and work perfectly
