### ISSUE TITLE
Bug-Report : Shapefiles aren't encoded properly in DotNetCore

### ISSUE THREAD

**Issue by Policegking** [DotSpatial/DotSpatial#1317]
Hello everyone, I've been porting my Backend from DotNet Framework to DotNet Core and ran into an issue with the Encoding of the Shapefiles. DotNet Framework and DotNet Core use a different Default Encoding Page for opening Files (Framework uses Windows-1252 and Core uses UTF-8). All the files I opened until now were seemingly encoded using the Windows-1252 codepage so when I open them now in the EF Core project certain Symbols like Ü,Ö,Ä, ß and more are displayed as  a "?".

### Steps to reproduce

1. Set up a DotNetCore Project
2. Open the included File using Shapefile.OpenFile(shapefileLocation)
3. The column "name" of several DataRows in the AttributeTable have their Letters replaced with a ?

Like for example in this file: "name": "�lkammer oben" instead of "name": "Ölkammer oben",

DotSpatial version:  1.9.0

### Expected behaviour

The file should be opened with the correct encoding and all symbols intact (or it should be possible to set the encoding manually like with a FileInputStream)

### Actual behaviour

The file is opened but with Symbols like Ü,Ö,Ä, ß and more being displayed as  a "?"

If I'm missing something then please tell me, otherwise an option to change the way the encoding of the Shapefile is handled would be very appreciated.

Here is an example Shapefile where this happens in DotNetCore
[daw_295933.zip](https://github.com/DotSpatial/DotSpatial/files/3910261/daw_295933.zip)

**Comment by sindizzy** [comment]
I don't think DotSpatial is Core compatible.

**Comment by skiiasa** [comment]
By Default CodePagesEncodingProviders are not registered in .Net core, i faced same issue while saving  and reading the shape files using DotSpatial. 
I registered the code provider in my class constructor-
_**System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);**_
And everything worked fine.

Ref-https://stackoverflow.com/questions/37870084/net-core-doesnt-know-about-windows-1252-how-to-fix

**Comment by Policegking** [comment]
Thanks for the help. I also tried skiiasa's suggestions before, but it didn't work for me DotNetCore would still read the file the wrong way. 
I instead changed to another package called NetTopologySuite which natively works on DotNetCore.
