### ISSUE TITLE
Using DotSpatial in a Windows Service

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1318]
DotSpatial version: 2.0
I have created a .NET project that collects trip data points and then plots them on a DotSpatial map. It then takes a snapshot of the map and saves it as a PNG. This all works great when I am testing under my account. 

Since we want this process automated we have made it into a Windows Service. It all seems to work but some odd things happen as we don't seem to have too much control of the map form. I know that it's because a service doesn't support GUI elements. However we do seem to get output but the image is too small. My question is...can we use DotSpatial without the controls being on a form? Can we create all the objects in memory and then take a "snapshot" of the map? Or is the map required to be displayed to the screen before taking a snapshot?

**Comment by mudnug** [comment]
Since you're able to get an image, I think you have already answered your question. Perhaps you can provide a sample and more information about what you are trying to do exactly (specify the image width and height, perhaps).

**Comment by sindizzy** [comment]
Nothing more than just putting data on a map and then saving the map to PNG. We do this in batch so what gets loaded changes. It all runs on a service so saving to say 1150x1150 pixels doesn't work as the map image gets saved to the same dimensions.

**Comment by jany-tenaj** [comment]
@sindizzy can we close this or is it still an issue?

**Comment by sindizzy** [comment]
Yes please close. This is a very old issue which isn't an issue anymore.

**Comment by jany-tenaj** [comment]
@sindizzy please check your other issues and close them if they have become obsolete.
