### ISSUE TITLE
The latest version has a build error

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#1323]
Hello
When Build or run project exception throw on Dotspatial.Control\LayoutLegend.cs
Line : 181 and line 294
error code : 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'lyr' does not exist in the current context	DotSpatial.Controls	C:\path\DotSpatial-master\Source\DotSpatial.Controls\LayoutLegend.cs	181	Active


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1002	; expected	DotSpatial.Controls	C:\path\DotSpatial-master\Source\DotSpatial.Controls\LayoutLegend.cs	294	Active
```

**Comment by DavisMillier** [comment]
I think the error is due to the C# version ,I use vs 2015

**Comment by jany-tenaj** [comment]
Based on the continous integration build I can say that everything is working for us. So if you figure it's because you're using VS 2015 you might have to think about switching to VS 2017 or even better to VS 2019. We're not gonna move the code backwards because of old VS versions.
