### ISSUE TITLE
Pull requests from 2018

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1324]
So I have about 4 or 5 pull requests I added in December 2018. They have yet to be reviewed. Is there a road map when some of the modifications will be looked at? I have about 3 or 4 more to add but I want to wait until my current list is reviewed.

**Comment by danames** [comment]
Hey Abel, I have been an absentee project manager for the last couple of
years. I'm hoping others will review these pull requests and pull them in.
You have been using DS long enough to probably merge your own PRs but it
would def be better to have someone else look at them first. -  Dan
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by sindizzy** [comment]
I would definitely appreciate if someone could review them as my first language is not C#.  I have, however, learned quite a bit since I started doing my own mods. I just don't wish the project to get stagnant as we use it quite a bit in my company.

Most are small changes but one that includes re-projection could be substantial.

**Comment by jany-tenaj** [comment]
@sindizzy Better late than never. But I think we're on the way to getting all your pull requests integrated ;)
