### ISSUE TITLE
How to access main map control from plugin/extension and entire application

### ISSUE THREAD

**Issue by TongZhai** [DotSpatial/DotSpatial#1328]
When using DemoMap as main application, I think that the plugins inherits from Controls.Extension, where the App.Map is the handle for the main map display, am I correct? If yes, is that the main way of accessing the map control? What's the best way to allow the map control to be accessible throughout the entire application from all custom libraries?

**Comment by TongZhai** [comment]
Actually, is there some tutorials that show how to code basic GIS operations on the map such as getting the current active layer, getting selected features, or finding a layer etc, that would be really helpful.

**Comment by TongZhai** [comment]
I figured out that the main form's `App` property has `Map` attribute that refers to the map control, I am migrating a MapWindow4 program that uses the `MapWin` object that has an equivalent name in the `DotSpatial.Compatiblity` library, how does `App.Map` related to `MapWin` and is there a way to get access to the `MapWin` property of the main application? If not, then is `DotSpatial.Compatibility` still relevant and being used? Basically, should I just forget about it and try to move to using `App.Map`?

**Comment by jany-tenaj** [comment]
I'd say yes forget about it.

**Comment by TongZhai** [comment]
@jany-tenaj thanks for the tip. I guess the bottom line question is this: when using DemoMap as front end to load in custom plugins, how can the custom plugins access the main form's controls (i.e. toolbar, main menu, map control, and legend tree)? Does each plugin need to be built with a reference to the main form project? thanks!

**Comment by jany-tenaj** [comment]
As you found out plugins are based on the Extension class. Extensions have access to the AppMager via the App property. From there you should be able to get everything you need.
