### ISSUE TITLE
Question: assign custom handler to default menu items in DemoMap

### ISSUE THREAD

**Issue by TongZhai** [DotSpatial/DotSpatial#1329]
I would like to modify the behavior of the '`File->New`' menu item, so I would like to retrieve that menu item and then intercept its click event. I know I can add/remove an entire menu tree from `DemoMap` main menu bar via `appManager.HeaderControl.Add` or `Remove` method, it doesn't seems possible to get a hold of an individual menu item in a menu tree (I didn't find an API method exposed on the `HeaderControl` property), unless I recompile `DemoMap` and change its behavior there or build my own UI from scratch. Any suggestions?

**Comment by sindizzy** [comment]
Take a look at my post https://github.com/DotSpatial/DotSpatial/issues/1182

**Comment by TongZhai** [comment]
I found the events associated with the opening project (`Deserializing`) and saving project (`Serializing`) in the same spirit as my post #1331 and these other posts here. This solved my issue of capturing these events with custom handler.
