### ISSUE TITLE
Potential Bug in RasterBoundsExt class CellsContainingExtent(...) method

### ISSUE THREAD

**Issue by VectorZita** [DotSpatial/DotSpatial#1332]
Bug observed in
--
**Class**: `DotSpatial.Data.PyramidImage`
**Method**: `public override Bitmap GetBitmap(Extent envelope, Rectangle window)`
**Problem**: `null` is returned, when it shouldn't.
______________________________________________________
Bug traced back to
----
**Class**: `DotSpatial.Data.RasterBoundsExt`
**Method 1**: `public static Rectangle CellsContainingExtent(this IRasterBounds self, Extent extent)`
**Method 2**: `public static RcIndex ProjToCell(this IRasterBounds bounds, Coordinate location)`
Problem: **Method 1** checks for coordinate _overflow_ (whether coordinates are outside the bounds of the image) and _direction of overflow_ using **comparisons** but **Method 2** represents out-of-bounds coordinates uniformly for all _directions_, through `RcIndex.Empty`.
_____________
Interpretation
-----
The returned value of **Method 2** for coordinates outside the bounds of an image is `RcIndex.Empty`, which has a `Row` and `Column` properties equal to `int.MinValue`. **Method 1** then proceeds to actually use these values to determine if the coordinate lies outside the bounds of the image. Since the comparison is improper, the way the code is written now results in an empty rectangle when the current viewport entirely contains the image.

Therefore, whenever the current viewport of the map is not entirely **within** the bounds of an image represented as a `PyramidImage`, the image will not be displayed at all (`GetBitmap` of `PyramidImage` returns null).
____________
Illustration
-----
Let's examine the code properly. First of all `ProjToCell` actually projects a coordinate and finds the corresponding "pixel" cell of an image based on the given raster bounds:
```
        public static RcIndex ProjToCell(this IRasterBounds bounds, Coordinate location)
        {
            var pc = new AffineTransform(bounds.AffineCoefficients).ProjToCell(location);
            if (pc.Row < 0 || pc.Column < 0 || pc.Row >= bounds.NumRows || pc.Column >= bounds.NumColumns)
            {
                return RcIndex.Empty;
            }

            return pc;
        }
```

Then, from **Method 1**, here is the necessary excerpt:

```
        //...
        foreach (var c in coords)
        {
            var rowCol = self.ProjToCell(c);
            if (rowCol.Row < minY) minY = rowCol.Row;
            if (rowCol.Column < minX) minX = rowCol.Column;
            if (rowCol.Row > maxY) maxY = rowCol.Row;
            if (rowCol.Column > maxX) maxX = rowCol.Column;
        }

        if (minX < 0) minX = 0;
        if (minY < 0) minY = 0;
        if (maxX > self.NumColumns) maxX = self.NumColumns;
        if (maxY > self.NumRows) maxY = self.NumRows;
        return new Rectangle(minX, minY, maxX - minX, maxY - minY);
```

This small piece of **Method 1** actually checks for 2 things at the same time. First of all, it checks whether the returned cell is **outside** the bounds of the current viewport. Secondly, it checks **at which side of the current viewport** the "overflow" is, and adapts the current viewed image rectangle bounds to the intersection of the viewport and the image.

Let's run this excerpt step-by-step using RcIndex.Empty, which has `int.MinValue` as its representative `.Row` and `.Column` value. Suppose at least **one** of the checked coordinate bounds happens to lie outside the image bounds, so `RcIndex.Empty` is returned by **Method 2**. Then:

rowCol.Row is int.MinValue
rowCol.Column is int.MinValue

In turn:
```
if (rowCol.Row < minY) minY = rowCol.Row; //This conditional WILL BE RUN.
if (rowCol.Column < minX) minX = rowCol.Column; //This conditional WILL BE RUN.
if (rowCol.Row > maxY) maxY = rowCol.Row; //This conditional will NEVER BE RUN.
if (rowCol.Column > maxX) maxX = rowCol.Column; //This conditional will NEVER BE RUN.
```
Then, after the `foreach` loop is finished, `minY` is assigned `int.MinValue` and `minX` is also assigned `int.MinValue`. This corresponds to the logical result that the current coordinate was determined to be to the left and south of the passed image bottom left extent point. However, that might not have been the case as **Method 2** would also return `RcIndex.Empty` for coordinates that overflow the current raster bounds from the right or the top as well!
_______________
**Why is this a problem?**
----
This is a problem because when the current viewport extent entirely contains the image raster bounds, all coordinates are returned as `RcIndex.Empty` from **Method 2**, and are treated as if overflowing to the bottom left in **Method 1**. Thus, the returned `Rectangle` of **Method 1** is an empty `Rectangle` (i.e, `new Rectangle(0,0,0,0)`).
_______________
Proposed Fix (tested and appears to fix the problem)
----
Because **Method 1** actually requires to know the direction of the overflow, simply **skipping** `RcIndex.Empty` in **Method 2** and just including overflowing values should be enough. Therefore, consider **Method 3**, which is a simplification of **Method 2**:

```
        //Method 3:
        public static RcIndex ProjToCellWithOverflow(this IRasterBounds bounds, Coordinate location)
        {
            var pc = new AffineTransform(bounds.AffineCoefficients).ProjToCell(location);
            return pc;
        }
```
The `AffineTransform.ProjToCell(...)` method does not care about the raster bounds and will happily return negative values or values larger than the current raster bounds. If these values are just left as they are, **Method 1** will be able to properly detect, through the comparisons, whether the overflow is to the bottom, left, right or top, and properly adjust the bounds.

Then, the only change needed to **Method 1** is to replace the line:

`var rowCol = self.ProjToCell(c);`

with

`var rowCol = self.ProjToCellWithOverflow(c);`

and everything should work as expected.

**Comment by TongZhai** [comment]
I've verified this fix (along with #1326) worked to resolve the problem of raster not displaying
