### ISSUE TITLE
create ribbon toolbar in DotSpatial needs recompilation

### ISSUE THREAD

**Issue by TongZhai** [DotSpatial/DotSpatial#1335]
The DotSpatial default control UI is plain looking, to get to the ribbon look, do we need to build ribbon UI ourselves then recompile DotSpatial? I found this link to the [`DotSpatial.Plugins.Ribbon` 1.4.29](https://www.myget.org/feed/dotspatial/package/nuget/DotSpatial.Plugins.Ribbon) that looks pertinent, but it is quite old, is this an abandoned effort?

**Comment by jany-tenaj** [comment]
No idea who created it but it did not belong to DotSpatial itself. And if you read the link you posted it was abandoned.

**Comment by sindizzy** [comment]
Maybe its time for a new control. The MapWindow ribbon looks fantactic.
