### ISSUE TITLE
Bug in AzimuthalEquidistant class 

### ISSUE THREAD

**Issue by VectorZita** [DotSpatial/DotSpatial#1342]
Bug observed in
--
**Class**: `DotSpatial.Projections.Transforms.AzimuthalEquidistant`
**Methods**: `SphericalInverse` and `EllipticalInverse`
**Problem**: Methods to transform multiple points only transform the first point.
______________________________________________________
Bug traced to
----
Porting from OSGeo.PROJ (proj.4)
**Source file**: [`aeqd.cpp`](https://github.com/OSGeo/PROJ/blob/46c47e9adf6376ae06afabe5d24a0016a05ced82/src/projections/aeqd.cpp)

Problem: The static methods in the file linked to above (aeqd.cpp) are meant to transform a single point. During porting, however, some `return` statements were not adapted to `continue`, in order to work for multiple points. Because the `return` statements are in place, the method stops after only transforming the first point of the passed array.
_____________
Proposed solution
-----
In method `protected override void SphericalInverse(double[] xy, double[] lp, int startIndex, int numPoints)` of class `DotSpatial.Projections.Transforms.AzimuthalEquidistant.cs` in the current repository, line 277 should be changed to `continue` instead of `return`.

The exact same change should be made to line 331 of the same class, in method `protected override void EllipticalInverse(double[] xy, double[] lp, int startIndex, int numPoints)`, i.e. `return` should be changed to `continue`.

**This bug is similar in nature to bug #781**.

**Comment by jany-tenaj** [comment]
@VectorZita You wrote that the method EllipticalInverse contains the error, too. Which line should be fixed there?

**Comment by VectorZita** [comment]
@jany-tenaj In method `EllipticalInverse`, line 331 should be changed, from `return` to `continue`.

> The exact same change should be made to line 331 of the same class, in method `protected override void EllipticalInverse(double[] xy, double[] lp, int startIndex, int numPoints)`, i.e. return should be changed to continue.
