### ISSUE TITLE
Null value for type double

### ISSUE THREAD

**Issue by AlirezaAsadi96** [DotSpatial/DotSpatial#1352]
Hi.
I'm using DotSpatial for getting data table of shapefile. Everythings is ok but when shapefile has a double type column with null value, It's return  **"*************"** insteadof null .

**Error**
invalid input syntax for type double precision: "*********************************"

**DotSpatial version: 1.9.0.0**

**Comment by sindizzy** [comment]
Shapefiles have very poor support for Null.
One link here https://support.esri.com/en/technical-article/000005811

**Comment by southernprogrammer** [comment]
Same

**Comment by AlirezaAsadi96** [comment]
> Shapefiles have very poor support for Null.
> One link here https://support.esri.com/en/technical-article/000005811

Thanks for your response

**Comment by AlirezaAsadi96** [comment]
> Shapefiles have very poor support for Null.
> One link here https://support.esri.com/en/technical-article/000005811

Thanks for your response
