### ISSUE TITLE
FeatureSet.GetPolygon too strict, throws 'Number of points must be 0 or >3'

### ISSUE THREAD

**Issue by coderb** [DotSpatial/DotSpatial#1354]
Under 2.x, I have a shapefile created by a third party with some data that is causing an exception in `FeatureSet.GetPolygon`.

It loads find under 1.9.

The exception is from the call to `FeatureGeometryFactory.CreateLinearRing(coords.ToArray())` which throws `System.ArgumentException: 'Number of points must be 0 or >3'`

I think the fix should be to add the following code:

```
            foreach (PartRange part in shape.Parts)
            {
                if (part.NumVertices < 4) {
                    continue;
                }
```

Additionally, there is slight optimization in that method to change coords from `List<Coorindate>()` to `Coordinate[part.NumVertices]` which saves a bit of unnecessary memory allocation.

**Comment by jany-tenaj** [comment]
I don't think that it's a good solution to fix this by hiding the error. Next people come and tell us that they don't see all of their geometries. Better fix your FeatureSet before you try to show it.

**Comment by coderb** [comment]
i'm loading data that is published by a third party so i'm not sure what you mean about fixing my FeatureSet.

why not just add a callback for when bad data is encountered?

there should be a way to load a shapefile that has a few bad polys.

**Comment by sindizzy** [comment]
Can you post the shapefile? I can test to see what other GIS do with your data.

**Comment by coderb** [comment]
file is at https://www.pastefile.com/2au57n (expires in 1 week i believe).

**Comment by coderb** [comment]
@jany-tenaj i noticed you closed this issue.  what is the resolution?
