### ISSUE TITLE
Question: How to smooth out a grainy looking raster

### ISSUE THREAD

**Issue by 3nick17** [DotSpatial/DotSpatial#1356]
I am doing an IDW interpolation of some points. The resulting raster is displayed as a discrete raster (see image) when it needs to be displayed as a continuous raster to produce a nice smooth surface. Is there some sort of bilinear resampling I can do to smooth it out or any other methods I could use to produce a more aesthetically pleasing raster? Thanks in advance for the help.

<img width="446" alt="Capture" src="https://user-images.githubusercontent.com/50955907/97058475-9323d500-1553-11eb-9ab3-7fe45e1b5467.PNG">

**Comment by qq745562704** [comment]
How do you use the IDW tool, can you show me the code?
