### ISSUE TITLE
need DotSpaitial.positioning.GPS

### ISSUE THREAD

**Issue by jondoe1970187** [DotSpatial/DotSpatial#1357]
DotSpaitial.positioning.GPS is in my References but i cant find a dll to fix this
i am using visual basic 2019

*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.
2.
3.

DotSpatial version: 1.9
### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by jany-tenaj** [comment]
No idea what the problem is supposed to be. If it still exists explain more clearly.

**Comment by jondoe1970187** [comment]
the biggest problem i had was not all the .dlls are included and could not
find the needed dlls
