### ISSUE TITLE
DemoMap Project - Open Street Map - Not Loading

### ISSUE THREAD

**Issue by Neverlyn** [DotSpatial/DotSpatial#1358]
### Steps to reproduce

1. Run DemoMap Project
2. Add a Layer
3. Select "Open Street Map" from Base Map Dropdown List

DotSpatial version: All recent releases including the latest release (e30421d)

### Expected behavior

The base map should load behind other layers.

### Actual behavior

The "Open Street Map" layer is not found and loads a blank Layer.

### Notes

I thought this may be because of the BruTile & BruTile.Desktop libraries in DotSpatial.Plugins.WebMap being a little old. So I updated them to the latest version in NuGet, but it made no difference to this issue.

**Comment by jany-tenaj** [comment]
You are correct in assuming that is the reason. Only that simply updating doesn't fix the issue. We'll have to rewrite some code, too.

**Comment by sindizzy** [comment]
From the discussion at https://github.com/DotSpatial/DotSpatial/issues/1351 and the pull request https://github.com/DotSpatial/DotSpatial/pull/1370
that seems to fix it.

**Comment by jany-tenaj** [comment]
@Neverlyn please check the latest version. I just pulled sindizzys fix.

**Comment by Neverlyn** [comment]
@sindizzy I just tested with the latest release and it did not work for me.

I am still getting a blank Layer when selecting "Open Street Map".

**Comment by sindizzy** [comment]
Can you post your exact steps to reproduce please.

**Comment by Neverlyn** [comment]
@sindizzy the steps as exactly the same as my original post.

**Comment by jany-tenaj** [comment]
Just checked and I can load Open Street Map with the current source code
