### ISSUE TITLE
MapWindow 6 Alpha

### ISSUE THREAD

**Issue by gfernan** [DotSpatial/DotSpatial#1364]
Does anybody have the old MapWindow 6 Alpha code (based on Dotspatial)

**Comment by danames** [comment]
I've searched my archives and don't seem to have that code around anymore.
As I recall the "mapwindow 6" based on DotSpatial was a super thin wrapper
around the DotSpatial libraries - similar to the example wrapper
applications that are in the DotSpatial code base.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
https://ceen.byu.edu/directory/dan-p-ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by sindizzy** [comment]
i think you can still download the archive https://archive.codeplex.com/?p=mapwindow6

**Comment by danames** [comment]
Good reminder, Abel. Thanks for sharing that link again.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
https://ceen.byu.edu/directory/dan-p-ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
