### ISSUE TITLE
Pull requests going on 2 years :(

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#1369]
Several years ago I committed to provide pull requests on this project since I use it extensively for my workflow. However, it seems like the project has gone in to a dormant state, which is quite disappointing. It is a robust and very, very useful GIS project for API and GUI interaction. In fact, I just added 2 more pull requests to fix some issues I detected.

Please, please let us make this project active again so we can bring the code up to date. Much has changed since the last major update. I am ready to help in any way that I can.

Thanks
AGP

**Comment by danames** [comment]
Hey Abel, great to hear from you. Although I started the project, I am not
using it right now so I'm not managing pull requests and issues. Others
have been fairly active till now. Perhaps we need to give you a turn as
project manager for a period of time and let you manage the pull requests
and issues? Would you be interested?

**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
https://ceen.byu.edu/directory/dan-p-ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by sindizzy** [comment]
Thanks for the offer Dan but IMHO I don't think I'm the man for the job. I say that because 99.9% of my code development is with VB. I do code a small amount with C#, mainly for the DotSpatial pull requests. I understand enough C# to fix small snippets or add small routines but a project the size of DS, I think, would be beyond my capability.

I can, however, assist in code review and testing. I also try to stay active on the project forums to help other users. I was also trying to bring back the [wiki from CodePlex](https://github.com/sindizzy/DSW/wiki). I don't recall where I left off on that exercise.

**Comment by danames** [comment]
OK thanks for responding. Let's hope someone else who is active with C# can
step in and do these code merges...
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
https://ceen.byu.edu/directory/dan-p-ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by jany-tenaj** [comment]
I hope to get my own work finished in a few month. Then I'll hopefully have time to take a look at the things that piled up here.

**Comment by sindizzy** [comment]
Thanks!
