### ISSUE TITLE
Unable to refresh map after adding feature to a existing featureset

### ISSUE THREAD

**Issue by zheuziihau** [DotSpatial/DotSpatial#1372]
DotSpatial version: 
1.7

I added a point to a mappointlayer, and called the method"map1.ResetBuffer()",but an error thrown, told me that "index out of range". 
I have tried to add dataSet.InitializeVertices() before map1.ResetBuffer() 
but failed (https://github.com/DotSpatial/DotSpatial/issues/929), the same error happened.
It is strange that the everything goes well if I add a point to a featureLayer which hasnt been saved to file. But when i want to add a point to an existing file, error happened

below is my code, please help to check it, thank you(forgive my poor english).
`private void map1_MouseDown(object sender, MouseEventArgs e)
        {
            Coordinate coord = map1.PixelToProj(e.Location);
            DotSpatial.Topology.Point newpoint = new DotSpatial.Topology.Point(coord);
            IFeatureSet addSet = curFeatureLayer.DataSet;//curFeatureLayer is the layer I want to add point to.
            IFeature fea = addSet.AddFeature(newpoint);
            addSet.InitializeVertices();
            addSet.Save();
            map1.ResetBuffer();
        }`
![image](https://user-images.githubusercontent.com/63400477/102972075-772db700-4535-11eb-99c5-32d0dfd567e4.png)

**Comment by zheuziihau** [comment]
private void map1_MouseDown(object sender, MouseEventArgs e) 
{ Coordinate coord = map1.PixelToProj(e.Location);
 DotSpatial.Topology.Point newpoint = new DotSpatial.Topology.Point(coord); 
IFeatureSet addSet = curFeatureLayer.DataSet;//curFeatureLayer is the layer I want to add point to. 
IFeature fea = addSet.AddFeature(newpoint); 
addSet.InitializeVertices(); 
addSet.Save();
map1.ResetBuffer(); }

**Comment by zheuziihau** [comment]
![image](https://user-images.githubusercontent.com/63400477/102972219-af34fa00-4535-11eb-9b4f-d43f0664e99c.png)

**Comment by sindizzy** [comment]
My suggestion would be to update to the 2.0 release.
