### ISSUE TITLE
DotSpatial.Projections.Reproject.ReprojectPoints with Height?

### ISSUE THREAD

**Issue by TimMakins** [DotSpatial/DotSpatial#1373]
Please can someone explain the Z array that the '.ReprojectPoints' command uses. Using the 'Earth from Space' projection: '+proj=ortho' I would like to reproject a point so that it is a specified distance above the planet surface - the idea is to draw a line from Point A on the ground to Point B on the ground that arcs into the sky and then comes down to earth again. Has anyone done this? I have it all working for lines that stay on the ground, but would like to enhance with arcs into the sky.

**Comment by sindizzy** [comment]
I have just saved the height in the Z property.

**Comment by jany-tenaj** [comment]
Reprojecting needs two projections. It converts the coordinates from one projection to another.
If this conversion affects the z values they should get changed.

But this doesn't affect drawing. If you want to draw height this sounds like you'd have to write something that shows the map in 3d.
