### ISSUE TITLE
ENC in dotspatial

### ISSUE THREAD

**Issue by rusimao** [DotSpatial/DotSpatial#1376]
Is dotspatial compatibile with .000 file types used by US? 
Is it easy to use dotspatial for displaying navigation charts?

**Comment by MatthiasSchilder** [comment]
Looks like gdal is capable of reading the ENC .000 file format: https://gdal.org/drivers/vector/s57.html

DotSpatial has an extension capable of reading raster data with gdal. Maybe you'll want to take a look at this to get a feel how to implement what you need.
