### ISSUE TITLE
Reprojection results different to consensus of online converters.

### ISSUE THREAD

**Issue by DaveTheSave** [DotSpatial/DotSpatial#1379]
Hi,

I am using DotSpatial 1.9.
When reprojecting from 27700 (OSGB36) to 4326 I get an offset when compared to what online point converters return.
I first tried pulling my source CRS from the shapefile, then forcing the feature set to be OSGB36 and finally I separated out the code with a single test point and explicitly defined the source and destination CRS systems using ESRI strings, as follows:
```
double[] z = new double[2];
ProjectionInfo src = ProjectionInfo.FromEsriString("PROJCS[\"OSGB 1936 / British National Grid\",GEOGCS[\"OSGB 1936\",DATUM[\"D_OSGB_1936\",SPHEROID[\"Airy_1830\",6377563.396,299.3249646]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",49],PARAMETER[\"central_meridian\",-2],PARAMETER[\"scale_factor\",0.9996012717],PARAMETER[\"false_easting\",400000],PARAMETER[\"false_northing\",-100000],UNIT[\"Meter\",1]]");
ProjectionInfo des = ProjectionInfo.FromEsriString("GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]]");
z[0] = 0;
z[1] = 0;
double[] points = new double[2];
points[0] = 360216.44430417975;
points[1] = 176543.59223759052;
Reproject.ReprojectPoints(points, z, src, des, 0, 1);
```
The result I get is:
-2.5730259368466863     51.485957413554139

When I try a selection of online converts they give:

-2.5743517    51.4864342

I'm new to spatial data, so I'm probably missing something obvious, but any help would be greatly appreciated.
Thanks

**Comment by MatthiasSchilder** [comment]
When dealing with different GEOGCS, you often need a datum transformation to achieve full precision. There is an overload of ReprojectPoints, which allows you to specify the correct one.

This is an example from our app for a Helmert-datum transformation between ETRS89 and DHDN:
`
var dtStage = new DatumTransformStage("ETRS89", "DHDN", new Spheroid(Proj4Ellipsoid.GRS_1980),
                new Spheroid(Proj4Ellipsoid.Bessel_1841), -598.1, -73.7, -418.2, -0.202, -0.045, 2.455, -6.7);
var dt = new DatumTransform(transformOpDHDN_ETRS89_3M);
`
Those correction factors are specific to the GEOGCS you want to convert. You need to look them up for yourself.
There are other approaches like grids supplying correction factors (gsa, gsb) for your specific transform. DotSpatial supports them. There is an wiki article at https://github.com/DotSpatial/DotSpatial/wiki/Grid-Shifts.

**Comment by DaveTheSave** [comment]
Thank you, I found this post that specifically helps with respect to OSGB1936:
[](https://stackoverflow.com/questions/1426941/proj-4-library-and-osgb36)

For anyone else in this position here's the code containing the proj4 string with added datum conversion:

```				
double[] z = new double[2];
ProjectionInfo src = ProjectionInfo.FromProj4String("+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.999601 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84 = 446.448,-125.157,542.060,0.1502,0.2470,0.8421,-20.4894 +units=m +no_defs <> ");
ProjectionInfo des = ProjectionInfo.FromProj4String("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs");
z[0] = 0;
z[1] = 0;
double[] points = new double[2];
points[0] = 360216.44430417975;
points[1] = 176543.59223759052;
Reproject.ReprojectPoints(points, z, src, des, 0, 1);
```
This converts correctly.

**Comment by MatthiasSchilder** [comment]
Yeah, the towgs84-parameter-part is essentially the same as supplying a DatumTransform with the corresponding params.

**Comment by DaveTheSave** [comment]
Thanks again, this has helped me out.
