### ISSUE TITLE
DotSpatial  not use in wpf application 

### ISSUE THREAD

**Issue by surajit-te** [DotSpatial/DotSpatial#1381]
i am not use DotSpatial map in wpf application

**Comment by MatthiasSchilder** [comment]
There is a control named WindowsFormsHost in WPF, which allows you to host WinForms-components (like the DotSpatial map) on WPF dialogs. You could try that.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.windowsformshost?view=netframework-4.6.1

**Comment by surajit-te** [comment]
Ok Thank you
