### ISSUE TITLE
Dot Spatial for .NET 3.5

### ISSUE THREAD

**Issue by Gwhitch** [DotSpatial/DotSpatial#1387]
I am looking for a Dot Spatial version that will work for .NET 3.5. Unfortunately, The project I want to put it in, requires .NET 3.5. 

#

**Comment by sindizzy** [comment]
What I would do is download the source code and set the .NET Framework to 3.5 and recompile. You may encounter issues since the current project is set at .NET 4.0.

**Comment by Gwhitch** [comment]
Thanks so dizzy. i tried that. created 314 errors in the project. too many calls to 4.0

**Comment by sindizzy** [comment]
You could try one of the older versions https://github.com/DotSpatial/DotSpatial/releases

**Comment by jany-tenaj** [comment]
DS 1.9 should work.
