### ISSUE TITLE
WGS84 to State Plane

### ISSUE THREAD

**Issue by Gwhitch** [DotSpatial/DotSpatial#1388]
When I try to convert Lat/Long to Texas State Plane, I get unexpected values.

### Steps to reproduce
DotSpatial.Projections.ProjectionInfo from = KnownCoordinateSystems.Geographic.World.WGS1984;
            string esristring = "PROJCS[\"NAD_1983_StatePlane_Texas_Central_FIPS_4203\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137,298.257222101004]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.0174532925199433]], PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",Infinity],PARAMETER[\"False_Northing\",Infinity],PARAMETER[\"Central_Meridian\",-100.333333333333],PARAMETER[\"Standard_Parallel_1\",30.1166666666667],PARAMETER[\"Standard_Parallel_2\",31.8833333333333],PARAMETER[\"Scale_Factor\",1],PARAMETER[\"Latitude_Of_Origin\",29.6666666666667],UNIT[\"Meter\",0]]";
DotSpatial.Projections.ProjectionInfo target = DotSpatial.Projections.ProjectionInfo.FromEsriString(esristring);

double[] XY = new double[2];
XY[0] = -95.73196411;
XY[1] = 29.62242699;
double[] Z = new double[1];
Z[0] = 1;
Reproject.ReprojectPoints(XY, Z, from, target, 0, 1);

I would expect a projected value for both X(Easting) and Y(Northing) for both values.

What I am seeing is both XY[0] and XY[1] are both NaN.

I would appreciate any help.

**Comment by Gwhitch** [comment]
The esristring came from DotSpatial so I'm sure that is correct.

**Comment by manfredwippel** [comment]
@Gwhitch following test case is working. Your esristring might be incorrect

`[Test]
        public void NAD_1983_StatePlane_Texas_Central_FIPS_4203()
        {
            ProjectionInfo from = KnownCoordinateSystems.Geographic.World.WGS1984;
            string esristring = "PROJCS[\"NAD_1983_StatePlane_Texas_Central_FIPS_4203_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137,298.257222101]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",2296583.333333333],PARAMETER[\"False_Northing\",9842499.999999998],PARAMETER[\"Central_Meridian\",-100.3333333333333],PARAMETER[\"Standard_Parallel_1\",30.11666666666667],PARAMETER[\"Standard_Parallel_2\",31.88333333333333],PARAMETER[\"Latitude_Of_Origin\",29.66666666666667],UNIT[\"Foot_US\",0.30480060960121924]]";
            ProjectionInfo target = ProjectionInfo.FromEsriString(esristring);

            double tolerance = 0.08d;
            //https://epsg.io/transform#s_srs=4326&t_srs=102739&x=-95.7319641&y=29.6224270

            double[] xy = new double[2] { -95.73196411, 29.62242699 };
            double[] z = new double[1];
            double[] expected = new double[2]
            {
                3758483.44118406, 9856648.08999862
            };
            Reproject.ReprojectPoints(xy, z, from, target, 0, 1);
            Assert.AreEqual(expected[0], xy[0], tolerance);
            Assert.AreEqual(expected[1], xy[1], tolerance);

            esristring = "PROJCS[\"NAD_1983_HARN_StatePlane_Texas_Central_FIPS_4203\",GEOGCS[\"GCS_North_American_1983_HARN\",DATUM[\"D_NAD83_High_Accuracy_Regional_Network\",SPHEROID[\"GRS_1980\",6378137,298.257222101]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",700000],PARAMETER[\"False_Northing\",3000000],PARAMETER[\"Central_Meridian\",-100.3333333333333],PARAMETER[\"Standard_Parallel_1\",30.11666666666667],PARAMETER[\"Standard_Parallel_2\",31.88333333333333],PARAMETER[\"Latitude_Of_Origin\",29.66666666666667],UNIT[\"Meter\",1]]";
            //https://epsg.io/transform#s_srs=4326&t_srs=102339&x=-95.7319641&y=29.6224270
            target = ProjectionInfo.FromEsriString(esristring);
            xy = new double[2] { -95.73196411, 29.62242699 };
            z = new double[1] { 1 };

            expected = new double[] { 1145588.04404899, 3004312.34645627 };

            Reproject.ReprojectPoints(xy, z, from, target, 0, 1);
            Assert.AreEqual(expected[0], xy[0], tolerance);
            Assert.AreEqual(expected[1], xy[1], tolerance);
        }`
