### ISSUE TITLE
Demo Map Menus and Toolbars not showing

### ISSUE THREAD

**Issue by Scott2142** [DotSpatial/DotSpatial#1389]
On opening DemoMap the expected Menus and Toolbars are not showing.

This occurs on current release and multiplie versions other versions. Trialled on debug bin version compiled on computer where all menus show but they still did not show. Any ideas on why?

### Expected behaviour

![image](https://user-images.githubusercontent.com/70848935/112150259-fd8c8e80-8c33-11eb-9916-65adf323aed3.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/70848935/112150364-19903000-8c34-11eb-83f2-680a9bea40ca.png)

**Comment by jany-tenaj** [comment]
Do you get any error messages? Please check the content of your plugin folders. Make sure the files that exist in your root folder do not get copied to the folders of your plugins.

**Comment by Scott2142** [comment]
I have resolved this issue. In case it helps others the issue was caused by Windows. If I run VS as admin then everything works as expected.

**Comment by jany-tenaj** [comment]
This should work without running VS on admin ,too.

**Comment by Scott2142** [comment]
Now that I have been able to successfully run as admin once I can now run without using Admin privileges.

**Comment by Scott2142** [comment]
I consider this resolved.
