### ISSUE TITLE
Feature request: Sign the DLLs distributed via NuGet

### ISSUE THREAD

**Issue by Hammerite** [DotSpatial/DotSpatial#1397]
The DotSpatial DLLs distributed via NuGet aren't signed (looking at version 1.9, which is the latest as far as I can tell). It would be helpful if they were signed.

https://en.wikipedia.org/wiki/Code_signing

**Comment by MatthiasSchilder** [comment]
Are there possibilies to get Code Signing certificates for free for OSS projects? In our company, we use EV certificates from DigiCert for signing, but those have a 1500 € price tag for a validity period of 3 years. It would also require a maintainer which manages the private key.

**Comment by Hammerite** [comment]
I appreciate that it might not be practical for the project to do this. I don't have answers to those questions. I thought it worthwhile to mention it in an issue so that it can either be done, or definitively addressed as "we won't do this".

**Comment by jany-tenaj** [comment]
Not gonna do this
