### ISSUE TITLE
Question: Can DotSpatial be used with .NET 5.0? 

### ISSUE THREAD

**Issue by pitonyak** [DotSpatial/DotSpatial#1399]
This is a question related to using DotSpatial with .NET 5.0

Been mostly handling Java projects the last few years so rusty with .NET rules and behaviors. 

DotSpatial was added to a .NET 5.0 project and there are warnings such as 

DotSpatial.Analysis 1.9.0 was restored using .NETFramework version 4.7.2 instead of the project target framework "net5.0-windows7.0" this package may not be fully compatible with your project. 

At runtime we see errors similar to: 

Failed to create component Legend
Could not load type System.Windows.Forms..ContextMenu from assembly Systems.Windows.Forms version 5.0.6.0

**Comment by Zeleksonob** [comment]
+1 to this question, we already in 2021 , please guys add support to .NET 5 or at least .net standard.

**Comment by shanto462** [comment]
> This is a question related to using DotSpatial with .NET 5.0
> 
> Been mostly handling Java projects the last few years so rusty with .NET rules and behaviors.
> 
> DotSpatial was added to a .NET 5.0 project and there are warnings such as
> 
> DotSpatial.Analysis 1.9.0 was restored using .NETFramework version 4.7.2 instead of the project target framework "net5.0-windows7.0" this package may not be fully compatible with your project.
> 
> At runtime we see errors similar to:
> 
> Failed to create component Legend
> Could not load type System.Windows.Forms..ContextMenu from assembly Systems.Windows.Forms version 5.0.6.0

you can check here

https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms

some of the winform controls were removed in .Net Core 3.1 and after.

**Comment by jany-tenaj** [comment]
No it can't.
