### ISSUE TITLE
Looking for codeplex documentation

### ISSUE THREAD

**Issue by pgauthier-at-atvent** [DotSpatial/DotSpatial#1406]
Hello!

I just found out that codeplex site is down and that original documentation is no longer available.

I'm looking for a programming guide with code samples and specially for a way to create complex point symbology.

Thank you for your help,
Pierre

**Comment by sindizzy** [comment]
Two places:
1. https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation
2. I attempted a conversion of the samples here: https://github.com/sindizzy/DSW/wiki

**Comment by pgauthier-at-atvent** [comment]
Thank you for the quick answer, the second place is exactly what I was looking for.
