### ISSUE TITLE
How to create complex custom symbols

### ISSUE THREAD

**Issue by pgauthier-at-atvent** [DotSpatial/DotSpatial#1408]
Hello!

I would like to create custom symbols and I saw that there is a way to create compound symbols by using a list of symbols but it seems we are limited to use the predefined PointShapes (ellipse, diamond, triangle, ...).

Is there a way to create custom symbols being a combination of lines, polygons, arcs and maybe labels with a value coming from an attribute of the feature such as a highway road number sign.

Thank you,
Pierre

**Comment by sindizzy** [comment]
Take a look here:
1. - https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation
2. - I attempted a conversion of the samples here: https://github.com/sindizzy/DSW/wiki
