### ISSUE TITLE
Adding labels to an in-memory layer throws an exception

### ISSUE THREAD

**Issue by eapbokma** [DotSpatial/DotSpatial#1417]
### Steps to reproduce

1. For any map, add new feature layer without loading it from a file

       FeatureSet fs = new FeatureSet(FeatureType.Point);
       Coordinate c = new Coordinate(Convert.ToDouble(100), Convert.ToDouble(100));
       IFeature f = fs.AddFeature(new NetTopologySuite.Geometries.Point(c));
       App.Map.Layers.Add(fs);

2. From the legend, right-click the layer and open Labeling > Label setup.
3. Set FID as the feature label and press apply.

DotSpatial version: 2.0.1

### Expected behaviour

The single point added to the feature is labeled with the feature id "0".

### Actual behaviour

An index out of range exception is thrown.
![image](https://user-images.githubusercontent.com/597606/148264010-18bb9c99-0083-4b6f-a422-afc1934367d1.png)

**Comment by sindizzy** [comment]
I don't remember exactly what issue I had but you could try a combo of these fields
fs.IndexMode
fs.AttributesPopulated

**Comment by jany-tenaj** [comment]
Your problem comes from the fact that you didn't update the DrawnStates. Furthermore switch IndexMode of after you create your FeatureSet, because otherwise updating the DrawnStates doesn't work. Be aware of issue #801.


```
            FeatureSet fs = new FeatureSet(FeatureType.Point);
            fs.IndexMode = false;

            Coordinate c = new Coordinate(Convert.ToDouble(100), Convert.ToDouble(100));
            IFeature f = fs.AddFeature(new NetTopologySuite.Geometries.Point(c));
            
            var l = App.Map.Layers.Add(fs);
            l.AssignFastDrawnStates();
```

**Comment by eapbokma** [comment]
I have tried changing the index mode and assigning fast drawn states, including directly using the code above. It still produces the same issue. However, when I step through the _AssignFastDrawnStates_ and inspect the _DataSet_ property with the debugger, it works. I'm not certain of what is going on yet, but when I first look at _DataSet.ShapeIndices.Count_, it is 0. After inspecting _DataSet_ with the debugger (I'm using Visual Studio 2019), _DataSet.ShapeIndices.Count_ is set to 1. It looks like some code in a property getter is not being triggered to update the _ShapeIndices_ to be consistent with the list of features.

**Comment by jany-tenaj** [comment]
Strange, that the code isn't working for you. If this is all you do to this FeatureSet ShapeIndices shouldn't be touched at all. 

DotSpatial knows to ways to work. One is IndexMode = true where it uses ShapeIndices and corresponding methods and one is IndexMode = false where it uses Features and corresponding methods. Unfortunately You can switch between both and there are some functions that depend on something not belonging to the IndexMode one uses. Therefore I found it best to make sure everything from IndexMode = true and IndexMode = false is in sync as shown in #801.
