### ISSUE TITLE
I don't solve Encoding 850 data not found..

### ISSUE THREAD

**Issue by Hongseonet** [DotSpatial/DotSpatial#1421]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Build app  by Unity
2. Run & load shp file
3. get error of Encoding 850 data could not be found..

DotSpatial version:  v2

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

attatch..
![image](https://user-images.githubusercontent.com/59943387/153552399-ef0e1a5a-d6a7-49f7-9c9e-57fbfcded366.png)

**Comment by jany-tenaj** [comment]
@Hongseonet Please tell us which version of Visual Studio and .Net you are using.

**Comment by Hongseonet** [comment]
> 
Thanks for answer.
Office using visual studio 2019 enterprise
Home using visual studio 2022 community

installed .net is 
![image](https://user-images.githubusercontent.com/59943387/153708943-315e9554-66c6-4af5-aec6-263661da8388.png)

**Comment by Hongseonet** [comment]
Thanks.. I solved.
Temporary remove encoding 850 routine.
