### ISSUE TITLE
Added Fathom as a DistanceUnit

### ISSUE THREAD

**Issue by azzimccc** [DotSpatial/DotSpatial#1422]
### Fathom into **DistanceUnit** enum

A fathom is a unit systems equal to 72 inches (1,828.8000 mm), used especially for [measuring the depth of water].

1 fathom is equal to :
6 ft
1.8288 m

TQIA

**Comment by sindizzy** [comment]
You added it to the code or you are requesting it to be added?

**Comment by azzimccc** [comment]
Sorry for the confusion ...... Its a request

**Comment by jany-tenaj** [comment]
Where are we supposed to add this?

**Comment by azzimccc** [comment]
> 

In the DistanceUnit enum

**Comment by jany-tenaj** [comment]
@azzimccc  please check out the code in the attached pull request / branche and let me know whether this works as expected.

**Comment by azzimccc** [comment]
Yup ... should be OK
