### ISSUE TITLE
UtmNad1983 Name properties are incorrect

### ISSUE THREAD

**Issue by daveatdnv** [DotSpatial/DotSpatial#1423]
### Actual behaviour
The names of the UtmNad1983 co-ordinate systems are incorrect. It looks like a global replacement error.

            NAD1983UTMZone1N.Name = "NAD_1983_UTM_Zone_1N";
            NAD1983UTMZone2N.Name = "NAD_1983_UTM_Zone_D1983UTMZone2N";
            NAD1983UTMZone3N.Name = "NAD_1983_UTM_Zone_D1983UTMZone3N";
            NAD1983UTMZone4N.Name = "NAD_1983_UTM_Zone_D1983UTMZone4N";
            NAD1983UTMZone5N.Name = "NAD_1983_UTM_Zone_D1983UTMZone5N";
            NAD1983UTMZone6N.Name = "NAD_1983_UTM_Zone_D1983UTMZone6N";
            NAD1983UTMZone7N.Name = "NAD_1983_UTM_Zone_D1983UTMZone7N";
            NAD1983UTMZone8N.Name = "NAD_1983_UTM_Zone_D1983UTMZone8N";
            NAD1983UTMZone9N.Name = "NAD_1983_UTM_Zone_D1983UTMZone9N";
            NAD1983UTMZone10N.Name = "NAD_1983_UTM_Zone_D1983UTMZone10N";
            NAD1983UTMZone11N.Name = "NAD_1983_UTM_Zone_D1983UTMZone11N";
            NAD1983UTMZone12N.Name = "NAD_1983_UTM_Zone_D1983UTMZone12N";
            NAD1983UTMZone13N.Name = "NAD_1983_UTM_Zone_D1983UTMZone13N";
            NAD1983UTMZone14N.Name = "NAD_1983_UTM_Zone_D1983UTMZone14N";
            NAD1983UTMZone15N.Name = "NAD_1983_UTM_Zone_D1983UTMZone15N";
            NAD1983UTMZone16N.Name = "NAD_1983_UTM_Zone_D1983UTMZone16N";

### Expected behaviour
The text **D1983UTMZone** needs removing.

            NAD1983UTMZone1N.Name = "NAD_1983_UTM_Zone_1N";
            NAD1983UTMZone2N.Name = "NAD_1983_UTM_Zone_2N";
            NAD1983UTMZone3N.Name = "NAD_1983_UTM_Zone_3N";
            NAD1983UTMZone4N.Name = "NAD_1983_UTM_Zone_4N";
            NAD1983UTMZone5N.Name = "NAD_1983_UTM_Zone_5N";
            NAD1983UTMZone6N.Name = "NAD_1983_UTM_Zone_6N";
            NAD1983UTMZone7N.Name = "NAD_1983_UTM_Zone_7N";
            NAD1983UTMZone8N.Name = "NAD_1983_UTM_Zone_8N";
            NAD1983UTMZone9N.Name = "NAD_1983_UTM_Zone_9N";
            NAD1983UTMZone10N.Name = "NAD_1983_UTM_Zone_10N";
            NAD1983UTMZone11N.Name = "NAD_1983_UTM_Zone_11N";
            NAD1983UTMZone12N.Name = "NAD_1983_UTM_Zone_12N";
            NAD1983UTMZone13N.Name = "NAD_1983_UTM_Zone_13N";
            NAD1983UTMZone14N.Name = "NAD_1983_UTM_Zone_14N";
            NAD1983UTMZone15N.Name = "NAD_1983_UTM_Zone_15N";
            NAD1983UTMZone16N.Name = "NAD_1983_UTM_Zone_16N";

DotSpatial version: 2.0.1

**Comment by jany-tenaj** [comment]
@daveatdnv  Please submit a pull request with those changes.
