### ISSUE TITLE
Override delete key down/press/up in DotSpatial.Controls.Map

### ISSUE THREAD

**Issue by sas371** [DotSpatial/DotSpatial#1446]
I am struggling to find the code that implements the keydown/keypress/keyup events when the active control is a DotSpatial.Controls.Map. I would like to disable this code for our custom application. Could someone please point me in the right direction? Thanks for your time.

**Comment by jany-tenaj** [comment]
Checkout [MapFunctionKeyNavigation](https://github.com/DotSpatial/DotSpatial/blob/master/Source/Core/DotSpatial.Controls/MapFunctionKeyNavigation.cs#L12).

It gets activated in [Map.Configure](https://github.com/DotSpatial/DotSpatial/blob/834fbffc6ae84ac7db23df2b1fa9fcb5ea249cac/Source/Core/DotSpatial.Controls/Map.cs#L1496). I think you should be able to remove this function from the MapFunctions.
