### ISSUE TITLE
change the code in "GenerateCentroid.cs"

### ISSUE THREAD

**Issue by mygh1209** [DotSpatial/DotSpatial#1465]
*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description
it's more timesaving to break the foreach loop when it comes to the "multPoint = true",or change the foreach to linq.

![pic](https://user-images.githubusercontent.com/24479244/196228738-fd4606c6-9d64-4713-89c6-9efdd66a4d2f.png)

**Comment by sindizzy** [comment]
How much time do you save?

**Comment by mygh1209** [comment]
I haven't tested or made any comparison actually. Forget about the execting time cost,But why continue the foreach loop when it comes to the "multiPoint=true;"?

**Comment by sindizzy** [comment]
You are not continuing the for-loop. 
When multiPoint=true there is a break out of the loop.

**Comment by jany-tenaj** [comment]
Currently can't test this myself but shouldn't you be able to change [those lines](https://github.com/DotSpatial/DotSpatial/blob/63e9cc41973932e6ea06bc9a24cc6308a2841ee0/Source/Core/DotSpatial.Tools/GenerateCentroid.cs#L80-L89) to

`output.FeatureType = input1.Features.Any(f => f.Geometry.NumGeometries > 1) ?  FeatureType.MultiPoint: FeatureType.Point;`
