### ISSUE TITLE
False polygon outlines are drawn at map boundary when not in edit mode

### ISSUE THREAD

**Issue by UliEgger** [DotSpatial/DotSpatial#1474]
### Steps to reproduce

1. Start DemoApp
2. Load a polygon layer (MapPolygonLayer)
3. Pan the layer so that some polygons overlap the map boundary

DotSpatial version: 

### Expected behaviour

There should be no outline drawn at the intersection line between map boundary and polygon (created with local bugfix)

![grafik](https://user-images.githubusercontent.com/8180924/205268483-5280222b-0a54-4d33-9b49-1b4317c53950.png)

### Actual behaviour

The polygon outline is drawn at the boundary as if it was clipped when creating an overlap with the boundary

![grafik](https://user-images.githubusercontent.com/8180924/205267282-faa29a04-d45a-450a-a6e5-d8d16babc59b.png)

![grafik](https://user-images.githubusercontent.com/8180924/205267750-a7dd5412-244d-411f-b4dd-833762cb0259.png)

**Comment by UliEgger** [comment]
I could create a Pull request if accepted

Solution:

There are two methods of MapPolygonLayer

private void BuildPaths(MapArgs e, IEnumerable<int> indices, out Dictionary<FastDrawnState, GraphicsPath> paths, bool selected)

private void BuildPaths(MapArgs e, IEnumerable<IFeature> features, out Dictionary<FastDrawnState, GraphicsPath> borderPaths, bool selected)

In both methods, a clipping rectangle is used but differently calculated

The first (used when not in edit mode) does:

            Rectangle clipRect = e.ProjToPixel(e.GeographicExtents);

The second (used in edit mode) does:

           Rectangle clipRect = ComputeClippingRectangle(e); 

ComputeClippingRetangle considers that there must be a buffer because of Symbology.

**Comment by jany-tenaj** [comment]
Your first picture doesn't show what happens in the first case because your polygon doesn't overlap the boundary there. Be careful about switching EditMode. It basically coresponds to IndexMode. If they get out of sync you'll get some unwanted errors.

**Comment by UliEgger** [comment]
I could now reproduce with DemoMap

Description is updated
