### ISSUE TITLE
Non UI Projects as .netstandard2.0 libraries.

### ISSUE THREAD

**Issue by UliEgger** [DotSpatial/DotSpatial#1479]
### Feature description

As a developer, I would like to use NON-UI Projets in .netstandard libraries.

These projects are:

DotSpatial.Data
DotSpatial.Extensions
DotSpatial.NTSExtension
DotSpatial.Projections
DotSpatial.Serialization
DotSpatial.Symbology

DotSpatial.Symbology has a reference on System.Drawing.Design because of the property

IFeatureScheme.PropertyEditor

implemented in FeatureScheme.PropertyEditor

But this property is unused. Can the property be removed ?

Reference to System.Drawing.Design would be not possible if shifting the project to .netstandard.

Shall I perpare a Merge Request ?

**Comment by jany-tenaj** [comment]
Can't say I'm a fan of supporting .Netstandard. It causes extra problems for something that's basically obsolete.

**Comment by UliEgger** [comment]
We did it in our company's fork and so far it didn't cause any problem.

The reason we do that is that we are forced to have some of our libraries to be still .Net Framework 4.8 because they are used as a plugin in another commercial .NET Framework Application.

**Comment by jany-tenaj** [comment]
If you did it then create a pull request. No idea what hassle it'll cause if we have to switch to .NET 7 or later. But there's always the possibility to get rid of it again later...

**Comment by UliEgger** [comment]
Pull request #1480 is created.
