### ISSUE TITLE
Some unit tests in OpenFileThrowsRightException fail because of ContractAssert in AttributeTable.Open

### ISSUE THREAD

**Issue by UliEgger** [DotSpatial/DotSpatial#1481]
### Steps to reproduce

1. Run the following unit tests

OpenFileTrowsRightException

DotSpatial version: Current master

### Expected behaviour

Unit tests do not show any failure

### Actual behaviour

The unit tests fail for the following files

cities.dbf, rivers.dbf, states.dbf

The reason is that in Class AttributeTable, method Open (string filename, List<int> deletedRows)

an assertion is done in the following line

Contract.Assert(File.Exists(_fileName), "The dbf file for this shapefile was not found.");

The unit tests fails with 

![grafik](https://user-images.githubusercontent.com/8180924/206211675-6d262fc0-0cee-499b-a77e-04ac49c84980.png)

It is the only place in the DotSpatial solution where such an assertion instead of exceptions is used
The assertion is not necessary because an exception will be thrown.

A missing dbf file is not our own programming error but an error in external data.
So an exception would be the right way to treat this failure.

**Comment by jany-tenaj** [comment]
I'd say Assert was throwing an error in .Net 4.x because there the test worked...

**Comment by UliEgger** [comment]
Thank you for the bugfix.

I wondered why there are so many changes in the file. Is there another reason

**Comment by UliEgger** [comment]
I made an adaption in the file AttributeTable.cs, so that it compiles also with .netstandard
I did this in the feature branch of the merge request

 Non UI Projects as .netstandard2.0 libraries #1480

**Comment by jany-tenaj** [comment]
The file formatting didn't fit to the defined rules

**Comment by UliEgger** [comment]
Ok, thank you !
