### ISSUE TITLE
Topology:  Area for a Polygon with Holes

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#16]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/20)**

**[AlamoMan](http://www.codeplex.com/site/users/view/AlamoMan)** wrote 2010-07-14 at 23:40
The area of a polygon with holes in the DotSpatial.Topology.dll is slightly different from the area in the NetTopologySuite. See the PolygonHoles Test Method in the PointsLinesPolygons class in the Spatial_Topology unit tests. These values should be exact.

**Comment by mogikanin** [comment]
@jany-tenaj : i guess this will be not actual after we merge your branch into master?

**Comment by jany-tenaj** [comment]
@mogikanin: Yes this should be gone considering we're now using a forked NTS.

Not sure how to test this as we can't use the original NTS and DotSpatial.NTS in the same test project.

**Comment by mogikanin** [comment]
I think we can assume that this issue is closed for 2.0.
