### ISSUE TITLE
Cannot delete newly added features

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#169]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/175)**

**[keenedge](http://www.codeplex.com/site/users/view/keenedge)** wrote 2010-11-30 at 02:41
With DemoMap

<ul>
<li>Add a layer </li><li>Enable the ShapeEditor tool </li><li>Digitize a shape </li><li>Using the select tool select the newly digitized shape. </li><li>Use the "remove Slected features" tool to remove the shape.

</li></ul>
Nothing happens. The new feature is not removed.

**[keenedge](http://www.codeplex.com/site/users/view/keenedge)** wrote 2010-12-06 at 21:30
Anyone have anything thoughts on why this is? It is a result of one of the recent change sets.

**[Shade1974](http://www.codeplex.com/site/users/view/Shade1974)** wrote 2010-12-06 at 23:02
Er.. it is obviously a bug. It might have to do with changing from index mode to Feature mode, but it's not intuitive to me as to what might be wrong since the vertices have to be defined correctly or else it couldn't draw the feature. I wonder if this
 is specific to one feature type or if this is true with all feature types. I'm sure I can get to the bottom of it, I just have been working on getting our documentation engine online. I'll be back to debugging probably later this week though and can look at
 testing it then.

Ted

**[geofran80](http://www.codeplex.com/site/users/view/geofran80)** wrote 2011-03-31 at 15:20
Dear friends, is fixed this issue?

Thanks.

Francisco J.

**Comment by jany-tenaj** [comment]
@mogikanin Do you have any idea what is meant by "remove selected features" tool? Without it this issue makes no sense.

**Comment by mogikanin** [comment]
No idea. Closing it.
