### ISSUE TITLE
SQLExpressionDialog Not Returning OK Result

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#185]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/191)**

**[pernsdorff](http://www.codeplex.com/site/users/view/pernsdorff)** wrote 2010-12-16 at 05:26
On button press of Ok dialog result returns Cancel. Reason seems to be the Ok button DialogResult property is set to None instead of OK.

**[Shade1974](http://www.codeplex.com/site/users/view/Shade1974)** wrote 2010-12-16 at 18:06
If you are working with the source code, can you please fix this and commit. I want people to be confident committing fixes. The more people we have that can actively solve their own issues, the stronger the whole open source project becomes. If you cannot
 do this, I will try to look into this tonight. If you are not a developer, then you can request to become one and you will be able to push up your fix to the repository.

**[pernsdorff](http://www.codeplex.com/site/users/view/pernsdorff)** wrote 2010-12-17 at 03:32
Yes, working from source. I have no problem checking in this change. Didn't want to overstep my "bounds" in case it was changed like this for a reason.

This had worked fine from a version of the source a few months ago.

**Comment by jany-tenaj** [comment]
@mogikanin: Just had a look at this. It's already fixed.

**Comment by mogikanin** [comment]
Closing then.
