### ISSUE TITLE
Slight shift on projections

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#187]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/193)**

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2010-12-17 at 23:39
I've been playing with the with Open Street Maps with are in KnownCoordinateSystems.Projected.World.WebMercator, however when I project the shapefile with .reproject (prj file at end of post), it is shifted a bit. If I take the same file and reproject
 it in ArcMap it works fine. Attached is a picture of the shift. 

The shape file projection: 

PROJCS["USA_Contiguous_Albers_Equal_Area_Conic_USGS_version",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Albers"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-96.0],PARAMETER["Standard_Parallel_1",29.5],PARAMETER["Standard_Parallel_2",45.5],PARAMETER["Latitude_Of_Origin",23.0],UNIT["Meter",1.0]]

**[Shade1974](http://www.codeplex.com/site/users/view/Shade1974)** wrote 2010-12-18 at 01:26
I think there is a standing issue that the WebMercator projection may not be fully supported. We need to find some documentation somewhere that shows what the math is supposed to be, and so far I haven't seen any. I haven't looked that hard though, but
 if someone is having direct problems from this, maybe you guys are the ones to take the lead on this. Aaron if you don't mind could you see if you can turn up a nice reference somewhere on WebMercator. Once we know what the math is supposed to look like, I
 think we could wedge it into the Transform function pretty easily.

Ted

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2010-12-21 at 16:30
Looks like Jiri knew more work need to be done on the webmercator. Looking at line 985 of projectionInfo.cs there are some comments and code that isn't fully implemented.

I looked around some and could only find one thing that specifically references "Web Mercator":

<a href="http://www.hydrometronics.com/downloads/Web%20Mercator%20-%20Non-Conformal,%20Non-Mercator%20%28notes%29.pdf" rel="nofollow">http://www.hydrometronics.com/downloads/Web%20Mercator%20-%20Non-Conformal,%20Non-Mercator%20%28notes%29.pdf</a>

Lots of references to "Sperical Mercator" which seems to be used interchangeable with "Web Mercator", but I couldn't find anything that said they were the same thing.

AP

**[jasond](http://www.codeplex.com/site/users/view/jasond)** wrote 2010-12-21 at 22:28
I assume you are using the latest build? When I updated to the Dec 15 build, my Web Mercator problems seem to have disappeared. Also, the OSM are not always 'correct', at least when compared with google, bing, etc.

That said here are some links I found when I was researching Web Mercator awhile back:

<a href="http://docs.openlayers.org/library/spherical_mercator.html" rel="nofollow">http://docs.openlayers.org/library/spherical_mercator.html</a>

<a href="http://trac.osgeo.org/openlayers/wiki/SphericalMercator" rel="nofollow">http://trac.osgeo.org/openlayers/wiki/SphericalMercator</a>

**[jasond](http://www.codeplex.com/site/users/view/jasond)** wrote 2011-01-04 at 01:11
I may have spoken too soon. I'm having a shift problem. If it's not related, let me know, and I will create a new task.

Indiana West (NAD1983StatePlaneIndianaWestFIPS1302) coordinates (meters):

Northing = 580105.11

Easting = 904951.048

Reproject to WebMercator:

Northing: 4907250.15356423 (wrong)

Easting: -9687572.79646669

Reproject to UTM (WGS1984UTMZone16N) to WebMercator:

Northing: 4935004.21575689 (right)

Easting: -9687572.79646669

I also converted from State Plane to GPS to Web and it worked fine.

**Comment by mogikanin** [comment]
Not reproduced.

**Comment by TranstecJasonD** [comment]
Hopefully this won't re-open the issue. I received an email that the issue was closed and finally had time to check it since I had forgotten. I can confirm the shift I saw with Indiana West is no longer there with version 1.7.
