### ISSUE TITLE
Unioning polygons gets "Bad distance calculation" exception.

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#209]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/215)**

**[kellison](http://www.codeplex.com/site/users/view/kellison)** wrote 2011-01-20 at 17:04
Unioning the polygons shown below fails with exception noted above:

<ul>
<li>plyShape {POLYGON ((-84.6976494321476000 41.7477691708729000, -84.6402221482214000 41.7477691708729000, -84.6402221482214000 41.6997514050474000, -84.6974494321476000 41.6997514050474000, -84.6974494321476000 41.6519336392220000, -84.7548767160738000 41.6519336392220000,
 -84.7548767160738000 41.6999514050475000, -84.6976494321476000 41.6999514050475000, -84.6976494321476000 41.7477691708729000))} DotSpatial.Topology.IGeometry {DotSpatial.Topology.Polygon}

</li><li>plyShapeE {POLYGON ((-84.6976494321476000 41.6999514050475000, -84.6402221482214000 41.6999514050475000, -84.6402221482214000 41.6519336392220000, -84.6976494321476000 41.6519336392220000, -84.6976494321476000 41.6999514050475000))} DotSpatial.Topology.IGeometry
 {DotSpatial.Topology.Polygon}

</li></ul>
plyShape.Union(plyShapeE);

**[kellison](http://www.codeplex.com/site/users/view/kellison)** wrote 2011-01-20 at 17:12
Fixed in Change Set 1356c135cf7a. The Topology engine is introducing z values sometimes that have to be dealt with when comparing 2D coordinates to 3D coordinates.

**Comment by jany-tenaj** [comment]
This already worked in DS 1.9
