### ISSUE TITLE
Read MW4 rendering information for grids *.mwleg

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#219]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/226)**

**[jlkittle](http://www.codeplex.com/site/users/view/jlkittle)** wrote 2011-01-28 at 19:28
MapWindow 4 saves rendering information for a grid in a file named after the grid with the extension .mwleg.

Attached file with extension .mwa is a MW4 archive file which MW4 can open using File/Archive/Restore Project. If you don't see Archive/Restore Project in the File menu, make sure Plugins/Archive Project Tool is enabled. If you need to open the archive without
 MW4, you can add a .zip extension and open it as a zip file.

**[jlkittle](http://www.codeplex.com/site/users/view/jlkittle)** wrote 2011-01-28 at 19:29
grid rendered in MW4

**[jlkittle](http://www.codeplex.com/site/users/view/jlkittle)** wrote 2011-01-28 at 19:29
legend in MW4 for sample grid

**Comment by mogikanin** [comment]
By some reason method for reading legend from .mwleg fully commented
https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Plugins.MapWindowProjectFileCompatibility/LegacyLayerDeserializer.cs#L164

**Comment by jany-tenaj** [comment]
we got rid of MapWindowProjectFileCompatibility plugin
