### ISSUE TITLE
Error opening GeoTiff raster file

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#233]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/240)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-02-05 at 09:48
I'm trying to open the attached GeoTiff (*.tif) raster file in the DotSpatial DemoMap application. When open the file using the "Add Layer" button, nothing shows on the map.

The problem is in the GdalRasterProvider.Open() method. 

The bandtype of my GeoTiff file is identified as: bandtype == ColorInterp.GCI_GrayIndex which makes GDAL think that the file is an image.

In fact, the file is an Int - type raster. 

If I remove the bandtype == ColorInterp.CGI_GrayIndex, then my raster is correctly displayed in the map.

However, I'm not quite whether removing the bandtype == ColorInterp.CGI_GrayIndex condition would cause errors when opening other GDAL images or rasters.

Another possible fix is to check the band.GetRasterColorInterpretation() method. 

Any suggestions?

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-02-05 at 18:31
I've fixed this issue for my raster by instructing GdalRasterProvider to open single-band grayscale GeoTiff files as rasters. For any other raster formats, bandtype==ColorInterp.CGI_GrayIndex will still be interpreted as image.

More unit tests for opening various types and sizes of GeoTiff rasters and images are required.

**[jlkittle](http://www.codeplex.com/site/users/view/jlkittle)** wrote 2011-06-16 at 02:56
Mass closing of fixed items.

** Closed by jlkittle 06/15/2011 3:56PM

**[jlkittle](http://www.codeplex.com/site/users/view/jlkittle)** wrote 2011-06-22 at 18:09
we have this issue with a NLCD2001 landcover raster file. it's bandtype is GCI_PaletteIndex.

the call to IsGeoTiffRaster returns false as only bandtype == ColorInterp.GCI_GrayIndex returns true.

**[vatavian](http://www.codeplex.com/site/users/view/vatavian)** wrote 2011-06-22 at 23:21
A proposed fix for this is pushed into Mercurial at rev 885:

In GdalRasterProvider.Open(string fileName)

remove the section of code testing bandtype and calling IsGeoTiffRaster.

This makes it always try GetBand for single-band GDAL files and if that succeeds, it gets opened as a raster. Since we are in GdalRasterProvider, I think we should go ahead and try to open it as a raster if it can be rather than guess that maybe someone really
 wanted an image and refuse to open it as a raster.

I do not think we have a complete plan for when to open as image vs. raster. In MW4 this is handled by a project-level flag rather than trying to determine automatically which files are intended as images vs. grids.

I agree that we need more unit tests that open various GeoTiff files.

**Comment by mogikanin** [comment]
Not reproduced.

**Comment by ykhaled** [comment]
I switched from VirtualBox to VMware and that seems to solve the issue for me.
