### ISSUE TITLE
Remove Map Frame context menu doesn't work

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#237]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/244)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-02-07 at 10:07
If I click on the 'Map Layers' item in the legend, there is a context menu 'Remove map frame'. If I click 'Remove map frame', nothing happens.

Either the 'remove map frame' should remove the 'Map Layers' item and all child layers from the map and legend,

or the 'Remove map frame' option should not be visible in the 'Map Layers' context menu.

**Comment by mogikanin** [comment]
'Remove map frame' option should not be visible.

**Comment by jany-tenaj** [comment]
When I started with DotSpatial I got the feeling that DotSpatial was build to use more than one map frame. Maybe that's where remove map frame comes from?

**Comment by mogikanin** [comment]
Yes, this is because potentially it is allowed to create tree structure with map frames.
