### ISSUE TITLE
SelectByAttributes - Unhandled Exception

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#253]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/260)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-03-03 at 01:46
Create a new FeatureSet (FeatureType.Point) and add it as a layer to the map.

In DemoMap main menu, go to Selection - Select By Attribute 

An unhandled exception is thrown in SQLQueryControl.cs : 

Unable to cast object of type 'System.Data.DataColumn' to type 'DotSpatial.Data.Field'.

This exception occurs for all types of shapefiles.

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-03-05 at 07:54
This issue only occurs when the FeatureSet is in-memory or when the Shapefiles are opened with OgrVectorProvider.

**[olivier57](http://www.codeplex.com/site/users/view/olivier57)** wrote 2011-03-05 at 11:44
I think that this is not the only problem with SelectByAttribute.

<a href="http://dotspatial.codeplex.com/discussions/247502" rel="nofollow">http://dotspatial.codeplex.com/discussions/247502</a>

**Comment by jany-tenaj** [comment]
@mogikanin Do you have any idea what function is meant by 

> In DemoMap main menu, go to Selection - Select By Attribute ?

I tried the Query from the Attribute table editor as well as the Find button in the toolbar in the main window on a temporary layer (create with shape editor) without causing an error. If one of those was meant I'd say the error no longer exists.

**Comment by mogikanin** [comment]
@jany-tenaj yes I think they meant selection inside Attribute Table Editor or inside outdated window [SelectByAttributes](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Symbology.Forms/SelectByAttributes.cs). Also I see that this SelectByAttributes not used anywhere and can be safely removed.

**Comment by mogikanin** [comment]
Ok, I've reused this SelectByAttributes window, now it's functionality available under Selection menu.

![image](https://cloud.githubusercontent.com/assets/840681/19431725/4451a7fc-9462-11e6-849e-fdb2e6d7dd19.png)

![image](https://cloud.githubusercontent.com/assets/840681/19431752/66be0bfa-9462-11e6-87cf-18155aa97863.png)
