### ISSUE TITLE
DotSpatial.Projections dll file is very big

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#27]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/31)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2010-07-21 at 06:03
The file DotSpatial.Projections.dll is very large (19 MB). I think the size of the dll file should be reduced. I think we need to find a better way how to embed the resources within the dll file so that it doesn't take so much disk space.

**[JohnDiss](http://www.codeplex.com/site/users/view/JohnDiss)** wrote 2010-07-23 at 00:19
I haven't had a chance to view the code, but assuming that the space is consumed by text lookup tables, these could be compressed before embedding using Deflate/Zip and using either the built in .NET classes for compression or a lib such as SharpZipLib

**[JohnDiss](http://www.codeplex.com/site/users/view/JohnDiss)** wrote 2010-07-23 at 00:21
^^ I meant decompressed using the built in compressed stream classes or SharpZipLib

**[Shade1974](http://www.codeplex.com/site/users/view/Shade1974)** wrote 2010-09-04 at 21:56
Definitely most of the space is occupied by text lookup tables. The actual projection code itself is negligible. Decompress of tables could add a performance hit, especially if the caller calls the public accessor over and over again for each point, rather
 than passing in an array, but the tables are only used in rare circumstances, so this is definitely worth a look. However I am also changing this to a "feature request" and will put bugs as higher priority than this.

**[robertson1](http://www.codeplex.com/site/users/view/robertson1)** wrote 2010-09-06 at 12:26
The largest of the embedded grid shift files is already binary (ntv2_0.GSB) and is 13.5 Mb on its own anyhow. I didnt need to use any of these grid shifts so just compliled without them which reduced the dll to about 1.8Mb without any ill effects. Poosiibly
 they could be packaged separately rather than as embedded resources?

**[mudnug](http://www.codeplex.com/site/users/view/mudnug)** wrote 2011-01-07 at 20:18
Would moving the nad and nad-dependent code to another assembly "DotSpatial.Projections.Nad" be satisfactory?

**[Shade1974](http://www.codeplex.com/site/users/view/Shade1974)** wrote 2011-01-07 at 21:02
In a way that would be ok, though it won't be as simple as picking out certain classes that use the tables versus classes that don't. Fundamentally everything boils down to a single Reproject.ReprojectPoints function. This may or may not invoke nad tables
 depending on whether or not the proejctions have matching datums, and whether or not a gridshift technique is used when referencing the two. I think the main case where this happens in the US is for NAD27. Nad83 to WGS84 shifts do not require the tables.

If we wanted to set it up in a different assembly it would probably have to work basically like a run-time discoverable plugin, and if the plug-in was missing then it would throw an exception, but only if a grid shift transform was attempted but the nad table
 was not found. One advantage of having the tables back outside of code would be that people could more easily add and remove the tables they need, and we could post them as a separate download and have much smaller release binaries. These nad tables are an
 order of magnitude larger than the memory required for the rest of the actual binaries themselves. But just keep in mind it would be nice if the mechanism that discovers the tables could be loaded programmatically. That way, if a third party developer wanted
 the tables to be embedded, rather than in a directory, they could embed the tables themselves and then load them programmatically. Anyway, that's just my suggestion, and maybe you have an even better idea. I think an ideal solution would allow the following:

1) Weekly posts of binaries could be hosted separately from whatever has the NAD tables, and that becomes a separate download (however it is organized.)

2) The functionality not requiring NAD tables would work regardless of whether the download takes place.

3) If an action that requries a grid-shift can't find the table, it reports this, and provides direct access to instructions to fix the problem. (perhaps even programmtically pulling the tables from the web automatically, something like a dialog that says:
 "This action require NAD shift tables. Do you wish to download the NAD tables now?" and if the answer is yes, then it creates the NAD directory and pulls the files from the internet.

But If you think of an even better solution, I'd love to hear it. The above is an ideal case and probably not a quick fix, so I might prioritize some other things before you tackle this creature.

Ted

**[the_roggy](http://www.codeplex.com/site/users/view/the_roggy)** wrote 2011-07-26 at 15:41
Would be a really good idea to implement one of the above solutions. We created a small tool based on dotspatial, but because of this file the download size of the tool is way to large to be normal... Putting the tables in a seperate dll, text file or
 zip file would be OK for us (and most people probably), as we don't need those projections...

**[mudnug](http://www.codeplex.com/site/users/view/mudnug)** wrote 2012-01-12 at 00:43
We may also need to ship a database file with this assembly.

**[mudnug](http://www.codeplex.com/site/users/view/mudnug)** wrote 2012-01-13 at 21:53
It appears that moving the gridshifting code to another assembly will cause breaking changes, so I'm reserving these changes for a future version.

**Comment by mogikanin** [comment]
I'm going to implement this enhancement. The idea is pack all heavy resources using deflate stream and unpack them one time on demand. Also I noticed that there are 2 files in resources which not needed at all there: DotSpatial.Projections\xml\gcs.csv and pcs.csv. Also I see that datums.xml re-readed everytime on ParseEsriString. This can be improved (read it also one time).

**Comment by mogikanin** [comment]
Now Projections has 10MB size. Closing issue for now.

**Comment by mkaring** [comment]
This is already a big step. I noticed that you implemented the compression with a additional tool that needs to be executed by hand every time those files are updated. I have some experience with modifying MSBuild (in a way Visual Studio understands) to add a custom build step that compresses the files during the compilation process (if required). This has the advantage that the compressed files don't need to be maintained in the repository and are created automatically when the project is build.

Also I'd suggest using the gzip stream instead of the plain deflate algorithm. Simply because it adds a checksum to ensure that the data is not corrupted during compression/decompression. The difference in size and cpu load between the two is barely measurable.

If there are no objections, I'd go ahead with the implementation and send a pull request as soon as I am done. Maybe I find something to get the size of this file further down. 10MB still seams large.

**Comment by mogikanin** [comment]
Sure Martin, go ahead. Implementing msbuild step is be better solution. Gzip will not solve size issue cardinally, it will be still about 10 mb because of 13mb ntv2_0.GSB file.

**Comment by mkaring** [comment]
The question is really of those national transformation files should even be published with DotSpatial. The files that are in there are only a very limited selection and will not be used by all users of the library. And everyone into the topic is able to fetch the files that are needed for each project.

I just had a look over the transformation files I have and if we put them in the DLL will be about 200MB.

**Comment by mogikanin** [comment]
Agree. We simply can exclude all of these nad files from assembly. And write instruction how to load them manually. Also better upload them to github wiki, no need to store them inside git repo.

**Comment by mogikanin** [comment]
In fact, nad tables lookup happens only in loop before this line: https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Projections/GridShift.cs#L96 
To avoid a lot of questions, why projection works wrong better to throw exception in case if gridshift not found (instead of  `Debug.WriteLine(...)` few lines below).

**Comment by mkaring** [comment]
Sounds good. A exception really sounds better. It gives a better idea what is happening in case the transformation fails.
A few information in the wiki on how to load and where to get the files from sounds okay to me too. I don't think those files need to be hosted here. There are a lot and every now and then they are updated.

**Comment by mogikanin** [comment]
Done. Now DotSpatial.Projections has 1.5MB size. See wiki for [details](https://github.com/DotSpatial/DotSpatial/wiki/Grid-Shifts).

**Comment by cwgrc2** [comment]
Late to the game here.  I am trying to use DotSpatial for conversion from WGS84 to StatePlaneNAD27(Wyoming East Central) and I am getting NaNs.  Then if I try and add: 

GridShift.InitializeExternalGrids("GeogTransformGrids", true);

I get an error that it can't find the files.  What do you suggest?  It is not clear in 2019 what the solution from above is. 

Thank you.

**Comment by cwgrc2** [comment]
The actual error to the console is:

An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in System.IO.FileSystem.dll
Could not find a part of the path 'C:\development\gems\Backend1\CRSProjections\bin\Debug\netcoreapp3.0\GeogTransformGrids'.

Thanks
