### ISSUE TITLE
Point symbolizer cutting off corners

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#276]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/283)**

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2011-04-18 at 21:55
When adding a point layer with the following code the upper left corner of the image is clipped.

if (File.Exists(fileName))

<pre><code>         {
             impl = new MapPointLayer(FeatureSet.OpenFile(fileName));
             impl.Reproject(KnownCoordinateSystems.Projected.World.WebMercator);
             impl.LegendText = config.AppSettings.Settings["farmPointsLayerName"].Value;
             impl.Symbolizer.SetFillColor(Color.Transparent);
             impl.Symbolizer.SetOutline(Color.Firebrick,2.0);
             impl.Symbolizer.SetSize(new Size2D(5.0,5.0));
         }
</code></pre>
You can go into the symbolizer dialog and make it bigger, change it to a cirlce (it's a square by default) and it is still broke. If you change the angle it seems to fix the problem.

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2011-04-18 at 22:00
I changed my code around to use an explicit iPointSymbolizer thinking that I might be getting some weird defaults, but it does the same thing:

IPointSymbolizer ips = new PointSymbolizer(Color.ForestGreen,PointShape.Ellipse,10);

<pre><code>             ips.SetOutline(Color.Black,1);
             impl.Symbolizer = ips;
</code></pre>
Attached is a screen shot zoomed in a bit.

**Comment by jany-tenaj** [comment]
already fixed
