### ISSUE TITLE
Selection Options

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#283]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/290)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-05-10 at 23:38
The selection tool should include the following capabilities (similar to ArcGIS):

-set selectable layers/ make only selectable layer 

-add to/ replace/ remove from current selection (from Home tab, not just from attribute table)

-clear selected features (from Home tab, not just from attribute table) 

-select by attributes/ select by location. 

(<a href="http://hydrodesktop.codeplex.com/workitem/7370" rel="nofollow">http://hydrodesktop.codeplex.com/workitem/7370</a>)

**Comment by jany-tenaj** [comment]
1. was just fixed

2. Can be done by using either shift (add), nothing (replace) or ctrl (remove) key while using the select tool. 
@mogikanin Do we need extra tool buttons for this?

3. already works

4. Select by Attributes can be done via Find tool
@mogikanin Do you know what is meant by select by location?

**Comment by mogikanin** [comment]
2. No need
4. Probably it means: give me a way to select features which located inside another feature. E.g. select all counties inside given state.

**Comment by jany-tenaj** [comment]
Select by location sounds like a not really simple feature. Not sure we need it but if we do I'd like to create a new issue for this and close this one.

**Comment by mogikanin** [comment]
OK
