### ISSUE TITLE
Cannot reproject Rasters or images

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#304]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/311)**

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2011-06-16 at 03:24
When told to reproject a Raster or image change is made in file coordinates. This happens when loading GeoTIFFs created via GDAL. IT also happens to BGD files.

**Comment by mogikanin** [comment]
Not reproduced.

**Comment by sindizzy** [comment]
Load any raster in WGS84 and then change map projection. Rasters are not reprojected.
