### ISSUE TITLE
Label Orientation/Rotation

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#308]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/315)**

**[ce_web](http://www.codeplex.com/site/users/view/ce_web)** wrote 2011-06-24 at 14:17
Hi 

The possibility to rotate labels, like in MapWindow is missing/not working check out
<a href="http://dotspatial.codeplex.com/discussions/257833" rel="nofollow">http://dotspatial.codeplex.com/discussions/257833</a>

Could this be or is it planned in the near future?

**Comment by jany-tenaj** [comment]
@mogikanin If I understand this problem correctly it was solved with changeset [eaabcebe71f4d2b3a89bd29b83d7d17c7a5e7217](http://dotspatial.codeplex.com/SourceControl/changeset/eaabcebe71f4d2b3a89bd29b83d7d17c7a5e7217)?

**Comment by mogikanin** [comment]
Yes, it is.
