### ISSUE TITLE
Saving a project doesn't preserve map projection

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#315]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/322)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-07-25 at 20:14
Saving a project and re-opening it doesn't preserve the projection of the map and layer if the projection of the layer is different from the projection of the source shapefile.

Steps to reproduce:

<ol>
<li>Open DemoMap </li><li>Add the U.S States layer (original coord. system - WGS84 Lat/Lon) </li><li>Right click on map frame, choose Projection.. and change projection to Projected-World-WebMercator
</li><li>The layer looks correctly reprojected </li><li>Save Project as "myProject.dspx" </li><li>Close DemoMap </li><li>Opening myProject.dspx in a text editor shows an element <member name="ProjectionEsriString".. with correct parameters for WebMercator
</li><li>Open DemoMap and open project myProject.dspx </li><li>No layers are visible in the map. When I choose "Zoom to layer" the layer appears to be drawn in the original WGS84 coord.sys. This is incorrect. It should be displayed in WebMercator. Also, when I go to MapFrame - Projection.. context menu, it
 incorrectly shows the WGS84 Lat/Long projection info. </li></ol>

**Comment by jany-tenaj** [comment]
This works.
