### ISSUE TITLE
ArgumentNullException while trying to use FeatureSet.SaveAs

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#349]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/356)**

**[Galod](http://www.codeplex.com/site/users/view/Galod)** wrote 2011-10-11 at 17:54
Exception has been thrown by the target of an invocation. ---> 

System.ArgumentNullException: 

Value cannot be null. 

Parameter name: toPath 

at DotSpatial.Data.FeatureSet.RelativePathTo(String toPath) in C:\Projects\ResGis\dotspatial\DotSpatial.Data\FeatureSet.cs:line 1692

at DotSpatial.Data.FeatureSet.get_FilePath() in C:\Projects\ResGis\dotspatial\DotSpatial.Data\FeatureSet.cs:line 1656

Exception has been thrown while trying to save manually added features. Error may be repeated, if you using ShapeEditor plug-in with DemoMap.

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-10-20 at 07:21
I'm having the same issue. 

In the code this occurs when calling SerializationManager.SaveProject if the map contains some in-memory featuresets (with Filename = NULL) which is also the case of featuresets newly created by the Shapefile editor.

**Comment by jany-tenaj** [comment]
problem couldn't be recreated in 95b7017190d8fe14644f2ce108b530ef5207cf18
