### ISSUE TITLE
Krovak Projection has Error

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#369]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/377)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-11-05 at 23:58
There is a serious error in Krovak (S-JTSK) projection. Results are completely incorrect.

double[] myOut = new double[2];

<pre><code>       myOut[0] = 12.8069888666667;
       myOut[1] = 49.4522626972222;
       double[] myZ = new double[1];
       myZ[0] = 0;
       DotSpatial.Projections.ProjectionInfo source = KnownCoordinateSystems.Geographic.World.WGS1984;
       string projJTSK2 = "+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +pm=greenwich +units=m +no_defs";
       DotSpatial.Projections.ProjectionInfo myJTSKPI = DotSpatial.Projections.ProjectionInfo.FromProj4String(projJTSK2);
       DotSpatial.Projections.Reproject.ReprojectPoints(myOut, myZ, source, myJTSKPI, 0, myZ.Length);

       //expected result is Y (-868208.52), X (-1095793.96)
       //result computed by DotSpatial is y (475022.2)   X (376370.6)
</code></pre>
When examining the source code, there are some errors in the code of Krovak.cs. 

First error identified in the OnInit() method. 

K0 = projInfo.CentralMeridian != null ? projInfo.Lam0 : 0.9999; 

This code is clearly incorrect! K0 is a scale factor and so the correct code should be:

K0 = projInfo.ScaleFactor != 1 ? projInfo.ScaleFactor : 0.9999; 

I have created a unit test KrovakTest.cs to test this bug.

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-11-08 at 20:48
The unit test KrovakTest now passes,

still need to do more testing using official benchmark points and reading / writing the .prj files (ToEsriString, FromEsriString) and writing the Proj4 string.

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-12-16 at 10:11
I have fixed this bug also with regards to reading prj files and added a unit test for reading the ESRI string and re-projecting between WGS1984 and S-JTSK Krovak East North. The fix is in changeset 224fe414e979.

**Comment by jany-tenaj** [comment]
Fixed
