### ISSUE TITLE
Add tool for Unselecting Features

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#382]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/390)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2011-11-30 at 07:57
(this item was reported by the user group when testing MapWindow6 / HydroDesktop)

There are multiple ways of selecting features in the map: 

Using the select tool in the home tab, right-clicking on category and choosing Select features, opening the attribute table and selecting rows.

However, there is no easy way to unselect features. At least the following un-selection options should be added:

<ol>
<li>Change the 'select features' in right-click on category to toggle to allow deselecting of the category
</li><li>Add a 'Selection -- Unselect all option to the layer right-click context menu
</li><li>Add a 'Deselect' button to the home tab next to the Select button. This should only be enabled when some features are selected in the map
</li><li>Add an indication of how many features are selected to the status bar. If some features are selected, then the status bar message should show 'N features selected'.
</li><li>Press the Ctrl key while the MapFunction.Select is active </li></ol>

**Comment by jany-tenaj** [comment]
This already works.
