### ISSUE TITLE
FeatureSet.Find throws KeyNotFoundException

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#393]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/401)**

**[jtrobbins](http://www.codeplex.com/site/users/view/jtrobbins)** wrote 2011-12-14 at 19:52
When calling this with a valid query it throws a KeyNotFoundException. 

If I look using the debugger at FeatureLayer.DataSet.DataTable it has the required columns.

If I trace into the Find function _dataTable has not columns. 

Chanding the Find method to use DataTable instead works fine.

<pre><code>    /// <inheritdoc/>
    public List<int> Find(string filterExpression)
    {
        DataRow[] hits = DataTable.Select(filterExpression);
        return hits.Select(dr => DataTable.Rows.IndexOf(dr)).ToList();
    }
</code></pre>

**Comment by jany-tenaj** [comment]
find method no longer exists
