### ISSUE TITLE
DotSpatial <-> GeoAPI converter

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#404]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/412)**

**[FObermaier](http://www.codeplex.com/site/users/view/FObermaier)** wrote 2012-01-19 at 01:29
The code in DotSpatial.Topology does not resemble the current version of the archetype JTS. If I'm right, it resembles JTS 1.7 plus some custom additions.

NetTopologySuite, from which DotSpatial.Topology was originlly derived, has cought up in the last time, and will release version 1.12 in a little while.

If you care for e.g.

<ul>
<li>Delauney Triangulation </li><li>Voronoi Diagrams </li><li>PreparedGeometries </li><li>overhauled Buffer operation </li><li>robustness and performance improvements </li><li>...

</li></ul>
I've written conversion code between the two libraries for geometry and DotSpatial's own Shape.

You find the code along with test case and GeoAPI/NTS binaries in the attached file.

Enjoy

**[D_Guidi](http://www.codeplex.com/site/users/view/D_Guidi)** wrote 2012-01-19 at 12:08
I didn't see the code in the zip, looks there are only binaries

**[FObermaier](http://www.codeplex.com/site/users/view/FObermaier)** wrote 2012-01-19 at 12:56
Oops

**Comment by mogikanin** [comment]
@jany-tenaj : I guess this will be not-actual after merging nts-integration branch?

**Comment by jany-tenaj** [comment]
Yes this will no longer be an issue.
