### ISSUE TITLE
Improve Usability of the Identifier Tool

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#430]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/22180)**

**[jirikadlec2](http://www.codeplex.com/site/users/view/jirikadlec2)** wrote 2012-02-08 at 03:42
When I was testing the identifier tool (Map tool - Identify in MenuBar) I found several issues that make it unintuitive and difficult to use:

<ul>
<li>I don't see the point where I clicked in the map </li><li>The identified shape is not highlighted in the map </li><li>The order of layers in the identifier is different from the order of layers in the map legend
</li><li>When I activate the indentifier for the first time, it doesn't show the attributes of the shape in the currently selected map layer. I have to select the layer again in the Identify layer list to see the expected information
</li><li>There is no link between Identify and Select. One important usage of Identify is to interactively explore the attributes of the shapes, and when I find the shape I'm interested in, select it for further analysis. Therefore I'd like to have a "Select
 this shape" button in the identifier form to make the identified shape selected if required.

 

I have summarized my testing and expected behavior in the attached report. See also HydroDesktop work item 8397 (<a href="http://hydrodesktop.codeplex.com/workitem/8397" rel="nofollow">http://hydrodesktop.codeplex.com/workitem/8397</a>)
</li></ul>

**Comment by jany-tenaj** [comment]
dup #418
