### ISSUE TITLE
WKBWriter adds 4 null bytes?

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#475]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/22468)**

**[illumenum](http://www.codeplex.com/site/users/view/illumenum)** wrote 2012-04-09 at 18:37
Using the following code with polygon and multipolygons, I'm seeing an extra 4 zero'ed bytes at the end of any WKB output. PostGIS doesn't care about them, but SQL Server sees this as invalid WKB. EG:

Yeilds:

0x010300000001000000070000004...33BCC4B4000000000

Should yeild:

0x010300000001000000070000004...33BCC4B40

<pre><code>
Shapefile shapefile = Shapefile.OpenFile(tempShpPath);

foreach (var feature in shapefile.Features)
{
byte[] wkb = feature.BasicGeometry.ToBinary();
Array.Resize(ref wkb, wkb.Length - 4); //chop off the weird last 4 bytes
//do something with the wkb
}</code></pre>

**[mudnug](http://www.codeplex.com/site/users/view/mudnug)** wrote 2012-04-10 at 22:01
It looks like that code was take from Net Topology Suite. Perhaps they have already posted an update.

**Comment by jany-tenaj** [comment]
@mogikanin Do you have any idea how to test this? We don't have the polygon that was used to create the binary shown above.

**Comment by jany-tenaj** [comment]
Just had an idea. I ran the following code in DS 1.9 as well as in DS 2.0.
```
        [Test]
        public void Test()
        {
            List<Coordinate> coords = new List<Coordinate>
            {
                new Coordinate(-84.6976494321476000, 41.7477691708729000),
                new Coordinate(-84.6402221482214000, 41.7477691708729000),
                new Coordinate(-84.6402221482214000, 41.6997514050474000),
                new Coordinate(-84.6974494321476000, 41.6997514050474000),
                new Coordinate(-84.6974494321476000, 41.6519336392220000),
                new Coordinate(-84.7548767160738000, 41.6519336392220000),
                new Coordinate(-84.7548767160738000, 41.6999514050475000),
                new Coordinate(-84.6976494321476000, 41.6999514050475000),
                new Coordinate(-84.6976494321476000, 41.7477691708729000),
            };
            Polygon p = new Polygon(new LinearRing(coords.ToArray()));
            var bin = p.ToBinary();
        }
```
In DS 2.0 the resulting byte array has a length of 157 while in DS 1.9 it has a length of 161 with the last 4 being 0.

I think we could say the issue is resolved?
I also think #499 should be resolved, too, as there it is also ToBinary that causes the problem?

**Comment by mogikanin** [comment]
@jany-tenaj yes, good test. Only add Assert() to check last 4 bytes, and commit it into repo. And then we can close this and #499 as well.

**Comment by jany-tenaj** [comment]
Any idea where to put this? This is essentially a Topology / NTS test and we no longer have Topology tests.

**Comment by mogikanin** [comment]
Inside DotSpatial.Data.Tests
