### ISSUE TITLE
SqlServer raise WKB is not valid format.

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#499]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/22868)**

**[mese79](http://www.codeplex.com/site/users/view/mese79)** wrote 2012-06-11 at 02:05
Hi

When i tried to create a new sqlserver DbGeometry from multipolygon IFeature WKB, i'v got error like 'WKB is not valid format', but WKT works with no error for the same IFeature.

 

//feature type is polygon and geometry type is multipolygon.

var geom = DbGeometry.FromBinary(ifeature.BasicGeometry.toBinary(), srid); //raises error

var geom = DbGeometry.FromText(ifeature.BasicGeometry.toString(), srid); //works

**[mudnug](http://www.codeplex.com/site/users/view/mudnug)** wrote 2012-06-12 at 20:23
Would you like to provide the WKT for this feature?

**[jocull](http://www.codeplex.com/site/users/view/jocull)** wrote 2015-04-15 at 17:25
This is happening to me as well. Here's the WKT (UTM)

**Comment by jany-tenaj** [comment]
@mogikanin Do you know how to test this? Seems we'd need a sqlserver DBGeometry object to test if the results can be read.

**Comment by jany-tenaj** [comment]
Should be resolved as it seems to be the same issue as #475.
