### ISSUE TITLE
Problem displaying world country layer in state plane coordinate system

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#501]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/22893)**

**[liquncao](http://www.codeplex.com/site/users/view/liquncao)** wrote 2012-06-14 at 21:58
If a world country polygon shapefile contains Antarctica region and the map projection is set to state plan coordinate system California zone 5, the map display becomes very strange. The ocean becomes filled, and the countries become holes. This may be
 caused by bad x, y in Antarctica area. It might be helpful is DotSpatial could detect bad x, y coordintes due to map projection and filter out from drawing on screen or being selected.

**[liquncao](http://www.codeplex.com/site/users/view/liquncao)** wrote 2012-06-14 at 22:01
Thanks.

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-03-24 at 13:04
Hi, can you attach sample shapefile to reproduce this issue?

**Comment by jany-tenaj** [comment]
@mogikanin Are we able to find this error without the sample shapefile you ordered or can we close this because the user didn't react?

**Comment by mogikanin** [comment]
Lets close it.
