### ISSUE TITLE
Problem with LAEA projection

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#568]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/23987)**

**[Yvan_B](http://www.codeplex.com/site/users/view/Yvan_B)** wrote 2013-02-24 at 23:56
Hello,

I'm new to Dot Spatial and really enthusiast to play with this great tool.

I am trying to convert lat/lng values to ETRS LAEA Europe coordinate system (EPSG:3035) but I always get NAN values (Not A Numeric). I think that this closed issue is probably the same:
<a href="http://dotspatial.codeplex.com/workitem/22212" rel="nofollow">http://dotspatial.codeplex.com/workitem/22212</a>

here is my code (VB.NET) :

<pre><code>        Dim xy(1) As Double
        xy(0) = 5
        xy(1) = 50
        Dim z(0) As Double
        z(0) = 1
        Dim pStart As ProjectionInfo = KnownCoordinateSystems.Geographic.World.WGS1984
        Dim pEnd As ProjectionInfo = ProjectionInfo.FromProj4String("+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
        Try
            Reproject.ReprojectPoints(xy, z, pStart, pEnd, 0, 1)
        Catch ex As Exception

        End Try
        MsgBox("The points have been reporjected." & vbCrLf & xy(0) & "," & xy(1))
</code></pre>
The code works well with other coordinate systems. It doesn't work with KnownCoordinateSystems.Projected.Europe.ETRS1989LAEA nor if I use the definition found in AuthorityCodeToProj4.txt (line 1006)

The Proj4 definition I use in the code is correct (verified in the epsg file of PROJ4).

Any idea? 

Yvan

**[IvanD79](http://www.codeplex.com/site/users/view/IvanD79)** wrote 2013-03-05 at 18:47
Same problem trying to convert from LAEA (3035) to WGS84 (4326), <strong>it's a real BIG issue...</strong>

For coordinates like, for example, 4175490.5731252655 - 1997066.9173578955 I receive NaN - NaN...

<code>ProjectionInfo pStart = ProjectionInfo.FromEpsgCode(3035);ProjectionInfo pEnd = KnownCoordinateSystems.Geographic.World.WGS1984;

SqlGeometry sqlPoint = sqlRing.STPointN(1);double[] xy = new double[2];xy[0] = sqlPoint.STX.Value;xy[1] = sqlPoint.STY.Value;Reproject.ReprojectPoints(xy, null, pStart, pEnd, 0, 1);</code>

**[tmanthey](http://www.codeplex.com/site/users/view/tmanthey)** wrote 2013-04-27 at 16:26
I can confirm this issue

**[tmanthey](http://www.codeplex.com/site/users/view/tmanthey)** wrote 2013-04-27 at 16:41
Working workaround is to use the .Net Wrapper for the native dll. Some good instructions are
<a href="http://www.spatialmarkets.com/blog/2012/8/2/using-proj4-in-net.html" rel="nofollow">
here</a>

**[Yvan_B](http://www.codeplex.com/site/users/view/Yvan_B)** wrote 2013-04-30 at 22:33
Thanks for the last suggestion. I came already to the same conclusion about .Net Wrapper (and it works)

Yvan

**Comment by brightbulbnz** [comment]
The workaround link no longer works unfortunately. Could anyone tell me more about the workaround?
