### ISSUE TITLE
no outgoing dirEdge found

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#602]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/24391)**

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2013-06-12 at 23:58
Using Version 1.4 of DS.

At times when I do an intersection with this call:

IFeatureSet secondClip = ifsIncidentCatchments.Intersection(siteDesignArea, FieldJoinType.All, null);

I get this error:

no outgoing dirEdge found [DotSpatial.Topology.coordinate)

Attached are the two files that show the error.

catchment.shp=ifsIncidentCatchments

siteDesignArea.shp=SiteDesignArea

One way to get around this is to slightly buffer the calling FeatureSet (ifsIncidentCatchments) by some random tiny amount and re-doing the intersection.

**[P_h_i_l](http://www.codeplex.com/site/users/view/P_h_i_l)** wrote 2013-06-13 at 04:38
I can confirm the occasional "no outgoing dirEdge found" exception, as well as occasional "Side location conflict at [DotSpatial.Topology.Coordinates]" exception, both with Intersection.

Note that Intersection is broken for FieldJoinType.ForeignOnly -- see source code patches for patched FeatureSetExt.cs. I believe the FieldJoinType.All code is okay, though, if you can live with Intersection putting fields from both feature sets into the result
 feature set. 

Not sure that anyone's home here - your best bet is probably to dig into the Topology assembly's code and try to fix this yourself.

**[FObermaier](http://www.codeplex.com/site/users/view/FObermaier)** wrote 2013-06-13 at 09:42
For NetTopologySuite, <code>geom.Buffer(0);</code> is a way to solve issues like this.

**[P_h_i_l](http://www.codeplex.com/site/users/view/P_h_i_l)** wrote 2013-06-19 at 00:13
<blockquote>
<blockquote>For NetTopologySuite, geom.Buffer(0); is a way to solve issues like this.

</blockquote>
</blockquote>
Please explain. 

Thanks. 

-Phil

**[FObermaier](http://www.codeplex.com/site/users/view/FObermaier)** wrote 2013-06-19 at 11:22
Some of your catchment shapes are made up of self intersecting linear rings. This is topologically invalid and leads to the mentioned error. You can verify this easily with QGIS geometry validator tool..

If you perform a buffer operation with a buffer value of 0, the polygons with self intersecting linear rings will be turned into a MultiPolygons which have two or more polygons which are made up of linear rings that touch at the intersecting location.

You said, buffer with some tiny value makes your operation pass, I say, buffer with 0 is better because it does not modify your coordinates and leads to the same result (pass the operation).

**[aparks](http://www.codeplex.com/site/users/view/aparks)** wrote 2013-06-19 at 16:36
Does DS have geometry validator tool?

**[Koval_Alex](http://www.codeplex.com/site/users/view/Koval_Alex)** wrote 2015-05-28 at 17:25
Hello all..Two years left, but this problem still remains.. Who knows how to fix this error, if geom.buffer(0) is not work?My code, which raised this error:IFeature feat1=somefeature.buffer(0);IFeature feat2=anotherfeature.buffer(0);feat1=feat1.union(feat2);Thanks

**[mbayles](http://www.codeplex.com/site/users/view/mbayles)** wrote 2015-06-09 at 18:22
Are you saying the geom.buffer does not work for you?

**Comment by jany-tenaj** [comment]
This runs without error in DS 2.0 with the changed GeoAPI.

I used the two attached shapefiles and the following code to check this problem:
```
IFeatureSet ifsIncidentCatchments = FeatureSet.Open(@"d:\noDirEdgeFiles\catchment.shp");
IFeatureSet siteDesignArea = FeatureSet.Open(@"d:\noDirEdgeFiles\siteDesignArea.shp");
IFeatureSet secondClip = ifsIncidentCatchments.Intersection(siteDesignArea, FieldJoinType.All, null);
```

**Comment by mogikanin** [comment]
@jany-tenaj Please create & commit unit test from code above. Last line should be `Assert.DoesNotThrow(...)`, I guess.
