### ISSUE TITLE
FeatureLayer.ClearSelection / SelectAll only work when FeatureLayer is selected in Legend

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#659]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25331)**

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-03-28 at 14:06
I have tried to use Dotspatial.Symbology.FeatureLayer.ClearSelection and Dotspatial.Symbology.FeatureLayer.SelectAll in code.

I found out that they work, if I have selected the FeatureLayer, from which I want to clear the selection / select all features, in the legend. But they don't work if I have selected another layer in the legend.

I don't see a reason why the layer should be selected in legend if I want to select its features in code.

By looking at the sourcecode of Dotspatial.Symbology.FeatureLayer I think the functions InvertSelection, Select and Unselect might have the same problem.

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-05-06 at 10:32
I think you can set in code IsSelected=true before calling these methods. And then select back another layer.

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-05-06 at 17:36
May be. But I don't see a reason why one should have to do that. If I use a function that belongs to a certain layer, I expect it to always work with that layer not only if that layer is selected in legend. I mean wouldn't you expect featureLayer.selectAll
 to selectAll features, if there is nowhere written, that it selects the features only if the layer is selected in legend?

If it has to be selected in legend I would name the function accordingly or add an according function-description. Else it makes no sense and one has to look at the code to know why the code is not working as expected.

I have no idea why the code is written that way. In my own version I simply removed the part that checked for the legend selection and it worked.

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-05-06 at 18:08
Agreed. I'll add additional functions documentation in which will be documented that functions works only when layer selected.

**[ModernaTider](http://www.codeplex.com/site/users/view/ModernaTider)** wrote 2015-02-23 at 10:05
For me this does not work, selected features remain selected: 

private void unselectAll() { foreach (var layer in _map1.Layers) { layer.IsSelected = true; layer.ClearSelection(); layer.IsSelected = false; } _map1.Refresh(); }

**Comment by jany-tenaj** [comment]
FeatureLayers ClearSelection, Select, InvertSelection, Unselect, SelectAll and UnSelectAll now work based on SelectionEnabled properties of FeatureLayer and its categories.
