### ISSUE TITLE
How to show linecap at middle of Line

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#662]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25384)**

**[sprashant80](http://www.codeplex.com/site/users/view/sprashant80)** wrote 2014-04-11 at 16:40
In my current project, I would like to show case line direction at the middle of line feature.

Please suggest a way to represent it. This is a really crucial issue for me.

Thanks in advance.

**[sprashant80](http://www.codeplex.com/site/users/view/sprashant80)** wrote 2014-04-11 at 16:41
In my current project, I would like to show case line direction at the middle of line feature.

Please suggest a way to represent it. This is a really crucial issue for me. 

Thanks in advance.

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-08-21 at 17:36
What does at the middle of the line mean? Do you have a thick line and want to show a small arrow in the middle like
<a href="http://topmms.ru/wp-content/uploads/2013/07/yandex.map-android.jpg" rel="nofollow">
here</a> or do you want to show the direction in the middle between the startpoint and the endpoint of a line?

**[sprashant80](http://www.codeplex.com/site/users/view/sprashant80)** wrote 2014-08-22 at 14:48
Thanks for your reply. 

Yes. I would like to display the arrow as shown in your shared image. Only change is, arrow head should be at middle of line. In your case, it is at the end of line / start of line.

It will great if you can share the code to display the line with arrow head at middle of line.

Thanks & Regards,Prashant

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-12-10 at 20:56
Are we talking about lines that have only a start and and endpoint or are we talking about lines that have more points in between?

If we are talking about lines with more than one part should the arrow appear only once or in the middle of each part? If it should appear only once then where exactly?

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2015-02-05 at 14:08
Resolved with changeset 75510: - Added posibility to show a single linecap at a percentual offset from the startpoint

<ul>
<li>Spread the DecorationPoints evenly on lines with more than one part </li><li>Show DecorationPoints with offset always on the same side of the line as shown in the preview of the LineSymbol window
</li><li>Corrected the direction of DecorationPoints on vertical lines </li><li>Flip first DecorationPoint back to initial position if FlipFirst and FlipAll are applied together
</li></ul>

**Comment by amitnkukanur** [comment]
I would like to re-open this. Please suggest how to do this.

**Comment by amitnkukanur** [comment]
@mogikanin, can you please suggest how should i achieve this. When line selected it should display direction of flow
