### ISSUE TITLE
Changing the design of UndefinedProjectionDialog

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#676]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25497)**

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-05-23 at 18:40
Hi,

I had some trouble with the design of the UndefinedProjectionDialog. In German the first line was running out of the window and I wanted to add the name of the layer, that gets changed. Furthermore there was much unused space between the radiobuttons and it
 looked kind of confusing.

So I went and had a look at it and made it change its size dynamically.

Because I don't know whether you would like to add this change I only did German (which I need) and the default language.

I removed the German DialogResource and put the needed strings in UndefinedProjectionStrings.resx.

If you decide to add this change this would have to be done for the other languages to.

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-06-13 at 12:28
Hi, try changeset 74557. I've fixed issue with first line in German, and also added LayerName to the form Caption. The idea with dynamically resizing is not very good, because currently we can specify controls location, size, etc for every languge separaretly
 and it is a very comfortably.

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-06-13 at 13:17
Hi, 

would have been nice to have the layername inside the first line, because that's where I'd look, but I understand why you put it in the Caption.

I figured you'd say something like that about the dynamic resizing. But I can't say that I find it really comfortable to have to resize all controls in such a small dialog for each language separately and have them look confusing. You have to resize them whenever
 you change some text and if you forget it's hard to read for the enduser.When I made the change I though one could use the dynamic approach for the languages which don't have to have specific locations and so on and do the other languages like before. You'd
 just have to change the autosizing elements in the corresponding designer.

**Comment by mogikanin** [comment]
@jany-tenaj I guess this issue already non-actual?

**Comment by jany-tenaj** [comment]
@mogikanin I still think the forms design is horrible. But I went and changed it in my own code, so if we don't want to change the design in DS I think this issue could be closed.
