### ISSUE TITLE
Open ShapefIle with "where" expression.

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#680]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25512)**

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-05-29 at 11:52
Something like this:

Shapefile.Open(fileName, "[Area]>100").

It will allow to load a piece of shapefile without loading entire file.

**Comment by mkaring** [comment]
You already can load shape data without fetching the entire file at once. Granted it is a little more text to write to get this working, but it basically enables you to iterate over the entire file without loading it into the memory all at once. This way you can easily apply a filter and only use the shape entries required.

Aside from convenience is this function expected to do anything else?

**Comment by mogikanin** [comment]
@mkaring can you show example how to do this? Really I've created this task when there is no such possibility. Of course, if already there is such way, this task has no sense.

**Comment by mkaring** [comment]
It is pretty simple. 

Basically you use a `DotSpatial.Data.ShapeReader` along with the `DotSpatial.Data.AttributeTable` to lazily load the shape file.

The shape reader allows you to read pages of shapes from a shape file and the attribute table allows you to fetch pages of attributes. You only need to combine both.

So the code is something like this:
```C#
ShapeReader reader = new ShapeReader(shapeSource);
AttributeTable attributes = new AttributeTable(shapeFileName);
foreach (Dictionary<Integer, Shape> page in reader)
{
    Integer start = page.Key.Min()
    Integer end = page.Key.Max()
    DataTable pageAttributes = attributes.SupplyPageOfData(pageStart, pageEnd - pageStart + 1)
    foreach (KeyValuePair<Integer, Shape> indexAndShape in page)
    {
        Shape shape = indexAndShape.Value
        shape.Attributes = attributes.Rows(indexAndShape.Key - pageStart).ItemArray
        // At this point the shape object is in the same format as you'd expect it.
    }
}
```

The massive advantage is that once you switch the page, all the "old" shape data is garbage collected. Some goes for the attributes.

I am using this approach with massive shape files (>1GB) and it works just fine.

**Comment by mogikanin** [comment]
Even more, in ShapefileFeatureSource there is [Select()](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Data/ShapefileFeatureSource.cs#L320) method which takes filterExpression as input.

**Comment by mkaring** [comment]
Never used that. I can't tell you what that does or how well it works. The code I am using uses the `ShapefileShapeSource` and this one can't filter anything.

I think the `ShapefileFeatureSource` already combines shapes and attributes. But I'd have to look at the implementation to know if this works with large shape files.

**Comment by mogikanin** [comment]
Ok. Anyway I'm closing this as not actual.
