### ISSUE TITLE
Some Changes in ShapeEditor

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#684]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25522)**

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-06-03 at 17:03
Hi,

I had some trouble with the ShapeEditor so I made the following changes:

<ul>
<li>In FeatureTypeDialog I added the possibility to save the created shapefile to harddisk by selecting a filename.
</li><li>I translated the FeatureTypeDialog to German. </li><li>Because the shapes that were created in AddShapeFunction were never saved, I added a line that saves the featureset if it has a filename and a new shape is added.

</li></ul>
What I do not understand is the fact that you can add shapes to a layer that was not saved to harddisk. But if you save the dspx and reload it again, adding features to the same temporary layer doesn't work anymore. Furthermore all shapes that were added before
 saving the dspx are gone, but the layer gets loaded on opening the dspx. Is that the way temporary layers are supposed to work?

jany_

**[mogikanin](http://www.codeplex.com/site/users/view/mogikanin)** wrote 2014-06-05 at 13:58
It looks like your changes is just workaround for the SerializationManager issue which not saves layers when saving project. Imho, all layers with not null Filename should be saved into directory with .dspx file.And probably this behavior should be configurable,
 e.g.<em> DoNothing - current behavior :)</em> SaveLayersToProjectDir - call for every layer SaveAs(ProjectDir). This will copy all layers into one project dir. This should be a default behavior.* SaveLayersWithTheirsFilenames - save all layers to theirs original
 locations, just simply call for every layer.Save()

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-06-05 at 15:31
Hey mogikanin, 

if you add a layer using the ShapeEditor the filename is never set. So following your logic it should never be saved. But it is still there after reloading the dspx.I just added the possibility to set the filename to where I want to save the layer (not nessessarily
 the folder with the dspx). 

When saving the added features I could agree with you. That part I just added because I didn't know according to which philosophy layerchanges get saved and I wanted to save those features. (In my own code everything gets saved as soon as it is created, so
 that nothing can go missing.)

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2015-03-26 at 14:11
Associated with changeset 75641: - Added possibility to save created shapefile to harddisk by selecting a filename

<ul>
<li>Translated FeatureTypeDialog to German </li></ul>

**Comment by mogikanin** [comment]
@jany-tenaj can we close it? looks like you pushed some changes on it

**Comment by jany-tenaj** [comment]
The only thing still open is the saving of the features that were added by AddShapeFunction.
I know there were some people asking for this as well.
I went and build my own ShapeEditor-Toolbar with all the other things that start popping up now like undo.
So I'd say, I don't care anymore whether we add the saving but for others it might be nice.

**Comment by mogikanin** [comment]
Ok, then I'm closing this. If someone wants this missing feature, we'll open separate feature request.
