### ISSUE TITLE
How to convert polygon into raster

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#710]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25725)**

**[frozencookie](http://www.codeplex.com/site/users/view/frozencookie)** wrote 2014-09-15 at 10:34
Hi, I want to convert a shape file with many polygons into a raster file. And the pixel value of the new raster would be the polygon index. I will be very plateful if anyone could answer me with code example.

Thx!

**Comment by oscarafone77** [comment]
Here a sample code:

`Dim rastout as Iraster= DotSpatial.Analysis.VectorToRaster.ToRaster(yourFeatureSet, cellsize, fieldName, outputFileName)`

you simply have to chose the fieldname related to the polygon index in your featureset

Oscar

**Comment by jany-tenaj** [comment]
This is not an issue.
