### ISSUE TITLE
Unable to cast object of type 'DotSpatial.Controls.MapLineLayer' to type 'DotSpatial.Controls.MapPolygonLayer'

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#712]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25732)**

**[uma5b3](http://www.codeplex.com/site/users/view/uma5b3)** wrote 2014-09-15 at 20:15
I'm new to GIS and Dotspatial, when was trying to build a sample application. i loaded .shp file and them then pressed vietattribute button then i got the error Unable to cast object of type 'DotSpatial.Controls.MapLineLayer' to type 'DotSpatial.Controls.MapPolygonLayer'.
 Please help . what kind of file should i load into the application ? only .shp or any other, if any other is possible please give me some documents link to samples.

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-09-15 at 22:09
What version of dotspatial do you use?

**[uma5b3](http://www.codeplex.com/site/users/view/uma5b3)** wrote 2014-09-16 at 08:28
Dotspatial 1.7

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-09-16 at 10:19
Do you get this error too when you load your shapes into DemoMap and press the View Attribute button there?

**[uma5b3](http://www.codeplex.com/site/users/view/uma5b3)** wrote 2014-09-16 at 11:06
where can i get shape files ? Could you please tell me where can i download shape file of India and how to add pointers to the shape file.

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2014-09-16 at 11:29
You can add the shapefiles you used in your own program by clicking on the "Add Layer..." button.I have no idea where you can get shapefiles of india.

**Comment by jany-tenaj** [comment]
@mogikanin Do you understand this issue?

**Comment by mogikanin** [comment]
No. Let's close it.
