### ISSUE TITLE
Export Feature and FeatureLayerActions

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#722]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/25949)**

**[ambiente](http://www.codeplex.com/site/users/view/ambiente)** wrote 2015-01-28 at 01:24
Hi,

I am translating DotSpatial.Symbology.Forms and I made changes in the FeatureLayerActions.cs and the SymbologyFormsMessageStrings.resx

Here my changes to localize the message box output

<pre><code>public void ExportData(IFeatureLayer e)
        {
            using (var frmExport = new ExportFeature())
            {
                frmExport.Filename = e.DataSet.Filename;
                if (ShowDialog(frmExport) != DialogResult.OK) return;

                // Create a FeatureSet of features that the client wants exported
                FeatureSet fs = null;
                switch (frmExport.FeaturesIndex)
                {
                    case 0:
                        fs = (FeatureSet) e.DataSet;
                        break;
                    case 1:
                        fs = e.Selection.ToFeatureSet();
                        break;
                    case 2:
                        var features = e.DataSet.Select(e.MapFrame.ViewExtents);
                        fs = new FeatureSet(features) {Projection = e.Projection};
                        break;
                }

                if (fs.Features.Count == 0)
                {
                    fs.CopyTableSchema(e.DataSet);
                    fs.FeatureType = e.DataSet.FeatureType;
                }

                fs.SaveAs(frmExport.Filename, true);

                if (MessageBox.Show(Owner, SymbologyFormsMessageStrings.ExportFeature_Features_Load,
                                    SymbologyFormsMessageStrings.ExportFeature_Features_Exported,
                                    MessageBoxButtons.YesNo) == DialogResult.Yes)
                {
                    LoadFeatureSetAsLayer(e, fs, Path.GetFileNameWithoutExtension(frmExport.Filename));
                }
            }
        }</code></pre>
And this 2 strings in the .resx file

ExportFeature_Features_Exported The layer was exported. 

ExportFeature_Features_Load Do you want to load the shapefile? 

I have a Problem if I need to use a Code page file .cpg thogether with my .shp file.

In this case the .cpg file is not exported too and the data in the exported file are shown with wrong coding.

Any idea how to change the Code to Export the cpg file too?

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2015-03-03 at 16:20
Associated with changeset 75589: Moved 2 Strings from FeatureLayerActions to SymbologyMessageStrings

**Comment by mogikanin** [comment]
This was done in a01eb0a84c60e9fc7c0ec49c7608d47530027c41

**Comment by jany-tenaj** [comment]
@mogikanin I only moved the Strings to the SymbologyMessageStrings. But I didn't touch the reported problem with the code page file.

**Comment by mogikanin** [comment]
Let's move that part into separate issue?

**Comment by jany-tenaj** [comment]
Yes I can live with that. ^^
