### ISSUE TITLE
raster extent shifts from correct extent

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#725]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/26002)**

**[Oscarafone77](http://www.codeplex.com/site/users/view/Oscarafone77)** wrote 2015-02-20 at 18:53
Dear all,

as already seen in previous discussions (see <a href="https://dotspatial.codeplex.com/discussions/294853" rel="nofollow">
here</a>)

there is a shift between the real raster extent and the one recovered with the library.

I noticed this problem when using the identify tool to recover raster cell values.

Visualization is shifted half cell to the left and half upward. 

Couldn't find in dotspatial sources the origin of the problem

Can anyone help on that?

Thank you

Oscar

**[Oscarafone77](http://www.codeplex.com/site/users/view/Oscarafone77)** wrote 2015-03-23 at 17:57
Attached find a picture describing the issue.Correct cells position is delineated as dashed lines next to visualized cells.

Thank youOscar

**[Oscarafone77](http://www.codeplex.com/site/users/view/Oscarafone77)** wrote 2015-03-26 at 16:43
I found what might cause the visualization shift. 

In MapRasterLayer.cs to create the visualized Bitmap, the extent is given through the following instruction (somewhere around line 125):

<code>var id = new InRamImage(bmp) { Bounds = { AffineCoefficients = raster.Bounds.AffineCoefficients } };</code>this assigns the same affine coefficients to the Bitmap.

If I substitute this assignment with this 

<pre><code></code></pre>
I get the correct visualization.I know this sounds more like a trick rather than a correct solution to the problem, but wrong raster visualization is very annoing

However this just to highlight that there is something to fix around affine coefficients definition

Oscar

**[Oscarafone77](http://www.codeplex.com/site/users/view/Oscarafone77)** wrote 2015-07-30 at 10:49
Something disappeared in previous post.

The substituting code is the following:

<pre><code>                double[] affine = new double[6];
                affine[0] = raster.Bounds.AffineCoefficients[0] + raster.Bounds.AffineCoefficients[1] / 2.0;
                affine[1] = raster.Bounds.AffineCoefficients[1];
                affine[2] = raster.Bounds.AffineCoefficients[2];
                affine[3] = raster.Bounds.AffineCoefficients[3] + raster.Bounds.AffineCoefficients[5]/2.0 ;
                affine[4] = raster.Bounds.AffineCoefficients[4];
                affine[5] = raster.Bounds.AffineCoefficients[5];
                //var id = new InRamImage(bmp) { Bounds = { AffineCoefficients = raster.Bounds.AffineCoefficients } };
                var id = new InRamImage(bmp) { Bounds = { AffineCoefficients = affine } };
</code></pre>
Oscar

**Comment by mogikanin** [comment]
Oscar, please check this issue with latest DS. Possibly it's already fixed within #822

**Comment by oscarafone77** [comment]
Hi Maxim,

It is now fixed, Issue can be closed

Thank you very much
Oscar

**Comment by mogikanin** [comment]
Ok, Thanks :)
