### ISSUE TITLE
LegendText ReadOnly

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#750]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63599)**

**[robertosalemi](http://www.codeplex.com/site/users/view/robertosalemi)** wrote 2015-09-03 at 10:47
Hi, 

I'm using this code for to identify the single layer present in 'MapLayers'

<pre><code>IMapFeatureLayer[] arrayLayer = currentMap.GetFeatureLayers();

foreach (IMapFeatureLayer layer in arrayLayer)
{
    if (layer.LegendText.Equals(layerToRemoved.LegendText))
    {
        //TODO
    }
}
</code></pre>

In treeview of 'MapLayers', can I block the name of layer as ReadOnly? 

Thanks.

**Comment by mogikanin** [comment]
Probably it will be useful feature to mark some tree nodes as ReadOnly. In this case user should not have possibility to rename them in GUI.

**Comment by sindizzy** [comment]
I would like this feature. Many of my apps are non-customizable as far as legen items. If possible i would suggest a property that makes Legend.Item.Text.ReadOnly and maybe Legend.Item.Symbology.ReadOnly. Also the same with the MapFrame since I want to limit the user from changing projection and such.

~AGP

**Comment by mogikanin** [comment]
@sindizzy would you like to create pull request with this? But only for tree nodes text. For the map frame\map projection better create separate task.

**Comment by sindizzy** [comment]
I'm not sure how to do that. I want to start contributing but not sure exactly how to setup.

**Comment by mogikanin** [comment]
> not sure exactly how to setup.

how to setup what?

**Comment by sindizzy** [comment]
I assume a "pull request" is a download of the code? Not sure what you asked me to do to create tasks.

**Comment by mogikanin** [comment]
Please read [this](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md)
