### ISSUE TITLE
Extensions not loaded after migrating to v 1.8

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#756]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63605)**

**[ModernaTider](http://www.codeplex.com/site/users/view/ModernaTider)** wrote 2015-11-09 at 15:55
At least for me, extensions are not loaded in experimental release 1.8. After appManager.LoadExtensions() has been called, appManager.Extensions list is empty. All extensions have been replaced with 1.8 versions.

**[subsci](http://www.codeplex.com/site/users/view/subsci)** wrote 2015-11-11 at 16:03
I am using version 1.8 and these are the Extensions in the AppManager after call to LoadExtensions(). There are 22 of them. Possible causes of no load are your directory structure (where DotSpatial expects to find plugins and windows extensions), or lack
 of subdirectories with objects within those directories

{DotSpatial.Plugins.About.AboutPlugin}

{Contourer.Snapin}

{DotSpatial.Plugins.FindFeature.FindFeaturePlugin}

{DotSpatial.Plugins.Help.HelpPlugin}

{DotSpatial.Plugins.Measure.MeasurePlugin}

{DotSpatial.Plugins.SetSelectable.SetSelectablePlugin}

{DotSpatial.Plugins.ShapeEditor.ShapeEditorPlugin}

{DotSpatial.Plugins.SimpleLegend.SimpleLegendPlugin}

{DotSpatial.Plugins.SimpleMap.SimpleMapPlugin}

{DotSpatial.Plugins.SpatiaLite.SpatiaLitePlugin}

{DemoMap.StatusShowCoordinates}

{DemoMap.StatusShowSelectionCount}

{DotSpatial.Plugins.TableEditor.TableEditorPlugin}

{DotSpatial.Plugins.ToolManager.ToolManagerPlugin}

{DotSpatial.Plugins.Uy.UyPlugin}

{DotSpatial.Plugins.ClickOnceUpdater.Updater}

{DotSpatial.Plugins.ExtensionManager.ExtensionManagerPlugin}

{DotSpatial.Plugins.MapWindowProjectFileCompatibility.RetrieveLegacySymbolizationPlugin}

{DotSpatial.Plugins.ScriptRunner.MapWindowDS.ScriptRunner.ScriptRunnerPlugin}

{DotSpatial.Plugins.Taudem.Port.TaudemPlugin}

{DotSpatial.Plugins.WebMap.WebMapPlugin}

{DotSpatial.Plugins.WFSClient.WfsPlugin}

**Comment by pedwik** [comment]
Cannot reproduce in version 1.9. I suggest you close this issue.

**Comment by mogikanin** [comment]
OK
