### ISSUE TITLE
Bug in tool Reproject Features

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#761]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63610)**

**[ModernaTider](http://www.codeplex.com/site/users/view/ModernaTider)** wrote 2015-12-17 at 17:21
The Toolbox tool called "Reproject Features" is returning "parameter missing" for a reprojection that works without problems when using myFeatureSet.Reproject(toProjectionInfo). At least when converting from KnownCoordinateSystems.Projected.NationalGridsSweden.RT9025gonV
 to 

KnownCoordinateSystems.Projected.NationalGridsSweden.SWEREF99TM. 

Source file attached.

**Comment by mogikanin** [comment]
Please upload shape file again. Attached one doesn't contain dbf.

**Comment by pedwik** [comment]
Sorry about that. New upload:
[Fagerdal.zip](https://github.com/DotSpatial/DotSpatial/files/293204/Fagerdal.zip)

**Comment by mogikanin** [comment]
Does this tool work earlier? Because now I have 2 warnings and message that "Tool cannot be run..."
![image](https://cloud.githubusercontent.com/assets/840681/15708164/a45ba158-2805-11e6-8b81-465cb2dd68bc.png)
