### ISSUE TITLE
Prevent projection dialog popup

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#762]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63611)**

**[pan054](http://www.codeplex.com/site/users/view/pan054)** wrote 2016-01-16 at 03:01
Hi, 

Does anyone know how to prevent the projection dialog box to automatically open when adding a (raster) layer to a map.

VS 2015, VB.Net, DS 1.8. 

Cheers

**Comment by oscarafone77** [comment]
Map1.MapFrame.ProjectionModeDefine = ActionMode.Never   
other choices are "PromptOnce" "Prompt" "Always"

if you also need to stop reprojectin request:
Map1.MapFrame.ProjectionModeReproject = ActionMode.Never
same other choices as above

Oscar

**Comment by jany-tenaj** [comment]
This is not an issue.
