### ISSUE TITLE
Bug: System.IndexOutOfRangeException given when trying to label an added MapPointLayer

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#767]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63616)**

**[maseology](http://www.codeplex.com/site/users/view/maseology)** wrote 2016-02-05 at 22:20
Since upgrading to v1.8, I get an index of of range message when attempting to label a newly created MapPointLayer, For example, the following code once executed successfully, an error is drawn when attempting to label the point with the FID attribute
 (the funny thing is, once the data are exported as a shapefile, labeling works just fine):

'the new point feature set

<pre><code>    Dim MyPointFeatureSet As New FeatureSet(FeatureType.Point)
    MyPointFeatureSet.Projection = Map.Projection

    'make a coordinate, add it to the featureset
    Dim MyCoordinate As New Coordinate
    MyCoordinate.X = -155
    MyCoordinate.Y = 65
    Dim MyPoint As New DotSpatial.Topology.Point(MyCoordinate)
    Dim MyFeature As IFeature = MyPointFeatureSet.AddFeature(MyPoint)
    MyPointFeatureSet.AddFeature(MyFeature)

    'add the featureSet as map layer
    Dim MyMapPointLayer As MapPointLayer = Map.Layers.Add(MyPointFeatureSet)
    MyMapPointLayer.LegendText = "Skeeter's Points"

    'refresh the map
    Map.ResetBuffer()</code></pre>

**Comment by gwenroyakkers** [comment]
I have the same problem. When I create a feature layer (MapPointLayer) from an in-memory FeatureSet, the application will crash when i apply a label from the UI.

Did you find a solution or workaround?

**Comment by jany-tenaj** [comment]
Can you post the code you used beginning by the creation of your feature layer up to the part where you add the labels?

**Comment by gwenroyakkers** [comment]
This is the function I use to create a FeatureSet From a MS Sql Server database.
<pre>
<code>
public FeatureSet GetTrajectFeatures()
        {
            FeatureSet fSet = new FeatureSet(DotSpatial.Topology.FeatureType.Point);
            fSet.Name = "Traject";
            fSet.DataTable = new DataTable("Traject");
            fSet.DataTable.Columns.Add("ID", typeof(int));
            fSet.DataTable.Columns[0].AutoIncrement = true;
            fSet.DataTable.Columns[0].AutoIncrementSeed = 1;
            fSet.DataTable.Columns[0].AutoIncrementStep = 1;

            fSet.DataTable.Columns.Add("SysTijd", typeof(TimeSpan));
            fSet.DataTable.Columns.Add("GpsTijd", typeof(TimeSpan));
            fSet.DataTable.Columns.Add("Richting", typeof(double));
            fSet.DataTable.Columns.Add("Vgps", typeof(double));
            fSet.DataTable.Columns.Add("Vpeisler", typeof(double));
            fSet.DataTable.Columns.Add("FixQuality", typeof(int));
            fSet.DataTable.Columns.Add("AantalSat", typeof(int));
            fSet.DataTable.Columns.Add("HorizontalDilution", typeof(double));
            fSet.DataTable.Columns.Add("GGAchks", typeof(bool));
            fSet.DataTable.Columns.Add("VTGchks", typeof(bool));
            fSet.DataTable.Columns.Add("PeislerOK", typeof(bool));
            fSet.DataTable.Columns.Add("MetingVolledig", typeof(bool));

            try
            {
                if (m_connection.State != ConnectionState.Open)
                {
                    m_connection.Open();
                }
                using (SqlCommand selectMapperRegelsCommand = m_connection.CreateCommand())
                {
                    selectMapperRegelsCommand.CommandType = CommandType.Text;
                    selectMapperRegelsCommand.CommandText = @"
                                                            SELECT [ID]
                                                                  ,[Geom]
                                                                  ,[SysTijd]
                                                                  ,[GpsTijd]
                                                                  ,[Richting]
                                                                  ,[Vgps]
                                                                  ,[Vpeisler]
                                                                  ,[FixQuality]
                                                                  ,[AantalSat]
                                                                  ,[HorizontalDilution]
                                                                  ,[GGAchks]
                                                                  ,[VTGchks]
                                                                  ,[PeislerOK]
                                                                  ,[MetingVolledig]
                                                              FROM [Mapper]";
                    using (SqlDataReader rdr = selectMapperRegelsCommand.ExecuteReader())
                    {
                        while (rdr.Read())
                        {
                            try
                            {
                                SqlGeometry geom = SqlGeometry.Deserialize(rdr.GetSqlBytes(1));
                                if (geom == null)
                                {
                                    continue;
                                }
                                Point pnt = new Point(geom.STX.Value, geom.STY.Value, geom.Z.Value);

                                Feature feat = new Feature(pnt, fSet);
                                feat.DataRow["ID"] = rdr.GetInt32(0);
                                feat.DataRow["SysTijd"] = rdr.GetTimeSpan(2);
                                feat.DataRow["GpsTijd"] = rdr.GetTimeSpan(3);
                                feat.DataRow["Richting"] = rdr.GetDouble(4);
                                feat.DataRow["Vgps"] = rdr.GetDouble(5);
                                feat.DataRow["Vpeisler"] = rdr.GetDouble(6);
                                feat.DataRow["FixQuality"] = rdr.GetInt32(7);
                                feat.DataRow["AantalSat"] = rdr.GetInt32(8);
                                feat.DataRow["HorizontalDilution"] = rdr.GetDouble(9);
                                feat.DataRow["GGAchks"] = rdr.GetBoolean(10);
                                feat.DataRow["VTGchks"] = rdr.GetBoolean(11);
                                feat.DataRow["PeislerOK"] = rdr.GetBoolean(12);
                                feat.DataRow["MetingVolledig"] = rdr.GetBoolean(13);
                            }
                            catch (Exception)
                            {

                                throw;
                            }
                        }
fSet.DataTable.Columns[0] };
                    }
                }
            }
            catch (Exception)
            {

                throw;
            }
            fSet.Projection = DotSpatial.Projections.KnownCoordinateSystems.Projected.NationalGrids.Rijksdriehoekstelsel;
            return fSet; 
        }

</code>
</pre>

And this is the code I use to add the FeatureSet to the map.
(DotspatialMap is the DotSpatial.Controls.Map of the UI)

<pre>
<code>
            TrajectSet = HuidigeTrajectDB.GetTrajectFeatures();
            DotSpatial.Controls.MapPointLayer trajectpuntLaag = new DotSpatial.Controls.MapPointLayer(TrajectSet);

            DotSpatial.Controls.IMapLabelLayer labelLayer = new DotSpatial.Controls.MapLabelLayer(TrajectSet);
            DotSpatial.Symbology.ILabelCategory categorie = labelLayer.Symbology.Categories[0];
            categorie.Symbolizer.PriorityField = "ID";
            categorie.SelectionSymbolizer.PriorityField = "ID";
            categorie.Expression = "[GpsTijd]";
            trajectpuntLaag.ShowLabels = true;
            trajectpuntLaag.LabelLayer = labelLayer;

            DotSpatialMap.Layers.Add(trajectpuntLaag);        
</code>
</pre>

When I comment out the code for the labels, the layer is visible in the Map Control.
If I try to add labels from the GUI with the Legend Control, the same "Index out of bounds" exception pops up.

**Comment by jany-tenaj** [comment]
add ` fSet.InitializeVertices();`
after `fSet.Projection...`

For me this removes the error.

**Comment by gwenroyakkers** [comment]
Thanks @jany-tenaj 
'fSet.InitializeVertices();' Did solve the problem

**Comment by maseology** [comment]
'.InitializeVertices();' Did **not** solve the problem for me. same issue arises as I attempt to add labels through the UI.

**Comment by jany-tenaj** [comment]
@maseology I ran your code again in 1.9 adding `myMapPointLayer.DataSet.InitializeVertices()` before `Map.ResetBuffer()`. I did this from the Shown event of a VB-version of DemoMap.
Then I right clicked on the skeeter layer in legend and opened the label setup under labeling. There I added [FID] to category0s expression.

This worked without problem and the label was shown.

If possible please upload a demoproject that reproduces your problem so that we can run this to check where the problem comes from.

**Comment by maseology** [comment]
Thanks **@jany-tenaj**
turns out my issue with the example I provided (above) was that I _InitializedVertices()_ on MyPointFeatureSet, in a similar fashion to @gwenroyakkers, rather than _myMapPointLayer.DataSet_ as later instructed by @jany-tenaj.  Now all is working fine.  Thank you.
