### ISSUE TITLE
Map Frame Dragging

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#772]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63621)**

**[snahdog](http://www.codeplex.com/site/users/view/snahdog)** wrote 2016-03-04 at 23:36
In the Legend, clicking and dragging the MapFrame (Map Layers) program to crash

**Comment by mogikanin** [comment]
Not reproduced. Can you give more detailed steps to reproduce, and exception stacktrace?

**Comment by snahdog** [comment]
Sorry that it took a long time for me to respond. Maybe this can be re-opened.

Steps to reproduce:
1. Open the DemoMap application.
2. Right click on the Map Layers item and click create new group.
3. Select the Map Layers item and drag it below the newly created group item.
4. The program crashes.

This happens in the latest version (1.9) and also in 1.8.

Thanks.

**Comment by mogikanin** [comment]
Hi, can you please check it with latest 2.0 version?

**Comment by snahdog** [comment]
Where can I obtain v2.0? I only see 1.9.

**Comment by mogikanin** [comment]
It's not published at nuget yet, but you always can get latest build from build [server ](https://ci.appveyor.com/project/mogikanin/dotspatial/history).
Here the direct [url](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master) to download.

**Comment by snahdog** [comment]
It also happens in 2.0

**Comment by mogikanin** [comment]
Yes, reproduced for me too. We should forbid to drag "Map Layers" root into any sub-groups.
