### ISSUE TITLE
Bug: MultiPolygon shapefile with holes with nested part not read correctly

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#779]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63628)**

**[xilconic](http://www.codeplex.com/site/users/view/xilconic)** wrote 2016-04-28 at 10:40
I would like to report the following bug in DotSpatial 1.8. The reproduction scenario is as follows:

<ol>
<li>Create a polygon shapefile (I've used QGis 2.2.0-Valmiera, a RD New coordinate system and the default 'ID' attribute).
</li><li>Add a new polygon feature. Make sure it's big enough to fit another polygon inside that has a ring/hole in it.
</li><li>Add a ring to the new polygon and make that big enough to fit another polygon inside that ring.
</li><li>Now select the polygon with a hole, and add a new part to it (defining a MultiPolygon geometry) within the confines of the ring.
</li><li>Next, add a ring to that inner polygon. You should now have 1 feature consisting of two polygons, each with one hole/ring and one of those geometries is nested inside the other. For convenience I've provided such a shapefile attached to the issue.
</li><li>After having created the shapefile, read the file with the following piece of code:
</li></ol>
<pre><code>string filePath = TODO; // Replace with path to file
using (var file = new PolygonShapefile(filePath))
{
    Debug.Assert(file.Features.Count == 1,
        "Expected the shapefile to have only 1 feature.");

    IFeature feature = file.GetFeature(0);
    Debug.Assert(feature.BasicGeometry.NumGeometries == 2,
        "Expect the feature to consist out of 2 geometries.");

    for (int i = 0; i < feature.BasicGeometry.NumGeometries; i++)
    {
        var polygon = (IBasicPolygon)feature.GetBasicGeometryN(i);
        Debug.Assert(polygon.NumHoles == 1,
            "Expect each polygon part to have 1 hole/ring."); // <-- Fails
    }
}</code></pre>
Observe that the marked assertion fails because one of the polygons has the holes of both polygons. Comparing the WKT generated by QGis with that from DotSpatial illustrates the bug (Reformatted the result to improve readability):

<strong>WKT from QGis:</strong>

<pre><code>wkt_geom         id
MULTIPOLYGON(
(
(-741345.93126927537377924 -5637152.46028447616845369,-393980.85810417239554226 -5634718.47078281920403242,-390851.44303061295067891 -5860384.06886505335569382,-742041.35684117756318301 -5848214.12135676667094231,-741345.93126927537377924 -5637152.46028447616845369),
(-725698.85590147797483951 -5648279.26943491026759148,-727785.13261718431022018 -5839173.58892203867435455,-404064.52889675297774374 -5848561.83414271753281355,-407193.94397031248081475 -5644454.42878944892436266,-725698.85590147797483951 -5648279.26943491026759148)
),
(
(-676671.35308237932622433 -5686179.96310357470065355,-440922.08420756470877677 -5678182.56902670115232468,-433272.40291664149845019 -5814485.98111951444298029,-672498.79965096665546298 -5797795.7673938637599349,-676671.35308237932622433 -5686179.96310357470065355),
(-661719.70328648400027305 -5693829.64439449831843376,-656504.01149721816182137 -5788407.52217318490147591,-439183.52027780946809798 -5807531.72540049254894257,-451701.1805720473639667 -5689657.0909630861133337,-661719.70328648400027305 -5693829.64439449831843376))
)
            1</code></pre>
<strong>WKT from DotSpatial:</strong>

<pre><code>MULTIPOLYGON (
(
(-741345.9312692750000000 -5637152.4602844800000000, -393980.8581041720000000 -5634718.4707828200000000, -390851.4430306130000000 -5860384.0688650500000000, -742041.3568411780000000 -5848214.1213567700000000, -741345.9312692750000000 -5637152.4602844800000000),
(-725698.8559014780000000 -5648279.2694349100000000, -727785.1326171840000000 -5839173.5889220400000000, -404064.5288967530000000 -5848561.8341427200000000, -407193.9439703120000000 -5644454.4287894500000000, -725698.8559014780000000 -5648279.2694349100000000),
(-661719.7032864840000000 -5693829.6443945000000000, -656504.0114972180000000 -5788407.5221731800000000, -439183.5202778090000000 -5807531.7254004900000000, -451701.1805720470000000 -5689657.0909630900000000, -661719.7032864840000000 -5693829.6443945000000000)
),
(
(-676671.3530823790000000 -5686179.9631035700000000, -440922.0842075650000000 -5678182.5690267000000000, -433272.4029166420000000 -5814485.9811195100000000, -672498.7996509670000000 -5797795.7673938600000000, -676671.3530823790000000 -5686179.9631035700000000),
(-661719.7032864840000000 -5693829.6443945000000000, -656504.0114972180000000 -5788407.5221731800000000, -439183.5202778090000000 -5807531.7254004900000000, -451701.1805720470000000 -5689657.0909630900000000, -661719.7032864840000000 -5693829.6443945000000000)
)
)</code></pre>
<strong>Expected behavior</strong> 

I would expect that once the shapefile is read, the provided code above (bullet 6.) does not trigger any of the assertions.

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2016-04-28 at 11:23
Please attach the shapefile you used (the one that doesn't yet contain the error).

Please show the code you used to do the steps 2-5. Or describe more clearly which tools/buttons you pushed if you did this process with the help of the toolbars available in DemoMap.

**[xilconic](http://www.codeplex.com/site/users/view/xilconic)** wrote 2016-04-28 at 14:10
I've attached a polygon that works just fine. It is an example shape file that would be the end product of reproduction steps 1-3.

The more detailed reproduction steps (I'll excuse myself in advance for any term that doesn't fully match in the English localization of QGis as I'm using a Dutch localized version):

1.1. Use QGis v2.2.0-Valmiera. 

1.2. Menu: Maplayers > New Shape Layer (CTRL+SHIFT+N) 

1.3.1. In the dialog, click "Polygon" shape type. 

1.3.2. As CRS, use "Amersfoort / RD New" with EPSG:28992. 

2.1. Menu: Edit > Add Object (CTRL+.) <img src="https://docs.qgis.org/2.2/en/_images/mActionCapturePolygon.png" alt="Image">

2.2. I've made all geometries rectangular, so click the 4 corners with the left mouse button in the central map area and then terminate the action with a right mouse click. You should now have a rectangular, filled polygon.

3.1. Menu: Edit > Add Ring <img src="https://docs.qgis.org/2.2/en/_images/mActionAddRing.png" alt="Image">

3.2. Click the 4 inner ring coordinates inside the already existing polygon. You should now have a rectangular, filled 'donut' polygon (similar to PolygonShapeBeforeAddingNestedPart)

4.1. Ensure you have selected the 'donut' polygon (Colored yellow). If now, select the feature first using the selection tool
<img src="https://docs.qgis.org/2.2/en/_images/mActionSelect.png" alt="Image"> 

4.2. Menu: Edit > Add Part <img src="https://docs.qgis.org/2.2/en/_images/mActionAddPart.png" alt="Image">

4.3. Click the 4 outer ring coordinates of the 2nd polygon part. Make sure all points are within the 'empty space' of the 'donut' polygon. Finish with right mouse button. You should now have a 'donut' polygon that fully encloses another rectangular polygon.

5.1. Menu: Edit > Add Ring <img src="https://docs.qgis.org/2.2/en/_images/mActionAddRing.png" alt="Image">

5.2. Click the 4 inner ring coordinates inside the 2nd existing polygon and terminate with right mouse button. You should now have 2 rectangular 'donut' polygons, where 1 is fully enclosed within the other. (Similar to the shape in ExampleMultiPolygonShapefile)

**Comment by orbitzhan** [comment]
Hello!
Is  there any problem in reading geometry of shp?
