### ISSUE TITLE
Clone a featureset with CopyFeatures throws exception

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#780]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63629)**

**[sindizzy](http://www.codeplex.com/site/users/view/sindizzy)** wrote 2016-05-04 at 19:33
I was following the sample code here <a href="https://dotspatial.codeplex.com/wikipage?title=Adding%20a%20Geographic%20Coordinate%20System%20to%20a%20Feature%20Set&referringTitle=DotSpatial.Projections#vb" rel="nofollow">
https://dotspatial.codeplex.com/wikipage?title=Adding%20a%20Geographic%20Coordinate%20System%20to%20a%20Feature%20Set&referringTitle=DotSpatial.Projections#vb</a> to clone a featureset. I've made countless tweaks to see if it works but I always get an exception.
 This is the only way I could get it to work:

<pre><code>'we will take a clone of the input featureset so as to prevent the original file from being edited
fsLine.FillAttributes()
Dim fsClone As New FeatureSet(fsLine.FeatureType)
fsClone.IndexMode = True
fsClone.Projection = fsLine.Projection
fsClone.CopyFeatures(fsLine, True)
Debug.Print("fsClone feature Count={0} of Type={1}", fsClone.Features.Count, fsClone.FeatureType.ToString)
</code></pre>
I took a look at the source code and the issues is with Not IndexMode in featureSet.cs. If you look at Line 529 it uses ShapeIndices[i]; Well that's empty every time which is why it bombs. Should it not be _shapeIndices[i] or maybe the _shapeIndices List needs
 to be assigned to the output featureset up at the beginning of the routine. 

This also happens at Line 567. 

One case is for AttributesPopulated and the other for !AttributesPopulated 

Also if I dont want attributes copied I dont do a FillAttributes and somehow that causes an exception as well although I havent been able to track that one down.

~AGP

**Comment by jany-tenaj** [comment]
@mogikanin I just had a look at this and I'm not sure this function makes sense. It goes and trys to replace everything essential of the IFeatureSet it is given.
It doesn't check whether the FeatureType of the given IFeatureSet and the FeatureSet calling the function is the same and it stumbles on the fact that FeatureSet.AttributesPolulated is set to true by default, although no attributes exist.

We already have CopySubset that is able to create a valid copy of the featureSet. Do we need a function that tries to do the same the other way round?

The only thing missing from CopySubset is the fact that there is no way not to copy the attributes.

**Comment by mogikanin** [comment]
OK. Lets make `CopyFeatures()` to use `CopySubset()` internally. Also then we need another overload of  `CopySubset()` which has additional boolean flag to copy attributes or not.

**Comment by jany-tenaj** [comment]
As I said CopyFeatures does the same as CopySubset but the other way round.

That would mean that to be able to use CopySubset inside CopyFeatures we have to change the definition of CopyFeatures from 
`fsClone.CopyFeatures(fsOriginal, copyAttributes)` 
to 
`fsClone = fsOriginal.CopyFeatures(copyAttributes)`, so that they work from the same side? 

If we do that the overload with the additional flag would be redundant with the new CopyFeatures.

I'm still wondering for which cases it could be usefull to copy the features to a prior defined IFeatureSet.

**Comment by mogikanin** [comment]
> That would mean that to be able to use CopySubset inside CopyFeatures we have to change the definition of CopyFeatures from 
fsClone.CopyFeatures(fsOriginal, copyAttributes) 
to 
fsClone = fsOriginal.CopyFeatures(copyAttributes), so that they work from the same side?

exactly

> I'm still wondering for which cases it could be usefull to copy the features to a prior defined IFeatureSet

No idea

**Comment by jany-tenaj** [comment]
> OK. Lets make CopyFeatures() to use CopySubset() internally. Also then we need another overload of CopySubset() which has additional boolean flag to copy attributes or not.

@mogikanin Is there a reason you want to have 3 methods that essentially do the same? This could also be done with CopySubset(string filterExpression, bool withAttributes = true) if a ""/String.Empty or null filterExpression would return all features.

I think having different named methods do the same thing is quiet confusing.

**Comment by sindizzy** [comment]
Look forward to testing this in the new release. I can test the current changes today right? I just haven't worked with anything other than official releases.

**Comment by jany-tenaj** [comment]
@sindizzy Sure. You can either clone or download the current source code from the Code tab or download the complied dlls from [AppVeyor](https://ci.appveyor.com/project/mogikanin/dotspatial/build/artifacts).

**Comment by sindizzy** [comment]
The AppVeyor package seems to be missing DLLs.
