### ISSUE TITLE
Intersection Issue

### ISSUE THREAD

**Issue by orbitzhan** [DotSpatial/DotSpatial#785]
When use IFeature intersection method, code like this:
              IFeature feature1;
              IFeature feature2;
              IFeature feature3 = feature1.Intersection(feature2);
throw the error in DotSpatial.Topology.GeometriesGraph.GeometryGraph.cs
Method: AddPolygonRing    "_lineEdgeMap(lr,e)"   have already the same key?

PS: I test my data both in ArcGIS and QGIS and there is no error.

**Comment by jany-tenaj** [comment]
Please show us the coordinates of those two features.

**Comment by orbitzhan** [comment]
## Coordinates:
Data Type:	Shapefile Feature Class 
Shapefile:
Geometry Type:	Polygon
Coordinates have Z values:	No 
Coordinates have measures:	No 

Projected Coordinate System:	Xian_1980_GK_CM_105E
Projection:	Gauss_Kruger
False_Easting:	500000.00000000
False_Northing:	0.00000000
Central_Meridian:	105.00000000
Scale_Factor:	1.00000000
Latitude_Of_Origin:	0.00000000
Linear Unit: 	Meter

Geographic Coordinate System:	GCS_Xian_1980
Datum: 	D_Xian_1980
Prime Meridian: 	Greenwich
Angular Unit: 	Degree

PS: Do you need the DATA? I can Email to you

**Comment by orbitzhan** [comment]
![error](https://cloud.githubusercontent.com/assets/13759823/15139704/1681acde-16ca-11e6-9aa4-7eb387775d18.PNG)

**Comment by jany-tenaj** [comment]
We need the Coordinates of your Features. If possible either upload the shapefile you used and tell us which features where the ones causing problems or post the WKB of the two features you used for intersecting.

**Comment by orbitzhan** [comment]
two shp（each shp has one polygon）
[Data.zip](https://github.com/DotSpatial/DotSpatial/files/256795/Data.zip)

**Comment by orbitzhan** [comment]
Sorry, it's too slow to upload.
There are two shp files and each one has one polygon.
[Data.zip](https://github.com/DotSpatial/DotSpatial/files/256938/Data.zip)

PS:
I changed the Code of GeometryGraph.cs。
`if(!_lineEdgeMap.Contains(lr))
{
_lineEdgeMap.Add(lr,e);
}`
It works, but I don't know if it is right.

**Comment by jany-tenaj** [comment]
I used the the following code and the current changeset ([23599f5](https://github.com/DotSpatial/DotSpatial/commit/23599f5e3fc6c87b6f1bac5dcb24a7eed85c6996)) to check your problem. 

```
 var shapeFile1 = Shapefile.OpenFile(@"d:\hilfe\orbitzhan\Data\test1.shp");
 var shapeFile2 = Shapefile.OpenFile(@"d:\hilfe\orbitzhan\Data\test2.shp");

            IFeature feature1 = shapeFile1.GetFeature(0);
            IFeature feature2 = shapeFile2.GetFeature(0);
            IFeature feature3 = feature1.Intersection(feature2.Geometry);
```
This worked without causing an error.
