### ISSUE TITLE
Adding OSM Layer in dotspatial 1.9

### ISSUE THREAD

**Issue by mishrapsaurabh** [DotSpatial/DotSpatial#790]
Hi ,

I have been trying to add an OSM layer in the dotspatial 1.9  map , after several attempts ,i dont seem to be getting anywhere ,can someone give me an example or sample of how this can be done.

**Comment by mogikanin** [comment]
Have a look into [WebMap](https://github.com/DotSpatial/DotSpatial/tree/master/Source/DotSpatial.Plugins.WebMap) plugin.
![image](https://cloud.githubusercontent.com/assets/840681/15984475/1e62a1fa-2fd5-11e6-877f-cd6db88bdcd8.png)

**Comment by mogikanin** [comment]
@mishrapsaurabh question is solved and we can close it?
