### ISSUE TITLE
How can move vertex point without plugin

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#791]
Hi dear
I try to develope my software with dotspitial i dont want to use plugin
How can i move and remove vertex point ?
And my second question , is dotspitial support 3d map ?

**Comment by sindizzy** [comment]
I think the first is covered here
http://dotspatial.codeplex.com/wikipage?title=Desktop_SampleCode

**Comment by mogikanin** [comment]
Regarding 3d map - no 3d view map control at the moment.

**Comment by jany-tenaj** [comment]
In discussions https://3dviewer.codeplex.com/ was mentioned a few times. But I've got no idea whether that works...

**Comment by ZimaSystem** [comment]
I saw sample code later but i can found any thing about move feature icon or shape point 
My u help me?

**Comment by jany-tenaj** [comment]
Have a look at the [moveVertex ](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Plugins.ShapeEditor/MoveVertexFunction.cs) function of the shape editor. This function can be used to move vertices. No idea why you don't want to use plugins as they are quiet essential for DotSpatial but there is no reason why you couldn't take the code and use it for your own function.

**Comment by mogikanin** [comment]
@ZimaSystem question is solved and we can close issue?
