### ISSUE TITLE
Reading formatted ESRI projection files

### ISSUE THREAD

**Issue by mkaring** [DotSpatial/DotSpatial#793]
### Feature description

I encountered projection files of shape files that came as a formatted string. Strictly speaking this violates the standard shape files. How ever those files just turn up every now and then created by some applications and libraries.

So the requested feature would be to add the ability to read those formatted projection files properly.
Such a file could look like this for example:

```
PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",
	GEOGCS["GCS_WGS_1984",
		DATUM["D_WGS_1984",
			SPHEROID["WGS_1984", 6378137, 298.257223562997]
		],
		PRIMEM["Greenwich", 0],
		UNIT["Degree", 0.0174532925199433]
	],
	PROJECTION["Mercator_Auxiliary_Sphere"],
	PARAMETER["False_Easting", 0],
	PARAMETER["False_Northing", 0],
	PARAMETER["Central_Meridian", 0],
	PARAMETER["Standard_Parallel_1", 0],
	PARAMETER["Scale_Factor", 1],
	PARAMETER["Auxiliary_Sphere_Type", 0.0],
	UNIT["Meter", 1]
]
```

**Comment by mogikanin** [comment]
Merged into master
