### ISSUE TITLE
Line layer disappears when the start isn't in the MapFrame

### ISSUE THREAD

**Issue by brightbulbnz** [DotSpatial/DotSpatial#799]
At this point I don't know if I'm doing something wrong, or if this is a bug.

First I am loaded a few shape files as layers into a Map.
I then add a MapLineLayer with a single feature (a line), to which I periodically add points.

After I add a point, I use `layer.FeatureSet.Features.InvalidateVertices();` followed by `map.MapFrame.Invalidate();` to force a redraw.

This seems to work fine, so long as the start of the line is visible. As soon as the start of the line is out of view, the whole line disappears. It becomes visible again when the start of the line is in view.

**Comment by jany-tenaj** [comment]
Please post the code you use for loading the layers, adding the MapLineLayer and adding the points.

**Comment by mogikanin** [comment]
@brightbulbnz we close issue since there is no response from you in more than [month](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md#common-rules). Feel free to reopen if you still need help with it.
