### ISSUE TITLE
Update Brutile version in Webmap?

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#800]
Brutile is now available as version 0.18 while WebMap plugin is using 0.10. We updated locally and there were only a few changes required. Maybe a good idea to update before releasing 2.0?

**Comment by mogikanin** [comment]
why not if it works fine?

**Comment by pedwik** [comment]
There are fixes in version 0.18. 
https://github.com/BruTile/BruTile/issues?q=is%3Aissue+is%3Aclosed

**Comment by mogikanin** [comment]
I scheduled it to 2.0. @pedwik would you like to create pull request with all necessary changes?

**Comment by pedwik** [comment]
It seems as if I underestimated some problems. The new Brutile is built for .net 4.5 (?). We also had to do some fixes that we are a bit uncertain of. In short we do not feel confident enough to do a pull request. I suggest the developers of WebMap and Brutile take the lead here.

**Comment by MatthiasSchilder** [comment]
Is this issue still of interest?
BruTile is now at version 0.22.1, which has some nice new features like support for legal attribution for map tiles. This is something I'd like to see in DotSpatial, I already created a small prototype on this topic.

I already updated BruTile to 0.22.1 in a private fork. There are a handful of breaking API changes in BruTile which make it neccessary to rewrite a few lines in the WebMap-plugin, but nothing overly complex. I use the updated plugin in production code for a month or so and didn't notice any problems. I can create a pullrequest, if wished-for.

Biggest problem is, as already mentioned, BruTile 0.22.1 uses .NET 4.5.2, so it would be neccessary to upgrade target framework for DotSpatial, also. Do you consider this as acceptable?

**Comment by jany-tenaj** [comment]
@mogikanin do you have anything against updating to .net 4.5.2?

@MatthiasSchilder if mogikanin doesn't have anything against it you'd be welcome to submit a pull request.

**Comment by mogikanin** [comment]
@jany, I don't mind. I think we could update DS to .net 4.5.2

**Comment by MatthiasSchilder** [comment]
@jany-tenaj 
See my pull request #1083.
I ran into one problem I forgot about at first.
