### ISSUE TITLE
Target Framework to .NET 4.5

### ISSUE THREAD

**Issue by mkaring** [DotSpatial/DotSpatial#802]
### Feature proposal

DotSpatial currently targets .NET 4 CP. I just want to put in the proposal to switch to .NET 4.5 for the upcoming 2.0 version since that seems like a good time to do so.

The reason is mostly that the newer .NET 4.5 offers the `async`/`await` pattern that could to leveraged in the IO-heavy components of DotSpatial. I am thinking especially about `DotSpatial.Data`.

Adding `*Async` functions there will improve the usability of DotSpatial, especially when used inside a UI.

**Comment by mogikanin** [comment]
switch to .net 4.5 good suggestion, but we also should ship .net 4.0 assemblies as well. Also we can switch to C#6 + VS2015

**Comment by mkaring** [comment]
So you are suggesting using the .NET 4.5 functions conditionally and building the library for both versions?

**Comment by mogikanin** [comment]
If there is no another way, then yes. But is it possible to write code in 4.5 style with async\awaits, and also ship .net4.0 assemblies using targeting pack? We can't fully refuse from net.4 since it's still very popular.

**Comment by mkaring** [comment]
Well the most obvious approach is to use precompiler defines to include and exclude parts of the library.

There also is https://www.nuget.org/packages/Microsoft.Bcl.Async
This extension adds `async`/`await` to .NET 4.0 but I do not know if that properly works for IO operations.

I mean you can also write those `async` methods with the means of .NET 4.0 by using the `BeginRead`  functions and such. But that is no fun at all.

**Comment by mogikanin** [comment]
@mkaring do you already know in which parts of code using async\await will give us cardinal speed improvement?

**Comment by mkaring** [comment]
@mogikanin Speed improvement is a strong word. :wink:

It will not suddenly turn everything faster. The thing with I/O operations is that the bottleneck is usually the I/O. There is not much you can do about that. The advantage of the `async`/`await` I/O pattern is mostly that you don't block threads while waiting for the I/O to be ready. This way you free additional handles and have the application scale better according to the system performance.

That being said I think the strongest candidate is `DotSpatial.Data`. There are a lot of file reading and writing operations there that will benefit from the usage of the `async`-I/O-pattern. Any class really that reads or writes things from the hard drive is a candidate for these functions really.

**Comment by mogikanin** [comment]
Yes, I know about I/O. But if we doing something, then we should understand why we doing this, and how this will improve usability or speed\memory consumption.  I suggest to you to add async\await into parts you are using in your project, and check how is better things with them. Only remember about .net 4.0 compatibility.

**Comment by mogikanin** [comment]
Martin, do you have plans to do something on this task?

**Comment by mkaring** [comment]
@mogikanin I just recently looked into that again, but there is still some need to discuss how the library should be evolving in that matter.

My proposal would be the following:
Handle DotSpatial as two different parts, the UI related things (So all the *.Forms Projects for example) and the components that are independent from any UI. The non-UI related components could become .NET Core projects. When changing the projects to .NET Core, it is really easy to create the projects to target multiple frameworks (.NET 2, .NET 3.5, .NET 4, .NET 4.5, .NET Standard, and so on). All dependencies share the same code and the parts that are dependant on specific targets are switched using compiler constants.

That way we could provide a wider range of target frameworks, maybe even mobile frameworks using xamarin and uwp. (future)

The upside to this is that the projects that are UI related can remain and normal C# Projects and target the .NET Core projects. They simply use the .NET Core target that match the project target.

What do you think about that?

**Comment by mogikanin** [comment]
Your proposal is good, and I agree with it :) I think targeting will be the most useful especially for DotSpatial.Data and DotSpatial.Projections.

**Comment by mkaring** [comment]
Yes. All libraries these require need to be changed as well. So serialization for example and the NTS libraries. I am not sure what exactly serialization is still needed for, I'd have to check this.

What are the backward compatibility requirements for DotSpatial 2.0 ? Is it acceptable to break the API compatibility or does it have to be maintained?

**Comment by mogikanin** [comment]
It's already broken versus 1.9 since we added NTS.  I think we can break it within a reasonable.

**Comment by mkaring** [comment]
I did some tests in that matter and noticed that the current version of the .NET Core tools do now allow C# projects to reference .NET Core projects in the same solution. I think that is mainly due to the fact that .NET Core is made to directly create NuGET packages.

This is a little tricky now, because it makes the large solution that contains the UI control libraries (.NET 4) and the soon to be portable libraries very hard to setup and maintain.

The easiest solution from my point of view would be to split the solution. One for the .NET core parts, one for the rest.

For the build automation I don't think this will be a issue. appvenyor just would have to build two solutions and reference the the output nuget packages of the first build during the package restore in the second build.

The only thing that may be a issue is referencing the libraries for local development, since you need to switch the solution, depending on what part you want to develop. Also you need to build the .NET core parts to be able to develop parts of the rest.

Any thoughts on that?

**Comment by mogikanin** [comment]
Its sux especially to local development. It will be quite uncomfortable to develop\debug things across several solutions.

**Comment by mogikanin** [comment]
btw, we can build assemblies\nuget packages for various .net targets without using .net core. Simply use msbuild scripts fro that.

**Comment by mkaring** [comment]
I know that. But .NET Core makes it extremely easy to support multiple targets because the IDE tells you what functions are available and what functions are not. Also it allows very easy switching of the current target framework during development.
