### ISSUE TITLE
Can't get vs 2013 or 2015 to load all the controls

### ISSUE THREAD

**Issue by dioslibre** [DotSpatial/DotSpatial#803]
When I try to add the controls from Dotspatial.Controls.dll located in the "bin/Debug" folder, all I get is 6 controls. Am I missing something?
![1](https://cloud.githubusercontent.com/assets/5884640/15859876/66193a30-2cb6-11e6-96f9-c857990b49c7.png)

**Comment by jany-tenaj** [comment]
In commit [838edd5d47de](https://dotspatial.codeplex.com/SourceControl/changeset/838edd5d47de3b0a395defae44632708271c68b5) some of the ToolboxItems were changed so that they are no longer visible. Do you need those to be visible?

**Comment by mogikanin** [comment]
@jany-tenaj , btw do you know why this was done? this commit has no sense

**Comment by dioslibre** [comment]
@jany-tenaj I don't need them to be visible but I thought something was wrong. thanks for your reply.

**Comment by jany-tenaj** [comment]
@mogikanin this didn't make sense to me either. But I've got no idea why it was done.
