### ISSUE TITLE
Access for download dll file

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#804]
Hi dear 
How can we download last dll file with out source code ?
I can not use .nuget , any way ?

**Comment by mogikanin** [comment]
Use this [link](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master) to download latest binaries (from master branch).

Regarding to nuget packages. At the moment latest stable version is 1.9. Current master is under development, but probably it will be published into nuget as pre-release version soon.

**Comment by ZimaSystem** [comment]
Thank you
