### ISSUE TITLE
Improve performance load shape

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#806]
Hi dear
I have idea for improve shape world map performance
But i dont know is it best way or not if you have any better idea i need to do it
My idea : convert map1 to bitmap image and stop full drawing and show it until next map1 activity

**Comment by mogikanin** [comment]
Dear @ZimaSystem not sure that I understand what you mean. But you can try at first do these changes in your own fork. If they really improve performance, please submit them as pull request. We'll review it, and if everything fine then we merge it into repository. Also, before submitting PR, please read this [link](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md).

**Comment by ZimaSystem** [comment]
Okey thank you for your response , i try to write it ...

**Comment by mogikanin** [comment]
@ZimaSystem do you have plans to do something on this issue? Otherwise I'll close it.
