### ISSUE TITLE
How can Show label programmaticaly

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#808]
Hi dear
How can show city label on zoom programmaticaly ?
What are class and method for do it ?

**Comment by sindizzy** [comment]
Did you check here https://dotspatial.codeplex.com/documentation
~AGP

**Comment by ZimaSystem** [comment]
Thank you for your response
But i can not found it ! My you help me with document can help me about my question ?

**Comment by sindizzy** [comment]
https://dotspatial.codeplex.com/wikipage?title=DotSpatial%20Tutorials&referringTitle=Documentation
