### ISSUE TITLE
How can get list of layer ?

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#809]
Hi guys
How can i get list of layer and see name of active layer ?

**Comment by jany-tenaj** [comment]
Have a look at the following code. 

```
For Each layer As ILayer In Map.Layers 'this gets you all layers inside your map
            If layer.IsSelected Then 'this indicates whether the layer is currently selected
                Dim legendText As String = layer.LegendText 
                Dim fl As IFeatureLayer = TryCast(layer, IFeatureLayer)
                If fl IsNot Nothing Then
                    Dim fileName = fl.DataSet.Filename
                End If
           End If
Next
```

Not sure what name you want to get. There is layer.LegendText (that is shown in legend), layer.Name (not sure whether that is always set) and if you have a FeatureLayer there is also DataSet.Name (not sure whether that is always set) and DataSet.FileName.

**Comment by jany-tenaj** [comment]
@ZimaSystem If your questions was answered please close the issue.

**Comment by TongZhai** [comment]
It appears that `Map.Layers` gets a mixed list of `MapGroup`s and individual map layers, so if one needs to get all of the single map layers, one would need to use that '`TryCast`' to differentiate between `MapGroup` and individual map layers. I ***think*** `ILayer` is parent to both `MapGroup` and `IMapFeatureLayer`.
