### ISSUE TITLE
Add image to map1

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#810]
Hi dear
How can i add image to map1 ?
Note : User set lat and long and layer name manual. C#

How can i add layer for images and before do it check for exist ?
Sry if i writting eng bad ...

**Comment by jany-tenaj** [comment]
The user could add the image himself by opening the image with the "Add Layer..." button you can see in DemoMap. The same can be done by using 

```
   if (System.IO.File.Exists(@"D:\example.png"))
                map1.AddLayer(@"D:\example.png");
```

For what do you need the lat long the user set?

**Comment by ZimaSystem** [comment]
Ty but i need reprogram it ..
I need to add some layer and add some image in each layer
May u help me about it?

**Comment by ZimaSystem** [comment]
For what do you need the lat long the user set?

cause add shape , vertex or icon on center of that lat and long

**Comment by jany-tenaj** [comment]
I've got no idea what your trying to do there but maybe having a look at the [Getting Started Guide](http://download-codeplex.sec.s-msft.com/Download?ProjectName=dotspatial&DownloadId=1460427) will help you.
