### ISSUE TITLE
Draw polygon on the map

### ISSUE THREAD

**Issue by orbitzhan** [DotSpatial/DotSpatial#817]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.get geometry by mouse move and click
2.add geometry to IMapPolygonLayer, like
`polygonLayer.DataSet.AddFeature(_polygon as IGeometry);` 
3.symbolize, like
`polygonLayer.Symbolizer = new PolygonSymbolizer(Color.Green, Color.LightSkyBlue, 1);` 

DotSpatial version: 1.9

### Expected behaviour

draw polyons on the map， although overlap

### Actual behaviour
i don't know why the overlap of the polygons is white？

![2016-06-22_204903](https://cloud.githubusercontent.com/assets/13759823/16286065/8f6f736a-390c-11e6-9db8-c239a40e626f.png)

**Comment by jany-tenaj** [comment]
How did you create your polygons? Using the Editor plugin or by some code you wrote yourself?

**Comment by orbitzhan** [comment]
i write a mapfuction to import polygon into a MapPolygonLayer. The polygons are created by mouse activies. if i export the polygons to shpfile and reload the shpfile, it is correct.

**Comment by orbitzhan** [comment]
`protected override void OnMouseDoubleClick(GeoMouseArgs e)
        {
            _isEnabled = false;
            _coordinatePoints.Clear();
            for (int i = 0; i< _points.Count; i++)
            {
                _coordinatePoints.Add(_map.PixelToProj(new System.Drawing.Point(_points[i].X, _points[i].Y)));
            }
            _coordinatePoints.Add(_map.PixelToProj(new System.Drawing.Point(_points[0].X, _points[0].Y)));
            LinearRing linearRing = new LinearRing(_coordinatePoints.ToArray());
            _polygon = new Polygon(linearRing);
            if (_isROI)
            {
                _roiLayer.AddFeature(_polygon as IGeometry);
            }
            _points.Clear();
            _map.Refresh();
            _isEnabled = true;
        }`

**Comment by jany-tenaj** [comment]
Can you add the code that creates/loads the _roiLayer? From your comment I take it this is a layer that you don't save to shapefile?

Am I assuming correctly that you created your overlapping polygons the following way?

1. Click all the coordinates of polygon 1.
2. Double click to finish polygon 1 and add it to _roiLayer.
3. Click all the coordinates of polygon 2.
4. Double click to finish polygon 2 and add it to _roiLayer.

**Comment by orbitzhan** [comment]
Yes, you are correct. That's what I wanted. _roiLayer is a MapPolygonLayer which you can create and add to map. In my program like this:
`_roiLayer = new MapPolygonLayer;`
`map.Layers.Add(_roiLayer);`

**Comment by orbitzhan** [comment]
Hi, i think i find the problem. When i create polygons, there are two directions which i call clockwise and anti-clockwise. If the two polygons have different directions, it may get error when rander.

**Comment by orbitzhan** [comment]
Hi, i think i find the problem. When i create polygons, there are two directions which i call clockwise and anti-clockwise. If the two polygons have different directions, it may get error when rander.
![1](https://cloud.githubusercontent.com/assets/13759823/16298930/498ec324-396a-11e6-9d75-9f3a741ffb4d.png)

**Comment by jany-tenaj** [comment]
Yes I think you found your error.

The shapefiles definition says that polygon shells are orientated clockwise and holes are orientated counterclockwise.

So based on this you have to correct your features orientation before adding it to the layer. 

Be aware that you get more problems if you add polygons that were drawn like an 8 for example, because those have crossing lines that are not allowed.
