### ISSUE TITLE
Open contextmenu strip on right click

### ISSUE THREAD

**Issue by ZimaSystem** [DotSpatial/DotSpatial#819]
Hi dear
How can i open context menu strip on right click on vertext and feature on map1 ? 
Every feauter may in different layer
What is different between vertex and feature ?

**Comment by jany-tenaj** [comment]
A vertex is one point of your feature. 

Have a look at the MouseUp event of [ShapeEditors.AddShapeFunction](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Plugins.ShapeEditor/AddShapeFunction.cs).
There you can see how to call a context menu on right mouse click.

If you want to call the context menu only when clicking on a feature or vertex you have to check whether the mouseclick was over a feature or vertex.

[ShapeEditor.SnappableMapFunction](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Plugins.ShapeEditor/SnappableMapFunction.cs) shows you how to check whether your mouse was over a vertex.

You can check whether you were above a feature by calling the Select function of the featureLayer you're interested in with the mouse coordinate as the Extent. As you seem to be interested in all your layers you'll have to circle through them and check them all.

**Comment by ZimaSystem** [comment]
I look it but i can not understand how can it work .... please help me in short source code sample

**Comment by jany-tenaj** [comment]
Have a look at the example inside [ContextExample.zip](https://github.com/DotSpatial/DotSpatial/files/343031/ContextExample.zip). I wrote this based on the DotSpatial 2.0 source code.

**Comment by mogikanin** [comment]
@ZimaSystem issue is solved and we can close it?
