### ISSUE TITLE
Move FeatureSet.Filename / FilePath to DataSet

### ISSUE THREAD

**Issue by jany-tenaj** [DotSpatial/DotSpatial#821]
Currently classes derived from FeatureSet can be saved with relative path in dspx. 
But the image classes that were derived from DataSet are saved with absolute path because they each have their own Filename property that contains the absolute path and is serialized to dspx.

I'd like to move FeatureSet.Filename and FilePath to DataSet to use them as common properties for all derived classes as they seem to be file based anyway. That way we wouldn't have to implement the saving of the relative path in each class.

**Comment by mogikanin** [comment]
don't mind

**Comment by jany-tenaj** [comment]
@mogikanin can we remove MakeRelativePath from FeatureSet? It isn't used by anything and doesn't make any sense in FeatureSet.

**Comment by mogikanin** [comment]
yes, please remove `FeatureSet.MakeRelativePath()`
