### ISSUE TITLE
Affine coefficients in dotspatial

### ISSUE THREAD

**Issue by ghgetonup** [DotSpatial/DotSpatial#822]
Hi, I'm confused about the use and implementation of affine transformations in dotspatial, especially with respect to the meaning of the first and fourth elements of the array of affine coefficients (let's call them c[0] and c[3]). In RasterBoundsExt.cs affine coefficients are read from an esri world file where c[0] and c[3] represent the coordinates of the _center_ of the top left cell. This also fits with method CellCenter_ToProj() in AffineTransform.cs. However:

1. Method ProjToCell() in AffineTransform.cs only works correctly if c[0] and c[3] are the coordinates of the _top left corner_ (not the center) of the top left cell. The issue is on lines 168-169, where Math.Floor is used rather than Math.Round.

2. In GdalRaster.cs (line 584) the affine coefficients are extracted with GetGeoTransform(), which afaik returns c[0] and c[3] as the coordinates of the top left corner (not the center) of the top left cell.

**Comment by jany-tenaj** [comment]
Could be you're stumbeling about [this issue](https://github.com/DotSpatial/DotSpatial/issues/725).

**Comment by ghgetonup** [comment]
Yes it's related to the issue you linked to. These issues can be fixed by clearly defining what c[0] and c[3] represent (either center or top left of the top left cell) and then sticking with that definition in all code.

**Comment by mogikanin** [comment]
I think it supposed that c[0] and c[3] are coordinates of _centre_  of the top left cell.
e.g. see methods `AffineTransform.CellCenter_ToProj()` and `AffineTransform.CellTopLeft_ToProj`
So, all places where this rule is broken, must be fixed.

**Comment by ghgetonup** [comment]
Yes if you go with center of top left cell then at least two things need to be fixed:
1. Replace Math.Floor with Math.Round on lines 168-169 of AffineTransForm.cs (in projtocell method).
2. Shift c[0] and c[3] by half a cell in GdalRaster.cs after line 584 (in readheader method).

**Comment by mogikanin** [comment]
Yep. @ghgetonup would you like to create PR with all necessary changes (and with unit-tests too)? If so, please read this [link](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md) at first and then go ahead :)

**Comment by ghgetonup** [comment]
Sure I can implement these two fixes, if I can figure out this github thing....

**Comment by mogikanin** [comment]
Done. Thanks @ghgetonup !

**Comment by oscarafone77** [comment]
Hi Maxim, 

I tested the new changes to dotspatial related to this issue, and the solve the issue rised by me (# 725) which can now be closed

Thank you all for your kind effort in fixing bugs and improving Dotspatial
Oscar
