### ISSUE TITLE
Using PostGreSQL with DotSpatial

### ISSUE THREAD

**Issue by rupakraj** [DotSpatial/DotSpatial#827]
Dear Team,
I am planning to develop the **desktop application** using DotSpatial Engine. In summary my application is intended for doing different operation such as filtering the map, coloring the map as per filter criteria, searching on map, splitting the polygon etc.
I already have _geo-database_, which includes the collection of different polygon and their attributes (lets say: House and their owner information).
While going through the tutorials and documentation, I found that I can load map if we have **shp** file. 

My question is: How can I connect PostGreSQL geo-database with DotSpatial ? Is there any sample project or code snippet so that I can get started...

Thanks
Rupak Raj

**Comment by eptiliom** [comment]
It's as simple as just getting your data from the database and then building the featureset.

Use a .net postgres provider, select the data, create the featureset, add columns, populate the columns.

http://dotspatial.codeplex.com/wikipage?title=CreateAttributes&referringTitle=Desktop_SampleCode

**Comment by worlanyo** [comment]
Consider the plugins at this link, it would be very helpful

https://github.com/FObermaier/DotSpatial.Plugins/tree/master/DotSpatial.Plugins.Database

**Comment by rupakraj** [comment]
Thanks everyone for support, I am implementing this now.
