### ISSUE TITLE
Create Tutorial For Using DotSpatial Controls using WPF

### ISSUE THREAD

**Issue by BenjaminHolland** [DotSpatial/DotSpatial#828]
There should be at least one tutorial showing how to use DotSpatial in a context other than WinForms.
In particular, tutorials on how to use the extensions and plugins without the designer would be helpful, as well as information on how to properly size the Map control.

**Comment by mogikanin** [comment]
@BenjaminHolland would you like to create such tutorial?

**Comment by Enhakiel** [comment]
No need of tutorial, in your view:
`<WindowsFormsHost	Grid.Row="1"	HorizontalAlignment="Stretch"  VerticalAlignment="Stretch"	Focusable="True"
					ClipToBounds="True"
					>
	<dotSpatial:Map	x:Name="uxMap"	AutoSize="True" AllowDrop="False" AutoSizeMode="GrowAndShrink" Dock="Fill" 
					BorderStyle="Fixed3D" 
					ProjectionModeDefine="Never"		ProjectionModeReproject="Never"
					RedrawLayersWhileResizing="False"	CollectAfterDraw="True"
					MouseEnter="UxMap_OnMouseEnter"
					/>
</WindowsFormsHost>`

in code behind:
`	
private void UxMap_OnMouseEnter(object sender, EventArgs e)
{
	uxMap.Focus();
}
`

**Comment by BigBlueBob** [comment]
Now I have a problem with using the Map control in WPF.
I use VS2019, the framework is .Net Framework 4.7. I use WindowsFormsHost in Window's Xaml, I instantiate a Map in the constructor of the WPF application, use the following statement to assign values:
Map map = new Map();
windowsFormsHost.Child = map;

The first is debugging. When loading a small shp file, the function of the window and map is normal. However, when loading data with a large amount of data, such as I have a 16MB shpfile(Ploygon), when the window is maximized, the window area (such as the title bar or other controls) other than the map cannot be displayed normally, and it is displayed as Transparent or black screen, the control actually still exists in the position of the transparent or black screen. It can respond to the operation of the mouse, but its response is very slow. If you press any key on the keyboard, such as "ESC", the content of the window will return to normal. Repeatedly shrinking and maximizing the form, the above abnormal phenomenon will still occur about 5-6 times, and then the phenomenon will no longer appear (depending on the size of the shp file, the larger the shp, the longer the phenomenon will last, even by Also appears when maximized to normal).

Then, I directly ran the generated exe application, tried to reproduce the above problem, and maximized the form after loading the 16MB shp, and found that the form including the map was displayed normally, without transparency or black screen, but the response was still very slow, after pressing the keyboard button, returns to normal, and there is no such phenomenon after repeated several times.

I guess if there is some problem with VS itself, or the Map control is not compatible with WPF, or my framework is not suitable?
