### ISSUE TITLE
Saveing feature layer that is created from selected elements

### ISSUE THREAD

**Issue by eroshani** [DotSpatial/DotSpatial#829]
If a layer is built using a set of selected elements from another layer, the layer.featureset.name and featureset.filename remain null. Therefore it is not possible to save the layer. Meaning that featureset.save() raises an exception.
I set those value and was able to save the layer without raising the exception but when I open the same layer it is empty. None of the selected features are in the file.

I would appreciate any help.

Regards,

**Comment by sindizzy** [comment]
Can you post your code.

**Comment by eroshani** [comment]
You can replicate the bug using the demo program.
All you need to do is:
Open a shapefile/layer. select some of the elements, while selected right click on the layer name in the legend window and from the selection menu choose create a layer from selected elements. It will build a layer and add it to your legend window which correctly shows all of the elements.
But if you try to save the layer/project you will get the error.

**Comment by sindizzy** [comment]
oic.
