### ISSUE TITLE
Migrate all missing source code and projects from CodePlex to GitHub

### ISSUE THREAD

**Issue by stakx** [DotSpatial/DotSpatial#834]
The [DotSpatial project page on CodePlex](https://dotspatial.codeplex.com/) states in big letters that DotSpatial "is now moved" here, to GitHub. Unfortunately, that phrase does not make it clear that code migration is not complete yet, or whether this might still be an ongoing effort.

In any case, the note says that the latest code may be found here, but some code appears to be missing on GitHub, e.g. the entire `DotSpatial.Topology` project. This leads to the unfortunate situation that one doesn't know where issues, pull requests etc. concerning the missing code should be posted. The CodePlex site states that discussion and new issues should be posted here on GitHub, but it doesn't seem to make much sense to post issues for code that resides in a different location.

I'd therefore like to request that **all** missing projects and source code be moved from CodePlex to GitHub, so that there will no longer be any ambiguity about where to post issues, discussions, or publish pull requests.

(If this is not possible or not desired by the project team for some reason, please update the note on CodePlex to make it clear how exactly the project is split between CodePlex and GitHub.)

**Comment by jany-tenaj** [comment]
There is no need for DotSpatial.Topology anymore. DotSpatial 2.0 is using DotSpatial.GeoApi and DotSpatial.NetTopologySuite instead. The code residing on GitHub is a complete DotSpatial project that might not be completely stable based on the fact that we might have missed some errors while switching from DotSpatial.Topology to NTS and GeoApi.


See also issue #786.

**Comment by stakx** [comment]
Thank you for replying so quickly. I did not realise that DotSpatial.Topology has been superseded. I'm assuming that this has happened only recently and the documentation hasn't been brought fully up to date yet?

**Comment by stakx** [comment]
Thank you, I understand what you're saying. I'll be closing this issue then.

I would just like to make one final suggestion, namely that the documentation be brought up to date to reflect what you are saying. For example, the GitHub `Readme.md` (probably the very first piece of documentation that people coming to DotSpatial will see) still links to the DotSpatial 1.9 NuGet packages (including the old DotSpatial.Topology), and does not even mention the new GeoAPI and NetTopologySuite. I can appreciate that DotSpatial 2.0 perhaps isn't quite ready yet, but it would help interested developers if the two DotSpatial project pages were a bit more explicit about what is current, and what isn't.

Thank you, in any case, for taking the time to reply!
