### ISSUE TITLE
how can use Osm Raw Data?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#835]
hi dear
i need to show map same as the first index of openstreetmap.org
i know that is not a shp file , "that is raw osm data" 
so how can i use raw osm data in Dotspatial ?
i need to show sea line

**Comment by jany-tenaj** [comment]
Try using the WebMap plugin. It is able to show open street map.

**Comment by DavisMillier** [comment]
@jany-tenaj Thank you for response.
