### ISSUE TITLE
how can i make layer and move point parent layer ?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#836]
hi dear
can you help me about make layers ?
do i need to define feature set for every layer or one featureset enough for different layers ?
and after that when i add "point" to one of the layer i need to change the parent of the point layer
how can i move one or more point from one layer to another layer ?

**Comment by jany-tenaj** [comment]
Have a look at the [documentation](https://dotspatial.codeplex.com/documentation). It could be a little outdated but you should be able to understand how to create layers.

You need one featureset for each layer.

If you want to move points between layers you'll have to remove the point from the first layer and add it to the second.

**Comment by DavisMillier** [comment]
how can i get the point coordinate for set on the new layer ?

**Comment by jany-tenaj** [comment]
Sorry, but I've got no idea what your question is supposed to mean.

**Comment by DavisMillier** [comment]
i mean how can i pickup point coordinate on the layer for set it on new layer ?

**Comment by DavisMillier** [comment]
this is my code ...
layer not change when i call this method 
how can i do it ? 
`        public void test(Coordinate coord,string ftype)
        {

            foreach (var item in map1.Layers)
            {
                if (item.LegendText ==ftype)
                {
                    int selectedIndex = map1.Layers.IndexOf(item);
                    //map1.Layers.SelectLayer(index);

                    //var selectedIndex = 0;

                    ((Legend)map1.Legend).ClearSelection();
                    map1.Layers[selectedIndex].IsSelected = true;
                    map1.Layers.SelectedLayer = map1.Layers[selectedIndex];
                    map1.Legend.RefreshNodes();
                    label1.Text = Convert.ToString(selectedIndex);
                }

            }
            DotSpatial.Topology.Point point = new DotSpatial.Topology.Point(coord);
            IFeatureSet ifs = new FeatureSet(FeatureType.Point);

            IFeature currentFeature = ifs.AddFeature(point);
            //IFeature currentFeature = new Feature(DotSpatial.Topology.FeatureType.Point);
            //currentFeature.DataRow["ID"] = pointID;
            //currentFeature.DataRow["label"] = "point #" + pointID.ToString();
            DotSpatial.Symbology.CharacterSymbol pcs = new DotSpatial.Symbology.CharacterSymbol('o', "Webdings", Color.Black, 32);
            DotSpatial.Symbology.PointCategory pc = new DotSpatial.Symbology.PointCategory(pcs);
            //Sweep Character For Show Shape Heading
            pcs.Angle = 270;

            pc.Symbolizer.ScaleMode = ScaleMode.Simple;
            //pc.FilterExpression = "[ID]='" + currentFeature.DataRow["ID"].ToString() + "'"; // <-- this is extremely important.Here the point ID is set
            //pc.LegendText = currentFeature.DataRow["label"].ToString();
            pointScheme.AddCategory(pc);

            mpl.Symbology = pointScheme;
            mpl.ApplyScheme(pointScheme);


            _tempLayer = mpl;


            map1.MapFrame.DrawingLayers.Add(mpl);


            map1.MapFrame.Invalidate();
            map1.Invalidate();
            pointID++;
            map1.FunctionMode = FunctionMode.None;

        }`
