### ISSUE TITLE
where Can i Download  basic definitions of Dotspatial

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#837]
hi dear
i need to download documents about basic definitions dotspatial method name
for example what is the Feature , FeatureSet , iFeature , Envelope , project , reproject , raster 
and etc ...
how can i found documents to know what is that ?

**Comment by jany-tenaj** [comment]
Have a look at the [sdk style documentation](https://dotspatial.codeplex.com/wikipage?title=DotSpatial%20SDK%20Documentation%20).

**Comment by DavisMillier** [comment]
@jany-tenaj  Thank you for response i see that but it is incomplete...
i try to know Dotspatial and be a Developer on it soon...
