### ISSUE TITLE
How can I add point feature to specific layer programmatically?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#838]
Hi there.
I put a combo box that show list of layers on the form
and 2 text box for insert lat and long of point
and button to insert feature ...
so this is my question : How can I add point feature to specific layer programmatically?

**Comment by sindizzy** [comment]
have you checked out https://dotspatial.codeplex.com/documentation

**Comment by DavisMillier** [comment]
i can't found any good documents for my problem , may u help me with sample source code ?

**Comment by sindizzy** [comment]
Not sure what you mean as under Code Snippets there are several examples on how to insert a point feature.

**Comment by DavisMillier** [comment]
yes i saw that i can insert point on feature ... but always inserted on last added layer ...
if i make 3 layer , point always insert in last layer ...
i cant found way to insert point on other layer

**Comment by sindizzy** [comment]
You have to reference the correct layer. each layer has a reference. Set the featureset to the one you want to edit.
Dim fs As IFeatureSet = {selected layer or specific layer}

**Comment by DavisMillier** [comment]
Exactly this is my question : how can i change selected layer or define specific layer ?
Dim fs As IFeatureSet = {**selected layer or specific layer**}
or
IFeatureSet fs = {**selected layer or specific layer**}

**Comment by sindizzy** [comment]
Try map.Layers to get a reference to the layer and then query the featureset.

**Comment by sindizzy** [comment]
try this
https://dotspatial.codeplex.com/discussions/549964

**Comment by DavisMillier** [comment]
it is not work ...
fs = Map1.Layers.Item(0).DataSet have Error
i try this before start topic but it is not work
```
            foreach (var item in map1.Layers)
            {
                if (item.LegendText ==ftype)
                {
                    selectedIndex = map1.Layers.IndexOf(item);
                    

                    //var selectedIndex = 0;

                    ((Legend)map1.Legend).ClearSelection();
                    map1.Layers[selectedIndex].IsSelected = true;
                    //map1.Layers.SelectedLayer = map1.Layers[selectedIndex];
                    map1.Layers.SelectLayer(selectedIndex);
                    map1.Legend.RefreshNodes();
                    label1.Text = Convert.ToString(selectedIndex);
                }

            }
```

**Comment by DavisMillier** [comment]
how can i reference selected layer to new IFeatureSet ?

**Comment by DavisMillier** [comment]
I found it We should to Change Mappointlayer

first found indexof layer 
`selectedIndex = map1.Layers.IndexOf(item);`
 then set it on map point layer
`mpl= (MapPointLayer)map1.Layers[selectedIndex];`

**Comment by DavisMillier** [comment]
Sry for Reopen ...
i do that i think it is ok
selectedIndex = map1.Layers.IndexOf(item);
then set it on map point layer
mpl= (MapPointLayer)map1.Layers[selectedIndex];
but it is make duplicates feature on other layer ... 
my u help me plz ?

**Comment by oscarafone77** [comment]
Dear Davis,

here some code that might help you (sorry it is vb, not c#, but you might find an automatic translator on the web).
First, when you fill the combo box with the selectable layers you might get track of the original index of each added layer in the layer tree:

`      
public iplayers() as integer   ///this vector stores for each layer added in your combobox the original position in layer tree 

        ComboBox1.Items.Clear()
        ///First add only point layers to your combobox
        For i As Integer = 0 To nlayers - 1
            If TryCast(mapDSform.Map1.Layers(i), IPointLayer) Is Nothing = False Then
                np = np + 1    /// number of layers added to your combobox
                ReDim Preserve iplayers(np)   ///this keeps all previous inserts in iplayers while increasing its size
                iplayers(np - 1) = i ///here you store at position np-1 in your combobox, the position "i" which is the position in the original layer tree 
                ComboBox1.Items.Add(mapDSform.Map1.Layers(i).LegendText);   ///this adds the layer name to the combobox
            End If
        Next
`

with the code above you filled the combobox with the appropriate selectable point layers. Moreover, you have now a vector named "iplayers" which has number of items equal to the number of layers in combobox, and in each position it stores the original position of the layer in dotspatial layer tree.

Once the user has selected the layer and clicked on the map, you may add the clicked point to the layer from layer tree in this position

`Map1.Layers(iplayers(ComboBox1.SelectedIndex))`

It is not a very elegant way I guess, but in my project it works. Maybe there is a easier and more beautiful way, but I don't know it.

Hope it helps

Oscar

**Comment by DavisMillier** [comment]
i have no problem in make list of layer in combo box ...
            foreach (var item in mapName.Layers)
            {
                cmbLayerList.Items.Add(item.LegendText);

            }
i can change active layer with this code 
            foreach (var item in map1.Layers)
            {
                if (item.LegendText ==ftype)
                {
                    selectedIndex = map1.Layers.IndexOf(item);
                    break;
                }
            }
MapPointLayer  mpl3 = (MapPointLayer)map1.Layers[selectedIndex];
but when i add point to map1 it also add on last layer made
so i try to direct use imaplayer 
but when i change layer and add point point was added in the last selected and new select and make all added point in last selected layer into new selected layer

**Comment by DavisMillier** [comment]
@oscarafone77 i found where am i wrong ...
i try to write sample code ... if i am not success , i ask for help
