### ISSUE TITLE
how can add text under feature on map ?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#839]
hi dear 
how can i add feature label or some text under/near feature "point , line , polygon" on map layer ?

**Comment by sindizzy** [comment]
Lots of examples here https://dotspatial.codeplex.com/documentation

**Comment by DavisMillier** [comment]
Yes , i was saw that example but not help me ...
i need to add image with a text under it, when i select image , text is select too

**Comment by DavisMillier** [comment]
@sindizzy Thank you for your response

**Comment by haydarai** [comment]
@DavisMillier so how did you actually done it?
