### ISSUE TITLE
LAEA NaN bug and possible solution

### ISSUE THREAD

**Issue by iratxoalbentia** [DotSpatial/DotSpatial#843]
The LAEA Transform seems to be broken. Any transform (direct or inverse) is resulting in a NaN value.

DotSpatial version: 
I have tested it in the 1.9 binary donwloadable version and after building the dotspatial-9be3db98e21ba9bb7ce0c622dfebbd044beadc84. it

It seems that the initialization of the LAEA Transform is wrong.

File Projections/Transforms/LambertAzimuthalEqualArea.cs, line 328 reads:
                     _sinb1 = Proj.Qsfn(sinphi, E, OneEs);
And based on PJ_laea.c it should read:
                     _sinb1 = Proj.Qsfn(sinphi, E, OneEs)/_qp;

Regards!

    Iratxo.

**Comment by mogikanin** [comment]
Iratxo, please try latest 2.0 version. This issue should be already fixed.

**Comment by iratxoalbentia** [comment]
It seems that 2.0 version is not already released, right? I have tried downloading the trunk and the problem appears to be there.

**Comment by jany-tenaj** [comment]
@iratxoalbentia Have a look at [line 329 of LambertAzimuthalEqualArea.cs](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Projections/Transforms/LambertAzimuthalEqualArea.cs#L329). It contains the change you're talking about. You can find the compiled dlls of the current master version [here](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master).

**Comment by mogikanin** [comment]
Already fixed.
