### ISSUE TITLE
polygon intersection error

### ISSUE THREAD

**Issue by sendreams** [DotSpatial/DotSpatial#844]
_IF BUG, INCLUDE THIS PART:_
### Steps to reproduce
1. two polygon, coordates is below:
   {LINEARRING (0.0000000000000000 -6.1026585365860800, 3.8000000000000000 -5.7690000000000000, 7.9000000000000000 -5.4090000000000000, 12.0000000000000000 -5.3690000000000000, 16.1000000000000000 -5.0990000000000000, 20.3000000000000000 -5.1390000000000000, 24.5000000000000000 -4.9090000000000000, 28.5000000000000000 -4.6390000000000000, 32.6000000000000000 -4.1890000000000000, 36.6000000000000000 -3.2890000000000000, 40.8000000000000000 -3.1890000000000000, 44.8000000000000000 -2.9490000000000000, 49.0000000000000000 -2.8200000000000000, 53.3000000000000000 -2.3600000000000000, 57.3000000000000000 -2.1400000000000000, 61.3000000000000000 -1.5200000000000000, 65.5000000000000000 -1.3900000000000000, 69.6000000000000000 -1.1700000000000000, 73.6000000000000000 -1.0100000000000000, 77.9000000000000000 -0.9700000000000000, 82.0000000000000000 -0.8000000000000000, 86.2000000000000000 -0.7400000000000000, 90.2000000000000000 -0.6700000000000000, 94.5000000000000000 -0.6000000000000000, 98.6000000000000000 -0.5000000000000000, 102.6000000000000000 -0.3900000000000000, 106.9000000000000000 -0.2400000000000000, 111.1000000000000000 -0.1500000000000000, 115.1000000000000000 -0.1510000000000000, 119.2000000000000000 -0.1510000000000000, 123.1000000000000000 -0.0510000000000000, 127.2000000000000000 0.0590000000000000, 131.2000000000000000 0.2090000000000000, 132.2000000000000000 1.0250000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 0.5000000000000000, 128.6000000000000000 0.5000000000000000, 106.2000000000000000 -2.3000000000000000, 49.9000000000000000 -2.3000000000000000, 31.0000000000000000 -5.4500000000000000, 0.0000000000000000 -5.4500000000000000, 0.0000000000000000 -6.1026585365860800)}

{LINEARRING (0.0000000000000000 2.6400000000000000, 0.0000000000000000 -6.0030697674418800, 0.3200000000000000 -5.9800000000000000, 4.6200000000000000 -5.6700000000000000, 8.8100000000000000 -5.1600000000000000, 13.1000000000000000 -5.2100000000000000, 17.1200000000000000 -4.8400000000000000, 21.2800000000000000 -5.1700000000000000, 25.5000000000000000 -5.1600000000000000, 29.7100000000000000 -4.6700000000000000, 34.1300000000000000 -3.9000000000000000, 38.2800000000000000 -3.4800000000000000, 42.6400000000000000 -3.3000000000000000, 46.9800000000000000 -3.2600000000000000, 51.1600000000000000 -2.8900000000000000, 55.3200000000000000 -2.8300000000000000, 59.3000000000000000 -2.9200000000000000, 63.6800000000000000 -2.3600000000000000, 67.4800000000000000 -2.5700000000000000, 70.8900000000000000 -2.4800000000000000, 74.8900000000000000 -2.5500000000000000, 78.8800000000000000 -2.6900000000000000, 82.4400000000000000 -2.4600000000000000, 87.5300000000000000 -2.8100000000000000, 91.6200000000000000 -2.7500000000000000, 95.9000000000000000 -2.1000000000000000, 100.2200000000000000 -2.2100000000000000, 104.4400000000000000 -2.3000000000000000, 109.1500000000000000 -1.9500000000000000, 113.2400000000000000 -2.8200000000000000, 117.2400000000000000 -1.9600000000000000, 120.9400000000000000 -1.3000000000000000, 125.0300000000000000 -0.8200000000000000, 126.6800000000000000 0.1300000000000000, 132.5500000000000000 1.5400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 0.0000000000000000 2.6400000000000000)}
2. invoke polygon's intersection function, will throw exception
3. the exception stack & message: no outgoing dirEdge found [ DotSpatial.Topology.Coordinate ]
   在 DotSpatial.Topology.GeometriesGraph.DirectedEdgeStar.LinkResultDirectedEdges()
   在 DotSpatial.Topology.GeometriesGraph.PlanarGraph.LinkResultDirectedEdges(IList nodes)
   在 DotSpatial.Topology.Operation.Overlay.PolygonBuilder.Add(IList dirEdges, IList nodes)
   在 DotSpatial.Topology.Operation.Overlay.PolygonBuilder.Add(PlanarGraph graph)
   在 DotSpatial.Topology.Operation.Overlay.OverlayOp.ComputeOverlay(SpatialFunction opCode)
   在 DotSpatial.Topology.Operation.Overlay.OverlayOp.GetResultGeometry(SpatialFunction funcCode)
   在 DotSpatial.Topology.Operation.Overlay.OverlayOp.Overlay(IGeometry geom0, IGeometry geom1, SpatialFunction opCode)
   在 DotSpatial.Topology.Geometry.Intersection(IGeometry other)
   在 Ware4u.Geomatics.Section.DotSpatialTest.Clip(GeoRegion region1, GeoRegion region2)

DotSpatial version: 1.9
### Expected behaviour

the intersection of two polygon, may be one or more ploygons.
### Actual behaviour

throw exception.

net framework 4.0,
win10 ent 64. 
vs2015,

**Comment by jany-tenaj** [comment]
@sendreams Please try the latest 2.0 version. This issue should be already fixed.

**Comment by sendreams** [comment]
@jany-tenaj i can not find 2.0 version in release, the latest is 1.9. how can i download 2.0? thanks

**Comment by sendreams** [comment]
@jany-tenaj DotSpatial.Topology now exchange to DotSpatial.NetTopologySuite?

**Comment by sendreams** [comment]
@jany-tenaj
