### ISSUE TITLE
LineString clip return null

### ISSUE THREAD

**Issue by sendreams** [DotSpatial/DotSpatial#845]
_IF BUG, INCLUDE THIS PART:_
### Steps to reproduce

1.a lineString with:
{LINESTRING (0 -5.15, 30 -5.15, 48.9 -2, 105.2 -2, 127.6 0.8, 132.6 0.8)}
2. clip with a rectangle polygon with 
{LINEARRING (15.325555555555553 0.8, 42.309375 0.8, 42.309375 -5.15, 15.325555555555553 -5.15, 15.325555555555553 0.8)}
3. return null

DotSpatial version:  2.0
### Expected behaviour

should return a LineString
### Actual behaviour

return null

**Comment by sendreams** [comment]
i'm sorry, it doesn't return null but return a MultiLineString object, why?

**Comment by mogikanin** [comment]
Please provide unit-test to reproduce issue, and explain why you expecting another result.

**Comment by mogikanin** [comment]
Close it since there is no response [much time](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md#common-rules). If you think the issue is actual, feel free to reopen it.
