### ISSUE TITLE
VisibilityExpression for layers

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#846]
In MapWindow you could set the .VisibilityExpression property of a layer and the framework would only display the filtered data. In ArcGIS you can do the same with a Definition Query. I don't see how to do it in DotSpatial. I can do it with categories but don't necessarily want my layer categorized. I just want to show part of the features. For example I have a Lat/Lon polyline shapefile. I want to load it but only display the 45N latitude.

Tried to use layerLine.Symbology.GetCategories.First.FilterExpression = "[VALUE] = '35N'" but doesn't seem to work.

**Comment by jany-tenaj** [comment]
This works alright. You just have to run `layerLine.ApplyScheme(layerLine.Symbology);` afterwards to update the displayed features.
