### ISSUE TITLE
How Can i get list of DataTable in DataSet ?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#847]
Hello Sir/Madam
May you help me how can i get list of datatable in layer Dataset ?
And How can i select layer with Dataset name ?
i try to add feature directly in Datatable ,  is this right way ?
How can i get Control of one exist layer with Dataset name ?

Where are lat and long of feature stored?

Thank You

**Comment by sindizzy** [comment]
Have you tried the documentation? I see samples for most of your questions here http://dotspatial.codeplex.com/wikipage?title=Desktop_SampleCode

**Comment by DavisMillier** [comment]
@sindizzy Thank you for your response
i saw that but i can not understand what should i do
may u send me sample code here ?

**Comment by sindizzy** [comment]
Do this:
```
            'Dim lyr As MapPolygonLayer = CType(myGroup.Layers(0), MapPolygonLayer) 'if using a group
            Dim lyr As MapPolygonLayer = CType(map.Layers(0), MapPolygonLayer) 'if no groups
            Dim fs As IFeatureSet = lyr.FeatureSet
            Debug.Print("Records=" & fs.DataTable.Rows.Count)
```

Make sure you are using the right type of MapXYZLayer object and also make sure that you are referencing a feature layer and not a category.

**Comment by DavisMillier** [comment]
@sindizzy Thank you in Advance
I can not found CType in MapPolygonLayer Class
is it work for 1.9 ?
may you check it again ?

**Comment by DavisMillier** [comment]
I realized Ctype is a Vb Command ... I should use Cast in C# ....
Thank You Dear @sindizzy

**Comment by DavisMillier** [comment]
@sindizzy id Dot that you say it finally work ...
but as you said it not work when i add category ....
do you have any idea about my new problem ?

**Comment by sindizzy** [comment]
The categories are enumerable just like layers. Do the same thing. Or if you want you can assign your category to a global variable. Look at the documentation SDK under DOTSPATIAL SDK STYLE DOCUMENTATION. That should show you all that is available to you. You should download the CHM help file and spend some time reviewing it.

**Comment by DavisMillier** [comment]
@sindizzy thank you for response
I do it .

**Comment by mogikanin** [comment]
@DavisMillier can we close the issue?

**Comment by DavisMillier** [comment]
@mogikanin Thank you for your respect
