### ISSUE TITLE
what is Indexmode and Editmode ?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#848]
Hello
Who can tell me what are Indexmode , Editmode ?
And how can i Get the Edit layer feature with call layer name ?

**Comment by mogikanin** [comment]
See xml docs.
[EditMode](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Symbology/IFeatureLayer.cs#L328)
[IndexMode](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Data/IFeatureSet.cs#L329)
