### ISSUE TITLE
The EPSG code is reported as 0 altough for known coordinate system

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#853]
Example: The EPSG code for coordinate system SWEREF99 TM is 3006, but
KnownCoordinateSystems.Projected.NationalGridsSweden.SWEREF99TM.EpsgCode returns 0 instead of 3006.

There are many other projections where the EPSG code returned is 0.

**Comment by pedwik** [comment]
I see know that EpsgCode is obsolete and replaced with AuthorityCode but the problem is the same.

**Comment by mogikanin** [comment]
dup #729

**Comment by mogikanin** [comment]
At least for Swedish projections it is fixed, so I'm closing it. For others leave open #729

**Comment by mogikanin** [comment]
@pedwik I did some refactoring in Swedish projections initialization. Take a look [into it](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Projections/ProjectedCategories/NationalGridsSweden.cs#L69). If you know mappings for other national grids, and have time to fix them - feel free to create PRs.
