### ISSUE TITLE
Bug In Zoom On point with 2 symbol Category

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#857]
_IF BUG, INCLUDE THIS PART:_
### Steps to reproduce

Add Point Layer With to simple symbol for each point when zoom Symbols was hide

DotSpatial version: 1.8 1.9
### Expected behaviour

Fix symbol Show in Zoom

**Comment by mogikanin** [comment]
Can you test it with DS2.0? If it reproduces, please attach also test project to reproduce.

**Comment by DavisMillier** [comment]
No , I can not found anywhere for download Ver.2
May you help me download it ?

**Comment by mogikanin** [comment]
Here the [link](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master)

**Comment by mogikanin** [comment]
I guess this not reproduced. Closing.
