### ISSUE TITLE
Imagelayer Symbol

### ISSUE THREAD

**Issue by zyhgis** [DotSpatial/DotSpatial#858]
In the tutorial,I learned how to change the symbol of raster,but I wonder how to change the symbol of imagelayer such as tiff? And if there is a api document for developer?
Thank you!

**Comment by mogikanin** [comment]
Take a look into API documentation at (codeplex)[https://dotspatial.codeplex.com/documentation]. It's a bit out of date, but mostly correct.

**Comment by zyhgis** [comment]
Yes,I noticed that,but in fact I think maybe it cannot be named api document but a guide book.Thank you all the same.
