### ISSUE TITLE
Pull request: Add ToolStripComboBox as optional parameter to method Add(DropDownActionItem item) in MenuHeaderBarControl

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#859]
I am not using Git yet, so I post the suggested change like this.

I have a derived ToolStripComboBox component that I want to use as combobox in DropDownAction item. The problem is the when adding a DropDownActionItem with MenuBarHeaderControl, a new ToolStripComboBox is created and it is messy to try to fix it afterwards.

Suggested change is simply to change from

```
public void Add(DropDownActionItem item)
            {
                var strip = GetOrCreateStrip(item.GroupCaption);
                var combo = new ToolStripComboBox(item.Key);

```
to
```
public void Add(DropDownActionItem item, ToolStripComboBox comboBox = null)
            {
                var strip = GetOrCreateStrip(item.GroupCaption);
                var combo = comboBox ?? item.combobox ?? : new ToolStripComboBox(item.Key);
              combo.Name = item.Key;
``` 

One could also allow for adding an optional ToolStripComboBox argument to the DropDownActionItem constructor itself.

**Comment by mogikanin** [comment]
Ok, good suggestion. I'll add this soon. But please, use Git for PR, it's not so hard :)

**Comment by mogikanin** [comment]
>  an optional ToolStripComboBox argument to the DropDownActionItem constructor itself.

This will be logically wrong, because `DropDownActionItem` (as well as any `ActionItem`) should not know anything about gui controls.

Also, note that you always can create own inheritor of `IHeaderControl`, `HeaderControl` or `MenuBarHeaderControl` with any behaviour.

**Comment by pedwik** [comment]
Concerning the latter (to add to the DropDownActionItem constuctor), the DropDownActionsItem has a public property of type ToolStripComboBox.

**Comment by mogikanin** [comment]
>  DropDownActionsItem has a public property of type ToolStripComboBox.

Not [anymore](https://github.com/DotSpatial/DotSpatial/commit/803a05c1c7a86b7a405890ff8a8ef7f6b28f17e9#diff-32bb3cb9f93e67892daceb94761c6750L20).

**Comment by mogikanin** [comment]
There is no plans to do suggested change. Close it.
