### ISSUE TITLE
Licensing: Is it MIT or LGPL?

### ISSUE THREAD

**Issue by theroc** [DotSpatial/DotSpatial#869]
Good morning,

We love the library and it is truly awesome but I'm trouble convincing my team that this is suitable for our next commercial venture. The issue only centres around licensing. Most of the source code still references LGPL. The GitHub repo and various files in DotSpatial.Positioning all reference MIT. Are portions licensed under other terms? or can the whole project be considered MIT?

Many thanks

**Comment by mogikanin** [comment]
It is MIT. I think we have to update all source code files to avoid confusions.

**Comment by theroc** [comment]
Thank you :), perhaps a paragraph could be added to the landing page on the GitHub project, something like: "The original DotSpatial (dotspatial.codeplex.com) was released under the LGPL, the new version is released under the MIT license."

Awesome project btw

**Comment by mogikanin** [comment]
Thanks :)
