### ISSUE TITLE
Update proj4 strings

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#870]
In #861  it was noted the proj4strings are not up to date.

**Comment by mogikanin** [comment]
If someone have actual proj4strings, feel free to contribute.

**Comment by pedwik** [comment]
What about using the latest version from the Proj4 project itself?
https://github.com/OSGeo/proj.4/blob/master/nad/epsg

If AuthorityCodeHandler is modified to handle that format instead it would simplify future upgrades. The file contains commented name tags that could also be utilized.

**Comment by mogikanin** [comment]
Yes, good suggestion. Let's use epsgs file in same format.
