### ISSUE TITLE
'System.Reflection.ReflectionTypeLoadException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by haydarai** [DotSpatial/DotSpatial#872]
### Steps to reproduce
I'm trying to create a user control with DotSpatial.
1. I build the Windows Form Control Library Project and add the `.dll` file to the reference of the Windows Form Application project.
2. However when I add the user control and call `appManager1.LoadExtensions();` it generates an exception `An unhandled exception of type 'System.Reflection.ReflectionTypeLoadException' occurred in mscorlib.dll`.

DotSpatial version: 1.9

### Expected behavior

No exception occurs.

### Actual behavior

`An unhandled exception of type 'System.Reflection.ReflectionTypeLoadException' occurred in mscorlib.dll`

What should I do? Does DotSpatial control unable to be used as Windows Form Control Library?

**Comment by mogikanin** [comment]
Please attach sample project to reproduce.

**Comment by haydarai** [comment]
Never mind, it was my fault by adding DotSpatial references with different version and thus make the exception occurred. Closing this issue now.
