### ISSUE TITLE
LayerKey for layers

### ISSUE THREAD

**Issue by sindizzy** [DotSpatial/DotSpatial#878]
MapWindow has this property called LayerKey that is used like so Map.LayerKey that can store some bit of info as the user sees fit. I load a description of the layer like so
Map.LayerKey(hnd) = shapeType & numShapes & calcTime

Later when a user hovers over the polyline I can show that info in a Tooltip. Does DotSpatial have a property that can hold a string of data like LayerKey?

**Comment by mogikanin** [comment]
There is no such property. But, for example, you can easily  create own dictionary in your program to store custom information per layer.
