### ISSUE TITLE
How can use Position Dll class method same as Azimuth , distance , etc in Dotspatial ?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#879]
Hello 
I need to know how can i use Azimuth , Distance , Angle in Dotspatial.position ?
May you help me or share some documents about it ?
Thank you.

**Comment by sindizzy** [comment]
I would suggest downloading the CHM file here https://dotspatial.codeplex.com/wikipage?title=DotSpatial%20SDK%20Documentation%20 and then searching for Position. Looks like most of the classes are there.

**Comment by DavisMillier** [comment]
Thank you @sindizzy 
I Found Bearing and distance but i can not method for calculate azimuth between 2 lat and long how can i do it ?
And i need to know how can calculate angle between 2 line ?

**Comment by DavisMillier** [comment]
Sry for new Replay New Issue
] try using Start.BearingTo(Dis point) but i just return Direction i need bearing in degree !
how can be do it ?

**Comment by DavisMillier** [comment]
Dear @sindizzy
may u Help me ?

**Comment by gojanpaolo** [comment]
Position.BearingTo(Position destination) returns an Azimuth.
You can then use Azimuth.DecimalDegrees to get bearing in degree.

**Comment by DavisMillier** [comment]
Thank you Dear @gojanpaolo 
And how can i calculate Angle Between 2 line ?
