### ISSUE TITLE
AttributeTable - Can't handle all field types, fails to handle null values properly

### ISSUE THREAD

**Issue by mkaring** [DotSpatial/DotSpatial#880]
I am encountering major issues when trying to read and write values from shape files containing null values in numeric fields and real number fields just as Long ("L") fields.

I am working at a pull request to resolve that and extend the capabilities of the `DotSpatial.Data.AttributeTable` class according to the specifications of the [dBase data format](http://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm).

**Comment by mogikanin** [comment]
Sure, waiting for PR :)

**Comment by mkaring** [comment]
There it is... 
All in all I am not absolutely happy with the state. The entire structure of the AttributeTable and it's supporting classes is pretty messy and a lot of things are defined and mapped in two or three places in different ways. That does not make things easier.

I think the mapping of the different dBase field types to the .NET data types should happen in the `Field` class along with parsing the values. Currently some mapping happens in the `Field` class and some directly in the `AttributeTable`.

**Comment by mogikanin** [comment]
Agree, it requires good refactoring.
