### ISSUE TITLE
Shp Writer

### ISSUE THREAD

**Issue by vahidarr** [DotSpatial/DotSpatial#883]
DotSpatial version: latest Version

I have latitude and longitude Data in my DB now I just want create one simple shp file (point or polyline or polygon) in my project.which class i need?

**Comment by jany-tenaj** [comment]
Have a look at the [featureset examples](http://dotspatial.codeplex.com/wikipage?title=Desktop_SampleCode).

**Comment by vahidarr** [comment]
tnx
