### ISSUE TITLE
Constructing shapefiles in memory

### ISSUE THREAD

**Issue by donogst** [DotSpatial/DotSpatial#885]
This is my first time trying to contribute to open source so sorry for any breaches in etiquette. 

I am trying to use dotspatial to create a shapefile on the fly in a web app.  I can create them to disk no problem but this is not an option on my server, I need to create them purely in memory.

My original plan was to construct each file in memory as a stream and then wrap the streams in a zip for download but the existing API does not seem well suited to this. I don't want to make too much mess and I would prefer to have a result that would be useful to the community.

I wondered if anyone has tried doing it in memory in the past? Or if there is any reason it would be impossible? Or if my feature is just crazy?

Steve

**Comment by mogikanin** [comment]
It's not crazy :). Your goal is return shapefile inside zip archive without storing intermediate files at hard-drive, is it?  Then yes, I think it's possible to adapt DotSpatial API for saving files into streams, and this feature will be quite useful for others.

**Comment by donogst** [comment]
Yes that is the goal exactly. I've had a look and perhaps it is not as hard as I thought, I will try to make the changes. I see support for .shp, .shx, .dbf and .prj. do you use any of the other files?

**Comment by mogikanin** [comment]
> .shp, .shx, .dbf and .prj

only these files
