### ISSUE TITLE
Show grid on map control

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#886]
Hi
i need to know is dotspatial have Grid show function ?

**Comment by mogikanin** [comment]
No such function.
But you can look into this discussions: [1](https://dotspatial.codeplex.com/discussions/649575), [2](https://dotspatial.codeplex.com/discussions/395453).

And please use search via discussions\issues before posting questions.

**Comment by DavisMillier** [comment]
I do it ..
Go to map Control find Onpaint override method
paste this code after existing code

`           System.Drawing.Point pt1, pt2;
            System.Drawing.Graphics mapGridHorizentalLine = map1.CreateGraphics();
            Pen pen = new Pen(Color.LightGray);
            float[] dashValues = { 2, 2, 2, 2 };
            pen.DashPattern = dashValues;
            Font lblFont = new Font("tahoma", 8);
            Brush lblBrush = new SolidBrush(Color.Cyan);

            Coordinate startPoint = new Coordinate();
            startPoint = map1.PixelToProj(new System.Drawing.Point(0, 0));

            Coordinate endPoint = new Coordinate();
            endPoint = map1.PixelToProj(new System.Drawing.Point(map1.Width, map1.Height));

            Coordinate st1 = new Coordinate(startPoint);
            Coordinate en1 = new Coordinate(endPoint);

            for (int i = (int)endPoint.Y + 1; i < startPoint.Y; i += 2)
            {
                st1.Y = i;
                en1.Y = i;
                pt1 = map1.ProjToPixel(new Coordinate(st1));
                pt2 = map1.ProjToPixel(new Coordinate(en1));
                mapGridHorizentalLine.DrawLine(pen, pt1, pt2);
                mapGridHorizentalLine.DrawString(Convert.ToString(i) + "°", lblFont, lblBrush, pt1);
            }
            //Vertical UTM Grid Line
            st1 = new Coordinate(startPoint);
            en1 = new Coordinate(endPoint);
            for (int i = (int)startPoint.X + 1; i < endPoint.X; i += 2)
            {
                
                st1.X = i;
                en1.X = i;
                pt1 = map1.ProjToPixel(new Coordinate(st1));
                pt2 = map1.ProjToPixel(new Coordinate(en1));
                mapGridHorizentalLine.DrawLine(pen, pt1, pt2);
                mapGridHorizentalLine.DrawString(Convert.ToString(i) + "°", lblFont, lblBrush, pt1);
            }`

**Comment by mogikanin** [comment]
Great. A few tips:
1. Move Pen, Font, Brush construction  outside this method. I.e. make them as readonly fields in class. This will improve performance.
2. Don't forget dispose `mapGridHorizentalLine` in the end. Otherwise it will be memory leak.
