### ISSUE TITLE
DotSpatial.Tools.ClipPolygonWithPolygon does not set output DataTable columns on FeatureSet

### ISSUE THREAD

**Issue by bdgza** [DotSpatial/DotSpatial#892]
### Steps to reproduce

1. Use Tools > Vector Overlay > Clip Feature Set With Polygon to clip a polygon shapefile with one or more attribute columns set.
2. Look at the output file using Attribute Table Editor and compare to source file.

DotSpatial version: 2.0.0 c7b3299

### Expected behaviour

The attribute columns and the values should be copied from the source shapefile to the output shapefile.

### Actual behaviour

The DataTable definition is not set and the output shapefile does not include the attribute columns.

![attributes-input-before-clip](https://cloud.githubusercontent.com/assets/21112080/20603042/eb637726-b25f-11e6-9716-fd4ee50ab109.png)
![attributes-actual-output](https://cloud.githubusercontent.com/assets/21112080/20603040/eb44a4e0-b25f-11e6-8e56-7cece937b857.png)
![attributes-expected-output](https://cloud.githubusercontent.com/assets/21112080/20603041/eb61dfb0-b25f-11e6-8021-8b96bc5cd475.png)

### Possible Fix

By setting output.AttributesPopulated = true; in ClipPolygonWithPolygon.cs on line 140 the output is as expected.

> 109:        public bool Execute(IFeatureSet input, IFeatureSet input2, IFeatureSet output, ICancelProgressHandler cancelProgressHandler)
> 110:        {
>             ...
> 140:            **output.AttributesPopulated = true;**
> 141:            output.SaveAs(output.Filename, true);
> 142:            return true;
> 143:        }

**Comment by mogikanin** [comment]
Thanks for reporting! Would you like to provide this fix (with unit-test) as pull request?

**Comment by bdgza** [comment]
I will take a crack at this.
