### ISSUE TITLE
ShapeFile DBF decimalCount max for real/double inconsistent between DotSpatial and OGR

### ISSUE THREAD

**Issue by bdgza** [DotSpatial/DotSpatial#893]
DotSpatial version: 2.0.0 276cac8

### Issue

When creating/writing a ShapeFile using OGR with an attribute column defined as OTFReal it is written as N(24,15). When reading the ShapeFile into DotSpatial DotSpatial.Data.Field has this code at line 200:
>if (decimalCount > 14)
>{
>&nbsp;&nbsp;&nbsp;&nbsp;// we know this has too many significant digits to fit in a double.
>&nbsp;&nbsp;&nbsp;&nbsp;DataType = typeof(string);
>&nbsp;&nbsp;&nbsp;&nbsp;MaxLength = length;
>&nbsp;&nbsp;&nbsp;&nbsp;return;
>}
15 > 14 so the REAL column gets loaded as a string instead of a double type.

### Request

Would it be possible to increase this conditional from > 14 to > 15, so it does not load all OGR created REAL columns as string instead of double?

**Comment by mogikanin** [comment]
Yes, we can change it since double has precision [15-16 digits](https://msdn.microsoft.com/en-us/library/678hzkk9.aspx). Could you please provide this as PR with unit-test with sample dbf?

**Comment by bdgza** [comment]
Ok, I will.

**Comment by mogikanin** [comment]
Thanks for contributing!
