### ISSUE TITLE
When the DotSpatial can use postgresql？Thanks

### ISSUE THREAD

**Issue by AllanHao** [DotSpatial/DotSpatial#896]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.
2.
3.

DotSpatial version: 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by CptTZ** [comment]
What do you mean by saying 'use'?

**Comment by AllanHao** [comment]
I wanna  read and write the data in PostGIS with Dotspatial,thanks.

**Comment by jany-tenaj** [comment]
Have a look at issue #827.

**Comment by AllanHao** [comment]
Thanks for your kind help. I will have a try later.
