### ISSUE TITLE
DS Feature refactorings

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#906]
1. `Feature.ExportToGml()` -  move as extension method into `FeatureExt`.
2. `Feature.ToBinary()` - remove. User can use `Feature.Geometry.AsBinary()` instead.
3. `Feature.ContentLengh\RecordNumber\ShapeType` - move as extension methods into`FeatureExt`.
4. `Feature.GeometryType\NumGeometries\NumPoints` - remove. User can use appropriate properties from  `Feature.Geometry`.

**Comment by jany-tenaj** [comment]
5. remove GetBasicGeometryN - can be reached from Feature.Geometry

**Comment by mogikanin** [comment]
And please move Feature.NumParts into extensions methods. Then we can delete Feature.NumPartsSource with CacheTypes enumeration.
