### ISSUE TITLE
Questions on ToolManager plugin

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#908]
Is the ToolManager plugin now replaced with the ToolManager in the Controls project?

**Comment by jany-tenaj** [comment]
No it has not been replaced. The Toolmanager plugin is used to load the ToolManager from the Controls project into the tab that you can see.

**Comment by pedwik** [comment]
From a user´s perspective I think it is rather confusing with the same name. The ToolManager plugin should be called for example ToolManagerLoaderPlugin.
