### ISSUE TITLE
NmeaSentence.ParseDilution produces an exception when an nmea string with dilution of precision not greater than 0 is used.

### ISSUE THREAD

**Issue by gojanpaolo** [DotSpatial/DotSpatial#909]
On a rare occasion, the gps string we received contained a dilution of precision not greater than 0.
We we're not able to catch the exact string but here is how to reproduce the issue.

```
double dop = 0
string ggaString = $"$GPGGA,172814.0,3723.46587704,N,12202.26957864,W,2,6,{dop},18.893,M,-25.669,M,2.0,0031*52";
var nmeaSentence = new NmeaSentence(ggaString);
var ggaSentence = new GpggaSentence(nmeaSentence.Sentence);
```

This will produce this exception.

> System.ArgumentException was unhandled
>   HResult=-2147024809
>   Message=Dillution of precision value must be > 0
>   Source=DotSpatial.Positioning
>   StackTrace:
>        at DotSpatial.Positioning.NmeaSentence.ParseDilution(Int32 position)
>        at DotSpatial.Positioning.GpggaSentence.SetPropertiesFromSentence()
>        at DotSpatial.Positioning.GpggaSentence..ctor(String sentence)

This is the method that caused the exception.
```
protected DilutionOfPrecision ParseDilution(int position)
{
    if (Words.Length <= position || Words[position].Length == 0) return DilutionOfPrecision.Invalid;
    return new DilutionOfPrecision(float.Parse(Words[position], NmeaCultureInfo));
}
```

My suggestion is to also check if the `float.Parse(Words[position]` is greater than 0.
if it is not, then return DilutionOfPrecision.Invalid instead of causing an excpetion.

DotSpatial version: DotSpatial.Positioning v.1.9.0

**Comment by jany-tenaj** [comment]
@gojanpaolo you can leave out the line
var nmeaSentence = new NmeaSentence(ggaString);
