### ISSUE TITLE
Create Polygon with multiple Point

### ISSUE THREAD

**Issue by vahidarr** [DotSpatial/DotSpatial#910]
DotSpatial version: latest Version

I have multiple latitude and longitude point with order number in my DB now I just want create one simple polygon shp file in my Web Project.I read [this ](http://dotspatial.codeplex.com/wikipage?title=MultypgFSCS&referringTitle=Desktop_SampleCode)Example but I dont Understand Completely.
this is my Point for Example:
order Nmber       latitude                           longitude 
1                         48.9160041021872           27.5997012829732
2                         48.9163221021872           27.5997312821732
3                         48.9130241021872           27.5997912821632
4                         48.9165641021872           27.5997112821132

1-which one become center according to sample Code in this line?
 Coordinate center = new Coordinate((rnd.Next(50) * 360) - 180, (rnd.Next(60) * 180) - 90);

2-this ii is next latitude and longitude points ?
coord[ii] = new Coordinate(center.X + Math.Cos((ii * 10) * Math.PI / 10), center.Y + (ii * 10) * Math.PI / 10);

**Comment by jany-tenaj** [comment]
Just put all your coordinates in a coordinate array and add the first point again as last point. Then use them to create a LinearRing that you can use to create your polygon.

```
            FeatureSet fs = new FeatureSet(FeatureType.Polygon);

            Coordinate[] coord = new Coordinate[]
            {
                new Coordinate(48.9160041021872, 27.5997012829732),
                new Coordinate(48.9163221021872, 27.5997312821732),
                new Coordinate(48.9130241021872, 27.5997912821632),
                new Coordinate(48.9165641021872, 27.5997112821132),
                new Coordinate(48.9160041021872, 27.5997012829732) //repeat the first coordinate to make sure the polygon is closed
            };

            fs.Features.Add(new Polygon(new LinearRing(coord)));
```

**Comment by vahidarr** [comment]
tnx alot for your help jany-tenaj. 
1-latitude is first parameter and longitude is second parameter of coordinate .is it correct?
2-I have a list of Data that each Data have a list of Geographic Coordinate, Each Data may have point or line or polygon Geographic Coordinate.is it ok if i define this two class this way and add it(point or Line or polygon) to FeatureSet ?
```

  Feature f = new Feature();
  FeatureSet fs = new FeatureSet(f.FeatureType);
// a foreach in Data that each Data have A list Of Geographic Coordinate

// if it is PolyGon
 var pg = new Polygon(new LinearRing(coord));  //coord is list of Coordinate
  fs.Features.Add(pg);
// if it is Line
  LineString ls = new LineString(coord); //coord is list of Coordinate
   fs.Features.Add(ls);
// if it is Point
  Coordinate c = new Coordinate(Lat, Lang);
   fs.Features.Add(c);
```

**Comment by jany-tenaj** [comment]
1. No idea what the correct order would be as I've never worked with them before.
2. Make sure that you have one featureset for polygons, one for lines and one for points. Don't put polygons, lines and points into the same featureset. Otherwise the posted code looks ok.

**Comment by vahidarr** [comment]
tnx jany-tenaj again for your help.
i cant make one featureset for polygons, one for lines and one for points.
because i want one final shp file.i create shp file with this line of code.what can i do?
`fs.SaveAs(fileAddress, true);`

**Comment by jany-tenaj** [comment]
According to their definition shapefiles can only contain a single feature type. So if you want to export polygons, lines and points to shapefile, you'll have to create one shapefile for each feature type.

What exactly is your problem with the code you posted?

**Comment by vahidarr** [comment]
i just want to create one shp file that is combine of point, line and polygon.if i have to create seprate feature type for point,Line and polygon(as you say ),how can i join theme to one shp file????

**Comment by jany-tenaj** [comment]
Based on the [Esri Shapefile Technical Documentation](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) page 4 paragraph 2: 

> All the non-Null shapes in a shapefile are required to be of the same shape type.  

that is not possible. So you either create one shapefile for polygons, one for lines and one for points or use some other way to export your shapes.

**Comment by vahidarr** [comment]
you are correct.
last question: how can i Instead of save shp file save it to memoryStream ?

**Comment by jany-tenaj** [comment]
I'm not sure but I think you'll have to write your own method for that.
Have a look at the [SaveAs method](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Data/PolygonShapefile.cs#L348) of PolygonShapefile for example.

**Comment by vahidarr** [comment]
I will check it if i have any question i will ask it in new issue.tnx for jany-tenaj help
