### ISSUE TITLE
Issue by following the dotSpatial tutorial 4 in "Create a Point shapefile" part.

### ISSUE THREAD

**Issue by Tisscl** [DotSpatial/DotSpatial#911]
Hello,

I want to create a point on my shapefile so i followed the tutorial on DotSpatial website but i have an issue on this part:

`
switch (shapeType)
            {
                case  "Point" :
                    if (e.Button == MouseButtons.Left)
                    {
                        if ((pointmouseClick))
                        {
                            Coordinate coord = map1.PixelToProj(e.Location); 
                            DotSpatial.Topology.Point point = new DotSpatial.Topology.Point(coord);
                            IFeature currentFeature = pointF.AddFeature(point);
                            pointID = pointID + 1;
                            currentFeature.DataRow["PointID"] = pointID; 
                            map1.ResetBuffer();
                        }
                    }
`
I have an error on these lines, which says "You need to add the assembly DotSpatial.GeoApi"

`
 Coordinate coord = map1.PixelToProj(e.Location); 
`
and on this line too

`
 IFeature currentFeature = pointF.AddFeature(point);
`
Further more if i use the assembly DotSpatial.GeoApi visual studio says "Unable to convert GeoAPI.Geometries.Coordinate to DotSpatial.Topology.Coordinate"

I don't find where i did it wrong, if someone can help me.
Faithfully
Clément

**Comment by sindizzy** [comment]
When you declare your Coordinate variables make sure you use the full namespace.

**Comment by jany-tenaj** [comment]
@Tisscl The example you used was based on DS 1.9 or earlier. DS 2.0 no longer contains Dotspatial.Topology.
If you're using the dlls from DS 1.9 (e.g from nuget) or earlier you'll need to reference Dotspatial.Topology. 
If you're using dlls from DS 2.0 (from github) you'll need to replace every mention of Dotspatial.Topology from the example by either GeoAPI or NetTopologySuite depending on where the things from Topology were moved to.

Point for example was moved to NetTopologySuite.Geometries.

**Comment by Tisscl** [comment]
Ok thank you for your answers !
I have no more errors on these lines but i have one error on this line : 
`NetTopologySuite.Geometries.Point point = new point(coord)`
It say "Unable to convert GeoAPI.Geometries.Coordinate to System.Drawing.Size"
Did i mess something else ?

**Comment by jany-tenaj** [comment]
it should be 
NetTopologySuite.Geometries.Point point = new NetTopologySuite.Geometries.Point(coord)

**Comment by Tisscl** [comment]
Oh my bad, thank you for your help it works now !
