### ISSUE TITLE
Outdated assemblies added when using Nuget

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#912]
When adding DotSpatial.Data version 1.9 via Nuget, depending libraries (DotSpatial.Topology, DotSpatial.Serialization, DotSpatial.Projections and DotSpatial.Mono) are added automatically, but of outdated versions (1.0) that are incompatible with DotSpatial.Data 1.9. So you must update these reference afterwards. Is this as designed?

**Comment by bdgza** [comment]
Do you know about NuGet Package Manager Install Options:
https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#install-options

You can set it to install Dependencies with the Highest version, instead of the default Lowest.

**Comment by pedwik** [comment]
Ahaa! Thanks!
