### ISSUE TITLE
How can i get the name of a layer ?

### ISSUE THREAD

**Issue by Tisscl** [DotSpatial/DotSpatial#914]
Hi guys,
How can i get the name of a layer opened with this instruction : map1.AddLayers();

Thank you

**Comment by bdgza** [comment]
Perhaps something like this?

> List&lt;IMapLayer&gt; layers = map1.AddLayers();
> foreach (IMapLayer layer in layers)
> {
> &nbsp;&nbsp;&nbsp;&nbsp;string filename = layer.DataSet?.Filename;
> }

**Comment by Tisscl** [comment]
Thank you it works, for only get the name of the file i used `layer.DataSet.Name` instead of `layer.DataSet.Filename` which gives you the path and the filename.
Have a nice day
