### ISSUE TITLE
Instructions for deployment

### ISSUE THREAD

**Issue by jirigcs** [DotSpatial/DotSpatial#921]
Are there any specific instructions for DotSpatial applications deployment? I tried to publish DemoMap solution (source/DotSpatial.sln) and I'm experiencing null reference errors. Also, some dlls (plugins, extensions) are not present among installation files.
Thank you,
Jiri

**Comment by mogikanin** [comment]
Jiri, after you build solution, everything are located in Source\bin\Debug[Release] folder. There will be demomap, all core dlls, and all plugins. Also, you always can download latest binaries from AppVeyour CI.
e.g. https://ci.appveyor.com/project/mogikanin/dotspatial/build/2.0.188/artifacts

**Comment by jirigcs** [comment]
Thank you for fast reply. With this approach, how do I handle the updates? I usually upload my updates to some server that is accessible to other users so the app updates itself automatically once the new version is issued.
Thank you
Jiri

**Comment by mogikanin** [comment]
AppVeyour  builds every commit in master, which is under development and might be unstable sometime. Stable updates will be published at nuget.org (e.g. upcoming 2.0).
Also, there is a way to setup nuget feed for every commit at AppVeyour, so you will be able to fetch every commit as a bunch of nuget packages.

**Comment by jirigcs** [comment]
Thank you for your fast reply. I'm sorry about the confusion but I meant my updates of my application. If I run my app by using exe file that has been created in Debug or Release folder, the app does not check for the updates while "regularly" installed app does.
My apologies for my newbie questions. Thank you,
Jiri

**Comment by mogikanin** [comment]
This depends from logic in your app. Hard to say.
