### ISSUE TITLE
How can i remove a point on a layer and in the datatable?

### ISSUE THREAD

**Issue by Tisscl** [DotSpatial/DotSpatial#922]
Hi guys,
I have a point layer, where i can add point on this layer with id, values etc.. These values are in the datatable too, how can i delete a point on the map with a simple button or by clicking on the point which delete the point values in the datatable and the point symbol on the map.
I tried `pointF.RemoveShapeAt(idOfThePoint)` but it did'nt work.
Thank for your help !

**Comment by jany-tenaj** [comment]
If you're using IndexMode you could use `FeatureLayer.RemoveFeaturesAt();`

When not in IndexMode you could use `FeatureLayer.DataSet.Features.Remove(feature);`

You might have to run one or more of the following lines afterwards, to make sure you don't produce index errors (see #801):

```
        FeatureLayer.DataSet.UpdateExtent()
        FeatureLayer.DataSet.InitializeVertices()
        If FeatureLayer.LabelLayer IsNot Nothing Then FeatureLayer.LabelLayer.CreateLabels()
      
        FeatureLayer.AssignFastDrawnStates()
       
         If Map IsNot Nothing Then
            Map.Refresh()
            Map.ResetBuffer()
        End If
```

**Comment by Tisscl** [comment]
I tried both methods, neither worked, maybe I have fail a step somewhere,
This is the code of my layer : `MapPointLayer pointLayer = new MapPointLayer()`
This is the code of my feature : `FeatureSet pointF = new FeatureSet(DotSpatial.Data.FeatureType.Point)`

So i tried this : `pointLayer.RemoveFeaturesAt(pointID)` (pointID is an int with the id of my featurepoint)
It says :  Unable to convert int into System.Collections.Generic.Inumerable<int>

Then i tried the other way : `pointLayer.DataSet.Features.Removes(pointF)`
It says : Unable to convert DotSpatial.Data.FeatureSet into DotSpatial.Data.IFeature

What should i do or what did i mess ?
Thank for your answer

**Comment by jany-tenaj** [comment]
RemoveFeaturesAt expects an Enumerable instead of an int. That means you'll have to pass a List or another Enumerable like this:
```
List<int> orderedIndex = new List<int>();
orderedIndex.Add(pointID);
pointLayer.RemoveFeaturesAt(orderedIndex);
```


Features.Remove expects the Feature you want to remove, not a FeatureSet.
```
FeatureSet pointF = new FeatureSet(DotSpatial.Data.FeatureType.Point);
IFeature feat = pointF.Features[0]; //replace with the feature you want to remove
pointF.Features.Remove(feat);
```

If this doesn't solve your problem please post the complete code.

**Comment by Tisscl** [comment]
I tried both, the point is still on the map and point's attributes too, this is my code : 
`private void map1_MouseDown(object sender, MouseEventArgs e)
        {
            auj = DateTime.Now;
            switch (shapeType)
            {
                case "Point":
                    if (e.Button == MouseButtons.Left)
                    {
                        
                        
                        if ((pointmouseClick))
                        {
                            frmValid f = new frmValid();
                            f.Show();
                            
                            GeoAPI.Geometries.Coordinate coord = map1.PixelToProj(e.Location);
                            NetTopologySuite.Geometries.Point point = new NetTopologySuite.Geometries.Point(coord);

                            IFeature currentFeature = pointF.AddFeature(point);
                            pointID = pointID + 1;
                            
                           
                            
                            if (Passerrelle.pass.ann == false)
                            {
                                //IFeature feat = pointF.Features[pointID];
                                //pointF.Features.Remove(currentFeature);
                                List<int> index = new List<int>();
                                index.Add(pointID);
                                pointLayer.RemoveFeaturesAt(index);
                            }
                            else
                            {
                                currentFeature.DataRow["Référence"] = fichier + Passerrelle.pass.reff;
                                currentFeature.DataRow["Date"] = auj;
                                currentFeature.DataRow["hmoy"] = Passerrelle.pass.hmoy;

                            }
                            map1.Refresh();
                            map1.ResetBuffer();
                            map1.FunctionMode = FunctionMode.Pan;
                            map1.Cursor = Cursors.Default;
                            pointmouseClick = false; 
                        }
                        
                    }

                    else
                    {
                        map1.ResetBuffer();
                        map1.Cursor = Cursors.Default;
                        pointmouseClick = false;
                        map1.FunctionMode = FunctionMode.Pan;
                    }
                    break;
            }
        }`
When the user set a point on the map a form appear and ask to set values, if the user press cancel, Passerrelle.pass.ann == false so i want to delete the point but a blank point is created with default values

**Comment by jany-tenaj** [comment]
You might solve this in two ways. 

1. Don't add the point before the user has left the dialog.

```
                     if ((pointmouseClick))
                        {
                            frmValid f = new frmValid();
                            f.Show(); //if this is a form you might use ShowDialog to make sure the form is closed before you continue

                            if (Passerrelle.pass.ann) //add the point only if the user didn't click cancel
                            {
                                GeoAPI.Geometries.Coordinate coord = map1.PixelToProj(e.Location);
                                NetTopologySuite.Geometries.Point point = new NetTopologySuite.Geometries.Point(coord);

                                IFeature currentFeature = pointF.AddFeature(point);
                                pointID = pointID + 1; //don't use this to find the pointID, it could differ from the actual pointID of your currentFeature

                                currentFeature.DataRow["Référence"] = fichier + Passerrelle.pass.reff;
                                currentFeature.DataRow["Date"] = auj;
                                currentFeature.DataRow["hmoy"] = Passerrelle.pass.hmoy;

                            }
                            map1.Refresh();
                            map1.ResetBuffer();
                            map1.FunctionMode = FunctionMode.Pan;
                            map1.Cursor = Cursors.Default;
                            pointmouseClick = false; 
                        }
```

2. Call the code I posted in my first answer to clean the lists:

```
                     if ((pointmouseClick))
                        {
                            frmValid f = new frmValid();
                            f.Show();
                            
                            GeoAPI.Geometries.Coordinate coord = map1.PixelToProj(e.Location);
                            NetTopologySuite.Geometries.Point point = new NetTopologySuite.Geometries.Point(coord);

                            IFeature currentFeature = pointF.AddFeature(point);
                            pointID = pointID + 1;
                            
                            if (Passerrelle.pass.ann == false)
                            {
                                pointF.Features.Remove(currentFeature); // remove currentFeature directly, you can't be sure that your pointID belongs to currentFeature

                                pointF.UpdateExtent(); //update the extent of the existing features
                                pointF.InitializeVertices(); //updates the vertex array so it no longer contains the delete feature vertices
                                pointLayer.AssignFastDrawnStates(); //updates the FastDrawn states
                            }
                            else
                            {
                                currentFeature.DataRow["Référence"] = fichier + Passerrelle.pass.reff;
                                currentFeature.DataRow["Date"] = auj;
                                currentFeature.DataRow["hmoy"] = Passerrelle.pass.hmoy;

                            }
                            map1.Refresh();
                            map1.ResetBuffer();
                            map1.FunctionMode = FunctionMode.Pan;
                            map1.Cursor = Cursors.Default;
                            pointmouseClick = false; 
                        }
```

**Comment by Tisscl** [comment]
I used the first way, thank you so much for your support, it works !

**Comment by jany-tenaj** [comment]
Check whether the feature you deleted has a FID that is not -1 if you remove the feature after reopening the project. 

Please also check whether the Features have been initialized before you select the feature you want to remove.

If your layer is in IndexMode the feature gets created from the vertices and can't be found inside DataSet.Features so it can't be removed.

As far as I remember I run the following code on layers after reopening projects to make sure I can use them afterwards without errors.
```
if (!fLayer.DataSet.AttributesPopulated) fLayer.DataSet.FillAttributes();
fLayer.DataSet.IndexMode = false;
```

**Comment by snahdog** [comment]
Thank you, it works now. Before you posted, I also found that accessing the dataset features after opening the project resolves the issue too (for instance, via `int dummy=lyr.DataSet.Features.Count;`).

**Comment by snahdog** [comment]
Thank you, that resolved it. Before you posted, I also found that accessing the dataset features when reopening the project resolves the issue (for instance `int dummy=lyr.DataSet.Features.Count;`).

**Comment by jany-tenaj** [comment]
Yes thats because the features list gets filled on the first access and IndexMode will be false afterwards.
