### ISSUE TITLE
DotSpatial.Plugins.BruTileLayer error v. 1.9

### ISSUE THREAD

**Issue by ragapack** [DotSpatial/DotSpatial#924]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. I downloaded the last DotSpatial.Plugins.BruTileLayer version for 1.9 and compiled with DS 1.9 from the nuget package of DS
2. I use the changeset for my application .
https://github.com/DotSpatial/DotSpatial/tree/5fcdd48792659b71b06458b8843e68486d07699e
3. I got an error at MapFrame.cs
// First draw all the vector content
            foreach (IMapLayer layer in Layers)
            {
                if (layer.VisibleAtExtent(ViewExtents)) layer.DrawRegions(args, regions);
            }

An exception of type 'System.MissingMethodException' occurred in DotSpatial.Controls.dll but was not handled in user code

Additional information: Método não encontrado: 'DotSpatial.Topology.Coordinate DotSpatial.Data.Extent.get_Center()'.

DotSpatial version:  1.9

### Expected behaviour

Load the Bru Tile Layer

For me there is a problem between the DotSpatial.Topology vs. DotSpatial.GeoAPI 
But I cannot find where is the bug.
I asked the same at 
https://github.com/FObermaier/DotSpatial.Plugins/issues/14

**Comment by jany-tenaj** [comment]
@ragapack Your using a plugin compiled with 1.9 against 2.0 source code. Either have FObermaier make a version compiled with 2.0 or use the [1.9 source code](https://dotspatial.codeplex.com/SourceControl/latest).

**Comment by mogikanin** [comment]
Closing it since there is no responses more than [month](https://github.com/DotSpatial/DotSpatial/blob/master/.github/CONTRIBUTING.md#common-rules).

**Comment by ragapack** [comment]
OK, I will wait until DS 2.0 is oficial released and ask then  FObermaier to update the plugin.
Thanks
