### ISSUE TITLE
Create Shp file with utm x,y,zone 

### ISSUE THREAD

**Issue by vahidarr** [DotSpatial/DotSpatial#928]
DotSpatial version: latest Version

I create shp file with latitude and longitude this way and now I want to create shp file with utm(x,y,zone).how can i do that? how can i change it for x,y,zone ? 
this is x,y,zone sample data:
1-X:649888.00	  Y:3289569.00	     Zone:39
2-X:656265.00	  Y:3291269.00	     Zone:39
3-X:656750.00	  Y:3297143.00	     Zone:39
4-X:649487.00	  Y:3295816.00      Zone: 39

```
 FeatureSet fs = new FeatureSet(FeatureType.Polygon);

            Coordinate[] coord = new Coordinate[]
            {
                new Coordinate(48.9160041021872, 27.5997012829732),
                new Coordinate(48.9163221021872, 27.5997312821732),
                new Coordinate(48.9130241021872, 27.5997912821632),
                new Coordinate(48.9165641021872, 27.5997112821132),
                new Coordinate(48.9160041021872, 27.5997012829732) 
            };

            fs.Features.Add(new Polygon(new LinearRing(coord)));
```

**Comment by jany-tenaj** [comment]
If you want to create a new featureset with UTM zone 39 just set the featuresets projection like this:

```
FeatureSet fs = new FeatureSet(FeatureType.Polygon);
fs.Projection = ProjectionInfo.FromAuthorityCode("EPSG", 32639); //this sets the Projection of your featureset to utm zone 33N based on the epsg code from http://spatialreference.org/ref/epsg/wgs-84-utm-zone-39n/ , make sure this is the correct projection for you
            Coordinate[] coord = new Coordinate[]
            {
             //.. put the coordinates with the utm values here
            };

            fs.Features.Add(new Polygon(new LinearRing(coord)));
```

If you want to take your featureset with the latitude/longitude values and change it to utm zone 39, you can do it like this:
```
var proj = ProjectionInfo.FromAuthorityCode("EPSG", 32639);
fs.Reproject(proj); //changes your featureset to utm zone 39n
```
If you add any features after this call you'll have to add them with utm values.

**Comment by vahidarr** [comment]
tnx jany-tenaj but zone is dynamic and is between 39,40,41

**Comment by vahidarr** [comment]
jany-tenaj how can i set ZoneDynamically????

**Comment by jany-tenaj** [comment]
As far as I understand one shapefile can have one zone. If you want to create one shapefile with more than one zone I have no idea.

If you create one shapefile for each zone you simply switch the EPGS values to the zone you want to use.

If you want to add features that belong to more than one zone you might have to use a different projection that contains all 3 zones.

**Comment by mogikanin** [comment]
I guess question is solved, and we can close it?

**Comment by vahidarr** [comment]
sorry for latency.it solved my problem
