### ISSUE TITLE
Question : How can i add point on an existing pointlayer shape file

### ISSUE THREAD

**Issue by Tisscl** [DotSpatial/DotSpatial#929]
Hi guys,
I load a linelayer file on my application and a pointlayer with existing point on it, when I want to add a point on it, it always create a new pointlayer and because of this new point layer i can't use `map1.function = FunctionMode.Info;` to get information of the first point layer should i change this part of my code :
```
            map1.Cursor = Cursors.Cross;
            shapeType = "Point";
            pointF.Projection = map1.Projection;
            compt++;
            pointLayer = (MapPointLayer)map1.Layers.Add(pointF);
            PointSymbolizer symbol = new PointSymbolizer(Color.Red, DotSpatial.Symbology.PointShape.Ellipse, 10);
            pointLayer.Symbolizer = symbol;
            pointLayer.LegendText = "point";
            pointmouseClick = true;
```
Thank you for your answer !

**Comment by jany-tenaj** [comment]
No idea what the rest of your code looks like but `pointLayer = (MapPointLayer)map1.Layers.Add(pointF);` definitely adds your pointF featureset as new pointlayer to the legend.

As you posted only the part that creates the point layer but not the code around it you'll have to find out yourself where you have to move the code so you won't add the layer more than once.

**Comment by Tisscl** [comment]
I tried to add pointF on my existing pointLayer by using `pointLayer = map1.Layers[1] as MapPointLayer;`
but i need something to add my pointF to this layers, i tried `pointLayer.DataSet.AddFeature(pointF);` but that does not work. What should i try ?


Here is my code : 

` public partial class frmCarte : Form
    {
        string shapeType;
        #region Point ShapeFile class level variable

        string fichier;
        FeatureSet pointF = new FeatureSet(DotSpatial.Data.FeatureType.Point);
        
        MapPointLayer pointLayer = new MapPointLayer();
        
        DataColumn colonneId = new DataColumn("id");
        DataColumn colonneRef = new DataColumn("Référence");
        DataColumn colonneDate = new DataColumn("Date");
        DataColumn colonneh1 = new DataColumn("h1");
        DataColumn colonneh2 = new DataColumn("h2");
        DataColumn colonneh3 = new DataColumn("h3");
        DataColumn colonnehmoy = new DataColumn("hmoy");
        DataColumn colonneBat = new DataColumn("Batiment");
        DataColumn colonneEta = new DataColumn("Etage");
        DataColumn colonneLat = new DataColumn("Latitude");
        DataColumn colonneLong = new DataColumn("Longitude");
        
        DateTime auj = new DateTime();
        int pointID = 0;

        int compt = 0;
        bool pointmouseClick = false;
        #endregion
        public frmCarte()
        {
            InitializeComponent();
        }

        private void btnChargerCarte_Click(object sender, EventArgs e)
        {
            
            map1.AddLayers();

            
            foreach (ILayer layer in map1.Layers)
            {
                fichier = layer.DataSet.Name;
            }
            map1.AddLayer("D:\\Stage2017\\charge\\bat400_et0_casa.shp");
//I tried this :
            pointLayer = map1.Layers[1] as MapPointLayer;
            
        }

        private void button2_Click(object sender, EventArgs e)
        {
            
            Passerrelle.pass.nbLay = map1.Layers.Count();
            Passerrelle.pass.tabLayer = pointLayer;
            InterfaceTableau.frmTab f = new frmTab();
            f.Show();
        }

        private void btnAddPoint_Click(object sender, EventArgs e)
        {
            if (compt == 0)
            {
                
                pointF.DataTable.Columns.Add(colonneId);
                pointF.DataTable.Columns.Add(colonneRef);
                pointF.DataTable.Columns.Add(colonneDate);
                pointF.DataTable.Columns.Add(colonneh1);
                pointF.DataTable.Columns.Add(colonneh2);
                pointF.DataTable.Columns.Add(colonneh3);
                pointF.DataTable.Columns.Add(colonnehmoy);
                pointF.DataTable.Columns.Add(colonneBat);
                pointF.DataTable.Columns.Add(colonneEta);
                pointF.DataTable.Columns.Add(colonneLat);
                pointF.DataTable.Columns.Add(colonneLong);


            }

            map1.Cursor = Cursors.Cross;
            shapeType = "Point";
            pointF.Projection = map1.Projection;
            compt++;
            pointLayer = (MapPointLayer)map1.Layers.Add(pointF);
            PointSymbolizer symbol = new PointSymbolizer(Color.Red, DotSpatial.Symbology.PointShape.Ellipse, 10);
            pointLayer.Symbolizer = symbol;
            pointLayer.LegendText = "point";
            pointmouseClick = true;
        }

        private void btnDeplacerCarte_Click(object sender, EventArgs e)
        {
            map1.FunctionMode = FunctionMode.Pan;
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            pointF.SaveAs("pointADP.shp", true);
            MessageBox.Show("Couche de point sauvegardé");
        }

        private void map1_MouseDown(object sender, MouseEventArgs e)
        {
            auj = DateTime.Now;
            switch (shapeType)
            {
                case "Point":
                    if (e.Button == MouseButtons.Left)
                    {
                        
                        
                        if ((pointmouseClick))
                        {
                            frmValid f = new frmValid();
                            f.ShowDialog();

                            if (Passerrelle.pass.ann)
                            {
                                GeoAPI.Geometries.Coordinate coord = map1.PixelToProj(e.Location);
                                NetTopologySuite.Geometries.Point point = new NetTopologySuite.Geometries.Point(coord);

                                IFeature currentFeature = pointF.AddFeature(point);
                                pointID = pointID + 1;
                                currentFeature.DataRow["Référence"] = fichier + Passerrelle.pass.reff;
                                currentFeature.DataRow["Date"] = auj;
                                currentFeature.DataRow["hmoy"] = Passerrelle.pass.hmoy;
                            }
                        }
                            map1.Refresh();
                            map1.ResetBuffer();
                            map1.FunctionMode = FunctionMode.Pan;
                            map1.Cursor = Cursors.Default;
                            pointmouseClick = false; 
                    }
                        
 

                    else
                    {
                        map1.ResetBuffer();
                        map1.Cursor = Cursors.Default;
                        pointmouseClick = false;
                        map1.FunctionMode = FunctionMode.Pan;
                    }
                    break;
                case "Suppr":
                    if (e.Button == MouseButtons.Left)
                    {
//This part is not finish, i try here to delete a point by only click on it
                        //GeoAPI.Geometries.Coordinate coord = map1.PixelToProj(e.Location);
                        //NetTopologySuite.Geometries.Point point = new NetTopologySuite.Geometries.Point(coord);
                        //pointLayer.RemoveFeaturesAt();
                    }
                    break;

            }
        }`

Thank a lot for your help

**Comment by jany-tenaj** [comment]
I think you have confused some things. Your pointF is a FeatureSet not a Point. That's why you can't add it to your existing pointLayer.

If you want to add your point to your existing layer use

`IFeature currentFeature = pointLayer.DataSet.AddFeature(point);`

instead of 

`IFeature currentFeature = pointF.AddFeature(point);`

**Comment by Tisscl** [comment]
It works, thank you again for your help !
