### ISSUE TITLE
Question : How to save change in form from functionmode.Info;

### ISSUE THREAD

**Issue by Tisscl** [DotSpatial/DotSpatial#930]
Hi guys,
I'm using a pointlayer, on it i have existing points, when i use `map1.FunctionMode = FunctionMode.Info;` on a point , a new form appear with a datatable which is composed of point's information. I can edit this datatable by clicking on a cell and change the value, but when i close this form and use again `map1.FunctionMode = FunctionMode.Info;` on the same point the value did'nt change. Is it possible to save the change by using `map1.FunctionMode = FunctionMode.Info;` or should i do something else ?
Thank for your help, 
A grateful student.

**Comment by jany-tenaj** [comment]
@mogikanin Should the data in Identify window actually be editable?

**Comment by mogikanin** [comment]
No, I think we simply should disable edit mode for rows in Identify window.

**Comment by jany-tenaj** [comment]
@Tisscl the identify window isn't meant to be editable. If you want to edit your features use the Attribute Table Editor. 
You can find it by casting  your layer to IFeatureLayer and calling ShowAttributes().

If you have the Table Editor plugin installed you can also find it by right clicking on your layer in the legend or by clicking on View Attribute Table in the menu bar.

**Comment by Tisscl** [comment]
Thank for your answers, i'll try your solution, where should i find the Table Editor plugin, i don't find it on google ?

Thank you

**Comment by jany-tenaj** [comment]
You can find the source code under https://github.com/DotSpatial/DotSpatial/tree/master/Source/DotSpatial.Plugins.TableEditor

If you downloaded the compiled dlls from the [main page](https://github.com/DotSpatial/DotSpatial) you'll find it in plugins folder as DotSpatial.Plugins.TableEditor folder.

**Comment by Tisscl** [comment]
Is it possible to find a point on the map by clicking  on it and then update or delate the point values with the TableEidtor plugin or by casting my layer to IFeatureLayer and calling ShowAttributes()?
I use :
`GeoAPI.Geometries.Coordinate coord = map1.PixelToProj(e.Location);`
But i want to now if there is a point on these coordinate or not. Thank fo your help
