### ISSUE TITLE
DS uses InRamImage although GDAL provider was selected

### ISSUE THREAD

**Issue by jany-tenaj** [DotSpatial/DotSpatial#931]
![grafik](https://cloud.githubusercontent.com/assets/13728699/22546502/9e5546c0-e93d-11e6-9943-6ea6ca329c2b.png)

### Steps to reproduce

1. Click on Add Layer... button.
2. Select a jpg file to load (I used the image from issue #889), GDAL - Images as format and click open.
3. See that used ram goes up although when using GDAL image provider it would stay the same.

DotSpatial version: current master

### Expected behaviour

As the  formats are added to the list based on the provider that can load them, DS should load the image with the provider that corresponds to the selected format entry.

### Actual behaviour

DS uses the first provider that is able to load the file (for images most often InRamImageProvider) although the list indicates that GDAL would be used.

**Comment by jany-tenaj** [comment]
@mogikanin Could you please have a look at this fix before I commit it to master branch?

**Comment by mogikanin** [comment]
Looks ok. You can merge it into master.
