### ISSUE TITLE
Documentation Still on CodePlex with Many Broken Links

### ISSUE THREAD

**Issue by ab-tools** [DotSpatial/DotSpatial#932]
### Steps to reproduce

Several links on the main GitHub page
https://github.com/DotSpatial/DotSpatial
redirects the user back to CodePlex where you were just directed to GitHub.

On these old CodePlex pages like the documentation pages
https://dotspatial.codeplex.com/wikipage?title=DotSpatial%20Tutorials&referringTitle=Documentation
many links are broken, e. g. a download of the tutorial files is not possible anymore.

### Expected behaviour

Documentation is moved to GitHub Wiki and links are fixed.

### Actual behaviour

User is directed back to CodePlex and many links a broken.

**Comment by mogikanin** [comment]
We have time till  December 15th, 2017.
https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/

**Comment by jany-tenaj** [comment]
dead links were removed by #1471
