### ISSUE TITLE
Projection Alert

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#934]
Hello 
i download some shp file from internet, when i try to load layer i get this message

> The layer "layer Name" uses projection "" while the map uses projection "".

> repoject layer to match the map coordinate system this will not affect the source file.

how can i solve this message ?

**Comment by jany-tenaj** [comment]
This message shows up whenever you use a different projection for your layer and your map. The only way to not get the message is to use the same projection for your map and your layer.

I think you could also deactivate the message, but then you have to decide whether you want to reproject all layers automatically or not at all.

**Comment by DavisMillier** [comment]
@jany-tenaj thank you for your help
How can i convert projection of layer "shp file" ?
Do you know any software to help me ?

**Comment by sindizzy** [comment]
DotSpatial will do it for you and then you have to save it.
Or if you have ArcGIS that will also do it for you.
