### ISSUE TITLE
Using different point colors on my pointlayer

### ISSUE THREAD

**Issue by Tisscl** [DotSpatial/DotSpatial#939]
Hi,
Is it possible to use different `pointLayer.Symbolizer` on my pointlayer?
I want to set a green color to the point which have values, and a red for points which don't have values.

**Comment by jany-tenaj** [comment]
Have a look at page 52 of the [Developer Getting Started Guide](http://download-codeplex.sec.s-msft.com/Download?ProjectName=dotspatial&DownloadId=1460427).

You'd have to create one category with the FilterExpression **[your field name] is Not NULL** and one category with the Filterexpression **[your field name] is NULL**.

**Comment by Tisscl** [comment]
Never saw this guide before, thank you !

**Comment by Tisscl** [comment]
I followed the guide but i have an issue for this line : `pointLayer.Symbology = mespts;`
Here is my code , did i mess something ?
```

public void affPts()
        {
            PointCategory pointR = new PointCategory(Color.Green, DotSpatial.Symbology.PointShape.Ellipse, 10);
            PointCategory pointV = new PointCategory(Color.Red, DotSpatial.Symbology.PointShape.Ellipse, 10);
            pointR.FilterExpression = "[\"hmoy\"]!= null";
            pointV.FilterExpression = "[\"hmoy\"]== null";
            pointR.LegendText = "point ok";
            pointV.LegendText = "point not ok";
            mespts.AddCategory(pointR);
            mespts.AddCategory(pointV);
            pointLayer.Symbology = mespts;
            map1.Refresh();
            map1.ResetBuffer();

        }
```

**Comment by jany-tenaj** [comment]
Try

```
 pointR.FilterExpression = "[hmoy] is Not NULL";
 pointV.FilterExpression = "[hmoy] is NULL";
```

There is no need for " inside [ ]. Checking for null is done the vb.net way instead of in c# syntax. That's why I pointed it out in my other post.

**Comment by Tisscl** [comment]
Oh thank you, my bad

**Comment by Tisscl** [comment]
Hi, i just changed my code for this part of my code i wanted to do that  : 
```

pointR.FilterExpression = "[hmoy] == 0";
            pointV.FilterExpression = "[hmoy] != 0";
```

instead of : 

```
pointR.FilterExpression = "[hmoy] is Not NULL";
 pointV.FilterExpression = "[hmoy] is NULL";
```
But that do an error
How can i fix it ?

**Comment by jany-tenaj** [comment]
You're doing it the c# way again.

Use the vb equivalents  = and <> instead.

Have a look at the expression editor dialog. (Right click on layer name in legend, click Properties, double click on the values part of the first line in the table) This shows you which operators you can use.

**Comment by Tisscl** [comment]
Oh ok, always use the vb way for this part, i take up ;)
Thank you again
