### ISSUE TITLE
Error reprojecting from UTM to Wgs84

### ISSUE THREAD

**Issue by jany-tenaj** [DotSpatial/DotSpatial#942]
Copied from codeplex issue [63640](https://dotspatial.codeplex.com/workitem/63640):

Hello Guys,

I have a problem while reprojecting from UTM (MGI / Austria GK West) to WGS84 (Lat/Lon), I have an error of about 500 m in Latitude and 50 m in Longitude, thats my VB.net code:

    ' lines
    Sub processLines(fs As IFeatureSet)

        ' set EPSG code
        fs.Projection.AuthorityCode = 31254

        '  Destination projection information
        Dim dest As DotSpatial.Projections.ProjectionInfo = KnownCoordinateSystems.Geographic.World.WGS1984
        dest.GeographicInfo = fs.Projection.GeographicInfo

        ' set EPSG code
        dest.AuthorityCode = 4326

        ' reproject
        fs.Reproject(dest)

I´m using Qgis to echeck the results. Thanks in Advance!

Oliver

**Comment by mogikanin** [comment]
Oliver, please provide sample coordinates (actual values, expected values).
