### ISSUE TITLE
feature.Coordinates.Clear() has no effect

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#943]
### Steps to reproduce

 var coordinates = new List<Coordinate>()
 {
                new Coordinate(10000, 10000),
                new Coordinate(10000, 10100),
                new Coordinate(10100, 10100),
                new Coordinate(10100, 10000),
                new Coordinate(10000, 10000)
};
var feature = new Feature(FeatureType.Polygon, coordinates);
feature.Coordinates.Clear();

DotSpatial version: 1.9

### Expected behaviour

feature.Coordinates should be empty

### Actual behaviour

feature.Coordinates.Clear-method has no effect

**Comment by jany-tenaj** [comment]
@pedwik feature.Coordinates no longer exists in DS 2.0, so we won't fix this.
Futhermore it's not a good idea to write code that tries to clear the Coordinates. In 2.0 Geometry.Coordinates becomes an array of invariable length, so you'll have to go and replace the whole geometry if you want to change it.

**Comment by pedwik** [comment]
I have an algorithm that inserts a new vertex when splitting a line feature into more line segments which is required for a certain reason, you mean that will not work? It appears to me one step back to use an array instead of a list.

**Comment by jany-tenaj** [comment]
Geometry belongs to NTS. NTS by default uses CoordinateArraySequence to store the coordinates.

If you check our Shape/FeatureSet class you'll see that there arrays are used, too. So essentially that means Geometries Coordinates no longer work differently than Shapes Coordinates.

To make your algorithm work correctly you could copy your coordinates to a list, edit that and use it to create a new geometry that you give back to your feature.
