### ISSUE TITLE
M part of XYZM coordinates is being ignored?

### ISSUE THREAD

**Issue by josbol** [DotSpatial/DotSpatial#946]
Hi,

I'm manually constructing linestrings with XYZM coordinates (Z= always 0 for now). When I inspect the coordinates individually, the values for M are correct, but when exporting the feature to WKT or WKB, the M part seems to be omitted for some reason. Considering WKT and WKB support XYZM, this doesn't make much sense to me. Is there a way to make the eport functions include the M part?

**Comment by jany-tenaj** [comment]
@josbol what version of DotSpatial do you use?

**Comment by josbol** [comment]
I'm using 1.9.0

**Comment by jany-tenaj** [comment]
I just had a look at the code. 1.9 only creates XY WKTs.

2.0 is able to create XYZ WKTs but still doesn't create XYZM WKTs. As we're using the original NTS source code in 2.0 I've created [issue](https://github.com/NetTopologySuite/NetTopologySuite/issues/156) an issue there to find out why the M support doesn't seem to work as expected.

So we'll have to wait for an answer before we can determine how we'll support XYZM WKTs in 2.0.

**Comment by josbol** [comment]
Thanks!

**Comment by jany-tenaj** [comment]
should work based on the linked NTS issue
