### ISSUE TITLE
How to Select Feature?

### ISSUE THREAD

**Issue by masgeomatik** [DotSpatial/DotSpatial#956]
Hi.
I'm building new attribute table. I want to if I click map, attiribute table is select about row.  What should I do?

**Comment by sindizzy** [comment]
Have you looked here https://dotspatial.codeplex.com/documentation

**Comment by masgeomatik** [comment]
I try access to FID data, but I'm failed. But if I open same shapefile, display to FID data.

![ekran alintisi003](https://cloud.githubusercontent.com/assets/26778438/24561326/f53f2fb2-164e-11e7-954a-a50eab613cb0.PNG)

**Comment by jany-tenaj** [comment]
If your Layer is missing the FID column you can add it via [FeatureSet.AddFid](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Data/FeatureSet.cs#L298).
