### ISSUE TITLE
Satellite details missing

### ISSUE THREAD

**Issue by jfevia** [DotSpatial/DotSpatial#958]
Details for several satellites launched after 15th March 2008 are missing

### Steps to reproduce

1. Connect to a GPS device
2. Review list of satellites connected
3. Details of satellites launched after that date are missing (i.e.: Name: New Satellite (24)) 

DotSpatial version: 1.9

### Expected behaviour

Corresponding satellite details should appear (i.e.: Name: GPS IIF-3)

### Actual behaviour

Satellite details are missing (i.e.: Name: New Satellite (24))

This issue applies to DS.Positioning (incl. Compact) 

I can work on these changes but I'm posting this here in case this is planned for next version

**Comment by mogikanin** [comment]
@jfevia , please take it :)

**Comment by jfevia** [comment]
Properties DateComissioned and DateDecomissioned in Satellite class are not accurate and difficult to be updated. No reliable source can provide this information.

I suggest the properties are removed and consider the next version as breaking changes.

@mogikanin

**Comment by mogikanin** [comment]
Jesus thanks for contributing!
