### ISSUE TITLE
DotSpatial.Tools > InverseDistanceWeighting compile problems

### ISSUE THREAD

**Issue by alperdincer** [DotSpatial/DotSpatial#961]
I'm trying to compile InverseDistanceWeighting.cs file in a web project but I can't compile due to following errors : 

1- 'IFeature' does not contain a definition for 'Geometry' and no extension method 'Geometry' accepting a first argument of type 'IFeature' could be found (are you missing a using directive or an assembly reference?)

2- Cannot implicitly convert type 'DotSpatial.Topology.Coordinate' to 'GeoAPI.Geometries.Coordinate' 

DotSpatial version:  1.9.0

Is there anything to fix these problems?

A.

**Comment by jfevia** [comment]
From changelog

```
Be aware that code written for 1.9 will not work out of the box because DotSpatial.Topology was replaced by DotSpatial.GeoAPI and DotSpatial.NetTopologySuite (#786).
```

Basically you are trying to compile a file from master branch while referencing 1.9 but they are no longer compatible

**Comment by alperdincer** [comment]
Thanks for the clarification. What is the best way to run this analysis? Is there any FAQ or docs to migrate to current branch.

**Comment by jany-tenaj** [comment]
1.9 contains [InverseDistanceWeighting](https://dotspatial.codeplex.com/SourceControl/latest#Trunk/DotSpatial.Tools/InverseDistanceWeighting.cs), too. As it is a tool it can be run from the Tools tab.

For switching from 1.9 to 2.0 have a look at the [switching guide](https://github.com/DotSpatial/DotSpatial/wiki/Switching-from-DotSpatial-1.9-to-2.0). 

Be aware that InverseDistanceWeighting has a [bug ](https://github.com/DotSpatial/DotSpatial/issues/895) in 2.0.

**Comment by alperdincer** [comment]
Thanks a lot. Now it is compiling with 1.9.
