### ISSUE TITLE
Create Polygon FeatureSet Problem

### ISSUE THREAD

**Issue by masgeomatik** [DotSpatial/DotSpatial#968]
Hi.
I want create polygon feature, but i created line feature?

```
FeatureSet fs = new FeatureSet(FeatureType.Polygon);
   fs.DataTable.Columns.Add(new DataColumn("ID", typeof(int)));
   Coordinate[] coordList = new Coordinate[...];
   LinearRing polygonGeometry = new LinearRing(coordList);
   IFeature polygonF = fs.AddFeature(polygonGeometry);
```

How can I fix this problem?

**Comment by jany-tenaj** [comment]
use 

`Polygon polygonGeometry  = new Polygon(new LinearRing(coordList));`

instead of 

`LinearRing polygonGeometry = new LinearRing(coordList);`

Make sure the first and the last point are the same, otherwise you'll get an error because your polygon is incomplete.

**Comment by masgeomatik** [comment]
@jany-tenaj thank you so much, solved problem :+1:
