### ISSUE TITLE
Legend Blank on LayoutForm

### ISSUE THREAD

**Issue by SteveV0189** [DotSpatial/DotSpatial#971]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Load Spatial Data (ne_data)
2. Create Layoutform with map control
3. Try to add legend via the control

Using this data: http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip

Using this code:

         
`this.Map = new DotSpatial.Controls.Map(); // Map Control`

...Form Init Method
            
```
Legend.AddMapFrame(Map.MapFrame);         
Map.AddLayer(Program.INFILE); //INFILE = static string, filepath
```

...User clicks to preview layout
```
var frm = new LayoutForm()
            {
                MapControl = Map
            };
```

DotSpatial version: 1.9 & 2.0 

### Expected behaviour

Legend should appear with the correct legend as is shown in the Legend Control. 

### Actual behaviour

https://shifty.site/uploads/images/2017-04-11_20-47.png
Legend is blank with no discernible information. 

Thanks for any help!

**Comment by jany-tenaj** [comment]
I ran the following code inside a button I added to DemoMap and then added a layout legend to the layout sheet and everything was working alright.
 ```
var frm = new LayoutForm();
            frm.MapControl = (Map)appManager.Map;
            frm.ShowDialog();
```

So please post the whole code so we can see what you are doing differently. Currently we have to guess how you created your Legend for example or how you see the layout legend if you didn't even open LayoutForm.

**Comment by SteveV0189** [comment]
My bad.

https://github.com/SteveV0189/ShapeInfo/blob/master/InfoShape/MapForm.cs#L125

I edited the layout form to add an event for capturing the image of the form, but I have have also verified that the legend is blank on the release 1.9 and beta 2.0 versions.

I tried to follow the code trail along the SimpleApp project, but all of the code for the adding of layers/showing the layout is abstracted away into the LoadExtensions method of the appmanager, it seems. The tutorials [here](https://dotspatial.codeplex.com/wikipage?title=DotSpatial%20Tutorials&referringTitle=Documentation) don't mention anything about an AppManager, so I'm now unsure if it's necessary or not for the legend to function.

**Comment by SteveV0189** [comment]
Found the issue..I hadn't set the legend property of the map, instead I did this: ` Legend.AddMapFrame(Map.MapFrame);`

This made the legend work fully, but caused something to not sync right with the print layout.

Also can't fault the documentation because it IS in there, just very unnoticeable. Cheers, thanks for the help.
