### ISSUE TITLE
How to project from nad27 to wgs84 for the entire United States?

### ISSUE THREAD

**Issue by robertleeplummerjr** [DotSpatial/DotSpatial#972]
I see the list of files here: https://github.com/DotSpatial/DotSpatial/tree/master/Source/DotSpatial.Projections/Nad/GridShifts
Which one do I use, if any?
If any of them are not applicable to the entire Unites States, do you know where I could find it/them?
Where do I put said file after it is unzipped?

Thank you for your hard work!

**Comment by TasGrinder** [comment]
Here is how I am doing it. 
You will need these DLLs
using DotSpatial.Positioning;
using DotSpatial.Projections;

        /// <summary>
        /// Projection method where elevation is a distance value form the altitude changed event. Latitude and Longitude are taken from a position method as the decimal degree.
        /// </summary>
        /// <param name="Elevation"></param>
        /// <param name="Latitude"></param>
        /// <param name="Longitude"></param>
        private void FromDDToUTM(double Elevation, double Latitude, double Longitude, int? zone)
        {
            //Sets up a array to contain the x and y coordinates
            double[] xy = new double[2];
            xy[0] = Longitude;
            xy[1] = Latitude;

            //An array for the z coordinate
            double[] z = new double[1];
            z[0] = Elevation;

            //Defines the starting and end coordinate system
            ProjectionInfo pStart = KnownCoordinateSystems.Geographic.World.WGS1984;
            ProjectionInfo pEnd = GetProjection(zone);

            if (pEnd != null)
            {
                //Calls the re-project function that will transform the input location to the output location
                Reproject.ReprojectPoints(xy, z, pStart, pEnd, 0, 1);

                int Easting = xy[0];
                int Northing = xy[1];
            }
        }

Get the .prj files from here:
http://spatialreference.org/

        /// <summary>
        /// Method to retrieve the projection
        /// </summary>
        /// <param name="zone"></param>
        private ProjectionInfo GetProjection(int? zone)
        {
            string locpre = @"C:\Projections\NAD 1983 UTM Zone ";
            string locsuf = "N.prj";
            ProjectionInfo result = null;
            try
            {
                result = ProjectionInfo.Open(locpre + zone + locsuf);
            }
            catch (Exception e)
            {
                MessageBox.Show(e.FullMessage(), "Error");
            }
            return result;
        }
I hope this helps

**Comment by robertleeplummerjr** [comment]
TY!  Do you need both the nad27 files and the wgs84, or just wgs84?

**Comment by TasGrinder** [comment]
A lot of the typically ones come packed in with the Projection DLL. So if you can't find what you want in: KnownCoordinateSystems. Then read them from file.

**Comment by robertleeplummerjr** [comment]
Perfect!

**Comment by robertleeplummerjr** [comment]
Also, ty DotSpatial devs, and @TasGrinder for your fantastic help and product!
