### ISSUE TITLE
Creation of polylineZ, pointZ

### ISSUE THREAD

**Issue by sbonifazzi** [DotSpatial/DotSpatial#980]
Hi everyone.
I don't know if it's a bug or not.
When I try to create a polylineZ, the result shapefile contain everytime also the M component.
The same is with pointZ
I don't want the M component because the file will be checked by a automatic process that don't accept M field. 

Thank's so much for any help.

**Comment by jany-tenaj** [comment]
According to the [ESRI Shapefile technical description](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) PointZ must have a M value. It may be "no data" but we have to write it.

For PolyLineZ M values are optional, so we don't have to write them, but it is not wrong if we write them using "no data" if they were not set.

**Comment by sbonifazzi** [comment]
I deleted the recors part relatively to 'M' component. Now the shapefile it's recognized (not from Esri product) only PolylineZ.
