### ISSUE TITLE
SelectionSymbolizer is not shown when new FeatureSet created, but is when Shapefile loaded

### ISSUE THREAD

**Issue by littlecharva** [DotSpatial/DotSpatial#984]
If I load a Point Shapefile and set the SelectionSymbolizer, then when I select the points, the symbol changes colour, as expected:

    var layer = _map.Layers.Add(path) as MapPointLayer;
    layer.Symbolizer = new PointSymbolizer(Color.Green, PointShape.Star, 20);
    layer.SelectionSymbolizer = new PointSymbolizer(Color.Yellow, PointShape.Star, 20);
    layer.DataSet.UpdateExtent();
    layer.DataSet.InitializeVertices();
    layer.AssignFastDrawnStates();
    _map.Refresh();
    _map.ResetBuffer();

However, if I create the FeatureSet myself and add a point:

    var featureSet = new FeatureSet();
    var feature = new DotSpatial.Topology.Point(new Coordinate(512999.147645373, 193411.512274086));
    featureSet.AddFeature(feature);
    featureSet.InitializeVertices();
    featureSet.UpdateExtent();

    var pointLayer = new MapPointLayer(featureSet);
    _map.Layers.Add(pointLayer);
    pointLayer.Symbolizer = new PointSymbolizer(Color.Green, PointShape.Star, 20);
    pointLayer.SelectionSymbolizer = new PointSymbolizer(Color.Yellow, PointShape.Star, 20);
    pointLayer.DataSet.UpdateExtent();
    pointLayer.DataSet.InitializeVertices();
    pointLayer.AssignFastDrawnStates();
    _map.Refresh();
    _map.ResetBuffer();`

Then when trying to select the point, the colour doesn't change. 

If I remove the AssignFastDrawnStates() call, then the colour changes, but then doesn't change back when I unselect it, or the select tool no longer unselects the point when I click elsewhere.

**Comment by jany-tenaj** [comment]
Check pointLayer.EditMode and pointLayer.Dataset.IndexMode.
If I remember correctly selection is not shown if EditMode is true.

**Comment by littlecharva** [comment]
Perfect, that was it.  Thank you so much!
