### ISSUE TITLE
Direction of Flow of line Clicked

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#986]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.Click on Line
2. It Should display flow of direction 

DotSpatial version: 
map1.FunctionMode = FunctionMode.Select;
This above line selects the line and displays with diff color

### Expected behaviour
What am trying to achieve is to show the arrow mark which indicates which side line is going from start point and end point.
Please suggest how to do this. I referred #662, but it did not help me am trying to do similar to that only.

Rgds,
Amit

**Comment by jany-tenaj** [comment]
Try the following code. ml would be your MapLineLayer. This has to be set before you try to select something from your layer.

```
var stroke = new CartographicStroke(Color.Cyan) { Width = 2 }; // width of the line - cyan is our selection color

var dec = new LineDecoration
{
    Symbol = new PointSymbolizer(Color.Cyan, PointShape.Triangle, 16), // creates a cyan arrow head sized 16
    NumSymbols = 1, // show only one arrow head - enter other number if you need more than one
    RotateWithLine = true, // arrow head is rotated like the line 
    PercentualPosition = 100, // show arrow head at the line end - delete this line if you need more than one arrow head
    FlipAll = true // arrow head looks from beginning to end of line
};
stroke.Decorations.Add(dec);

ml.SelectionSymbolizer.Strokes.Clear(); // clear whatever strokes the selection symbolizer contains
ml.SelectionSymbolizer.Strokes.Add(stroke); // add the newly created stroke
```

**Comment by amitnkukanur** [comment]
Wow, It Worked. 
Thanks for providing solution.
