### ISSUE TITLE
Automatically update lines when its From Node and To Nodes are changed

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#987]
Hi,

I am trying for some change in displaying the data.
When i change the Node ID from Old to some other node id, can we draw the lines to that particular node.

I tried by changing the Node Id from Attribute table editor. It did not reflect.

Regards,
Amit

**Comment by jany-tenaj** [comment]
Please explain more clearly what you're trying to do. If possible include pictures.

**Comment by amitnkukanur** [comment]
![image](https://cloud.githubusercontent.com/assets/25892886/26293954/fe3bf214-3edd-11e7-82c8-aff68ebc48d7.png)

**Comment by amitnkukanur** [comment]
In this above pic, i have a line from D7 to D8, D8 to D9
If i want a line from D7 to D9, then where i have to change. I tried using Attribute Table editor by changing node id's it did not update.

**Comment by jany-tenaj** [comment]
Ok so basically you have a line geometry with the points D7, D8 and D9. And you want to change this line to only have the points D7 and D9.

Changing the attributes doesn't change the geometry. Attributes are just values you can display.

To change the line you'll have to do the following things:

- Get your feature layer (e.g. from Map.Layers).
- Find the feature the line belongs to
- Create a new line geometry from D7 to D9
- Assign the new geometry to the Geometry property of your feature
- Synchronize the underlying lists (#801) to make sure the drawing gets updated and you don't cause any errors

**Comment by amitnkukanur** [comment]
Thanks for the reply, i am trying to understand the points mentioned but finding difficult to interpret and implement. I request for more depth explanation.
