### ISSUE TITLE
How Can download V2 in appveyor ?

### ISSUE THREAD

**Issue by DavisMillier** [DotSpatial/DotSpatial#988]
Hello there
How Can i download Dotspatial V2 in appveyor ?
i found release but i can not download source code

**Comment by jany-tenaj** [comment]
Each successfull AppVeyor build has an [Artifacts page](https://ci.appveyor.com/project/mogikanin/dotspatial/branch/master/artifacts) that contains the DotSpatial.zip with all project dlls and the nuget files.

If you only want to downloaded the latest zip file, you can get this via the [Latest available build from master branch](https://ci.appveyor.com/api/projects/mogikanin/dotspatial/artifacts/Source/bin/Release.zip?branch=master) link from the [main page](https://github.com/DotSpatial/DotSpatial).

The source code is not meant to be downloaded via AppVeyor. To download the latest source code use the **Clone or download** button from the [main page](https://github.com/DotSpatial/DotSpatial).

If you don't want to download the latest source code click on the **1,121 commits** that is currently shown on [main page](https://github.com/DotSpatial/DotSpatial). Then find the commit you want to download and click on the <> button of the commit. You'll get the main page for this commit and can download the source via **Clone or download** button again.
