### ISSUE TITLE
Show All Entities in Identity Window

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#990]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Load Map
2. Click Identity
3. Display All Entities in Identity Window

DotSpatial version: 
 Shows the Identity details of single selected entity

### Expected behaviour
 Display all Nodes and Lines which helps to iterate through them

Tell us what should happen
Display all Nodes and Lines which helps to iterate through them

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by jany-tenaj** [comment]
Identity is meant to show only the details of the features below the mouse click point.

If you want to see the details of all your features either have a look at the attribute table editor or write your own MapFunction.
