### ISSUE TITLE
Question: Find the degree of a node

### ISSUE THREAD

**Issue by karthikaditya** [DotSpatial/DotSpatial#992]
DotSpatial version: 2.0

I have a line layer on top of a point layer and I want to find the number of edges(lines) adjacent to each node i.e. the degree of the node. 

![degreee](https://cloud.githubusercontent.com/assets/16631223/26624098/7b4e4460-460d-11e7-8334-c91eeac30c6d.PNG)

I searched the SDK but couldn't find anything related to this. 

 Is it possible to find the degree of a node? If yes, how to find it? 

 Thanks in advance,
 Karthik

**Comment by jany-tenaj** [comment]
Hey Karthik, 

thanks for adding the picture. I couldn't understand your post on Codeplex without it.

So if I understand you correctly you want to find the number of lines that have the coordinate of a point as either their end or start point.

If you want to do this for a single point at a time you can do it like this:

- get the point
- make a very small buffer around the point
- use the buffer to find the intersecting lines in the line layer
- for each line that was found check whether the x/y values of the end or start point are same as the x/y values of your point

**Comment by karthikaditya** [comment]
Thanks for your answer.

I will try to follow the steps you've mentioned.

And just to be clear, there is no property or method to find it directly, right?

**Comment by jany-tenaj** [comment]
No there is no property or method.
