### ISSUE TITLE
How to re-order the layers

### ISSUE THREAD

**Issue by littlecharva** [DotSpatial/DotSpatial#993]
Is there a way to control the order of the layers?

I'm loading layers in the order I want, but then at some stage I need to clear some layers and load them in again.  Unfortunately this loads them in on top of everything else, but I need them to be in a specific order.

Anthony

**Comment by jany-tenaj** [comment]
Check whether you can find the move function in Map.Layers. It can be used to move layers up or down.

**Comment by littlecharva** [comment]
Perfect - thanks for the help!
