### ISSUE TITLE
Reorder Attribute Names

### ISSUE THREAD

**Issue by amitnkukanur** [DotSpatial/DotSpatial#994]
Hi,

When we see the attribute table or identity window, it shows various attributes, diff column names.
Is there any way i can create custom names or more meaning full names

for example : Vacant, Crop_Acr1, PercentFew, HSEHLD_1_M..... etc
These names are not helpful for reading, is there any way to rename these.

I was thinking of changing a datagrid view in identify to have comboboxes in datagrid rows as well if i need to assign some value i could do from there itself.

Please suggest.

Regards,
Amit

**Comment by sindizzy** [comment]
Other GIS support field aliases. I would look for that in the documentation.

**Comment by jany-tenaj** [comment]
FeatureSet.DataTable (which is shown inside the attribute table editor window) is a simple DataTable. You can reorder and rename columns like you can with any other DataTable, too. If you want to keep the column names the same inside the shapefile you could use DataColumn.Caption instead to simply change the way the columns get shown to the user.

**Comment by amitnkukanur** [comment]
Ok
