### ISSUE TITLE
FeatureSet.OpenFile() throws wrong exception description when .shx file is not found

### ISSUE THREAD

**Issue by gojanpaolo** [DotSpatial/DotSpatial#996]
### Steps to reproduce
1. use FeatureSet.OpenFile() and include only .shp and .dbf files in the folder

DotSpatial version:  v1.9.0

### Expected behaviour
Throw exception saying .shx file is not found.

### Actual behaviour
Throws exception saying .shp is not found.

**Comment by jany-tenaj** [comment]
This was already fixed for 2.0.
