### ISSUE TITLE
UnionShapes() Fails

### ISSUE THREAD

**Issue by rickyburrell** [DotSpatial/DotSpatial#999]
UnionShapes() fails on the attached shape file containing two polygons.

Error message is "Directed Edge visited twice during ring-building at DotSpatial.Topology.Coordinate"

[debug.zip](https://github.com/DotSpatial/DotSpatial/files/1058438/debug.zip)

*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. FeatureSet.Open(@"C:\debug\debug.shp").UnionShapes(ShapeRelateType.All);

DotSpatial version: 1.9

### Expected behaviour

QGIS & ArcGIS do not throw this error. Expected result is a dissolved polygon.

**Comment by jany-tenaj** [comment]
I just ran this in 2.0 without error.
